"use strict";
// Español. Chave: o texto em português (igual ao EN de idioma.js). Faltou alguma? Cai no inglês.
TRADUCOES.es = {
  "{0}: puxa o inimigo e chuta pro espaço. Atrás da banana!": "{0}: atrae al enemigo y patéalo al espacio. ¡Persigue el plátano!",
  "+{0} moedas. Atrás da banana!": "+{0} monedas. ¡Persigue el plátano!",
  "Selva": "Selva",
  "Deserto": "Desierto",
  "Era do Gelo": "Era de Hielo",
  "Vulcão de Lava": "Volcán de Lava",
  "Gorila Rei": "Gorila Rey",
  "Escorpião Faraó": "Escorpión Faraón",
  "Yeti Ancestral": "Yeti Ancestral",
  "Dragão de Magma": "Dragón de Magma",
  "{0} - Chefe": "{0} - Jefe",
  "Espinhos": "Pinchos",
  "Cipós de balançar": "Lianas para columpiarse",
  "Cogumelo pula-pula": "Seta saltarina",
  "Troncos rolando": "Troncos rodantes",
  "Plantas carnívoras": "Plantas carnívoras",
  "Areia movediça": "Arenas movedizas",
  "Redemoinho": "Remolino",
  "Armadilha de dardos": "Trampa de dardos",
  "Pedras rolando": "Rocas rodantes",
  "Ventania de areia": "Tormenta de arena",
  "Túnel de gelo (deslize!)": "Túnel de hielo (¡deslízate!)",
  "Estalactites": "Estalactitas",
  "Pista de gelo": "Pista de hielo",
  "Gelo fino": "Hielo fino",
  "Avalanche": "Avalancha",
  "Lago de lava": "Lago de lava",
  "Rocha de impulso": "Roca impulsora",
  "Plataformas que caem": "Plataformas que caen",
  "Barra de fogo": "Barra de fuego",
  "Chuva de meteoros": "Lluvia de meteoritos",
  "Cobra": "Serpiente",
  "Abelha": "Abeja",
  "Sapo": "Rana",
  "Macaco Ladrão": "Mono Ladrón",
  "Aranha": "Araña",
  "Escorpião": "Escorpión",
  "Abutre": "Buitre",
  "Cacto Atirador": "Cactus Tirador",
  "Múmia": "Momia",
  "Tatu-bola": "Armadillo",
  "Pinguim": "Pingüino",
  "Morcego de Gelo": "Murciélago de Hielo",
  "Boneco de Neve": "Muñeco de Nieve",
  "Foca": "Foca",
  "Lobo do Gelo": "Lobo de Hielo",
  "Slime de Magma": "Slime de Magma",
  "Morcego de Fogo": "Murciélago de Fuego",
  "Diabinho": "Diablillo",
  "Golem de Pedra": "Gólem de Piedra",
  "Fênix": "Fénix",
  "{esquerda}/{direita} andar   {pulo} pular\nSegure {pulo} para pular mais alto": "{esquerda}/{direita} andar   {pulo} saltar\nMantén {pulo} para saltar más alto",
  "Bem-vindo: {0}!": "¡Bienvenido: {0}!",
  "Novo inimigo: {0}!": "¡Nuevo enemigo: {0}!",
  "Novo inimigo: Cobra! Pule na cabeça dela!": "¡Nuevo enemigo: Serpiente! ¡Salta sobre su cabeza!",
  "Seu prêmio: cipó-laço! {laco}: puxa o inimigo": "¡Tu premio: liana-lazo! {laco}: atrae al enemigo",
  "Vença o Gorila Rei para ganhar o cipó-laço!": "¡Vence al Gorila Rey para ganar la liana-lazo!",
  "Você ganhou o cipó-laço!": "¡Has ganado la liana-lazo!",
  "Arraste para andar": "Arrastra para andar",
  "Tutorial": "Tutorial",
  "Boa!": "¡Bien!",
  "Arraste o analógico para a direita": "Arrastra el joystick a la derecha",
  "Ande para a direita: {0}": "Anda a la derecha: {0}",
  "Toque em PULO para pular o bloco": "Toca SALTO para saltar el bloque",
  "Pule o bloco: {0}": "Salta el bloque: {0}",
  "Pule na cabeça da cobra!": "¡Salta sobre la cabeza de la serpiente!",
  "Pegue a banana!": "¡Atrapa el plátano!",
  "Tutorial completo!": "¡Tutorial completado!",
  "ou": "o",
  "Agora é pra valer: atravesse os 4 mundos!": "Ahora va en serio: ¡cruza los 4 mundos!",
  "Toque para pular": "Toca para saltar",
  "{0}: puxa o inimigo e chuta pro espaço. Pegue a banana!": "{0}: atrae al enemigo y patéalo al espacio. ¡Atrapa el plátano!",
  "Novo: {0}!": "¡Nuevo: {0}!",
  "Pule por cima dos espinhos!": "¡Salta por encima de los pinchos!",
  "Pule no cipó para se agarrar!\n{pulo} solta": "¡Salta a la liana para agarrarte!\n{pulo} suelta",
  "Pule no cogumelo para ir bem alto!": "¡Salta sobre la seta para llegar muy alto!",
  "Pule por cima deles!": "¡Salta por encima de ellos!",
  "Passe quando a planta se esconder!": "¡Pasa cuando la planta se esconda!",
  "Pule rápido para não afundar!": "¡Salta rápido para no hundirte!",
  "Entre no redemoinho para subir!": "¡Entra en el remolino para subir!",
  "Pule os dardos de baixo,\ndeslize ({baixo}) nos de cima!": "¡Salta los dardos de abajo,\ndesliza ({baixo}) bajo los de arriba!",
  "Elas são enormes: pule na hora certa!": "Son enormes: ¡salta en el momento justo!",
  "Espere o vento parar para pular!": "¡Espera a que pare el viento para saltar!",
  "Corra e segure {baixo} para deslizar!": "¡Corre y mantén {baixo} para deslizarte!",
  "Não pare embaixo das estalactites!": "¡No te pares debajo de las estalactitas!",
  "Deslize ({baixo}) no gelo para pular longe!": "¡Deslízate ({baixo}) en el hielo para saltar lejos!",
  "O gelo fino quebra! Não fique parado": "¡El hielo fino se rompe! No te quedes quieto",
  "Pule as bolas de neve!": "¡Salta las bolas de nieve!",
  "Lava queima! Pule por cima": "¡La lava quema! Salta por encima",
  "Pule na rocha de magma: IMPULSO!": "Salta sobre la roca de magma: ¡IMPULSO!",
  "Essas plataformas despencam!": "¡Estas plataformas se caen!",
  "Passe quando a barra de fogo girar!": "¡Pasa cuando la barra de fuego gire!",
  "Fuja das sombras vermelhas!": "¡Huye de las sombras rojas!",
  "Pule na cabeça dela!": "¡Salta sobre su cabeza!",
  "Ela voa: pule nela ou passe por baixo!": "Vuela: ¡salta encima o pasa por debajo!",
  "Ele pula atrás de você!": "¡Te persigue a saltos!",
  "Ele joga cocos!": "¡Lanza cocos!",
  "Ela desce quando você passa!": "¡Baja cuando pasas!",
  "Pule na cabeça dele!": "¡Salta sobre su cabeza!",
  "Ele mergulha em você!": "¡Se lanza en picado hacia ti!",
  "Espinhoso: não pise, deslize nele!": "Espinoso: ¡no lo pises, deslízate contra él!",
  "Lenta mas resistente!": "¡Lenta pero resistente!",
  "Não pise quando ele rolar!": "¡No lo pises mientras rueda!",
  "Ele escorrega na sua direção!": "¡Se desliza hacia ti!",
  "Voa rápido!": "¡Vuela rápido!",
  "Joga bolas de neve!": "¡Lanza bolas de nieve!",
  "Pula atrás de você!": "¡Te persigue a saltos!",
  "Corre muito rápido!": "¡Corre muy rápido!",
  "Quente: não pise, deslize nele!": "Caliente: ¡no lo pises, deslízate contra él!",
  "Voa muito rápido!": "¡Vuela muy rápido!",
  "Atira bolas de fogo!": "¡Dispara bolas de fuego!",
  "Pule na cabeça ou use o cipó-laço!": "¡Salta sobre su cabeza o usa la liana-lazo!",
  "Mergulha soltando fogo!": "¡Se lanza escupiendo fuego!",
  "Clássico": "Clásico",
  "Dourado": "Dorado",
  "Chiclete": "Chicle",
  "Gelo": "Hielo",
  "Sombra": "Sombra",
  "Camuflado": "Camuflado",
  "Fogo": "Fuego",
  "Dálmata": "Dálmata",
  "Zumbi": "Zombi",
  "Robô": "Robot",
  "Esqueleto": "Esqueleto",
  "Fantasma": "Fantasma",
  "Diamante": "Diamante",
  "Galáxia": "Galaxia",
  "Arco-íris": "Arcoíris",
  "Tigre": "Tigre",
  "Gorila": "Gorila",
  "Camelo": "Camello",
  "Dragão": "Dragón",
  "Prata": "Plata",
  "Ouro": "Oro",
  "Lendário": "Legendario",
  "Boné": "Gorra",
  "Chapéu de Festa": "Gorro de Fiesta",
  "Gorro": "Gorro de lana",
  "Chapéu de Cowboy": "Sombrero de Vaquero",
  "Cartola": "Chistera",
  "Chapéu de Chef": "Gorro de Chef",
  "Capacete Viking": "Casco Vikingo",
  "Auréola": "Aureola",
  "Coroa": "Corona",
  "Folha": "Hoja",
  "Chapéu de Explorador": "Sombrero de Explorador",
  "Turbante": "Turbante",
  "Coroa de Faraó": "Corona de Faraón",
  "Protetor de Orelha": "Orejeras",
  "Chapéu de Pele": "Gorro de Piel",
  "Capacete de Bombeiro": "Casco de Bombero",
  "Chifres de Demônio": "Cuernos de Demonio",
  "Óculos Escuros": "Gafas de Sol",
  "Óculos 3D": "Gafas 3D",
  "Óculos de Nerd": "Gafas de Empollón",
  "Máscara": "Máscara",
  "Óculos de Coração": "Gafas de Corazón",
  "Monóculo": "Monóculo",
  "Visor Cyber": "Visor Ciber",
  "Pintura de Guerra": "Pintura de Guerra",
  "Óculos de Aviador": "Gafas de Aviador",
  "Óculos de Esqui": "Gafas de Esquí",
  "Óculos de Solda": "Gafas de Soldador",
  "Gravata": "Corbata",
  "Camiseta": "Camiseta",
  "Cachecol": "Bufanda",
  "Macacão": "Peto",
  "Colete Salva-vidas": "Chaleco Salvavidas",
  "Smoking": "Esmoquin",
  "Capa de Herói": "Capa de Héroe",
  "Armadura": "Armadura",
  "Colar de Flores": "Collar de Flores",
  "Lenço de Bandido": "Pañuelo de Bandido",
  "Faixas de Múmia": "Vendas de Momia",
  "Jaqueta de Neve": "Chaqueta de Nieve",
  "Capa de Fogo": "Capa de Fuego",
  "Super Velocidade": "Supervelocidad",
  "+60% de velocidade por 10s": "+60% de velocidad durante 10 s",
  "Pulo Duplo": "Doble Salto",
  "Pula de novo no ar por 15s": "Salta otra vez en el aire durante 15 s",
  "Escudo": "Escudo",
  "Invencível por 8s": "Invencible durante 8 s",
  "Ímã de Moedas": "Imán de Monedas",
  "Puxa as moedas por 15s": "Atrae las monedas durante 15 s",
  "Explode os inimigos perto": "Hace explotar a los enemigos cercanos",
  "Dispara pra frente e atravessa inimigos": "Sale disparado y atraviesa enemigos",
  "Coração Extra": "Corazón Extra",
  "Coração Extra II": "Corazón Extra II",
  "+1 coração de vida": "+1 corazón de vida",
  "Revólver Turbo": "Revólver Turbo",
  "8 balas, tiro e recarga mais rápidos": "8 balas, disparo y recarga más rápidos",
  "Cipó Longo": "Liana Larga",
  "O laço de cipó alcança mais longe": "La liana-lazo llega más lejos",
  "Chapéus": "Sombreros",
  "Óculos": "Gafas",
  "Roupas": "Ropa",
  "Poderes": "Poderes",
  "Melhorias": "Mejoras",
  "Andar para a esquerda": "Andar a la izquierda",
  "Andar para a direita": "Andar a la derecha",
  "Pular": "Saltar",
  "Deslizar / soltar do cipó": "Deslizarse / soltar la liana",
  "Revólver": "Revólver",
  "Recarregar": "Recargar",
  "Cipó-laço": "Liana-lazo",
  "Poder: Super Velocidade": "Poder: Supervelocidad",
  "Poder: Pulo Duplo": "Poder: Doble Salto",
  "Poder: Escudo": "Poder: Escudo",
  "Poder: Ímã de Moedas": "Poder: Imán de Monedas",
  "Poder: Nuke": "Poder: Nuke",
  "Loja": "Tienda",
  "Pausa": "Pausa",
  "Ligar/desligar som": "Activar/desactivar sonido",
  "Espaço": "Espacio",
  "Apagar": "Retroceso",
  "andar": "andar",
  "pular (segure: mais alto)": "saltar (mantén: más alto)",
  "deslizar": "deslizarse",
  "revólver": "revólver",
  "recarregar": "recargar",
  "cipó-laço (puxa o inimigo e chuta pro espaço!)": "liana-lazo (¡atrae al enemigo y patéalo al espacio!)",
  "dash (melhoria)": "dash (mejora)",
  "poderes": "poderes",
  "loja": "tienda",
  "pausa": "pausa",
  "Ação": "Acción",
  "Tecla 1": "Tecla 1",
  "Tecla 2": "Tecla 2",
  "Tecla 3": "Tecla 3",
  "aperte...": "pulsa...",
  "trocar poder": "cambiar poder",
  "Saru": "Saru",
  "Saru Gigante": "Saru Gigante",
  "Nível {0}+: um macaco lendário pode aparecer 1 vez por dia": "Nivel {0}+: un mono legendario puede aparecer 1 vez al día",
  "Você venceu o Saru hoje! Ele pode voltar amanhã.": "¡Hoy venciste a Saru! Puede volver mañana.",
  "Volte amanhã: o Saru pode aparecer": "Vuelve mañana: Saru puede aparecer",
  "O Saru apareceu! Enfrentar ({0})": "¡Ha aparecido Saru! Enfrentarlo ({0})",
  "O Saru Nv {1} apareceu! Enfrentar ({0})": "¡Ha aparecido Saru Nv {1}! Enfrentarlo ({0})",
  "Nv {0}": "Nv {0}",
  "Nível {0}: mais vida, mais rápido e furioso mais cedo": "Nivel {0}: más vida, más rápido y se enfurece antes",
  "Você venceu o Saru hoje! Ele pode voltar amanhã, mais forte.": "¡Hoy venciste a Saru! Puede volver mañana, más fuerte.",
  "Saru: +3 tentativas (anúncio)": "Saru: +3 intentos (anuncio)",
  "Sem tentativas contra o Saru hoje. Volte amanhã!": "No te quedan intentos contra Saru hoy. ¡Vuelve mañana!",
  "O Saru venceu!": "¡Saru ganó!",
  "Tentativas restantes: {0}": "Intentos restantes: {0}",
  "Nova skin: Saru  ·  Nova melhoria: Nuvem Mágica  ·  +{0} moedas": "Nueva skin: Saru  ·  Nueva mejora: Nube Mágica  ·  +{0} monedas",
  "Saru derrotado!": "¡Saru derrotado!",
  "A lua cheia nasceu...": "Ha salido la luna llena...",
  "Fase {0}/2": "Fase {0}/2",
  "O macaco lendário! Tentativas restantes: {0}": "¡El mono legendario! Intentos restantes: {0}",
  "Nuvem Mágica!": "¡Nube Mágica!",
  "Nuvem Mágica": "Nube Mágica",
  "Uma vez por fase, se cair num buraco, a nuvem te salva sem perder vida": "Una vez por nivel, si caes en un hoyo, la nube te salva sin perder vida",
  "Derrote o Saru": "Derrota a Saru",
  "Volte amanhã: ele pode aparecer de novo.": "Vuelve mañana: puede aparecer otra vez.",
  "Tentar de novo (Enter)": "Reintentar (Enter)",
  "Assistir anúncio: +3 tentativas": "Ver anuncio: +3 intentos",
  "Voltar ao menu (Esc)": "Volver al menú (Esc)",
  "Opções": "Opciones",
  "Idioma": "Idioma",
  "Adicionais": "Extras",
  "Escolha o idioma do jogo.": "Elige el idioma del juego.",
  "O cronômetro mostra o tempo da run e de cada fase, com os seus recordes.": "El cronómetro muestra el tiempo de la partida y de cada nivel, con tus récords.",
  "Assistir anúncio: +{0} moedas": "Ver anuncio: +{0} monedas",
  "Grátis (anúncio)": "Gratis (anuncio)",
  "+{0} moedas!": "¡+{0} monedas!",
  "+1 {0}!": "¡+1 {0}!",
  "O anúncio não terminou, nada ganho.": "El anuncio no terminó, no ganas nada.",
  "Moedas grátis": "Monedas gratis",
  "Completa": "Completado",
  "Sem perder vida": "Sin perder vidas",
  "Até {0}": "En menos de {0}",
  "NOVA!": "¡NUEVA!",
  "Tempo {0}": "Tiempo {0}",
  "Recorde {0}": "Récord {0}",
  "Estrelas: {0}/{1}": "Estrellas: {0}/{1}",
  "Modo speedrun liberado! O cronômetro foi ligado.": "¡Modo speedrun desbloqueado! El cronómetro está activado.",
  "Zerado! Jogar = nova run": "¡Completado! Jugar = nueva partida",
  "PULO": "SALTO",
  "TIRO": "DISPARO",
  "LAÇO": "LAZO",
  "LOJA": "TIENDA",
  "PAUSA": "PAUSA",
  "arraste do lado esquerdo: andar e deslizar": "arrastra en el lado izquierdo: andar y deslizarse",
  "toque nos poderes para usar": "toca un poder para usarlo",
  "Toque na tela para começar": "Toca la pantalla para empezar",
  "Toque na tela para voltar ao menu": "Toca la pantalla para volver al menú",
  "usar poder": "usar poder",
  "Jogo zerado!": "¡Juego completado!",
  "Próxima: {0}": "Siguiente: {0}",
  " · Recorde: {0}": " · Récord: {0}",
  "Som: ligado ({0})": "Sonido: sí ({0})",
  "Som: desligado ({0})": "Sonido: no ({0})",
  "Cronômetro: ligado": "Cronómetro: sí",
  "Cronômetro: desligado": "Cronómetro: no",
  "Idioma: Português": "Idioma: Español",
  "Chefe": "Jefe",
  "Chefe: ": "Jefe: ",
  "Prêmio": "Premio",
  "Épico": "Épico",
  "Raro": "Raro",
  "Comum": "Común",
  "{0}. Tecla {1}.": "{0}. Tecla {1}.",
  "Você tem: {0}": "Tienes: {0}",
  "Comprar": "Comprar",
  "Faltam {0}": "Faltan {0}",
  "{0} (permanente)": "{0} (permanente)",
  "Comprado": "Comprado",
  "Precisa: {0}": "Requiere: {0}",
  "Equipado": "Equipado",
  "Seu": "Tuyo",
  "Passe a fase {0}": "Supera {0}",
  "Chegue ao nível {0}": "Llega al nivel {0}",
  "Bloqueado": "Bloqueado",
  "Tirar": "Quitar",
  "Equipar": "Equipar",
  "-1 vida": "-1 vida",
  "recarregando": "recargando",
  "Você perdeu!": "¡Has perdido!",
  "Voltando do checkpoint...": "Volviendo al punto de control...",
  "Tentando de novo...": "Reintentando...",
  "Fase completa!": "¡Nivel completado!",
  "{0} completo!": "¡{0} completado!",
  "A banana escapou de novo! Próximo: {0}": "¡El plátano se escapó otra vez! Siguiente: {0}",
  "Você ganhou: {0}!  Próximo: {1}": "¡Has ganado: {0}!  Siguiente: {1}",
  "Chefe derrotado!": "¡Jefe derrotado!",
  "+{0} moedas. Pegue a banana!": "+{0} monedas. ¡Atrapa el plátano!",
  "Reviveu!": "¡Revivido!",
  "+{0} moedas": "+{0} monedas",
  "  ·  Nova skin: {0}!": "  ·  ¡Nueva skin: {0}!",
  "NÍVEL {0}!": "¡NIVEL {0}!",
  "{0} - o chefe do mundo": "{0} - el jefe del mundo",
  "Novo inimigo: {0}": "Nuevo enemigo: {0}",
  "Novo obstáculo: {0}": "Nuevo obstáculo: {0}",
  "Prêmio ao terminar: {0}": "Premio al terminar: {0}",
  "FASE": "NIVEL",
  "Recorde da fase": "Récord del nivel",
  "Primeiro tempo!": "¡Primer tiempo!",
  "{0}  Recorde!": "{0}  ¡Récord!",
  "  (primeira run!)": "  (¡primera partida!)",
  "  NOVO RECORDE! ({0})": "  ¡NUEVO RÉCORD! ({0})",
  "  (recorde: {0})": "  (récord: {0})",
  "O vento levou a banana!": "¡El viento se llevó el plátano!",
  "Atravesse a Selva, o Deserto, a Era do Gelo e o Vulcão para recuperá-la!": "¡Cruza la Selva, el Desierto, la Era de Hielo y el Volcán para recuperarlo!",
  "Dizem que ela foi parar nas garras do Dragão de Magma...": "Dicen que acabó en las garras del Dragón de Magma...",
  "Clique ou aperte qualquer tecla para começar": "Haz clic o pulsa cualquier tecla para empezar",
  "Nham!": "¡Ñam!",
  "FIM!": "¡FIN!",
  "O primata derrotou o Dragão de Magma e finalmente comeu a sua banana!": "¡El primate derrotó al Dragón de Magma y por fin se comió su plátano!",
  "Nível {0}   ·   Moedas: {1}": "Nivel {0}   ·   Monedas: {1}",
  "Inimigos derrotados: {0}   ·   Chutados pro espaço: {1}": "Enemigos derrotados: {0}   ·   Pateados al espacio: {1}",
  "Chefes derrotados: {0}   ·   Quedas: {1}": "Jefes derrotados: {0}   ·   Caídas: {1}",
  "Tempo de jogo: {0}": "Tiempo de juego: {0}",
  "Nova skin: {0}!": "¡Nueva skin: {0}!",
  "Clique ou aperte qualquer tecla para voltar ao menu": "Haz clic o pulsa cualquier tecla para volver al menú",
  "PAUSA (P)": "PAUSA (P)",
  "LOJA (L)": "TIENDA (L)",
  "A grande caçada à banana": "La gran caza del plátano",
  "moedas": "monedas",
  "Fase": "Nivel",
  "Nível": "Nivel",
  "Jogar (Enter)": "Jugar (Enter)",
  "Escolher fase": "Elegir nivel",
  "Controles": "Controles",
  "Escolha a fase": "Elige un nivel",
  "Voltar": "Volver",
  "Pausado": "En pausa",
  "Continuar (P)": "Continuar (P)",
  "Loja (L)": "Tienda (L)",
  "Recomeçar fase": "Reiniciar nivel",
  "Som": "Sonido",
  "Cronômetro": "Cronómetro",
  "Menu principal": "Menú principal",
  "Assista um anúncio para continuar daqui com todas as vidas.": "Mira un anuncio para seguir desde aquí con todas las vidas.",
  "Assistir e reviver (Enter)": "Ver y revivir (Enter)",
  "Voltar do checkpoint (Esc)": "Volver al punto de control (Esc)",
  "Clique numa tecla e aperte a nova.": "Haz clic en una tecla y pulsa la nueva.",
  "apaga.": "la borra.",
  "volta.": "vuelve.",
  "Restaurar padrão": "Restaurar predeterminado",
  "Loja do Primata": "Tienda del Primate",
  "L ou Esc para voltar": "L o Esc para volver",
  "{0} ou Esc para voltar": "{0} o Esc para volver",
  "Continuar": "Continuar"
};
