"use strict";
// Français. Chave: o texto em português (igual ao EN de idioma.js). Faltou alguma? Cai no inglês.
TRADUCOES.fr = {
  "{0}: puxa o inimigo e chuta pro espaço. Atrás da banana!": "{0} : attire l'ennemi et envoie-le dans l'espace. Rattrape la banane !",
  "+{0} moedas. Atrás da banana!": "+{0} pièces. Rattrape la banane !",
  "Selva": "Jungle",
  "Deserto": "Désert",
  "Era do Gelo": "Ère glaciaire",
  "Vulcão de Lava": "Volcan de lave",
  "Gorila Rei": "Gorille Roi",
  "Escorpião Faraó": "Scorpion Pharaon",
  "Yeti Ancestral": "Yéti Ancestral",
  "Dragão de Magma": "Dragon de Magma",
  "{0} - Chefe": "{0} - Boss",
  "Espinhos": "Pics",
  "Cipós de balançar": "Lianes qui se balancent",
  "Cogumelo pula-pula": "Champignon rebondissant",
  "Troncos rolando": "Troncs qui roulent",
  "Plantas carnívoras": "Plantes carnivores",
  "Areia movediça": "Sables mouvants",
  "Redemoinho": "Tourbillon",
  "Armadilha de dardos": "Piège à fléchettes",
  "Pedras rolando": "Rochers qui roulent",
  "Ventania de areia": "Tempête de sable",
  "Túnel de gelo (deslize!)": "Tunnel de glace (glisse !)",
  "Estalactites": "Stalactites",
  "Pista de gelo": "Piste de glace",
  "Gelo fino": "Glace fine",
  "Avalanche": "Avalanche",
  "Lago de lava": "Lac de lave",
  "Rocha de impulso": "Rocher propulseur",
  "Plataformas que caem": "Plateformes qui tombent",
  "Barra de fogo": "Barre de feu",
  "Chuva de meteoros": "Pluie de météores",
  "Cobra": "Serpent",
  "Abelha": "Abeille",
  "Sapo": "Grenouille",
  "Macaco Ladrão": "Singe Voleur",
  "Aranha": "Araignée",
  "Escorpião": "Scorpion",
  "Abutre": "Vautour",
  "Cacto Atirador": "Cactus Tireur",
  "Múmia": "Momie",
  "Tatu-bola": "Tatou",
  "Pinguim": "Pingouin",
  "Morcego de Gelo": "Chauve-souris de glace",
  "Boneco de Neve": "Bonhomme de neige",
  "Foca": "Phoque",
  "Lobo do Gelo": "Loup des glaces",
  "Slime de Magma": "Slime de magma",
  "Morcego de Fogo": "Chauve-souris de feu",
  "Diabinho": "Diablotin",
  "Golem de Pedra": "Golem de pierre",
  "Fênix": "Phénix",
  "{esquerda}/{direita} andar   {pulo} pular\nSegure {pulo} para pular mais alto": "{esquerda}/{direita} marcher   {pulo} sauter\nMaintiens {pulo} pour sauter plus haut",
  "Bem-vindo: {0}!": "Bienvenue : {0} !",
  "Novo inimigo: {0}!": "Nouvel ennemi : {0} !",
  "Novo inimigo: Cobra! Pule na cabeça dela!": "Nouvel ennemi : Serpent ! Saute sur sa tête !",
  "Seu prêmio: cipó-laço! {laco}: puxa o inimigo": "Ta récompense : la liane-lasso ! {laco} : attire l'ennemi",
  "Vença o Gorila Rei para ganhar o cipó-laço!": "Bats le Gorille Roi pour gagner la liane-lasso !",
  "Você ganhou o cipó-laço!": "Tu as gagné la liane-lasso !",
  "Arraste para andar": "Glisse pour marcher",
  "Tutorial": "Tutoriel",
  "Boa!": "Bravo !",
  "Arraste o analógico para a direita": "Pousse le joystick vers la droite",
  "Ande para a direita: {0}": "Marche vers la droite : {0}",
  "Toque em PULO para pular o bloco": "Touche SAUT pour sauter le bloc",
  "Pule o bloco: {0}": "Saute le bloc : {0}",
  "Pule na cabeça da cobra!": "Saute sur la tête du serpent !",
  "Pegue a banana!": "Attrape la banane !",
  "Tutorial completo!": "Tutoriel terminé !",
  "ou": "ou",
  "Agora é pra valer: atravesse os 4 mundos!": "Maintenant pour de vrai : traverse les 4 mondes !",
  "Toque para pular": "Touche pour sauter",
  "{0}: puxa o inimigo e chuta pro espaço. Pegue a banana!": "{0} : attire l'ennemi et envoie-le dans l'espace. Attrape la banane !",
  "Novo: {0}!": "Nouveau : {0} !",
  "Pule por cima dos espinhos!": "Saute par-dessus les pics !",
  "Pule no cipó para se agarrar!\n{pulo} solta": "Saute sur la liane pour t'y accrocher !\n{pulo} pour lâcher",
  "Pule no cogumelo para ir bem alto!": "Saute sur le champignon pour aller très haut !",
  "Pule por cima deles!": "Saute par-dessus !",
  "Passe quando a planta se esconder!": "Passe quand la plante se cache !",
  "Pule rápido para não afundar!": "Saute vite pour ne pas t'enfoncer !",
  "Entre no redemoinho para subir!": "Entre dans le tourbillon pour monter !",
  "Pule os dardos de baixo,\ndeslize ({baixo}) nos de cima!": "Saute les fléchettes du bas,\nglisse ({baixo}) sous celles du haut !",
  "Elas são enormes: pule na hora certa!": "Ils sont énormes : saute au bon moment !",
  "Espere o vento parar para pular!": "Attends que le vent s'arrête pour sauter !",
  "Corra e segure {baixo} para deslizar!": "Cours et maintiens {baixo} pour glisser !",
  "Não pare embaixo das estalactites!": "Ne t'arrête pas sous les stalactites !",
  "Deslize ({baixo}) no gelo para pular longe!": "Glisse ({baixo}) sur la glace pour sauter loin !",
  "O gelo fino quebra! Não fique parado": "La glace fine se brise ! Ne reste pas immobile",
  "Pule as bolas de neve!": "Saute les boules de neige !",
  "Lava queima! Pule por cima": "La lave brûle ! Saute par-dessus",
  "Pule na rocha de magma: IMPULSO!": "Saute sur le rocher de magma : PROPULSION !",
  "Essas plataformas despencam!": "Ces plateformes s'effondrent !",
  "Passe quando a barra de fogo girar!": "Passe quand la barre de feu tourne !",
  "Fuja das sombras vermelhas!": "Évite les ombres rouges !",
  "Pule na cabeça dela!": "Saute sur sa tête !",
  "Ela voa: pule nela ou passe por baixo!": "Elle vole : saute dessus ou passe en dessous !",
  "Ele pula atrás de você!": "Elle te poursuit en sautant !",
  "Ele joga cocos!": "Il lance des noix de coco !",
  "Ela desce quando você passa!": "Elle descend quand tu passes !",
  "Pule na cabeça dele!": "Saute sur sa tête !",
  "Ele mergulha em você!": "Il pique sur toi !",
  "Espinhoso: não pise, deslize nele!": "Piquant : ne saute pas dessus, glisse dedans !",
  "Lenta mas resistente!": "Lente mais résistante !",
  "Não pise quando ele rolar!": "Ne saute pas dessus quand il roule !",
  "Ele escorrega na sua direção!": "Il glisse vers toi !",
  "Voa rápido!": "Vole vite !",
  "Joga bolas de neve!": "Lance des boules de neige !",
  "Pula atrás de você!": "Te poursuit en sautant !",
  "Corre muito rápido!": "Court très vite !",
  "Quente: não pise, deslize nele!": "Brûlant : ne saute pas dessus, glisse dedans !",
  "Voa muito rápido!": "Vole très vite !",
  "Atira bolas de fogo!": "Lance des boules de feu !",
  "Pule na cabeça ou use o cipó-laço!": "Saute sur sa tête ou utilise la liane-lasso !",
  "Mergulha soltando fogo!": "Pique en crachant du feu !",
  "Clássico": "Classique",
  "Dourado": "Doré",
  "Chiclete": "Chewing-gum",
  "Gelo": "Glace",
  "Sombra": "Ombre",
  "Camuflado": "Camouflé",
  "Fogo": "Feu",
  "Dálmata": "Dalmatien",
  "Zumbi": "Zombie",
  "Robô": "Robot",
  "Esqueleto": "Squelette",
  "Fantasma": "Fantôme",
  "Diamante": "Diamant",
  "Galáxia": "Galaxie",
  "Arco-íris": "Arc-en-ciel",
  "Tigre": "Tigre",
  "Gorila": "Gorille",
  "Camelo": "Chameau",
  "Dragão": "Dragon",
  "Prata": "Argent",
  "Ouro": "Or",
  "Lendário": "Légendaire",
  "Boné": "Casquette",
  "Chapéu de Festa": "Chapeau de fête",
  "Gorro": "Bonnet",
  "Chapéu de Cowboy": "Chapeau de cow-boy",
  "Cartola": "Haut-de-forme",
  "Chapéu de Chef": "Toque de chef",
  "Capacete Viking": "Casque viking",
  "Auréola": "Auréole",
  "Coroa": "Couronne",
  "Folha": "Feuille",
  "Chapéu de Explorador": "Chapeau d'explorateur",
  "Turbante": "Turban",
  "Coroa de Faraó": "Couronne de pharaon",
  "Protetor de Orelha": "Cache-oreilles",
  "Chapéu de Pele": "Chapka",
  "Capacete de Bombeiro": "Casque de pompier",
  "Chifres de Demônio": "Cornes de démon",
  "Óculos Escuros": "Lunettes de soleil",
  "Óculos 3D": "Lunettes 3D",
  "Óculos de Nerd": "Lunettes d'intello",
  "Máscara": "Masque",
  "Óculos de Coração": "Lunettes cœur",
  "Monóculo": "Monocle",
  "Visor Cyber": "Visière cyber",
  "Pintura de Guerra": "Peinture de guerre",
  "Óculos de Aviador": "Lunettes d'aviateur",
  "Óculos de Esqui": "Masque de ski",
  "Óculos de Solda": "Lunettes de soudeur",
  "Gravata": "Cravate",
  "Camiseta": "T-shirt",
  "Cachecol": "Écharpe",
  "Macacão": "Salopette",
  "Colete Salva-vidas": "Gilet de sauvetage",
  "Smoking": "Smoking",
  "Capa de Herói": "Cape de héros",
  "Armadura": "Armure",
  "Colar de Flores": "Collier de fleurs",
  "Lenço de Bandido": "Bandana de bandit",
  "Faixas de Múmia": "Bandelettes de momie",
  "Jaqueta de Neve": "Veste de neige",
  "Capa de Fogo": "Cape de feu",
  "Super Velocidade": "Super vitesse",
  "+60% de velocidade por 10s": "+60 % de vitesse pendant 10 s",
  "Pulo Duplo": "Double saut",
  "Pula de novo no ar por 15s": "Resaute en l'air pendant 15 s",
  "Escudo": "Bouclier",
  "Invencível por 8s": "Invincible pendant 8 s",
  "Ímã de Moedas": "Aimant à pièces",
  "Puxa as moedas por 15s": "Attire les pièces pendant 15 s",
  "Explode os inimigos perto": "Fait exploser les ennemis proches",
  "Dispara pra frente e atravessa inimigos": "Fonce en avant à travers les ennemis",
  "Coração Extra": "Cœur bonus",
  "Coração Extra II": "Cœur bonus II",
  "+1 coração de vida": "+1 cœur de vie",
  "Revólver Turbo": "Revolver turbo",
  "8 balas, tiro e recarga mais rápidos": "8 balles, tir et recharge plus rapides",
  "Cipó Longo": "Longue liane",
  "O laço de cipó alcança mais longe": "La liane-lasso va plus loin",
  "Chapéus": "Chapeaux",
  "Óculos": "Lunettes",
  "Roupas": "Tenues",
  "Poderes": "Pouvoirs",
  "Melhorias": "Améliorations",
  "Andar para a esquerda": "Marcher à gauche",
  "Andar para a direita": "Marcher à droite",
  "Pular": "Sauter",
  "Deslizar / soltar do cipó": "Glisser / lâcher la liane",
  "Revólver": "Revolver",
  "Recarregar": "Recharger",
  "Cipó-laço": "Liane-lasso",
  "Poder: Super Velocidade": "Pouvoir : Super vitesse",
  "Poder: Pulo Duplo": "Pouvoir : Double saut",
  "Poder: Escudo": "Pouvoir : Bouclier",
  "Poder: Ímã de Moedas": "Pouvoir : Aimant à pièces",
  "Poder: Nuke": "Pouvoir : Nuke",
  "Loja": "Boutique",
  "Pausa": "Pause",
  "Ligar/desligar som": "Activer/couper le son",
  "Espaço": "Espace",
  "Apagar": "Retour arrière",
  "andar": "marcher",
  "pular (segure: mais alto)": "sauter (maintenir : plus haut)",
  "deslizar": "glisser",
  "revólver": "revolver",
  "recarregar": "recharger",
  "cipó-laço (puxa o inimigo e chuta pro espaço!)": "liane-lasso (attire l'ennemi et envoie-le dans l'espace !)",
  "dash (melhoria)": "dash (amélioration)",
  "poderes": "pouvoirs",
  "loja": "boutique",
  "pausa": "pause",
  "Ação": "Action",
  "Tecla 1": "Touche 1",
  "Tecla 2": "Touche 2",
  "Tecla 3": "Touche 3",
  "aperte...": "appuie...",
  "trocar poder": "changer de pouvoir",
  "Saru": "Saru",
  "Saru Gigante": "Saru Géant",
  "Nível {0}+: um macaco lendário pode aparecer 1 vez por dia": "Niveau {0}+ : un singe légendaire peut apparaître 1 fois par jour",
  "Você venceu o Saru hoje! Ele pode voltar amanhã.": "Tu as battu Saru aujourd'hui ! Il reviendra peut-être demain.",
  "Volte amanhã: o Saru pode aparecer": "Reviens demain : Saru peut apparaître",
  "O Saru apareceu! Enfrentar ({0})": "Saru est là ! L'affronter ({0})",
  "O Saru Nv {1} apareceu! Enfrentar ({0})": "Saru Nv {1} est là ! L'affronter ({0})",
  "Nv {0}": "Nv {0}",
  "Nível {0}: mais vida, mais rápido e furioso mais cedo": "Niveau {0} : plus de vie, plus rapide et enragé plus tôt",
  "Você venceu o Saru hoje! Ele pode voltar amanhã, mais forte.": "Tu as battu Saru aujourd'hui ! Il reviendra peut-être demain, plus fort.",
  "Saru: +3 tentativas (anúncio)": "Saru : +3 essais (pub)",
  "Sem tentativas contra o Saru hoje. Volte amanhã!": "Plus d'essais contre Saru aujourd'hui. Reviens demain !",
  "O Saru venceu!": "Saru a gagné !",
  "Tentativas restantes: {0}": "Essais restants : {0}",
  "Nova skin: Saru  ·  Nova melhoria: Nuvem Mágica  ·  +{0} moedas": "Nouveau skin : Saru  ·  Nouvelle amélioration : Nuage magique  ·  +{0} pièces",
  "Saru derrotado!": "Saru vaincu !",
  "A lua cheia nasceu...": "La pleine lune se lève...",
  "Fase {0}/2": "Phase {0}/2",
  "O macaco lendário! Tentativas restantes: {0}": "Le singe légendaire ! Essais restants : {0}",
  "Nuvem Mágica!": "Nuage magique !",
  "Nuvem Mágica": "Nuage magique",
  "Uma vez por fase, se cair num buraco, a nuvem te salva sem perder vida": "Une fois par niveau, si tu tombes dans un trou, le nuage te sauve sans perdre de vie",
  "Derrote o Saru": "Bats Saru",
  "Volte amanhã: ele pode aparecer de novo.": "Reviens demain : il peut réapparaître.",
  "Tentar de novo (Enter)": "Réessayer (Entrée)",
  "Assistir anúncio: +3 tentativas": "Regarder une pub : +3 essais",
  "Voltar ao menu (Esc)": "Retour au menu (Échap)",
  "Opções": "Options",
  "Idioma": "Langue",
  "Adicionais": "Extras",
  "Escolha o idioma do jogo.": "Choisis la langue du jeu.",
  "O cronômetro mostra o tempo da run e de cada fase, com os seus recordes.": "Le chrono affiche le temps de la partie et de chaque niveau, avec tes records.",
  "Assistir anúncio: +{0} moedas": "Regarder une pub : +{0} pièces",
  "Grátis (anúncio)": "Gratuit (pub)",
  "+{0} moedas!": "+{0} pièces !",
  "+1 {0}!": "+1 {0} !",
  "O anúncio não terminou, nada ganho.": "La pub ne s'est pas terminée, aucune récompense.",
  "Moedas grátis": "Pièces gratuites",
  "Completa": "Terminé",
  "Sem perder vida": "Sans perdre de vie",
  "Até {0}": "En moins de {0}",
  "NOVA!": "NOUVEAU !",
  "Tempo {0}": "Temps {0}",
  "Recorde {0}": "Record {0}",
  "Estrelas: {0}/{1}": "Étoiles : {0}/{1}",
  "Modo speedrun liberado! O cronômetro foi ligado.": "Mode speedrun débloqué ! Le chrono est activé.",
  "Zerado! Jogar = nova run": "Terminé ! Jouer = nouvelle partie",
  "PULO": "SAUT",
  "TIRO": "TIR",
  "LAÇO": "LASSO",
  "LOJA": "BOUTIQUE",
  "PAUSA": "PAUSE",
  "arraste do lado esquerdo: andar e deslizar": "glisse à gauche : marcher et glisser",
  "toque nos poderes para usar": "touche un pouvoir pour l'utiliser",
  "Toque na tela para começar": "Touche l'écran pour commencer",
  "Toque na tela para voltar ao menu": "Touche l'écran pour revenir au menu",
  "usar poder": "utiliser un pouvoir",
  "Jogo zerado!": "Jeu terminé !",
  "Próxima: {0}": "Suivant : {0}",
  " · Recorde: {0}": " · Record : {0}",
  "Som: ligado ({0})": "Son : activé ({0})",
  "Som: desligado ({0})": "Son : coupé ({0})",
  "Cronômetro: ligado": "Chrono : activé",
  "Cronômetro: desligado": "Chrono : désactivé",
  "Idioma: Português": "Langue : Français",
  "Chefe": "Boss",
  "Chefe: ": "Boss : ",
  "Prêmio": "Récompense",
  "Épico": "Épique",
  "Raro": "Rare",
  "Comum": "Commun",
  "{0}. Tecla {1}.": "{0}. Touche {1}.",
  "Você tem: {0}": "Tu en as : {0}",
  "Comprar": "Acheter",
  "Faltam {0}": "Il manque {0}",
  "{0} (permanente)": "{0} (permanent)",
  "Comprado": "Acheté",
  "Precisa: {0}": "Requis : {0}",
  "Equipado": "Équipé",
  "Seu": "Acquis",
  "Passe a fase {0}": "Termine {0}",
  "Chegue ao nível {0}": "Atteins le niveau {0}",
  "Bloqueado": "Verrouillé",
  "Tirar": "Retirer",
  "Equipar": "Équiper",
  "-1 vida": "-1 vie",
  "recarregando": "recharge",
  "Você perdeu!": "Perdu !",
  "Voltando do checkpoint...": "Retour au point de contrôle...",
  "Tentando de novo...": "Nouvel essai...",
  "Fase completa!": "Niveau terminé !",
  "{0} completo!": "{0} terminé !",
  "A banana escapou de novo! Próximo: {0}": "La banane s'est encore échappée ! Suivant : {0}",
  "Você ganhou: {0}!  Próximo: {1}": "Tu as gagné : {0} !  Suivant : {1}",
  "Chefe derrotado!": "Boss vaincu !",
  "+{0} moedas. Pegue a banana!": "+{0} pièces. Attrape la banane !",
  "Reviveu!": "De retour !",
  "+{0} moedas": "+{0} pièces",
  "  ·  Nova skin: {0}!": "  ·  Nouveau skin : {0} !",
  "NÍVEL {0}!": "NIVEAU {0} !",
  "{0} - o chefe do mundo": "{0} - le boss du monde",
  "Novo inimigo: {0}": "Nouvel ennemi : {0}",
  "Novo obstáculo: {0}": "Nouvel obstacle : {0}",
  "Prêmio ao terminar: {0}": "Récompense à la fin : {0}",
  "FASE": "NIVEAU",
  "Recorde da fase": "Record du niveau",
  "Primeiro tempo!": "Premier temps !",
  "{0}  Recorde!": "{0}  Record !",
  "  (primeira run!)": "  (première partie !)",
  "  NOVO RECORDE! ({0})": "  NOUVEAU RECORD ! ({0})",
  "  (recorde: {0})": "  (record : {0})",
  "O vento levou a banana!": "Le vent a emporté la banane !",
  "Atravesse a Selva, o Deserto, a Era do Gelo e o Vulcão para recuperá-la!": "Traverse la Jungle, le Désert, l'Ère glaciaire et le Volcan pour la récupérer !",
  "Dizem que ela foi parar nas garras do Dragão de Magma...": "On dit qu'elle a fini entre les griffes du Dragon de Magma...",
  "Clique ou aperte qualquer tecla para começar": "Clique ou appuie sur une touche pour commencer",
  "Nham!": "Miam !",
  "FIM!": "FIN !",
  "O primata derrotou o Dragão de Magma e finalmente comeu a sua banana!": "Le primate a vaincu le Dragon de Magma et a enfin mangé sa banane !",
  "Nível {0}   ·   Moedas: {1}": "Niveau {0}   ·   Pièces : {1}",
  "Inimigos derrotados: {0}   ·   Chutados pro espaço: {1}": "Ennemis vaincus : {0}   ·   Envoyés dans l'espace : {1}",
  "Chefes derrotados: {0}   ·   Quedas: {1}": "Boss vaincus : {0}   ·   Chutes : {1}",
  "Tempo de jogo: {0}": "Temps de jeu : {0}",
  "Nova skin: {0}!": "Nouveau skin : {0} !",
  "Clique ou aperte qualquer tecla para voltar ao menu": "Clique ou appuie sur une touche pour revenir au menu",
  "PAUSA (P)": "PAUSE (P)",
  "LOJA (L)": "BOUTIQUE (L)",
  "A grande caçada à banana": "La grande chasse à la banane",
  "moedas": "pièces",
  "Fase": "Niveau",
  "Nível": "Niveau",
  "Jogar (Enter)": "Jouer (Entrée)",
  "Escolher fase": "Choisir un niveau",
  "Controles": "Commandes",
  "Escolha a fase": "Choisis un niveau",
  "Voltar": "Retour",
  "Pausado": "En pause",
  "Continuar (P)": "Reprendre (P)",
  "Loja (L)": "Boutique (L)",
  "Recomeçar fase": "Recommencer le niveau",
  "Som": "Son",
  "Cronômetro": "Chrono",
  "Menu principal": "Menu principal",
  "Assista um anúncio para continuar daqui com todas as vidas.": "Regarde une pub pour continuer d'ici avec toutes tes vies.",
  "Assistir e reviver (Enter)": "Regarder et revivre (Entrée)",
  "Voltar do checkpoint (Esc)": "Retour au point de contrôle (Échap)",
  "Clique numa tecla e aperte a nova.": "Clique sur une touche puis appuie sur la nouvelle.",
  "apaga.": "l'efface.",
  "volta.": "revient.",
  "Restaurar padrão": "Par défaut",
  "Loja do Primata": "Boutique du Primate",
  "L ou Esc para voltar": "L ou Échap pour revenir",
  "{0} ou Esc para voltar": "{0} ou Échap pour revenir",
  "Continuar": "Reprendre"
};
