"use strict";
// Italiano. Chave: o texto em português (igual ao EN de idioma.js). Faltou alguma? Cai no inglês.
TRADUCOES.it = {
  "Selva": "Giungla",
  "Deserto": "Deserto",
  "Era do Gelo": "Era Glaciale",
  "Vulcão de Lava": "Vulcano di Lava",
  "Gorila Rei": "Gorilla Re",
  "Escorpião Faraó": "Scorpione Faraone",
  "Yeti Ancestral": "Yeti Ancestrale",
  "Dragão de Magma": "Drago di Magma",
  "{0} - Chefe": "{0} - Boss",
  "Espinhos": "Spuntoni",
  "Cipós de balançar": "Liane oscillanti",
  "Cogumelo pula-pula": "Fungo rimbalzante",
  "Troncos rolando": "Tronchi rotolanti",
  "Plantas carnívoras": "Piante carnivore",
  "Areia movediça": "Sabbie mobili",
  "Redemoinho": "Mulinello",
  "Armadilha de dardos": "Trappola a dardi",
  "Pedras rolando": "Massi rotolanti",
  "Ventania de areia": "Tempesta di sabbia",
  "Túnel de gelo (deslize!)": "Tunnel di ghiaccio (scivola!)",
  "Estalactites": "Stalattiti",
  "Pista de gelo": "Pista di ghiaccio",
  "Gelo fino": "Ghiaccio sottile",
  "Avalanche": "Valanga",
  "Lago de lava": "Lago di lava",
  "Rocha de impulso": "Roccia di spinta",
  "Plataformas que caem": "Piattaforme che cadono",
  "Barra de fogo": "Barra di fuoco",
  "Chuva de meteoros": "Pioggia di meteore",
  "Cobra": "Serpente",
  "Abelha": "Ape",
  "Sapo": "Rana",
  "Macaco Ladrão": "Scimmia Ladra",
  "Aranha": "Ragno",
  "Escorpião": "Scorpione",
  "Abutre": "Avvoltoio",
  "Cacto Atirador": "Cactus Sparatore",
  "Múmia": "Mummia",
  "Tatu-bola": "Armadillo",
  "Pinguim": "Pinguino",
  "Morcego de Gelo": "Pipistrello di Ghiaccio",
  "Boneco de Neve": "Pupazzo di Neve",
  "Foca": "Foca",
  "Lobo do Gelo": "Lupo dei Ghiacci",
  "Slime de Magma": "Slime di Magma",
  "Morcego de Fogo": "Pipistrello di Fuoco",
  "Diabinho": "Diavoletto",
  "Golem de Pedra": "Golem di Pietra",
  "Fênix": "Fenice",
  "{esquerda}/{direita} andar   {pulo} pular\nSegure {pulo} para pular mais alto": "{esquerda}/{direita} cammina   {pulo} salta\nTieni premuto {pulo} per saltare più in alto",
  "Bem-vindo: {0}!": "Benvenuto: {0}!",
  "Novo inimigo: {0}!": "Nuovo nemico: {0}!",
  "Novo inimigo: Cobra! Pule na cabeça dela!": "Nuovo nemico: Serpente! Saltale sulla testa!",
  "Seu prêmio: cipó-laço! {laco}: puxa o inimigo": "Il tuo premio: liana-lazo! {laco}: tira a te il nemico",
  "Vença o Gorila Rei para ganhar o cipó-laço!": "Sconfiggi il Gorilla Re per ottenere la liana-lazo!",
  "Você ganhou o cipó-laço!": "Hai ottenuto la liana-lazo!",
  "Arraste para andar": "Trascina per camminare",
  "Tutorial": "Tutorial",
  "Boa!": "Ottimo!",
  "Arraste o analógico para a direita": "Trascina la levetta a destra",
  "Ande para a direita: {0}": "Cammina a destra: {0}",
  "Toque em PULO para pular o bloco": "Tocca SALTO per saltare il blocco",
  "Pule o bloco: {0}": "Salta il blocco: {0}",
  "Pule na cabeça da cobra!": "Salta sulla testa del serpente!",
  "Pegue a banana!": "Prendi la banana!",
  "Tutorial completo!": "Tutorial completato!",
  "ou": "o",
  "Agora é pra valer: atravesse os 4 mundos!": "Ora si fa sul serio: attraversa i 4 mondi!",
  "Toque para pular": "Tocca per saltare",
  "{0}: puxa o inimigo e chuta pro espaço. Pegue a banana!": "{0}: tira a te il nemico e calcialo nello spazio. Prendi la banana!",
  "Novo: {0}!": "Novità: {0}!",
  "Pule por cima dos espinhos!": "Salta sopra gli spuntoni!",
  "Pule no cipó para se agarrar!\n{pulo} solta": "Salta sulla liana per aggrapparti!\n{pulo} per mollare",
  "Pule no cogumelo para ir bem alto!": "Salta sul fungo per andare altissimo!",
  "Pule por cima deles!": "Saltaci sopra!",
  "Passe quando a planta se esconder!": "Passa quando la pianta si nasconde!",
  "Pule rápido para não afundar!": "Salta in fretta per non affondare!",
  "Entre no redemoinho para subir!": "Entra nel mulinello per salire!",
  "Pule os dardos de baixo,\ndeslize ({baixo}) nos de cima!": "Salta i dardi in basso,\nscivola ({baixo}) sotto quelli in alto!",
  "Elas são enormes: pule na hora certa!": "Sono enormi: salta al momento giusto!",
  "Espere o vento parar para pular!": "Aspetta che il vento si fermi per saltare!",
  "Corra e segure {baixo} para deslizar!": "Corri e tieni premuto {baixo} per scivolare!",
  "Não pare embaixo das estalactites!": "Non fermarti sotto le stalattiti!",
  "Deslize ({baixo}) no gelo para pular longe!": "Scivola ({baixo}) sul ghiaccio per saltare lontano!",
  "O gelo fino quebra! Não fique parado": "Il ghiaccio sottile si rompe! Non stare fermo",
  "Pule as bolas de neve!": "Salta le palle di neve!",
  "Lava queima! Pule por cima": "La lava brucia! Saltaci sopra",
  "Pule na rocha de magma: IMPULSO!": "Salta sulla roccia di magma: SPINTA!",
  "Essas plataformas despencam!": "Queste piattaforme crollano!",
  "Passe quando a barra de fogo girar!": "Passa quando la barra di fuoco gira!",
  "Fuja das sombras vermelhas!": "Evita le ombre rosse!",
  "Pule na cabeça dela!": "Saltale sulla testa!",
  "Ela voa: pule nela ou passe por baixo!": "Vola: saltale sopra o passale sotto!",
  "Ele pula atrás de você!": "Ti insegue saltando!",
  "Ele joga cocos!": "Lancia noci di cocco!",
  "Ela desce quando você passa!": "Scende quando passi!",
  "Pule na cabeça dele!": "Saltagli sulla testa!",
  "Ele mergulha em você!": "Si getta in picchiata su di te!",
  "Espinhoso: não pise, deslize nele!": "Spinoso: non saltarci sopra, scivolaci contro!",
  "Lenta mas resistente!": "Lenta ma resistente!",
  "Não pise quando ele rolar!": "Non saltarci sopra mentre rotola!",
  "Ele escorrega na sua direção!": "Scivola verso di te!",
  "Voa rápido!": "Vola veloce!",
  "Joga bolas de neve!": "Lancia palle di neve!",
  "Pula atrás de você!": "Ti insegue saltando!",
  "Corre muito rápido!": "Corre velocissimo!",
  "Quente: não pise, deslize nele!": "Rovente: non saltarci sopra, scivolaci contro!",
  "Voa muito rápido!": "Vola velocissimo!",
  "Atira bolas de fogo!": "Spara palle di fuoco!",
  "Pule na cabeça ou use o cipó-laço!": "Saltagli in testa o usa la liana-lazo!",
  "Mergulha soltando fogo!": "Si getta in picchiata sputando fuoco!",
  "Clássico": "Classico",
  "Dourado": "Dorato",
  "Chiclete": "Gomma da masticare",
  "Gelo": "Ghiaccio",
  "Sombra": "Ombra",
  "Camuflado": "Mimetico",
  "Fogo": "Fuoco",
  "Dálmata": "Dalmata",
  "Zumbi": "Zombie",
  "Robô": "Robot",
  "Esqueleto": "Scheletro",
  "Fantasma": "Fantasma",
  "Diamante": "Diamante",
  "Galáxia": "Galassia",
  "Arco-íris": "Arcobaleno",
  "Tigre": "Tigre",
  "Gorila": "Gorilla",
  "Camelo": "Cammello",
  "Dragão": "Drago",
  "Prata": "Argento",
  "Ouro": "Oro",
  "Lendário": "Leggendario",
  "Boné": "Berretto",
  "Chapéu de Festa": "Cappellino da festa",
  "Gorro": "Berretto di lana",
  "Chapéu de Cowboy": "Cappello da cowboy",
  "Cartola": "Cilindro",
  "Chapéu de Chef": "Cappello da chef",
  "Capacete Viking": "Elmo vichingo",
  "Auréola": "Aureola",
  "Coroa": "Corona",
  "Folha": "Foglia",
  "Chapéu de Explorador": "Cappello da esploratore",
  "Turbante": "Turbante",
  "Coroa de Faraó": "Corona da faraone",
  "Protetor de Orelha": "Paraorecchie",
  "Chapéu de Pele": "Colbacco",
  "Capacete de Bombeiro": "Casco da pompiere",
  "Chifres de Demônio": "Corna da demone",
  "Óculos Escuros": "Occhiali da sole",
  "Óculos 3D": "Occhiali 3D",
  "Óculos de Nerd": "Occhiali da nerd",
  "Máscara": "Maschera",
  "Óculos de Coração": "Occhiali a cuore",
  "Monóculo": "Monocolo",
  "Visor Cyber": "Visore cyber",
  "Pintura de Guerra": "Pittura di guerra",
  "Óculos de Aviador": "Occhiali da aviatore",
  "Óculos de Esqui": "Maschera da sci",
  "Óculos de Solda": "Occhiali da saldatore",
  "Gravata": "Cravatta",
  "Camiseta": "Maglietta",
  "Cachecol": "Sciarpa",
  "Macacão": "Salopette",
  "Colete Salva-vidas": "Giubbotto salvagente",
  "Smoking": "Smoking",
  "Capa de Herói": "Mantello da eroe",
  "Armadura": "Armatura",
  "Colar de Flores": "Collana di fiori",
  "Lenço de Bandido": "Bandana da bandito",
  "Faixas de Múmia": "Bende da mummia",
  "Jaqueta de Neve": "Giacca da neve",
  "Capa de Fogo": "Mantello di fuoco",
  "Super Velocidade": "Super velocità",
  "+60% de velocidade por 10s": "+60% di velocità per 10 s",
  "Pulo Duplo": "Doppio salto",
  "Pula de novo no ar por 15s": "Salta di nuovo in aria per 15 s",
  "Escudo": "Scudo",
  "Invencível por 8s": "Invincibile per 8 s",
  "Ímã de Moedas": "Calamita per monete",
  "Puxa as moedas por 15s": "Attira le monete per 15 s",
  "Explode os inimigos perto": "Fa esplodere i nemici vicini",
  "Dispara pra frente e atravessa inimigos": "Scatta in avanti attraversando i nemici",
  "Coração Extra": "Cuore extra",
  "Coração Extra II": "Cuore extra II",
  "+1 coração de vida": "+1 cuore di vita",
  "Revólver Turbo": "Revolver turbo",
  "8 balas, tiro e recarga mais rápidos": "8 colpi, sparo e ricarica più veloci",
  "Cipó Longo": "Liana lunga",
  "O laço de cipó alcança mais longe": "La liana-lazo arriva più lontano",
  "Chapéus": "Cappelli",
  "Óculos": "Occhiali",
  "Roupas": "Vestiti",
  "Poderes": "Poteri",
  "Melhorias": "Potenziamenti",
  "Andar para a esquerda": "Cammina a sinistra",
  "Andar para a direita": "Cammina a destra",
  "Pular": "Salta",
  "Deslizar / soltar do cipó": "Scivola / molla la liana",
  "Revólver": "Revolver",
  "Recarregar": "Ricarica",
  "Cipó-laço": "Liana-lazo",
  "Poder: Super Velocidade": "Potere: Super velocità",
  "Poder: Pulo Duplo": "Potere: Doppio salto",
  "Poder: Escudo": "Potere: Scudo",
  "Poder: Ímã de Moedas": "Potere: Calamita per monete",
  "Poder: Nuke": "Potere: Nuke",
  "Loja": "Negozio",
  "Pausa": "Pausa",
  "Ligar/desligar som": "Audio sì/no",
  "Espaço": "Spazio",
  "Apagar": "Backspace",
  "andar": "camminare",
  "pular (segure: mais alto)": "saltare (tieni premuto: più in alto)",
  "deslizar": "scivolare",
  "revólver": "revolver",
  "recarregar": "ricaricare",
  "cipó-laço (puxa o inimigo e chuta pro espaço!)": "liana-lazo (tira a te il nemico e calcialo nello spazio!)",
  "dash (melhoria)": "scatto (potenziamento)",
  "poderes": "poteri",
  "loja": "negozio",
  "pausa": "pausa",
  "Ação": "Azione",
  "Tecla 1": "Tasto 1",
  "Tecla 2": "Tasto 2",
  "Tecla 3": "Tasto 3",
  "aperte...": "premi...",
  "trocar poder": "cambia potere",
  "Saru": "Saru",
  "Saru Gigante": "Saru Gigante",
  "Nível {0}+: um macaco lendário pode aparecer 1 vez por dia": "Livello {0}+: una scimmia leggendaria può apparire 1 volta al giorno",
  "Você venceu o Saru hoje! Ele pode voltar amanhã.": "Oggi hai battuto Saru! Potrebbe tornare domani.",
  "Volte amanhã: o Saru pode aparecer": "Torna domani: Saru potrebbe apparire",
  "O Saru apareceu! Enfrentar ({0})": "È apparso Saru! Affrontalo ({0})",
  "O Saru Nv {1} apareceu! Enfrentar ({0})": "È apparso Saru Lv {1}! Affrontalo ({0})",
  "Nv {0}": "Lv {0}",
  "Nível {0}: mais vida, mais rápido e furioso mais cedo": "Livello {0}: più vita, più veloce e si infuria prima",
  "Você venceu o Saru hoje! Ele pode voltar amanhã, mais forte.": "Oggi hai battuto Saru! Potrebbe tornare domani, più forte.",
  "Saru: +3 tentativas (anúncio)": "Saru: +3 tentativi (pubblicità)",
  "Sem tentativas contra o Saru hoje. Volte amanhã!": "Niente più tentativi contro Saru oggi. Torna domani!",
  "O Saru venceu!": "Ha vinto Saru!",
  "Tentativas restantes: {0}": "Tentativi rimasti: {0}",
  "Nova skin: Saru  ·  Nova melhoria: Nuvem Mágica  ·  +{0} moedas": "Nuova skin: Saru  ·  Nuovo potenziamento: Nuvola Magica  ·  +{0} monete",
  "Saru derrotado!": "Saru sconfitto!",
  "A lua cheia nasceu...": "È sorta la luna piena...",
  "Fase {0}/2": "Fase {0}/2",
  "O macaco lendário! Tentativas restantes: {0}": "La scimmia leggendaria! Tentativi rimasti: {0}",
  "Nuvem Mágica!": "Nuvola Magica!",
  "Nuvem Mágica": "Nuvola Magica",
  "Uma vez por fase, se cair num buraco, a nuvem te salva sem perder vida": "Una volta per livello, se cadi in un buco, la nuvola ti salva senza perdere vite",
  "Derrote o Saru": "Sconfiggi Saru",
  "Volte amanhã: ele pode aparecer de novo.": "Torna domani: potrebbe riapparire.",
  "Tentar de novo (Enter)": "Riprova (Invio)",
  "Assistir anúncio: +3 tentativas": "Guarda pubblicità: +3 tentativi",
  "Voltar ao menu (Esc)": "Torna al menu (Esc)",
  "Opções": "Opzioni",
  "Idioma": "Lingua",
  "Adicionais": "Extra",
  "Escolha o idioma do jogo.": "Scegli la lingua del gioco.",
  "O cronômetro mostra o tempo da run e de cada fase, com os seus recordes.": "Il cronometro mostra il tempo della partita e di ogni livello, con i tuoi record.",
  "Assistir anúncio: +{0} moedas": "Guarda pubblicità: +{0} monete",
  "Grátis (anúncio)": "Gratis (pubblicità)",
  "+{0} moedas!": "+{0} monete!",
  "+1 {0}!": "+1 {0}!",
  "O anúncio não terminou, nada ganho.": "La pubblicità non è finita, nessun premio.",
  "Moedas grátis": "Monete gratis",
  "Completa": "Completato",
  "Sem perder vida": "Senza perdere vite",
  "Até {0}": "Entro {0}",
  "NOVA!": "NUOVA!",
  "Tempo {0}": "Tempo {0}",
  "Recorde {0}": "Record {0}",
  "Estrelas: {0}/{1}": "Stelle: {0}/{1}",
  "Modo speedrun liberado! O cronômetro foi ligado.": "Modalità speedrun sbloccata! Il cronometro è attivo.",
  "Zerado! Jogar = nova run": "Completato! Gioca = nuova partita",
  "PULO": "SALTO",
  "TIRO": "SPARO",
  "LAÇO": "LAZO",
  "LOJA": "NEGOZIO",
  "PAUSA": "PAUSA",
  "arraste do lado esquerdo: andar e deslizar": "trascina a sinistra: cammina e scivola",
  "toque nos poderes para usar": "tocca un potere per usarlo",
  "Toque na tela para começar": "Tocca lo schermo per iniziare",
  "Toque na tela para voltar ao menu": "Tocca lo schermo per tornare al menu",
  "usar poder": "usa potere",
  "Jogo zerado!": "Gioco completato!",
  "Próxima: {0}": "Prossimo: {0}",
  " · Recorde: {0}": " · Record: {0}",
  "Som: ligado ({0})": "Audio: sì ({0})",
  "Som: desligado ({0})": "Audio: no ({0})",
  "Cronômetro: ligado": "Cronometro: sì",
  "Cronômetro: desligado": "Cronometro: no",
  "Idioma: Português": "Lingua: Italiano",
  "Chefe": "Boss",
  "Chefe: ": "Boss: ",
  "Prêmio": "Premio",
  "Épico": "Epico",
  "Raro": "Raro",
  "Comum": "Comune",
  "{0}. Tecla {1}.": "{0}. Tasto {1}.",
  "Você tem: {0}": "Ne hai: {0}",
  "Comprar": "Compra",
  "Faltam {0}": "Mancano {0}",
  "{0} (permanente)": "{0} (permanente)",
  "Comprado": "Acquistato",
  "Precisa: {0}": "Richiede: {0}",
  "Equipado": "Equipaggiato",
  "Seu": "Tuo",
  "Passe a fase {0}": "Supera {0}",
  "Chegue ao nível {0}": "Raggiungi il livello {0}",
  "Bloqueado": "Bloccato",
  "Tirar": "Togli",
  "Equipar": "Equipaggia",
  "-1 vida": "-1 vita",
  "recarregando": "ricarica",
  "Você perdeu!": "Hai perso!",
  "Voltando do checkpoint...": "Si riparte dal checkpoint...",
  "Tentando de novo...": "Nuovo tentativo...",
  "Fase completa!": "Livello completato!",
  "{0} completo!": "{0} completato!",
  "A banana escapou de novo! Próximo: {0}": "La banana è scappata di nuovo! Prossimo: {0}",
  "Você ganhou: {0}!  Próximo: {1}": "Hai ottenuto: {0}!  Prossimo: {1}",
  "Chefe derrotado!": "Boss sconfitto!",
  "+{0} moedas. Pegue a banana!": "+{0} monete. Prendi la banana!",
  "Reviveu!": "Sei tornato in vita!",
  "+{0} moedas": "+{0} monete",
  "  ·  Nova skin: {0}!": "  ·  Nuova skin: {0}!",
  "NÍVEL {0}!": "LIVELLO {0}!",
  "{0} - o chefe do mundo": "{0} - il boss del mondo",
  "Novo inimigo: {0}": "Nuovo nemico: {0}",
  "Novo obstáculo: {0}": "Nuovo ostacolo: {0}",
  "Prêmio ao terminar: {0}": "Premio alla fine: {0}",
  "FASE": "LIVELLO",
  "Recorde da fase": "Record del livello",
  "Primeiro tempo!": "Primo tempo!",
  "{0}  Recorde!": "{0}  Record!",
  "  (primeira run!)": "  (prima partita!)",
  "  NOVO RECORDE! ({0})": "  NUOVO RECORD! ({0})",
  "  (recorde: {0})": "  (record: {0})",
  "O vento levou a banana!": "Il vento si è portato via la banana!",
  "Atravesse a Selva, o Deserto, a Era do Gelo e o Vulcão para recuperá-la!": "Attraversa la Giungla, il Deserto, l'Era Glaciale e il Vulcano per riprenderla!",
  "Dizem que ela foi parar nas garras do Dragão de Magma...": "Dicono che sia finita negli artigli del Drago di Magma...",
  "Clique ou aperte qualquer tecla para começar": "Clicca o premi un tasto per iniziare",
  "Nham!": "Gnam!",
  "FIM!": "FINE!",
  "O primata derrotou o Dragão de Magma e finalmente comeu a sua banana!": "Il primate ha sconfitto il Drago di Magma e finalmente ha mangiato la sua banana!",
  "Nível {0}   ·   Moedas: {1}": "Livello {0}   ·   Monete: {1}",
  "Inimigos derrotados: {0}   ·   Chutados pro espaço: {1}": "Nemici sconfitti: {0}   ·   Calciati nello spazio: {1}",
  "Chefes derrotados: {0}   ·   Quedas: {1}": "Boss sconfitti: {0}   ·   Cadute: {1}",
  "Tempo de jogo: {0}": "Tempo di gioco: {0}",
  "Nova skin: {0}!": "Nuova skin: {0}!",
  "Clique ou aperte qualquer tecla para voltar ao menu": "Clicca o premi un tasto per tornare al menu",
  "PAUSA (P)": "PAUSA (P)",
  "LOJA (L)": "NEGOZIO (L)",
  "A grande caçada à banana": "La grande caccia alla banana",
  "moedas": "monete",
  "Fase": "Livello",
  "Nível": "Livello",
  "Jogar (Enter)": "Gioca (Invio)",
  "Escolher fase": "Scegli livello",
  "Controles": "Comandi",
  "Escolha a fase": "Scegli un livello",
  "Voltar": "Indietro",
  "Pausado": "In pausa",
  "Continuar (P)": "Riprendi (P)",
  "Loja (L)": "Negozio (L)",
  "Recomeçar fase": "Ricomincia livello",
  "Som": "Audio",
  "Cronômetro": "Cronometro",
  "Menu principal": "Menu principale",
  "Assista um anúncio para continuar daqui com todas as vidas.": "Guarda una pubblicità per continuare da qui con tutte le vite.",
  "Assistir e reviver (Enter)": "Guarda e rinasci (Invio)",
  "Voltar do checkpoint (Esc)": "Riparti dal checkpoint (Esc)",
  "Clique numa tecla e aperte a nova.": "Clicca su un tasto e premi quello nuovo.",
  "apaga.": "lo cancella.",
  "volta.": "torna indietro.",
  "Restaurar padrão": "Ripristina",
  "Loja do Primata": "Negozio del Primate",
  "L ou Esc para voltar": "L o Esc per tornare",
  "{0} ou Esc para voltar": "{0} o Esc per tornare",
  "Continuar": "Riprendi"
};
