"use strict";
// Nederlands. Chave: o texto em português (igual ao EN de idioma.js). Faltou alguma? Cai no inglês.
TRADUCOES.nl = {
  "Selva": "Jungle",
  "Deserto": "Woestijn",
  "Era do Gelo": "IJstijd",
  "Vulcão de Lava": "Lavavulkaan",
  "Gorila Rei": "Gorillakoning",
  "Escorpião Faraó": "Farao-schorpioen",
  "Yeti Ancestral": "Oeroude Yeti",
  "Dragão de Magma": "Magmadraak",
  "{0} - Chefe": "{0} - Baas",
  "Espinhos": "Stekels",
  "Cipós de balançar": "Slingerlianen",
  "Cogumelo pula-pula": "Stuiterpaddenstoel",
  "Troncos rolando": "Rollende boomstammen",
  "Plantas carnívoras": "Vleesetende planten",
  "Areia movediça": "Drijfzand",
  "Redemoinho": "Wervelwind",
  "Armadilha de dardos": "Pijlenval",
  "Pedras rolando": "Rollende rotsblokken",
  "Ventania de areia": "Zandstorm",
  "Túnel de gelo (deslize!)": "IJstunnel (glijden!)",
  "Estalactites": "IJspegels",
  "Pista de gelo": "IJsbaan",
  "Gelo fino": "Dun ijs",
  "Avalanche": "Lawine",
  "Lago de lava": "Lavameer",
  "Rocha de impulso": "Lanceerrots",
  "Plataformas que caem": "Vallende platforms",
  "Barra de fogo": "Vuurstaaf",
  "Chuva de meteoros": "Meteorietenregen",
  "Cobra": "Slang",
  "Abelha": "Bij",
  "Sapo": "Kikker",
  "Macaco Ladrão": "Dievenaap",
  "Aranha": "Spin",
  "Escorpião": "Schorpioen",
  "Abutre": "Gier",
  "Cacto Atirador": "Schietcactus",
  "Múmia": "Mummie",
  "Tatu-bola": "Gordeldier",
  "Pinguim": "Pinguïn",
  "Morcego de Gelo": "IJsvleermuis",
  "Boneco de Neve": "Sneeuwpop",
  "Foca": "Zeehond",
  "Lobo do Gelo": "IJswolf",
  "Slime de Magma": "Magmaslijm",
  "Morcego de Fogo": "Vuurvleermuis",
  "Diabinho": "Duiveltje",
  "Golem de Pedra": "Stenen golem",
  "Fênix": "Feniks",
  "{esquerda}/{direita} andar   {pulo} pular\nSegure {pulo} para pular mais alto": "{esquerda}/{direita} lopen   {pulo} springen\nHoud {pulo} ingedrukt om hoger te springen",
  "Bem-vindo: {0}!": "Welkom: {0}!",
  "Novo inimigo: {0}!": "Nieuwe vijand: {0}!",
  "Novo inimigo: Cobra! Pule na cabeça dela!": "Nieuwe vijand: Slang! Spring op haar kop!",
  "Seu prêmio: cipó-laço! {laco}: puxa o inimigo": "Jouw prijs: de lianenlasso! {laco}: trekt vijanden naar je toe",
  "Vença o Gorila Rei para ganhar o cipó-laço!": "Versla de Gorillakoning voor de lianenlasso!",
  "Você ganhou o cipó-laço!": "Je hebt de lianenlasso!",
  "Arraste para andar": "Sleep om te lopen",
  "Tutorial": "Tutorial",
  "Boa!": "Goed zo!",
  "Arraste o analógico para a direita": "Sleep de stick naar rechts",
  "Ande para a direita: {0}": "Loop naar rechts: {0}",
  "Toque em PULO para pular o bloco": "Tik op SPRING om over het blok te springen",
  "Pule o bloco: {0}": "Spring over het blok: {0}",
  "Pule na cabeça da cobra!": "Spring op de kop van de slang!",
  "Pegue a banana!": "Pak de banaan!",
  "Tutorial completo!": "Tutorial voltooid!",
  "ou": "of",
  "Agora é pra valer: atravesse os 4 mundos!": "Nu menens: doorkruis alle 4 werelden!",
  "Toque para pular": "Tik om te springen",
  "{0}: puxa o inimigo e chuta pro espaço. Pegue a banana!": "{0}: trek vijanden naar je toe en schop ze de ruimte in. Pak de banaan!",
  "Novo: {0}!": "Nieuw: {0}!",
  "Pule por cima dos espinhos!": "Spring over de stekels!",
  "Pule no cipó para se agarrar!\n{pulo} solta": "Spring naar de liaan om je vast te grijpen!\n{pulo} laat los",
  "Pule no cogumelo para ir bem alto!": "Spring op de paddenstoel om heel hoog te komen!",
  "Pule por cima deles!": "Spring eroverheen!",
  "Passe quando a planta se esconder!": "Ga erlangs als de plant zich verstopt!",
  "Pule rápido para não afundar!": "Spring snel, anders zak je weg!",
  "Entre no redemoinho para subir!": "Ga de wervelwind in om omhoog te komen!",
  "Pule os dardos de baixo,\ndeslize ({baixo}) nos de cima!": "Spring over de lage pijlen,\nglij ({baixo}) onder de hoge door!",
  "Elas são enormes: pule na hora certa!": "Ze zijn enorm: spring op het juiste moment!",
  "Espere o vento parar para pular!": "Wacht tot de wind stopt en spring dan!",
  "Corra e segure {baixo} para deslizar!": "Ren en houd {baixo} ingedrukt om te glijden!",
  "Não pare embaixo das estalactites!": "Blijf niet onder de ijspegels staan!",
  "Deslize ({baixo}) no gelo para pular longe!": "Glij ({baixo}) over het ijs om ver te springen!",
  "O gelo fino quebra! Não fique parado": "Dun ijs breekt! Blijf in beweging",
  "Pule as bolas de neve!": "Spring over de sneeuwballen!",
  "Lava queima! Pule por cima": "Lava brandt! Spring eroverheen",
  "Pule na rocha de magma: IMPULSO!": "Spring op de magmarots: BOOST!",
  "Essas plataformas despencam!": "Deze platforms storten neer!",
  "Passe quando a barra de fogo girar!": "Ga erlangs als de vuurstaaf wegdraait!",
  "Fuja das sombras vermelhas!": "Blijf uit de rode schaduwen!",
  "Pule na cabeça dela!": "Spring op haar kop!",
  "Ela voa: pule nela ou passe por baixo!": "Ze vliegt: spring erop of ga eronderdoor!",
  "Ele pula atrás de você!": "Hij springt achter je aan!",
  "Ele joga cocos!": "Hij gooit kokosnoten!",
  "Ela desce quando você passa!": "Ze zakt naar beneden als je langsloopt!",
  "Pule na cabeça dele!": "Spring op zijn kop!",
  "Ele mergulha em você!": "Hij duikt op je af!",
  "Espinhoso: não pise, deslize nele!": "Stekelig: spring er niet op, glij ertegenaan!",
  "Lenta mas resistente!": "Traag maar taai!",
  "Não pise quando ele rolar!": "Spring er niet op als hij rolt!",
  "Ele escorrega na sua direção!": "Hij glijdt naar je toe!",
  "Voa rápido!": "Vliegt snel!",
  "Joga bolas de neve!": "Gooit sneeuwballen!",
  "Pula atrás de você!": "Springt achter je aan!",
  "Corre muito rápido!": "Rent heel snel!",
  "Quente: não pise, deslize nele!": "Heet: spring er niet op, glij ertegenaan!",
  "Voa muito rápido!": "Vliegt heel snel!",
  "Atira bolas de fogo!": "Schiet vuurballen!",
  "Pule na cabeça ou use o cipó-laço!": "Spring op zijn kop of gebruik de lianenlasso!",
  "Mergulha soltando fogo!": "Duikt omlaag en spuwt vuur!",
  "Clássico": "Klassiek",
  "Dourado": "Goud",
  "Chiclete": "Kauwgom",
  "Gelo": "IJs",
  "Sombra": "Schaduw",
  "Camuflado": "Camouflage",
  "Fogo": "Vuur",
  "Dálmata": "Dalmatiër",
  "Zumbi": "Zombie",
  "Robô": "Robot",
  "Esqueleto": "Skelet",
  "Fantasma": "Spook",
  "Diamante": "Diamant",
  "Galáxia": "Sterrenstelsel",
  "Arco-íris": "Regenboog",
  "Tigre": "Tijger",
  "Gorila": "Gorilla",
  "Camelo": "Kameel",
  "Dragão": "Draak",
  "Prata": "Zilver",
  "Ouro": "Goud",
  "Lendário": "Legendarisch",
  "Boné": "Pet",
  "Chapéu de Festa": "Feesthoedje",
  "Gorro": "Muts",
  "Chapéu de Cowboy": "Cowboyhoed",
  "Cartola": "Hoge hoed",
  "Chapéu de Chef": "Koksmuts",
  "Capacete Viking": "Vikinghelm",
  "Auréola": "Stralenkrans",
  "Coroa": "Kroon",
  "Folha": "Blad",
  "Chapéu de Explorador": "Ontdekkingshoed",
  "Turbante": "Tulband",
  "Coroa de Faraó": "Faraokroon",
  "Protetor de Orelha": "Oorwarmers",
  "Chapéu de Pele": "Bontmuts",
  "Capacete de Bombeiro": "Brandweerhelm",
  "Chifres de Demônio": "Duivelshoorns",
  "Óculos Escuros": "Zonnebril",
  "Óculos 3D": "3D-bril",
  "Óculos de Nerd": "Nerdbril",
  "Máscara": "Masker",
  "Óculos de Coração": "Hartjesbril",
  "Monóculo": "Monocle",
  "Visor Cyber": "Cybervizier",
  "Pintura de Guerra": "Oorlogsverf",
  "Óculos de Aviador": "Pilotenbril",
  "Óculos de Esqui": "Skibril",
  "Óculos de Solda": "Lasbril",
  "Gravata": "Stropdas",
  "Camiseta": "T-shirt",
  "Cachecol": "Sjaal",
  "Macacão": "Tuinbroek",
  "Colete Salva-vidas": "Reddingsvest",
  "Smoking": "Smoking",
  "Capa de Herói": "Heldencape",
  "Armadura": "Harnas",
  "Colar de Flores": "Bloemenketting",
  "Lenço de Bandido": "Bandietendoek",
  "Faixas de Múmia": "Mummiezwachtels",
  "Jaqueta de Neve": "Sneeuwjas",
  "Capa de Fogo": "Vuurcape",
  "Super Velocidade": "Supersnelheid",
  "+60% de velocidade por 10s": "+60% snelheid gedurende 10 s",
  "Pulo Duplo": "Dubbele sprong",
  "Pula de novo no ar por 15s": "Spring 15 s lang nog een keer in de lucht",
  "Escudo": "Schild",
  "Invencível por 8s": "8 s onkwetsbaar",
  "Ímã de Moedas": "Muntmagneet",
  "Puxa as moedas por 15s": "Trekt 15 s lang munten aan",
  "Explode os inimigos perto": "Blaast vijanden in de buurt op",
  "Dispara pra frente e atravessa inimigos": "Schiet vooruit, dwars door vijanden",
  "Coração Extra": "Extra hart",
  "Coração Extra II": "Extra hart II",
  "+1 coração de vida": "+1 hart",
  "Revólver Turbo": "Turborevolver",
  "8 balas, tiro e recarga mais rápidos": "8 kogels, sneller schieten en herladen",
  "Cipó Longo": "Lange liaan",
  "O laço de cipó alcança mais longe": "De lianenlasso reikt verder",
  "Chapéus": "Hoeden",
  "Óculos": "Brillen",
  "Roupas": "Kleding",
  "Poderes": "Krachten",
  "Melhorias": "Upgrades",
  "Andar para a esquerda": "Naar links lopen",
  "Andar para a direita": "Naar rechts lopen",
  "Pular": "Springen",
  "Deslizar / soltar do cipó": "Glijden / liaan loslaten",
  "Revólver": "Revolver",
  "Recarregar": "Herladen",
  "Cipó-laço": "Lianenlasso",
  "Poder: Super Velocidade": "Kracht: Supersnelheid",
  "Poder: Pulo Duplo": "Kracht: Dubbele sprong",
  "Poder: Escudo": "Kracht: Schild",
  "Poder: Ímã de Moedas": "Kracht: Muntmagneet",
  "Poder: Nuke": "Kracht: Nuke",
  "Loja": "Winkel",
  "Pausa": "Pauze",
  "Ligar/desligar som": "Geluid aan/uit",
  "Espaço": "Spatie",
  "Apagar": "Backspace",
  "andar": "lopen",
  "pular (segure: mais alto)": "springen (ingedrukt: hoger)",
  "deslizar": "glijden",
  "revólver": "revolver",
  "recarregar": "herladen",
  "cipó-laço (puxa o inimigo e chuta pro espaço!)": "lianenlasso (trek de vijand naar je toe en schop hem de ruimte in!)",
  "dash (melhoria)": "dash (upgrade)",
  "poderes": "krachten",
  "loja": "winkel",
  "pausa": "pauze",
  "Ação": "Actie",
  "Tecla 1": "Toets 1",
  "Tecla 2": "Toets 2",
  "Tecla 3": "Toets 3",
  "aperte...": "druk...",
  "trocar poder": "kracht wisselen",
  "Saru": "Saru",
  "Saru Gigante": "Reuzen-Saru",
  "Nível {0}+: um macaco lendário pode aparecer 1 vez por dia": "Level {0}+: een legendarische aap kan 1 keer per dag verschijnen",
  "Você venceu o Saru hoje! Ele pode voltar amanhã.": "Je hebt Saru vandaag verslagen! Misschien komt hij morgen terug.",
  "Volte amanhã: o Saru pode aparecer": "Kom morgen terug: Saru kan verschijnen",
  "O Saru apareceu! Enfrentar ({0})": "Saru is er! Vechten ({0})",
  "O Saru Nv {1} apareceu! Enfrentar ({0})": "Saru Lv {1} is er! Vechten ({0})",
  "Nv {0}": "Lv {0}",
  "Nível {0}: mais vida, mais rápido e furioso mais cedo": "Level {0}: meer levens, sneller en eerder woedend",
  "Você venceu o Saru hoje! Ele pode voltar amanhã, mais forte.": "Je hebt Saru vandaag verslagen! Misschien komt hij morgen sterker terug.",
  "Saru: +3 tentativas (anúncio)": "Saru: +3 pogingen (advertentie)",
  "Sem tentativas contra o Saru hoje. Volte amanhã!": "Geen pogingen meer tegen Saru vandaag. Kom morgen terug!",
  "O Saru venceu!": "Saru heeft gewonnen!",
  "Tentativas restantes: {0}": "Pogingen over: {0}",
  "Nova skin: Saru  ·  Nova melhoria: Nuvem Mágica  ·  +{0} moedas": "Nieuwe skin: Saru  ·  Nieuwe upgrade: Toverwolk  ·  +{0} munten",
  "Saru derrotado!": "Saru verslagen!",
  "A lua cheia nasceu...": "De volle maan komt op...",
  "Fase {0}/2": "Fase {0}/2",
  "O macaco lendário! Tentativas restantes: {0}": "De legendarische aap! Pogingen over: {0}",
  "Nuvem Mágica!": "Toverwolk!",
  "Nuvem Mágica": "Toverwolk",
  "Uma vez por fase, se cair num buraco, a nuvem te salva sem perder vida": "Eén keer per level redt de wolk je zonder levensverlies als je in een gat valt",
  "Derrote o Saru": "Versla Saru",
  "Volte amanhã: ele pode aparecer de novo.": "Kom morgen terug: hij kan weer verschijnen.",
  "Tentar de novo (Enter)": "Opnieuw (Enter)",
  "Assistir anúncio: +3 tentativas": "Advertentie bekijken: +3 pogingen",
  "Voltar ao menu (Esc)": "Naar het menu (Esc)",
  "Opções": "Opties",
  "Idioma": "Taal",
  "Adicionais": "Extra's",
  "Escolha o idioma do jogo.": "Kies de taal van het spel.",
  "O cronômetro mostra o tempo da run e de cada fase, com os seus recordes.": "De timer toont de tijd van je run en van elk level, met je records.",
  "Assistir anúncio: +{0} moedas": "Advertentie bekijken: +{0} munten",
  "Grátis (anúncio)": "Gratis (advertentie)",
  "+{0} moedas!": "+{0} munten!",
  "+1 {0}!": "+1 {0}!",
  "O anúncio não terminou, nada ganho.": "De advertentie is niet afgemaakt, geen beloning.",
  "Moedas grátis": "Gratis munten",
  "Completa": "Voltooid",
  "Sem perder vida": "Zonder levensverlies",
  "Até {0}": "Binnen {0}",
  "NOVA!": "NIEUW!",
  "Tempo {0}": "Tijd {0}",
  "Recorde {0}": "Record {0}",
  "Estrelas: {0}/{1}": "Sterren: {0}/{1}",
  "Modo speedrun liberado! O cronômetro foi ligado.": "Speedrunmodus ontgrendeld! De timer staat aan.",
  "Zerado! Jogar = nova run": "Uitgespeeld! Spelen = nieuwe run",
  "PULO": "SPRING",
  "TIRO": "SCHIET",
  "LAÇO": "LASSO",
  "LOJA": "WINKEL",
  "PAUSA": "PAUZE",
  "arraste do lado esquerdo: andar e deslizar": "sleep aan de linkerkant: lopen en glijden",
  "toque nos poderes para usar": "tik op een kracht om die te gebruiken",
  "Toque na tela para começar": "Tik op het scherm om te beginnen",
  "Toque na tela para voltar ao menu": "Tik op het scherm om terug te gaan naar het menu",
  "usar poder": "kracht gebruiken",
  "Jogo zerado!": "Spel uitgespeeld!",
  "Próxima: {0}": "Volgende: {0}",
  " · Recorde: {0}": " · Record: {0}",
  "Som: ligado ({0})": "Geluid: aan ({0})",
  "Som: desligado ({0})": "Geluid: uit ({0})",
  "Cronômetro: ligado": "Timer: aan",
  "Cronômetro: desligado": "Timer: uit",
  "Idioma: Português": "Taal: Nederlands",
  "Chefe": "Baas",
  "Chefe: ": "Baas: ",
  "Prêmio": "Prijs",
  "Épico": "Episch",
  "Raro": "Zeldzaam",
  "Comum": "Gewoon",
  "{0}. Tecla {1}.": "{0}. Toets {1}.",
  "Você tem: {0}": "Je hebt: {0}",
  "Comprar": "Kopen",
  "Faltam {0}": "Nog {0} nodig",
  "{0} (permanente)": "{0} (permanent)",
  "Comprado": "Gekocht",
  "Precisa: {0}": "Vereist: {0}",
  "Equipado": "Uitgerust",
  "Seu": "Van jou",
  "Passe a fase {0}": "Haal {0}",
  "Chegue ao nível {0}": "Bereik level {0}",
  "Bloqueado": "Vergrendeld",
  "Tirar": "Afdoen",
  "Equipar": "Uitrusten",
  "-1 vida": "-1 leven",
  "recarregando": "herladen",
  "Você perdeu!": "Verloren!",
  "Voltando do checkpoint...": "Terug naar het checkpoint...",
  "Tentando de novo...": "Nieuwe poging...",
  "Fase completa!": "Level voltooid!",
  "{0} completo!": "{0} voltooid!",
  "A banana escapou de novo! Próximo: {0}": "De banaan is weer ontsnapt! Volgende: {0}",
  "Você ganhou: {0}!  Próximo: {1}": "Je kreeg: {0}!  Volgende: {1}",
  "Chefe derrotado!": "Baas verslagen!",
  "+{0} moedas. Pegue a banana!": "+{0} munten. Pak de banaan!",
  "Reviveu!": "Weer tot leven!",
  "+{0} moedas": "+{0} munten",
  "  ·  Nova skin: {0}!": "  ·  Nieuwe skin: {0}!",
  "NÍVEL {0}!": "LEVEL {0}!",
  "{0} - o chefe do mundo": "{0} - de baas van de wereld",
  "Novo inimigo: {0}": "Nieuwe vijand: {0}",
  "Novo obstáculo: {0}": "Nieuw obstakel: {0}",
  "Prêmio ao terminar: {0}": "Prijs na afloop: {0}",
  "FASE": "LEVEL",
  "Recorde da fase": "Levelrecord",
  "Primeiro tempo!": "Eerste tijd!",
  "{0}  Recorde!": "{0}  Record!",
  "  (primeira run!)": "  (eerste run!)",
  "  NOVO RECORDE! ({0})": "  NIEUW RECORD! ({0})",
  "  (recorde: {0})": "  (record: {0})",
  "O vento levou a banana!": "De wind heeft de banaan meegenomen!",
  "Atravesse a Selva, o Deserto, a Era do Gelo e o Vulcão para recuperá-la!": "Doorkruis de Jungle, de Woestijn, de IJstijd en de Vulkaan om hem terug te halen!",
  "Dizem que ela foi parar nas garras do Dragão de Magma...": "Men zegt dat hij in de klauwen van de Magmadraak terecht is gekomen...",
  "Clique ou aperte qualquer tecla para começar": "Klik of druk op een toets om te beginnen",
  "Nham!": "Smul!",
  "FIM!": "EINDE!",
  "O primata derrotou o Dragão de Magma e finalmente comeu a sua banana!": "De primaat versloeg de Magmadraak en at eindelijk zijn banaan op!",
  "Nível {0}   ·   Moedas: {1}": "Level {0}   ·   Munten: {1}",
  "Inimigos derrotados: {0}   ·   Chutados pro espaço: {1}": "Verslagen vijanden: {0}   ·   De ruimte in geschopt: {1}",
  "Chefes derrotados: {0}   ·   Quedas: {1}": "Verslagen bazen: {0}   ·   Vallen: {1}",
  "Tempo de jogo: {0}": "Speeltijd: {0}",
  "Nova skin: {0}!": "Nieuwe skin: {0}!",
  "Clique ou aperte qualquer tecla para voltar ao menu": "Klik of druk op een toets om terug te gaan naar het menu",
  "PAUSA (P)": "PAUZE (P)",
  "LOJA (L)": "WINKEL (L)",
  "A grande caçada à banana": "De grote bananenjacht",
  "moedas": "munten",
  "Fase": "Level",
  "Nível": "Level",
  "Jogar (Enter)": "Spelen (Enter)",
  "Escolher fase": "Level kiezen",
  "Controles": "Besturing",
  "Escolha a fase": "Kies een level",
  "Voltar": "Terug",
  "Pausado": "Gepauzeerd",
  "Continuar (P)": "Verder (P)",
  "Loja (L)": "Winkel (L)",
  "Recomeçar fase": "Level herstarten",
  "Som": "Geluid",
  "Cronômetro": "Timer",
  "Menu principal": "Hoofdmenu",
  "Assista um anúncio para continuar daqui com todas as vidas.": "Bekijk een advertentie om hier verder te gaan met al je levens.",
  "Assistir e reviver (Enter)": "Bekijken en herleven (Enter)",
  "Voltar do checkpoint (Esc)": "Terug naar checkpoint (Esc)",
  "Clique numa tecla e aperte a nova.": "Klik op een toets en druk op de nieuwe.",
  "apaga.": "wist hem.",
  "volta.": "gaat terug.",
  "Restaurar padrão": "Standaard",
  "Loja do Primata": "Primatenwinkel",
  "L ou Esc para voltar": "L of Esc om terug te gaan",
  "{0} ou Esc para voltar": "{0} of Esc om terug te gaan",
  "Continuar": "Verder"
};
