"use strict";
// Polski. Chave: o texto em português (igual ao EN de idioma.js). Faltou alguma? Cai no inglês.
TRADUCOES.pl = {
  "Selva": "Dżungla",
  "Deserto": "Pustynia",
  "Era do Gelo": "Epoka Lodowcowa",
  "Vulcão de Lava": "Wulkan Lawy",
  "Gorila Rei": "Król Goryli",
  "Escorpião Faraó": "Skorpion Faraon",
  "Yeti Ancestral": "Prastary Yeti",
  "Dragão de Magma": "Smok Magmy",
  "{0} - Chefe": "{0} - Boss",
  "Espinhos": "Kolce",
  "Cipós de balançar": "Huśtające się liany",
  "Cogumelo pula-pula": "Skaczący grzyb",
  "Troncos rolando": "Toczące się kłody",
  "Plantas carnívoras": "Rośliny mięsożerne",
  "Areia movediça": "Ruchome piaski",
  "Redemoinho": "Trąba powietrzna",
  "Armadilha de dardos": "Pułapka z rzutkami",
  "Pedras rolando": "Toczące się głazy",
  "Ventania de areia": "Burza piaskowa",
  "Túnel de gelo (deslize!)": "Lodowy tunel (ślizg!)",
  "Estalactites": "Sople",
  "Pista de gelo": "Lodowisko",
  "Gelo fino": "Cienki lód",
  "Avalanche": "Lawina",
  "Lago de lava": "Jezioro lawy",
  "Rocha de impulso": "Skała wybijająca",
  "Plataformas que caem": "Spadające platformy",
  "Barra de fogo": "Ognisty pręt",
  "Chuva de meteoros": "Deszcz meteorów",
  "Cobra": "Wąż",
  "Abelha": "Pszczoła",
  "Sapo": "Żaba",
  "Macaco Ladrão": "Małpa Złodziej",
  "Aranha": "Pająk",
  "Escorpião": "Skorpion",
  "Abutre": "Sęp",
  "Cacto Atirador": "Strzelający Kaktus",
  "Múmia": "Mumia",
  "Tatu-bola": "Pancernik",
  "Pinguim": "Pingwin",
  "Morcego de Gelo": "Lodowy Nietoperz",
  "Boneco de Neve": "Bałwan",
  "Foca": "Foka",
  "Lobo do Gelo": "Lodowy Wilk",
  "Slime de Magma": "Magmowy Glut",
  "Morcego de Fogo": "Ognisty Nietoperz",
  "Diabinho": "Diabełek",
  "Golem de Pedra": "Kamienny Golem",
  "Fênix": "Feniks",
  "{esquerda}/{direita} andar   {pulo} pular\nSegure {pulo} para pular mais alto": "{esquerda}/{direita} chodzenie   {pulo} skok\nPrzytrzymaj {pulo}, by skoczyć wyżej",
  "Bem-vindo: {0}!": "Witaj: {0}!",
  "Novo inimigo: {0}!": "Nowy wróg: {0}!",
  "Novo inimigo: Cobra! Pule na cabeça dela!": "Nowy wróg: Wąż! Skocz mu na głowę!",
  "Seu prêmio: cipó-laço! {laco}: puxa o inimigo": "Twoja nagroda: liana-lasso! {laco}: przyciąga wroga",
  "Vença o Gorila Rei para ganhar o cipó-laço!": "Pokonaj Króla Goryli, by zdobyć lianę-lasso!",
  "Você ganhou o cipó-laço!": "Zdobywasz lianę-lasso!",
  "Arraste para andar": "Przeciągnij, by iść",
  "Tutorial": "Samouczek",
  "Boa!": "Brawo!",
  "Arraste o analógico para a direita": "Przeciągnij gałkę w prawo",
  "Ande para a direita: {0}": "Idź w prawo: {0}",
  "Toque em PULO para pular o bloco": "Dotknij SKOK, by przeskoczyć blok",
  "Pule o bloco: {0}": "Przeskocz blok: {0}",
  "Pule na cabeça da cobra!": "Skocz wężowi na głowę!",
  "Pegue a banana!": "Złap banana!",
  "Tutorial completo!": "Samouczek ukończony!",
  "ou": "lub",
  "Agora é pra valer: atravesse os 4 mundos!": "Teraz na serio: przemierz wszystkie 4 światy!",
  "Toque para pular": "Dotknij, by skoczyć",
  "{0}: puxa o inimigo e chuta pro espaço. Pegue a banana!": "{0}: przyciągnij wroga i kopnij go w kosmos. Złap banana!",
  "Novo: {0}!": "Nowość: {0}!",
  "Pule por cima dos espinhos!": "Przeskocz kolce!",
  "Pule no cipó para se agarrar!\n{pulo} solta": "Skocz na lianę, by się złapać!\n{pulo} puszcza",
  "Pule no cogumelo para ir bem alto!": "Skocz na grzyba, by wzbić się wysoko!",
  "Pule por cima deles!": "Przeskocz je!",
  "Passe quando a planta se esconder!": "Przejdź, gdy roślina się schowa!",
  "Pule rápido para não afundar!": "Skacz szybko, żeby nie utonąć!",
  "Entre no redemoinho para subir!": "Wejdź w trąbę powietrzną, by wznieść się w górę!",
  "Pule os dardos de baixo,\ndeslize ({baixo}) nos de cima!": "Przeskakuj dolne rzutki,\nprześlizgnij się ({baixo}) pod górnymi!",
  "Elas são enormes: pule na hora certa!": "Są ogromne: skocz we właściwej chwili!",
  "Espere o vento parar para pular!": "Poczekaj, aż wiatr ustanie, i skacz!",
  "Corra e segure {baixo} para deslizar!": "Biegnij i przytrzymaj {baixo}, by się ślizgać!",
  "Não pare embaixo das estalactites!": "Nie zatrzymuj się pod soplami!",
  "Deslize ({baixo}) no gelo para pular longe!": "Ślizgaj się ({baixo}) po lodzie, by skoczyć daleko!",
  "O gelo fino quebra! Não fique parado": "Cienki lód pęka! Nie stój w miejscu",
  "Pule as bolas de neve!": "Przeskakuj śnieżki!",
  "Lava queima! Pule por cima": "Lawa parzy! Przeskocz ją",
  "Pule na rocha de magma: IMPULSO!": "Skocz na skałę magmy: WYRZUT!",
  "Essas plataformas despencam!": "Te platformy spadają!",
  "Passe quando a barra de fogo girar!": "Przejdź, gdy ognisty pręt się odwróci!",
  "Fuja das sombras vermelhas!": "Uciekaj przed czerwonymi cieniami!",
  "Pule na cabeça dela!": "Skocz jej na głowę!",
  "Ela voa: pule nela ou passe por baixo!": "Lata: skocz na nią albo przejdź pod spodem!",
  "Ele pula atrás de você!": "Skacze za tobą!",
  "Ele joga cocos!": "Rzuca kokosami!",
  "Ela desce quando você passa!": "Opuszcza się, gdy przechodzisz!",
  "Pule na cabeça dele!": "Skocz mu na głowę!",
  "Ele mergulha em você!": "Pikuje na ciebie!",
  "Espinhoso: não pise, deslize nele!": "Kolczasty: nie skacz na niego, wjedź w niego ślizgiem!",
  "Lenta mas resistente!": "Powolna, ale wytrzymała!",
  "Não pise quando ele rolar!": "Nie skacz na niego, gdy się toczy!",
  "Ele escorrega na sua direção!": "Ślizga się w twoją stronę!",
  "Voa rápido!": "Lata szybko!",
  "Joga bolas de neve!": "Rzuca śnieżkami!",
  "Pula atrás de você!": "Skacze za tobą!",
  "Corre muito rápido!": "Biega bardzo szybko!",
  "Quente: não pise, deslize nele!": "Gorący: nie skacz na niego, wjedź w niego ślizgiem!",
  "Voa muito rápido!": "Lata bardzo szybko!",
  "Atira bolas de fogo!": "Strzela kulami ognia!",
  "Pule na cabeça ou use o cipó-laço!": "Skocz mu na głowę albo użyj liany-lasso!",
  "Mergulha soltando fogo!": "Pikuje, ziejąc ogniem!",
  "Clássico": "Klasyczny",
  "Dourado": "Złoty",
  "Chiclete": "Guma do żucia",
  "Gelo": "Lód",
  "Sombra": "Cień",
  "Camuflado": "Moro",
  "Fogo": "Ogień",
  "Dálmata": "Dalmatyńczyk",
  "Zumbi": "Zombie",
  "Robô": "Robot",
  "Esqueleto": "Szkielet",
  "Fantasma": "Duch",
  "Diamante": "Diament",
  "Galáxia": "Galaktyka",
  "Arco-íris": "Tęcza",
  "Tigre": "Tygrys",
  "Gorila": "Goryl",
  "Camelo": "Wielbłąd",
  "Dragão": "Smok",
  "Prata": "Srebro",
  "Ouro": "Złoto",
  "Lendário": "Legendarny",
  "Boné": "Czapka z daszkiem",
  "Chapéu de Festa": "Czapeczka imprezowa",
  "Gorro": "Czapka zimowa",
  "Chapéu de Cowboy": "Kapelusz kowbojski",
  "Cartola": "Cylinder",
  "Chapéu de Chef": "Czapka kucharska",
  "Capacete Viking": "Hełm wikinga",
  "Auréola": "Aureola",
  "Coroa": "Korona",
  "Folha": "Liść",
  "Chapéu de Explorador": "Kapelusz odkrywcy",
  "Turbante": "Turban",
  "Coroa de Faraó": "Korona faraona",
  "Protetor de Orelha": "Nauszniki",
  "Chapéu de Pele": "Futrzana czapka",
  "Capacete de Bombeiro": "Hełm strażacki",
  "Chifres de Demônio": "Rogi demona",
  "Óculos Escuros": "Okulary przeciwsłoneczne",
  "Óculos 3D": "Okulary 3D",
  "Óculos de Nerd": "Okulary kujona",
  "Máscara": "Maska",
  "Óculos de Coração": "Okulary w serca",
  "Monóculo": "Monokl",
  "Visor Cyber": "Cyberwizjer",
  "Pintura de Guerra": "Barwy wojenne",
  "Óculos de Aviador": "Okulary pilota",
  "Óculos de Esqui": "Gogle narciarskie",
  "Óculos de Solda": "Okulary spawacza",
  "Gravata": "Krawat",
  "Camiseta": "Koszulka",
  "Cachecol": "Szalik",
  "Macacão": "Ogrodniczki",
  "Colete Salva-vidas": "Kamizelka ratunkowa",
  "Smoking": "Smoking",
  "Capa de Herói": "Peleryna bohatera",
  "Armadura": "Zbroja",
  "Colar de Flores": "Naszyjnik z kwiatów",
  "Lenço de Bandido": "Chusta bandyty",
  "Faixas de Múmia": "Bandaże mumii",
  "Jaqueta de Neve": "Kurtka zimowa",
  "Capa de Fogo": "Ognista peleryna",
  "Super Velocidade": "Superprędkość",
  "+60% de velocidade por 10s": "+60% prędkości przez 10 s",
  "Pulo Duplo": "Podwójny skok",
  "Pula de novo no ar por 15s": "Drugi skok w powietrzu przez 15 s",
  "Escudo": "Tarcza",
  "Invencível por 8s": "Nietykalność przez 8 s",
  "Ímã de Moedas": "Magnes na monety",
  "Puxa as moedas por 15s": "Przyciąga monety przez 15 s",
  "Explode os inimigos perto": "Wysadza pobliskich wrogów",
  "Dispara pra frente e atravessa inimigos": "Wystrzeliwuje cię do przodu przez wrogów",
  "Coração Extra": "Dodatkowe serce",
  "Coração Extra II": "Dodatkowe serce II",
  "+1 coração de vida": "+1 serce życia",
  "Revólver Turbo": "Turborewolwer",
  "8 balas, tiro e recarga mais rápidos": "8 naboi, szybsze strzały i przeładowanie",
  "Cipó Longo": "Długa liana",
  "O laço de cipó alcança mais longe": "Liana-lasso sięga dalej",
  "Chapéus": "Czapki",
  "Óculos": "Okulary",
  "Roupas": "Stroje",
  "Poderes": "Moce",
  "Melhorias": "Ulepszenia",
  "Andar para a esquerda": "Idź w lewo",
  "Andar para a direita": "Idź w prawo",
  "Pular": "Skok",
  "Deslizar / soltar do cipó": "Ślizg / puść lianę",
  "Revólver": "Rewolwer",
  "Recarregar": "Przeładuj",
  "Cipó-laço": "Liana-lasso",
  "Poder: Super Velocidade": "Moc: Superprędkość",
  "Poder: Pulo Duplo": "Moc: Podwójny skok",
  "Poder: Escudo": "Moc: Tarcza",
  "Poder: Ímã de Moedas": "Moc: Magnes na monety",
  "Poder: Nuke": "Moc: Nuke",
  "Loja": "Sklep",
  "Pausa": "Pauza",
  "Ligar/desligar som": "Dźwięk wł./wył.",
  "Espaço": "Spacja",
  "Apagar": "Backspace",
  "andar": "chodzenie",
  "pular (segure: mais alto)": "skok (przytrzymaj: wyżej)",
  "deslizar": "ślizg",
  "revólver": "rewolwer",
  "recarregar": "przeładowanie",
  "cipó-laço (puxa o inimigo e chuta pro espaço!)": "liana-lasso (przyciągnij wroga i kopnij go w kosmos!)",
  "dash (melhoria)": "zryw (ulepszenie)",
  "poderes": "moce",
  "loja": "sklep",
  "pausa": "pauza",
  "Ação": "Akcja",
  "Tecla 1": "Klawisz 1",
  "Tecla 2": "Klawisz 2",
  "Tecla 3": "Klawisz 3",
  "aperte...": "naciśnij...",
  "trocar poder": "zmień moc",
  "Saru": "Saru",
  "Saru Gigante": "Gigantyczny Saru",
  "Nível {0}+: um macaco lendário pode aparecer 1 vez por dia": "Poziom {0}+: legendarna małpa może pojawić się raz dziennie",
  "Você venceu o Saru hoje! Ele pode voltar amanhã.": "Dziś pokonujesz Saru! Może wrócić jutro.",
  "Volte amanhã: o Saru pode aparecer": "Wróć jutro: Saru może się pojawić",
  "O Saru apareceu! Enfrentar ({0})": "Pojawił się Saru! Walcz ({0})",
  "O Saru Nv {1} apareceu! Enfrentar ({0})": "Pojawił się Saru Poz. {1}! Walcz ({0})",
  "Nv {0}": "Poz. {0}",
  "Nível {0}: mais vida, mais rápido e furioso mais cedo": "Poziom {0}: więcej życia, szybszy i wcześniej wściekły",
  "Você venceu o Saru hoje! Ele pode voltar amanhã, mais forte.": "Dziś pokonujesz Saru! Może wrócić jutro, silniejszy.",
  "Saru: +3 tentativas (anúncio)": "Saru: +3 próby (reklama)",
  "Sem tentativas contra o Saru hoje. Volte amanhã!": "Brak prób przeciw Saru na dziś. Wróć jutro!",
  "O Saru venceu!": "Saru wygrał!",
  "Tentativas restantes: {0}": "Pozostałe próby: {0}",
  "Nova skin: Saru  ·  Nova melhoria: Nuvem Mágica  ·  +{0} moedas": "Nowy skin: Saru  ·  Nowe ulepszenie: Magiczna Chmurka  ·  +{0} monet",
  "Saru derrotado!": "Saru pokonany!",
  "A lua cheia nasceu...": "Wschodzi pełnia księżyca...",
  "Fase {0}/2": "Faza {0}/2",
  "O macaco lendário! Tentativas restantes: {0}": "Legendarna małpa! Pozostałe próby: {0}",
  "Nuvem Mágica!": "Magiczna Chmurka!",
  "Nuvem Mágica": "Magiczna Chmurka",
  "Uma vez por fase, se cair num buraco, a nuvem te salva sem perder vida": "Raz na poziom, gdy wpadniesz do dziury, chmurka ratuje cię bez utraty życia",
  "Derrote o Saru": "Pokonaj Saru",
  "Volte amanhã: ele pode aparecer de novo.": "Wróć jutro: może pojawić się znowu.",
  "Tentar de novo (Enter)": "Jeszcze raz (Enter)",
  "Assistir anúncio: +3 tentativas": "Obejrzyj reklamę: +3 próby",
  "Voltar ao menu (Esc)": "Wróć do menu (Esc)",
  "Opções": "Opcje",
  "Idioma": "Język",
  "Adicionais": "Dodatki",
  "Escolha o idioma do jogo.": "Wybierz język gry.",
  "O cronômetro mostra o tempo da run e de cada fase, com os seus recordes.": "Stoper pokazuje czas całej gry i każdego poziomu, z twoimi rekordami.",
  "Assistir anúncio: +{0} moedas": "Obejrzyj reklamę: +{0} monet",
  "Grátis (anúncio)": "Za darmo (reklama)",
  "+{0} moedas!": "+{0} monet!",
  "+1 {0}!": "+1 {0}!",
  "O anúncio não terminou, nada ganho.": "Reklama się nie skończyła, brak nagrody.",
  "Moedas grátis": "Darmowe monety",
  "Completa": "Ukończony",
  "Sem perder vida": "Bez utraty życia",
  "Até {0}": "Poniżej {0}",
  "NOVA!": "NOWA!",
  "Tempo {0}": "Czas {0}",
  "Recorde {0}": "Rekord {0}",
  "Estrelas: {0}/{1}": "Gwiazdki: {0}/{1}",
  "Modo speedrun liberado! O cronômetro foi ligado.": "Odblokowano tryb speedrun! Stoper jest włączony.",
  "Zerado! Jogar = nova run": "Ukończone! Graj = nowa gra",
  "PULO": "SKOK",
  "TIRO": "STRZAŁ",
  "LAÇO": "LASSO",
  "LOJA": "SKLEP",
  "PAUSA": "PAUZA",
  "arraste do lado esquerdo: andar e deslizar": "przeciągaj po lewej: chodzenie i ślizg",
  "toque nos poderes para usar": "dotknij mocy, by jej użyć",
  "Toque na tela para começar": "Dotknij ekranu, by zacząć",
  "Toque na tela para voltar ao menu": "Dotknij ekranu, by wrócić do menu",
  "usar poder": "użyj mocy",
  "Jogo zerado!": "Gra ukończona!",
  "Próxima: {0}": "Następny: {0}",
  " · Recorde: {0}": " · Rekord: {0}",
  "Som: ligado ({0})": "Dźwięk: wł. ({0})",
  "Som: desligado ({0})": "Dźwięk: wył. ({0})",
  "Cronômetro: ligado": "Stoper: wł.",
  "Cronômetro: desligado": "Stoper: wył.",
  "Idioma: Português": "Język: Polski",
  "Chefe": "Boss",
  "Chefe: ": "Boss: ",
  "Prêmio": "Nagroda",
  "Épico": "Epicki",
  "Raro": "Rzadki",
  "Comum": "Zwykły",
  "{0}. Tecla {1}.": "{0}. Klawisz {1}.",
  "Você tem: {0}": "Masz: {0}",
  "Comprar": "Kup",
  "Faltam {0}": "Brakuje {0}",
  "{0} (permanente)": "{0} (na stałe)",
  "Comprado": "Kupione",
  "Precisa: {0}": "Wymaga: {0}",
  "Equipado": "Założone",
  "Seu": "Twoje",
  "Passe a fase {0}": "Ukończ {0}",
  "Chegue ao nível {0}": "Osiągnij poziom {0}",
  "Bloqueado": "Zablokowane",
  "Tirar": "Zdejmij",
  "Equipar": "Załóż",
  "-1 vida": "-1 życie",
  "recarregando": "przeładowanie",
  "Você perdeu!": "Przegrana!",
  "Voltando do checkpoint...": "Powrót do punktu kontrolnego...",
  "Tentando de novo...": "Kolejna próba...",
  "Fase completa!": "Poziom ukończony!",
  "{0} completo!": "{0} ukończony!",
  "A banana escapou de novo! Próximo: {0}": "Banan znowu uciekł! Następny: {0}",
  "Você ganhou: {0}!  Próximo: {1}": "Zdobywasz: {0}!  Następny: {1}",
  "Chefe derrotado!": "Boss pokonany!",
  "+{0} moedas. Pegue a banana!": "+{0} monet. Złap banana!",
  "Reviveu!": "Wracasz do gry!",
  "+{0} moedas": "+{0} monet",
  "  ·  Nova skin: {0}!": "  ·  Nowy skin: {0}!",
  "NÍVEL {0}!": "POZIOM {0}!",
  "{0} - o chefe do mundo": "{0} - boss świata",
  "Novo inimigo: {0}": "Nowy wróg: {0}",
  "Novo obstáculo: {0}": "Nowa przeszkoda: {0}",
  "Prêmio ao terminar: {0}": "Nagroda za ukończenie: {0}",
  "FASE": "POZIOM",
  "Recorde da fase": "Rekord poziomu",
  "Primeiro tempo!": "Pierwszy czas!",
  "{0}  Recorde!": "{0}  Rekord!",
  "  (primeira run!)": "  (pierwsza gra!)",
  "  NOVO RECORDE! ({0})": "  NOWY REKORD! ({0})",
  "  (recorde: {0})": "  (rekord: {0})",
  "O vento levou a banana!": "Wiatr porwał banana!",
  "Atravesse a Selva, o Deserto, a Era do Gelo e o Vulcão para recuperá-la!": "Przemierz Dżunglę, Pustynię, Epokę Lodowcową i Wulkan, by go odzyskać!",
  "Dizem que ela foi parar nas garras do Dragão de Magma...": "Podobno trafił w szpony Smoka Magmy...",
  "Clique ou aperte qualquer tecla para começar": "Kliknij lub naciśnij dowolny klawisz, by zacząć",
  "Nham!": "Mniam!",
  "FIM!": "KONIEC!",
  "O primata derrotou o Dragão de Magma e finalmente comeu a sua banana!": "Naczelny pokonał Smoka Magmy i w końcu zjadł swojego banana!",
  "Nível {0}   ·   Moedas: {1}": "Poziom {0}   ·   Monety: {1}",
  "Inimigos derrotados: {0}   ·   Chutados pro espaço: {1}": "Pokonani wrogowie: {0}   ·   Kopnięci w kosmos: {1}",
  "Chefes derrotados: {0}   ·   Quedas: {1}": "Pokonani bossowie: {0}   ·   Upadki: {1}",
  "Tempo de jogo: {0}": "Czas gry: {0}",
  "Nova skin: {0}!": "Nowy skin: {0}!",
  "Clique ou aperte qualquer tecla para voltar ao menu": "Kliknij lub naciśnij dowolny klawisz, by wrócić do menu",
  "PAUSA (P)": "PAUZA (P)",
  "LOJA (L)": "SKLEP (L)",
  "A grande caçada à banana": "Wielkie polowanie na banana",
  "moedas": "monety",
  "Fase": "Poziom",
  "Nível": "Poziom",
  "Jogar (Enter)": "Graj (Enter)",
  "Escolher fase": "Wybierz poziom",
  "Controles": "Sterowanie",
  "Escolha a fase": "Wybierz poziom",
  "Voltar": "Wróć",
  "Pausado": "Pauza",
  "Continuar (P)": "Wznów (P)",
  "Loja (L)": "Sklep (L)",
  "Recomeçar fase": "Zacznij poziom od nowa",
  "Som": "Dźwięk",
  "Cronômetro": "Stoper",
  "Menu principal": "Menu główne",
  "Assista um anúncio para continuar daqui com todas as vidas.": "Obejrzyj reklamę, by grać dalej stąd z pełnym życiem.",
  "Assistir e reviver (Enter)": "Obejrzyj i wróć do gry (Enter)",
  "Voltar do checkpoint (Esc)": "Wróć do punktu kontrolnego (Esc)",
  "Clique numa tecla e aperte a nova.": "Kliknij klawisz i naciśnij nowy.",
  "apaga.": "usuwa go.",
  "volta.": "wraca.",
  "Restaurar padrão": "Przywróć domyślne",
  "Loja do Primata": "Sklep Naczelnego",
  "L ou Esc para voltar": "L lub Esc, by wrócić",
  "{0} ou Esc para voltar": "{0} lub Esc, by wrócić",
  "Continuar": "Wznów"
};
