"use strict";
// Türkçe. Chave: o texto em português (igual ao EN de idioma.js). Faltou alguma? Cai no inglês.
TRADUCOES.tr = {
  "Selva": "Orman",
  "Deserto": "Çöl",
  "Era do Gelo": "Buzul Çağı",
  "Vulcão de Lava": "Lav Volkanı",
  "Gorila Rei": "Goril Kral",
  "Escorpião Faraó": "Firavun Akrep",
  "Yeti Ancestral": "Kadim Yeti",
  "Dragão de Magma": "Magma Ejderhası",
  "{0} - Chefe": "{0} - Boss",
  "Espinhos": "Dikenler",
  "Cipós de balançar": "Sallanan sarmaşıklar",
  "Cogumelo pula-pula": "Zıplatan mantar",
  "Troncos rolando": "Yuvarlanan kütükler",
  "Plantas carnívoras": "Etçil bitkiler",
  "Areia movediça": "Bataklık kum",
  "Redemoinho": "Hortum",
  "Armadilha de dardos": "Dart tuzağı",
  "Pedras rolando": "Yuvarlanan kayalar",
  "Ventania de areia": "Kum fırtınası",
  "Túnel de gelo (deslize!)": "Buz tüneli (kay!)",
  "Estalactites": "Buz sarkıtları",
  "Pista de gelo": "Buz pisti",
  "Gelo fino": "İnce buz",
  "Avalanche": "Çığ",
  "Lago de lava": "Lav gölü",
  "Rocha de impulso": "Fırlatan kaya",
  "Plataformas que caem": "Düşen platformlar",
  "Barra de fogo": "Ateş çubuğu",
  "Chuva de meteoros": "Meteor yağmuru",
  "Cobra": "Yılan",
  "Abelha": "Arı",
  "Sapo": "Kurbağa",
  "Macaco Ladrão": "Hırsız Maymun",
  "Aranha": "Örümcek",
  "Escorpião": "Akrep",
  "Abutre": "Akbaba",
  "Cacto Atirador": "Nişancı Kaktüs",
  "Múmia": "Mumya",
  "Tatu-bola": "Armadillo",
  "Pinguim": "Penguen",
  "Morcego de Gelo": "Buz Yarasası",
  "Boneco de Neve": "Kardan Adam",
  "Foca": "Fok",
  "Lobo do Gelo": "Buz Kurdu",
  "Slime de Magma": "Magma Balçığı",
  "Morcego de Fogo": "Ateş Yarasası",
  "Diabinho": "Küçük Şeytan",
  "Golem de Pedra": "Taş Golem",
  "Fênix": "Anka Kuşu",
  "{esquerda}/{direita} andar   {pulo} pular\nSegure {pulo} para pular mais alto": "{esquerda}/{direita} yürü   {pulo} zıpla\nDaha yükseğe zıplamak için {pulo} basılı tut",
  "Bem-vindo: {0}!": "Hoş geldin: {0}!",
  "Novo inimigo: {0}!": "Yeni düşman: {0}!",
  "Novo inimigo: Cobra! Pule na cabeça dela!": "Yeni düşman: Yılan! Kafasına zıpla!",
  "Seu prêmio: cipó-laço! {laco}: puxa o inimigo": "Ödülün: sarmaşık kement! {laco}: düşmanı çeker",
  "Vença o Gorila Rei para ganhar o cipó-laço!": "Sarmaşık kementi kazanmak için Goril Kral'ı yen!",
  "Você ganhou o cipó-laço!": "Sarmaşık kementi kazandın!",
  "Arraste para andar": "Yürümek için sürükle",
  "Tutorial": "Eğitim",
  "Boa!": "Harika!",
  "Arraste o analógico para a direita": "Kolu sağa sürükle",
  "Ande para a direita: {0}": "Sağa yürü: {0}",
  "Toque em PULO para pular o bloco": "Bloğun üstünden atlamak için ZIPLA'ya dokun",
  "Pule o bloco: {0}": "Bloğun üstünden zıpla: {0}",
  "Pule na cabeça da cobra!": "Yılanın kafasına zıpla!",
  "Pegue a banana!": "Muzu yakala!",
  "Tutorial completo!": "Eğitim tamamlandı!",
  "ou": "veya",
  "Agora é pra valer: atravesse os 4 mundos!": "Şimdi gerçek oyun: 4 dünyayı da geç!",
  "Toque para pular": "Zıplamak için dokun",
  "{0}: puxa o inimigo e chuta pro espaço. Pegue a banana!": "{0}: düşmanı çek ve uzaya tekmele. Muzu yakala!",
  "Novo: {0}!": "Yeni: {0}!",
  "Pule por cima dos espinhos!": "Dikenlerin üstünden zıpla!",
  "Pule no cipó para se agarrar!\n{pulo} solta": "Tutunmak için sarmaşığa zıpla!\n{pulo} bırakır",
  "Pule no cogumelo para ir bem alto!": "Çok yükseğe çıkmak için mantara zıpla!",
  "Pule por cima deles!": "Üstlerinden zıpla!",
  "Passe quando a planta se esconder!": "Bitki saklanınca geç!",
  "Pule rápido para não afundar!": "Batmamak için hızlı zıpla!",
  "Entre no redemoinho para subir!": "Yükselmek için hortuma gir!",
  "Pule os dardos de baixo,\ndeslize ({baixo}) nos de cima!": "Alttaki dartların üstünden zıpla,\nüsttekilerin altından kay ({baixo})!",
  "Elas são enormes: pule na hora certa!": "Kocamanlar: doğru anda zıpla!",
  "Espere o vento parar para pular!": "Zıplamak için rüzgârın durmasını bekle!",
  "Corra e segure {baixo} para deslizar!": "Koş ve kaymak için {baixo} basılı tut!",
  "Não pare embaixo das estalactites!": "Buz sarkıtlarının altında durma!",
  "Deslize ({baixo}) no gelo para pular longe!": "Uzağa zıplamak için buzda kay ({baixo})!",
  "O gelo fino quebra! Não fique parado": "İnce buz kırılır! Durma",
  "Pule as bolas de neve!": "Kartoplarının üstünden zıpla!",
  "Lava queima! Pule por cima": "Lav yakar! Üstünden zıpla",
  "Pule na rocha de magma: IMPULSO!": "Magma kayasına zıpla: FIRLAT!",
  "Essas plataformas despencam!": "Bu platformlar çöker!",
  "Passe quando a barra de fogo girar!": "Ateş çubuğu dönünce geç!",
  "Fuja das sombras vermelhas!": "Kırmızı gölgelerden kaç!",
  "Pule na cabeça dela!": "Kafasına zıpla!",
  "Ela voa: pule nela ou passe por baixo!": "Uçar: üstüne zıpla ya da altından geç!",
  "Ele pula atrás de você!": "Peşinden zıplar!",
  "Ele joga cocos!": "Hindistancevizi atar!",
  "Ela desce quando você passa!": "Geçerken aşağı iner!",
  "Pule na cabeça dele!": "Kafasına zıpla!",
  "Ele mergulha em você!": "Üstüne dalış yapar!",
  "Espinhoso: não pise, deslize nele!": "Dikenli: üstüne basma, kayarak çarp!",
  "Lenta mas resistente!": "Yavaş ama dayanıklı!",
  "Não pise quando ele rolar!": "Yuvarlanırken üstüne basma!",
  "Ele escorrega na sua direção!": "Sana doğru kayar!",
  "Voa rápido!": "Hızlı uçar!",
  "Joga bolas de neve!": "Kartopu atar!",
  "Pula atrás de você!": "Peşinden zıplar!",
  "Corre muito rápido!": "Çok hızlı koşar!",
  "Quente: não pise, deslize nele!": "Sıcak: üstüne basma, kayarak çarp!",
  "Voa muito rápido!": "Çok hızlı uçar!",
  "Atira bolas de fogo!": "Ateş topu fırlatır!",
  "Pule na cabeça ou use o cipó-laço!": "Kafasına zıpla ya da sarmaşık kementi kullan!",
  "Mergulha soltando fogo!": "Ateş püskürterek dalış yapar!",
  "Clássico": "Klasik",
  "Dourado": "Altın Rengi",
  "Chiclete": "Sakız",
  "Gelo": "Buz",
  "Sombra": "Gölge",
  "Camuflado": "Kamuflaj",
  "Fogo": "Ateş",
  "Dálmata": "Dalmaçyalı",
  "Zumbi": "Zombi",
  "Robô": "Robot",
  "Esqueleto": "İskelet",
  "Fantasma": "Hayalet",
  "Diamante": "Elmas",
  "Galáxia": "Galaksi",
  "Arco-íris": "Gökkuşağı",
  "Tigre": "Kaplan",
  "Gorila": "Goril",
  "Camelo": "Deve",
  "Dragão": "Ejderha",
  "Prata": "Gümüş",
  "Ouro": "Altın",
  "Lendário": "Efsanevi",
  "Boné": "Şapka",
  "Chapéu de Festa": "Parti Şapkası",
  "Gorro": "Bere",
  "Chapéu de Cowboy": "Kovboy Şapkası",
  "Cartola": "Silindir Şapka",
  "Chapéu de Chef": "Aşçı Şapkası",
  "Capacete Viking": "Viking Miğferi",
  "Auréola": "Hale",
  "Coroa": "Taç",
  "Folha": "Yaprak",
  "Chapéu de Explorador": "Kaşif Şapkası",
  "Turbante": "Türban",
  "Coroa de Faraó": "Firavun Tacı",
  "Protetor de Orelha": "Kulaklık",
  "Chapéu de Pele": "Kürk Şapka",
  "Capacete de Bombeiro": "İtfaiyeci Kaskı",
  "Chifres de Demônio": "Şeytan Boynuzları",
  "Óculos Escuros": "Güneş Gözlüğü",
  "Óculos 3D": "3D Gözlük",
  "Óculos de Nerd": "İnek Gözlüğü",
  "Máscara": "Maske",
  "Óculos de Coração": "Kalpli Gözlük",
  "Monóculo": "Monokl",
  "Visor Cyber": "Siber Vizör",
  "Pintura de Guerra": "Savaş Boyası",
  "Óculos de Aviador": "Pilot Gözlüğü",
  "Óculos de Esqui": "Kayak Gözlüğü",
  "Óculos de Solda": "Kaynakçı Gözlüğü",
  "Gravata": "Kravat",
  "Camiseta": "Tişört",
  "Cachecol": "Atkı",
  "Macacão": "Tulum",
  "Colete Salva-vidas": "Can Yeleği",
  "Smoking": "Smokin",
  "Capa de Herói": "Kahraman Pelerini",
  "Armadura": "Zırh",
  "Colar de Flores": "Çiçek Kolye",
  "Lenço de Bandido": "Haydut Bandanası",
  "Faixas de Múmia": "Mumya Sargıları",
  "Jaqueta de Neve": "Kar Montu",
  "Capa de Fogo": "Ateş Pelerini",
  "Super Velocidade": "Süper Hız",
  "+60% de velocidade por 10s": "10 sn boyunca +%60 hız",
  "Pulo Duplo": "Çift Zıplama",
  "Pula de novo no ar por 15s": "15 sn boyunca havada tekrar zıpla",
  "Escudo": "Kalkan",
  "Invencível por 8s": "8 sn boyunca yenilmez",
  "Ímã de Moedas": "Para Mıknatısı",
  "Puxa as moedas por 15s": "15 sn boyunca paraları çeker",
  "Explode os inimigos perto": "Yakındaki düşmanları patlatır",
  "Dispara pra frente e atravessa inimigos": "İleri atılır ve düşmanların içinden geçer",
  "Coração Extra": "Ekstra Kalp",
  "Coração Extra II": "Ekstra Kalp II",
  "+1 coração de vida": "+1 can kalbi",
  "Revólver Turbo": "Turbo Tabanca",
  "8 balas, tiro e recarga mais rápidos": "8 mermi, daha hızlı atış ve doldurma",
  "Cipó Longo": "Uzun Sarmaşık",
  "O laço de cipó alcança mais longe": "Sarmaşık kement daha uzağa ulaşır",
  "Chapéus": "Şapkalar",
  "Óculos": "Gözlükler",
  "Roupas": "Kıyafetler",
  "Poderes": "Güçler",
  "Melhorias": "Geliştirmeler",
  "Andar para a esquerda": "Sola yürü",
  "Andar para a direita": "Sağa yürü",
  "Pular": "Zıpla",
  "Deslizar / soltar do cipó": "Kay / sarmaşığı bırak",
  "Revólver": "Tabanca",
  "Recarregar": "Doldur",
  "Cipó-laço": "Sarmaşık kement",
  "Poder: Super Velocidade": "Güç: Süper Hız",
  "Poder: Pulo Duplo": "Güç: Çift Zıplama",
  "Poder: Escudo": "Güç: Kalkan",
  "Poder: Ímã de Moedas": "Güç: Para Mıknatısı",
  "Poder: Nuke": "Güç: Nuke",
  "Loja": "Mağaza",
  "Pausa": "Duraklat",
  "Ligar/desligar som": "Sesi aç/kapat",
  "Espaço": "Boşluk",
  "Apagar": "Geri Al",
  "andar": "yürü",
  "pular (segure: mais alto)": "zıpla (basılı tut: daha yüksek)",
  "deslizar": "kay",
  "revólver": "tabanca",
  "recarregar": "doldur",
  "cipó-laço (puxa o inimigo e chuta pro espaço!)": "sarmaşık kement (düşmanı çek ve uzaya tekmele!)",
  "dash (melhoria)": "atılma (geliştirme)",
  "poderes": "güçler",
  "loja": "mağaza",
  "pausa": "duraklat",
  "Ação": "Eylem",
  "Tecla 1": "Tuş 1",
  "Tecla 2": "Tuş 2",
  "Tecla 3": "Tuş 3",
  "aperte...": "bas...",
  "trocar poder": "gücü değiştir",
  "Saru": "Saru",
  "Saru Gigante": "Dev Saru",
  "Nível {0}+: um macaco lendário pode aparecer 1 vez por dia": "Seviye {0}+: efsanevi bir maymun günde 1 kez çıkabilir",
  "Você venceu o Saru hoje! Ele pode voltar amanhã.": "Bugün Saru'yu yendin! Yarın geri gelebilir.",
  "Volte amanhã: o Saru pode aparecer": "Yarın gel: Saru çıkabilir",
  "O Saru apareceu! Enfrentar ({0})": "Saru geldi! Savaş ({0})",
  "O Saru Nv {1} apareceu! Enfrentar ({0})": "Saru Sv {1} geldi! Savaş ({0})",
  "Nv {0}": "Sv {0}",
  "Nível {0}: mais vida, mais rápido e furioso mais cedo": "Seviye {0}: daha çok can, daha hızlı ve daha erken öfkelenir",
  "Você venceu o Saru hoje! Ele pode voltar amanhã, mais forte.": "Bugün Saru'yu yendin! Yarın daha güçlü dönebilir.",
  "Saru: +3 tentativas (anúncio)": "Saru: +3 deneme (reklam)",
  "Sem tentativas contra o Saru hoje. Volte amanhã!": "Bugün Saru'ya karşı deneme hakkın kalmadı. Yarın gel!",
  "O Saru venceu!": "Saru kazandı!",
  "Tentativas restantes: {0}": "Kalan deneme: {0}",
  "Nova skin: Saru  ·  Nova melhoria: Nuvem Mágica  ·  +{0} moedas": "Yeni görünüm: Saru  ·  Yeni geliştirme: Sihirli Bulut  ·  +{0} para",
  "Saru derrotado!": "Saru yenildi!",
  "A lua cheia nasceu...": "Dolunay doğdu...",
  "Fase {0}/2": "Aşama {0}/2",
  "O macaco lendário! Tentativas restantes: {0}": "Efsanevi maymun! Kalan deneme: {0}",
  "Nuvem Mágica!": "Sihirli Bulut!",
  "Nuvem Mágica": "Sihirli Bulut",
  "Uma vez por fase, se cair num buraco, a nuvem te salva sem perder vida": "Bölüm başına bir kez, bir çukura düşersen bulut seni can kaybetmeden kurtarır",
  "Derrote o Saru": "Saru'yu yen",
  "Volte amanhã: ele pode aparecer de novo.": "Yarın gel: tekrar çıkabilir.",
  "Tentar de novo (Enter)": "Tekrar dene (Enter)",
  "Assistir anúncio: +3 tentativas": "Reklam izle: +3 deneme",
  "Voltar ao menu (Esc)": "Menüye dön (Esc)",
  "Opções": "Ayarlar",
  "Idioma": "Dil",
  "Adicionais": "Ekstralar",
  "Escolha o idioma do jogo.": "Oyunun dilini seç.",
  "O cronômetro mostra o tempo da run e de cada fase, com os seus recordes.": "Kronometre oyunun ve her bölümün süresini rekorlarınla birlikte gösterir.",
  "Assistir anúncio: +{0} moedas": "Reklam izle: +{0} para",
  "Grátis (anúncio)": "Ücretsiz (reklam)",
  "+{0} moedas!": "+{0} para!",
  "+1 {0}!": "+1 {0}!",
  "O anúncio não terminou, nada ganho.": "Reklam bitmedi, ödül yok.",
  "Moedas grátis": "Ücretsiz para",
  "Completa": "Tamamlandı",
  "Sem perder vida": "Can kaybetmeden",
  "Até {0}": "{0} altında",
  "NOVA!": "YENİ!",
  "Tempo {0}": "Süre {0}",
  "Recorde {0}": "Rekor {0}",
  "Estrelas: {0}/{1}": "Yıldızlar: {0}/{1}",
  "Modo speedrun liberado! O cronômetro foi ligado.": "Speedrun modu açıldı! Kronometre açık.",
  "Zerado! Jogar = nova run": "Bitirildi! Oyna = yeni oyun",
  "PULO": "ZIPLA",
  "TIRO": "ATEŞ",
  "LAÇO": "KEMENT",
  "LOJA": "MAĞAZA",
  "PAUSA": "DURAKLAT",
  "arraste do lado esquerdo: andar e deslizar": "sol tarafta sürükle: yürü ve kay",
  "toque nos poderes para usar": "kullanmak için bir güce dokun",
  "Toque na tela para começar": "Başlamak için ekrana dokun",
  "Toque na tela para voltar ao menu": "Menüye dönmek için ekrana dokun",
  "usar poder": "güç kullan",
  "Jogo zerado!": "Oyun bitti!",
  "Próxima: {0}": "Sıradaki: {0}",
  " · Recorde: {0}": " · Rekor: {0}",
  "Som: ligado ({0})": "Ses: açık ({0})",
  "Som: desligado ({0})": "Ses: kapalı ({0})",
  "Cronômetro: ligado": "Kronometre: açık",
  "Cronômetro: desligado": "Kronometre: kapalı",
  "Idioma: Português": "Dil: Türkçe",
  "Chefe": "Boss",
  "Chefe: ": "Boss: ",
  "Prêmio": "Ödül",
  "Épico": "Destansı",
  "Raro": "Nadir",
  "Comum": "Sıradan",
  "{0}. Tecla {1}.": "{0}. Tuş {1}.",
  "Você tem: {0}": "Sende: {0}",
  "Comprar": "Satın al",
  "Faltam {0}": "{0} eksik",
  "{0} (permanente)": "{0} (kalıcı)",
  "Comprado": "Satın alındı",
  "Precisa: {0}": "Gerekli: {0}",
  "Equipado": "Kuşanıldı",
  "Seu": "Senin",
  "Passe a fase {0}": "{0} bölümünü geç",
  "Chegue ao nível {0}": "{0}. seviyeye ulaş",
  "Bloqueado": "Kilitli",
  "Tirar": "Çıkar",
  "Equipar": "Kuşan",
  "-1 vida": "-1 can",
  "recarregando": "dolduruluyor",
  "Você perdeu!": "Kaybettin!",
  "Voltando do checkpoint...": "Kontrol noktasına dönülüyor...",
  "Tentando de novo...": "Tekrar deneniyor...",
  "Fase completa!": "Bölüm tamamlandı!",
  "{0} completo!": "{0} tamamlandı!",
  "A banana escapou de novo! Próximo: {0}": "Muz yine kaçtı! Sıradaki: {0}",
  "Você ganhou: {0}!  Próximo: {1}": "Kazandın: {0}!  Sıradaki: {1}",
  "Chefe derrotado!": "Boss yenildi!",
  "+{0} moedas. Pegue a banana!": "+{0} para. Muzu yakala!",
  "Reviveu!": "Dirildin!",
  "+{0} moedas": "+{0} para",
  "  ·  Nova skin: {0}!": "  ·  Yeni görünüm: {0}!",
  "NÍVEL {0}!": "SEVİYE {0}!",
  "{0} - o chefe do mundo": "{0} - dünyanın bossu",
  "Novo inimigo: {0}": "Yeni düşman: {0}",
  "Novo obstáculo: {0}": "Yeni engel: {0}",
  "Prêmio ao terminar: {0}": "Bitirme ödülü: {0}",
  "FASE": "BÖLÜM",
  "Recorde da fase": "Bölüm rekoru",
  "Primeiro tempo!": "İlk süre!",
  "{0}  Recorde!": "{0}  Rekor!",
  "  (primeira run!)": "  (ilk oyun!)",
  "  NOVO RECORDE! ({0})": "  YENİ REKOR! ({0})",
  "  (recorde: {0})": "  (rekor: {0})",
  "O vento levou a banana!": "Rüzgâr muzu uçurdu!",
  "Atravesse a Selva, o Deserto, a Era do Gelo e o Vulcão para recuperá-la!": "Geri almak için Orman'ı, Çöl'ü, Buzul Çağı'nı ve Volkan'ı geç!",
  "Dizem que ela foi parar nas garras do Dragão de Magma...": "Dediklerine göre Magma Ejderhası'nın pençelerine düşmüş...",
  "Clique ou aperte qualquer tecla para começar": "Başlamak için tıkla ya da bir tuşa bas",
  "Nham!": "Hamm!",
  "FIM!": "SON!",
  "O primata derrotou o Dragão de Magma e finalmente comeu a sua banana!": "Primat, Magma Ejderhası'nı yendi ve sonunda muzunu yedi!",
  "Nível {0}   ·   Moedas: {1}": "Seviye {0}   ·   Para: {1}",
  "Inimigos derrotados: {0}   ·   Chutados pro espaço: {1}": "Yenilen düşman: {0}   ·   Uzaya tekmelenen: {1}",
  "Chefes derrotados: {0}   ·   Quedas: {1}": "Yenilen boss: {0}   ·   Düşüş: {1}",
  "Tempo de jogo: {0}": "Oyun süresi: {0}",
  "Nova skin: {0}!": "Yeni görünüm: {0}!",
  "Clique ou aperte qualquer tecla para voltar ao menu": "Menüye dönmek için tıkla ya da bir tuşa bas",
  "PAUSA (P)": "DURAKLAT (P)",
  "LOJA (L)": "MAĞAZA (L)",
  "A grande caçada à banana": "Büyük muz avı",
  "moedas": "para",
  "Fase": "Bölüm",
  "Nível": "Seviye",
  "Jogar (Enter)": "Oyna (Enter)",
  "Escolher fase": "Bölüm seç",
  "Controles": "Kontroller",
  "Escolha a fase": "Bir bölüm seç",
  "Voltar": "Geri",
  "Pausado": "Duraklatıldı",
  "Continuar (P)": "Devam (P)",
  "Loja (L)": "Mağaza (L)",
  "Recomeçar fase": "Bölümü yeniden başlat",
  "Som": "Ses",
  "Cronômetro": "Kronometre",
  "Menu principal": "Ana menü",
  "Assista um anúncio para continuar daqui com todas as vidas.": "Buradan tüm canlarınla devam etmek için bir reklam izle.",
  "Assistir e reviver (Enter)": "İzle ve diril (Enter)",
  "Voltar do checkpoint (Esc)": "Kontrol noktasına dön (Esc)",
  "Clique numa tecla e aperte a nova.": "Bir tuşa tıkla ve yenisine bas.",
  "apaga.": "siler.",
  "volta.": "geri döner.",
  "Restaurar padrão": "Varsayılana dön",
  "Loja do Primata": "Primat Mağazası",
  "L ou Esc para voltar": "Geri dönmek için L veya Esc",
  "{0} ou Esc para voltar": "Geri dönmek için {0} veya Esc",
  "Continuar": "Devam"
};
