"use strict";
TEXTOS.en = {
  titulo: "Ball Duel",
  jogar: "PLAY",
  idioma: "Language",
  som_on: "Sound: on",
  som_off: "Sound: off",
  voltar: "Back",
  pausado: "Paused",
  continuar: "Resume",
  menu: "Menu",
  anuncio_falhou: "The ad didn't load. Try again later.",
  escolha_modo: "How do you want to play?",
  contra_bot: "Vs bot",
  dois_jogadores: "2 players",
  dica_bot_teclado: "A D / ← → move\nW / ↑ jump\nF / Space / L shoot",
  dica_bot_toque: "Left: drag to move and jump\nRight: hold to shoot",
  dica_2p_teclado: "Player 1: A D W + F\nPlayer 2: ← → ↑ + L\nOn the same keyboard!",
  dica_2p_toque: "Each player uses their half of the screen",
  lendaria: "Legendary Match",
  lendaria_anuncio: "Legendary Match: rare weapons only (ad)",
  lendaria_ativada: "Legendary Match on! Pick a mode",
  continuar_anuncio: "▶ Continue",
  continuar_explica: "Watch an ad and the match goes on: the bot loses its last point.",
  nao_obrigado: "No, thanks",
  voce: "YOU",
  voce_curto: "YOU",
  bot: "BOT",
  jogador_n: "PLAYER {0}",
  rodada_n: "Round {0}",
  dano_dobro: "DOUBLE DAMAGE!",
  lute: "FIGHT!",
  empate: "DRAW!",
  voce_venceu_rodada: "YOU WIN THE ROUND!",
  bot_venceu_rodada: "THE BOT WINS THE ROUND",
  jogador_venceu_rodada: "ROUND TO PLAYER {0}!",
  voce_venceu: "YOU WIN!",
  bot_venceu: "THE BOT WINS",
  jogador_venceu: "PLAYER {0} WINS!",
  queda: "ARM WRESTLING!",
  queda_sub: "Time's up! Whoever clicks faster wins",
  queda_dica_bot: "CLICK / SPACE!",
  queda_dica_toque: "TAP THE SCREEN!",
  queda_dica_p1: "PRESS F!",
  queda_dica_p2: "PRESS L!",
  queda_dica_toque_esq: "TAP THE LEFT SIDE!",
  queda_dica_toque_dir: "TAP THE RIGHT SIDE!",
  toque_mover: "move",
  toque_tiro: "SHOOT",
  pegou_arma: "{0}!",
  c_campo: "Meadow",
  r_campo: "Classic: just fight!",
  c_gelo: "Glacier",
  r_gelo: "Ice: everything slides!",
  c_lua: "Moon",
  r_lua: "Low gravity: giant jumps",
  c_vulcao: "Volcano",
  r_vulcao: "Lava rises and falls: stay high!",
  c_espaco: "Space",
  r_espaco: "Almost no gravity: jump to fly",
  c_laboratorio: "Lab",
  r_laboratorio: "Gravity flips upside down!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: push your rival off!",
  c_cidade: "Neon City",
  r_cidade: "Mind the gap between buildings!",
  c_fliperama: "Pinball",
  r_fliperama: "Bumpers launch you away!",
  c_floresta: "Night Forest",
  r_floresta: "In the dark: you only see near light",
  c_deserto: "Desert",
  r_deserto: "Strong wind changes sides!",
  c_fabrica: "Factory",
  r_fabrica: "Conveyor belts carry you!",
  c_oceano: "Deep Sea",
  r_oceano: "Underwater: jump to swim",
  c_templo: "Temple",
  r_templo: "Exit one side, enter the other. Portals!",
  c_castelo: "Castle",
  r_castelo: "Meteor shower: dodge the targets!",
  k_escudo: "Shield",
  kd_escudo: "Blocks 40 damage",
  k_rapidez: "Speed",
  kd_rapidez: "Faster for 7 s",
  k_cura: "Heal",
  kd_cura: "+35 health",
  k_furia: "Fury",
  kd_furia: "Double damage for 6 s",
  k_tiro_duplo: "Double Shot",
  kd_tiro_duplo: "Every shot is doubled",
  k_mini: "Mini",
  kd_mini: "Tiny and hard to hit",
  k_congelar: "Freeze",
  kd_congelar: "Freezes your rival",
  k_fantasma: "Ghost",
  kd_fantasma: "Almost invisible for 5 s",
  k_reflexo: "Reflect",
  kd_reflexo: "Bounces shots back for 5 s",
  k_super_pulo: "Super Jump",
  kd_super_pulo: "Triple, higher jumps",
  k_chuva: "Meteor Shower",
  kd_chuva: "5 meteors on your rival",
  k_municao: "Infinite Ammo",
  kd_municao: "No ammo used for 8 s",
  a_estilingue: "Slingshot",
  a_pistola: "Pistol",
  a_revolver: "Revolver",
  a_submetralhadora: "SMG",
  a_minigun: "Minigun",
  a_escopeta: "Shotgun",
  a_escopeta_dupla: "Double Shotgun",
  a_rifle: "Rifle",
  a_sniper: "Sniper",
  a_plasma: "Plasma Gun",
  a_pula_pula: "Bouncy Gun",
  a_confete: "Confetti Cannon",
  a_arma_agua: "Water Gun",
  a_zarabatana: "Blowgun",
  a_onda_sonora: "Sonic Wave",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boomerang",
  a_arco: "Bow",
  a_arco_triplo: "Triple Bow",
  a_besta: "Crossbow",
  a_serra: "Saw Blade",
  a_bola_neve: "Snowball",
  a_gancho: "Grapple",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Grenade Launcher",
  a_granada: "Grenade",
  a_dinamite: "Dynamite",
  a_fragmentacao: "Cluster Grenade",
  a_canhao: "Cannon",
  a_mini_misseis: "Mini Rockets",
  a_missil: "Homing Missile",
  a_abelhas: "Bee Swarm",
  a_bola_fogo: "Fireball",
  a_granada_gelo: "Ice Grenade",
  a_mina: "Mine",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Rainbow Laser",
  a_feixe: "Beam Gun",
  a_tesla: "Tesla Gun",
  a_raio_gelo: "Ice Ray",
  a_bolhas: "Bubble Gun",
  a_buraco_negro: "Black Hole",
  a_lanca_chamas: "Flamethrower",
  a_soprador: "Leaf Blower",
  a_martelo: "Hammer",
  a_espada: "Sword",
  a_luva_boxe: "Boxing Glove",
  a_meteoro: "Meteors",
  a_relampago: "Lightning"
};
