"use strict";
TEXTOS.en = {
  titulo: "Crazy Balls Duel",
  jogar: "PLAY",
  idioma: "Language",
  som_on: "Sound: on",
  som_off: "Sound: off",
  voltar: "Back",
  pausado: "Paused",
  continuar: "Resume",
  menu: "Menu",
  anuncio_falhou: "The ad didn't load. Try again later.",
  escolha_modo: "How do you want to play?",
  contra_bot: "Vs bot",
  dois_jogadores: "2 players",
  dica_bot_teclado: "A D / ← → move\nW / ↑ jump\nF / Space / L shoot",
  dica_bot_toque: "Left: drag to move and jump\nRight: drag to aim and shoot",
  dica_2p_teclado: "Player 1: A D W + F\nPlayer 2: ← → ↑ + L\nOn the same keyboard!",
  dica_2p_toque: "Each player uses their half of the screen",
  lendaria: "Legendary Match",
  lendaria_anuncio: "Legendary Match: rare weapons only (ad)",
  lendaria_ativada: "Legendary Match on! Pick a mode",
  continuar_anuncio: "▶ Continue",
  continuar_explica: "Watch an ad and the match goes on: the bot loses its last point.",
  nao_obrigado: "No, thanks",
  voce: "YOU",
  voce_curto: "YOU",
  bot: "BOT",
  jogador_n: "PLAYER {0}",
  rodada_n: "Round {0}",
  dano_dobro: "DOUBLE DAMAGE!",
  lute: "FIGHT!",
  empate: "DRAW!",
  voce_venceu_rodada: "YOU WIN THE ROUND!",
  bot_venceu_rodada: "THE BOT WINS THE ROUND",
  jogador_venceu_rodada: "ROUND TO PLAYER {0}!",
  voce_venceu: "YOU WIN!",
  bot_venceu: "THE BOT WINS",
  jogador_venceu: "PLAYER {0} WINS!",
  queda: "ARM WRESTLING!",
  queda_sub: "Time's up! Whoever clicks faster wins",
  queda_dica_bot: "CLICK / SPACE!",
  queda_dica_toque: "TAP THE SCREEN!",
  queda_dica_p1: "PRESS F!",
  queda_dica_p2: "PRESS L!",
  queda_dica_toque_esq: "TAP THE LEFT SIDE!",
  queda_dica_toque_dir: "TAP THE RIGHT SIDE!",
  toque_mover: "move",
  toque_tiro: "SHOOT",
  pegou_arma: "{0}!",
  missoes: "Missions",
  skins: "Skins",
  opcoes: "Options",
  controles: "Controls",
  controles_mouse: "Player 1 can also aim with the MOUSE (click shoots). Click a key, then press the new one.",
  teclas_padrao: "Default keys",
  semana: "Weekly",
  conquistas: "Achievements",
  skins_corpo: "Ball",
  skins_acessorio: "Accessory",
  dobrar_moedas: "Double coins",
  resgatar: "Claim",
  trocar: "Swap",
  missoes_explica: "Complete missions to earn coins. You can swap 1 mission per day.",
  semana_termina: "Ends in {0}d {1}h",
  premio_semana: "Weekly prize: complete all 4 challenges",
  equipado: "Equipped",
  equipar: "Equip",
  so_semanal: "Weekly prize",
  acao_esquerda: "Left",
  acao_direita: "Right",
  acao_pulo: "Jump",
  acao_baixo: "Down",
  acao_tiro: "Shoot",
  tecla_espaco: "Space",
  toque_mira: "AIM",
  dica_bot_v2: "{0} move · {1} jump\nMouse: aim and shoot (or {2})",
  dica_2p_v2: "Player 1: {0}\nPlayer 2: {1}\nOn the same keyboard!",
  aviso_missao: "Mission complete!",
  aviso_desafio: "Weekly challenge complete!",
  aviso_conquista: "Achievement: {0}!",
  nivel_bot: "🤖 Bot level {0}",
  nivel_curto: "Lv. {0}",
  bot_subiu: "Bot leveled up to {0}!",
  bot_desceu: "Bot dropped to level {0}",
  nivel_jogador: "Level {0}",
  subiu_nivel: "Level up! Level {0}",
  abrir_bau: "Open chest",
  abrir_bau_nivel: "Open level chest!",
  outro_bau: "Open another chest",
  revanche: "REMATCH",
  premio_skin: "New skin: {0}!",
  diaria: "Daily reward",
  diaria_explica: "Come back every day: the reward grows! Miss a day and it restarts.",
  dia_n: "Day {0}",
  bau: "chest",
  bau_lendario: "legendary chest",
  pegar: "Claim",
  fechar: "Close",
  sobrevivencia: "Survival",
  sobrevivencia_dica: "Waves of ever stronger bots.\nHow far can you go?",
  onda_n: "WAVE {0}",
  onda_concluida: "WAVE {0} CLEARED!",
  fim_sobrevivencia: "You reached wave {0}!",
  recorde_onda: "Best: wave {0}",
  novo_recorde: "NEW RECORD!",
  continuar_vida: "Watch an ad and continue on the same wave with full health.",
  c_campo: "Meadow",
  r_campo: "Classic: just fight!",
  c_gelo: "Glacier",
  r_gelo: "Ice: everything slides!",
  c_lua: "Moon",
  r_lua: "Low gravity: giant jumps",
  c_vulcao: "Volcano",
  r_vulcao: "Lava rises and falls: stay high!",
  c_espaco: "Space",
  r_espaco: "Almost no gravity: jump to fly",
  c_laboratorio: "Lab",
  r_laboratorio: "Gravity flips upside down!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: push your rival off!",
  c_cidade: "Neon City",
  r_cidade: "Mind the gap between buildings!",
  c_fliperama: "Pinball",
  r_fliperama: "Bumpers launch you away!",
  c_floresta: "Night Forest",
  r_floresta: "In the dark: you only see near light",
  c_deserto: "Desert",
  r_deserto: "Strong wind changes sides!",
  c_fabrica: "Factory",
  r_fabrica: "Conveyor belts carry you!",
  c_oceano: "Deep Sea",
  r_oceano: "Underwater: jump to swim",
  c_templo: "Temple",
  r_templo: "Exit one side, enter the other. Portals!",
  c_castelo: "Castle",
  r_castelo: "Meteor shower: dodge the targets!",
  k_escudo: "Shield",
  kd_escudo: "Blocks 40 damage",
  k_rapidez: "Speed",
  kd_rapidez: "Faster for 7 s",
  k_cura: "Heal",
  kd_cura: "+35 health",
  k_furia: "Fury",
  kd_furia: "Double damage for 6 s",
  k_tiro_duplo: "Double Shot",
  kd_tiro_duplo: "Every shot is doubled",
  k_mini: "Mini",
  kd_mini: "Tiny and hard to hit",
  k_congelar: "Freeze",
  kd_congelar: "Freezes your rival",
  k_fantasma: "Ghost",
  kd_fantasma: "Almost invisible for 5 s",
  k_reflexo: "Reflect",
  kd_reflexo: "Bounces shots back for 5 s",
  k_super_pulo: "Super Jump",
  kd_super_pulo: "Triple, higher jumps",
  k_chuva: "Meteor Shower",
  kd_chuva: "5 meteors on your rival",
  k_municao: "Infinite Ammo",
  kd_municao: "No ammo used for 8 s",
  a_estilingue: "Slingshot",
  a_pistola: "Pistol",
  a_revolver: "Revolver",
  a_submetralhadora: "SMG",
  a_minigun: "Minigun",
  a_escopeta: "Shotgun",
  a_escopeta_dupla: "Double Shotgun",
  a_rifle: "Rifle",
  a_sniper: "Sniper",
  a_plasma: "Plasma Gun",
  a_pula_pula: "Bouncy Gun",
  a_confete: "Confetti Cannon",
  a_arma_agua: "Water Gun",
  a_zarabatana: "Blowgun",
  a_onda_sonora: "Sonic Wave",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boomerang",
  a_arco: "Bow",
  a_arco_triplo: "Triple Bow",
  a_besta: "Crossbow",
  a_serra: "Saw Blade",
  a_bola_neve: "Snowball",
  a_gancho: "Grapple",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Grenade Launcher",
  a_granada: "Grenade",
  a_dinamite: "Dynamite",
  a_fragmentacao: "Cluster Grenade",
  a_canhao: "Cannon",
  a_mini_misseis: "Mini Rockets",
  a_missil: "Homing Missile",
  a_abelhas: "Bee Swarm",
  a_bola_fogo: "Fireball",
  a_granada_gelo: "Ice Grenade",
  a_mina: "Mine",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Rainbow Laser",
  a_feixe: "Beam Gun",
  a_tesla: "Tesla Gun",
  a_raio_gelo: "Ice Ray",
  a_bolhas: "Bubble Gun",
  a_buraco_negro: "Black Hole",
  a_lanca_chamas: "Flamethrower",
  a_soprador: "Leaf Blower",
  a_martelo: "Hammer",
  a_espada: "Sword",
  a_luva_boxe: "Boxing Glove",
  a_meteoro: "Meteors",
  a_relampago: "Lightning",
  mi_vitorias: "Win {0} match(es) vs the bot",
  mi_rodadas: "Win {0} rounds",
  mi_dano: "Deal {0} damage",
  mi_quedas: "Win {0} arm wrestle(s)",
  mi_cartas: "Grab {0} cards",
  mi_caixas: "Grab {0} weapon crates",
  mi_abatesExpl: "Win {0} round(s) with explosives",
  mi_abatesMelee: "Win {0} round(s) in melee",
  mi_perfeitas: "Win {0} round(s) without taking damage",
  mi_partidas: "Play {0} matches",
  mi_partidas2p: "Play {0} 2-player match(es)",
  mi_rodadaCenario: "Win {0} round(s) in: {1}",
  de_s_vitorias: "Win {0} match(es) vs the bot",
  de_s_rodadas: "Win {0} rounds",
  de_s_dano: "Deal {0} damage",
  de_s_quedas: "Win {0} arm wrestle(s)",
  de_s_cenarios: "Win rounds in {0} different arenas",
  de_s_5x0: "Win a match 5 – 0",
  de_s_expl: "Win {0} round(s) with explosives",
  de_s_cartas: "Grab {0} cards",
  de_s_perfeitas: "Win {0} round(s) without taking damage",
  de_s_virada: "Come back from 3 points down to win",
  co_primeira_vitoria: "First Win",
  cod_primeira_vitoria: "Win {0} match(es) vs the bot",
  co_vitorias_10: "Duelist",
  cod_vitorias_10: "Win {0} match(es) vs the bot",
  co_vitorias_25: "Veteran",
  cod_vitorias_25: "Win {0} match(es) vs the bot",
  co_vitorias_100: "Legend",
  cod_vitorias_100: "Win {0} match(es) vs the bot",
  co_partidas_50: "Hooked",
  cod_partidas_50: "Play {0} matches",
  co_rodadas_50: "Round Winner",
  cod_rodadas_50: "Win {0} rounds",
  co_rodadas_250: "Machine",
  cod_rodadas_250: "Win {0} rounds",
  co_dano_20000: "Destroyer",
  cod_dano_20000: "Deal {0} damage",
  co_dano_100000: "Apocalypse",
  cod_dano_100000: "Deal {0} damage",
  co_quedas_5: "Strong Arm",
  cod_quedas_5: "Win {0} arm wrestle(s)",
  co_quedas_20: "Arm Champion",
  cod_quedas_20: "Win {0} arm wrestle(s)",
  co_explosivos_50: "Demolisher",
  cod_explosivos_50: "Win {0} round(s) with explosives",
  co_melee_20: "Brawler",
  cod_melee_20: "Win {0} round(s) in melee",
  co_perfeitas_10: "Untouchable",
  cod_perfeitas_10: "Win {0} round(s) without taking damage",
  co_cenarios_todos: "Explorer",
  cod_cenarios_todos: "Win rounds in {0} different arenas",
  co_armas_25: "Collector",
  cod_armas_25: "Grab {0} different weapons",
  co_armas_todas: "Full Arsenal",
  cod_armas_todas: "Grab {0} different weapons",
  co_cartas_todas: "Full Deck",
  cod_cartas_todas: "Grab all {0} different cards",
  co_placar_5x0: "Flawless",
  cod_placar_5x0: "Win a match 5 – 0",
  co_virada: "Epic Comeback",
  cod_virada: "Come back from 3 points down to win",
  co_bot_mestre: "Bot Master",
  cod_bot_mestre: "Beat the bot at its top level",
  co_dois_jogadores_10: "Best Friends",
  cod_dois_jogadores_10: "Play {0} 2-player match(es)",
  co_missoes_10: "Dedicated",
  cod_missoes_10: "Claim {0} missions",
  co_missoes_50: "Tireless",
  cod_missoes_50: "Claim {0} missions",
  co_semana_completa: "Perfect Week",
  cod_semana_completa: "Complete every challenge of a week",
  co_onda_5: "Survivor",
  cod_onda_5: "Reach wave {0} in Survival",
  co_onda_10: "Unstoppable",
  cod_onda_10: "Reach wave {0} in Survival",
  sk_classico: "Classic",
  sk_listras: "Stripes",
  sk_pintas: "Polka Dots",
  sk_xadrez: "Checkers",
  sk_camuflado: "Camo",
  sk_futebol: "Soccer Ball",
  sk_melancia: "Watermelon",
  sk_robo: "Robot",
  sk_doce: "Candy",
  sk_cromado: "Chrome",
  sk_gelo: "Ice Crystal",
  sk_neon: "Neon",
  sk_lava: "Lava",
  sk_diamante: "Diamond",
  sk_galaxia: "Galaxy",
  sk_ouro: "Gold",
  sk_nenhum: "None",
  sk_bone: "Cap",
  sk_oculos: "Sunglasses",
  sk_orelhas_gato: "Cat Ears",
  sk_fone: "Headphones",
  sk_cartola: "Top Hat",
  sk_chifres: "Horns",
  sk_tiara_flores: "Flower Crown",
  sk_mascara_ninja: "Ninja Mask",
  sk_viking: "Viking Helmet",
  sk_cowboy: "Cowboy Hat",
  sk_antena: "Alien Antenna",
  sk_aureola: "Halo",
  sk_coroa: "Crown"
};
