"use strict";
TEXTOS.es = {
  titulo: "Crazy Balls Duel",
  jogar: "JUGAR",
  idioma: "Idioma",
  som_on: "Sonido: sí",
  som_off: "Sonido: no",
  voltar: "Volver",
  pausado: "Pausa",
  continuar: "Continuar",
  menu: "Menú",
  anuncio_falhou: "El anuncio no cargó. Inténtalo más tarde.",
  escolha_modo: "¿Cómo quieres jugar?",
  contra_bot: "Contra el bot",
  dois_jogadores: "2 jugadores",
  dica_bot_teclado: "A D / ← → moverse\nW / ↑ saltar\nF / Espacio / L disparar",
  dica_bot_toque: "Izquierda: arrastra para moverte\nDerecha: arriba salta · abajo apunta y dispara",
  dica_2p_teclado: "Jugador 1: A D W + F\nJugador 2: ← → ↑ + L\n¡En el mismo teclado!",
  dica_2p_toque: "Dos en el mismo móvil, en horizontal: cada uno usa una mitad de la pantalla",
  lendaria: "Partida Legendaria",
  lendaria_anuncio: "Partida Legendaria: solo armas raras (anuncio)",
  lendaria_ativada: "¡Partida Legendaria activada! Elige el modo",
  continuar_anuncio: "▶ Continuar",
  continuar_explica: "Mira un anuncio y la partida sigue: el bot pierde su último punto.",
  nao_obrigado: "No, gracias",
  voce: "TÚ",
  voce_curto: "TÚ",
  bot: "BOT",
  jogador_n: "JUGADOR {0}",
  rodada_n: "Ronda {0}",
  dano_dobro: "¡DAÑO DOBLE!",
  lute: "¡LUCHA!",
  empate: "¡EMPATE!",
  voce_venceu_rodada: "¡GANASTE LA RONDA!",
  bot_venceu_rodada: "EL BOT GANA LA RONDA",
  jogador_venceu_rodada: "¡RONDA PARA EL JUGADOR {0}!",
  voce_venceu: "¡GANASTE!",
  bot_venceu: "EL BOT GANA",
  jogador_venceu: "¡GANA EL JUGADOR {0}!",
  queda: "¡PULSO!",
  queda_sub: "¡Se acabó el tiempo! Gana quien haga clic más rápido",
  queda_dica_bot: "¡CLIC / ESPACIO!",
  queda_dica_toque: "¡TOCA LA PANTALLA!",
  queda_dica_p1: "¡PULSA F!",
  queda_dica_p2: "¡PULSA L!",
  queda_dica_toque_esq: "¡TOCA A LA IZQUIERDA!",
  queda_dica_toque_dir: "¡TOCA A LA DERECHA!",
  toque_mover: "mover",
  toque_tiro: "DISPARAR",
  pegou_arma: "¡{0}!",
  mesmo_aparelho: "En el mismo dispositivo · no es online",
  qualidade_auto: "Gráficos: automático",
  qualidade_alta: "Gráficos: altos",
  qualidade_leve: "Gráficos: ligeros",
  perfeito: "¡PERFECTO!",
  missoes: "Misiones",
  skins: "Skins",
  opcoes: "Opciones",
  controles: "Controles",
  controles_mouse: "El jugador 1 también apunta con el RATÓN (clic dispara). Haz clic en una tecla y pulsa la nueva.",
  teclas_padrao: "Teclas por defecto",
  semana: "Semanal",
  conquistas: "Logros",
  skins_corpo: "Bola",
  skins_acessorio: "Accesorio",
  dobrar_moedas: "Duplicar monedas",
  resgatar: "Reclamar",
  trocar: "Cambiar",
  missoes_explica: "Completa misiones para ganar monedas. Puedes cambiar 1 misión al día.",
  semana_termina: "Termina en {0}d {1}h",
  premio_semana: "Premio semanal: completa los 4 desafíos",
  equipado: "Equipado",
  equipar: "Equipar",
  so_semanal: "Premio semanal",
  acao_esquerda: "Izquierda",
  acao_direita: "Derecha",
  acao_pulo: "Saltar",
  acao_baixo: "Bajar",
  acao_tiro: "Disparar",
  tecla_espaco: "Espacio",
  toque_mira: "APUNTAR",
  dica_bot_v2: "{0} moverse · {1} saltar\nRatón: apunta y dispara (o {2})",
  dica_2p_v2: "Jugador 1: {0}\nJugador 2: {1}\n¡En el mismo teclado!",
  aviso_missao: "¡Misión completada!",
  aviso_desafio: "¡Desafío semanal completado!",
  aviso_conquista: "Logro: {0}!",
  nivel_bot: "🤖 Bot nivel {0}",
  nivel_curto: "Nv. {0}",
  bot_subiu: "¡El bot subió al nivel {0}!",
  bot_desceu: "El bot bajó al nivel {0}",
  nivel_jogador: "Nivel {0}",
  subiu_nivel: "¡Subiste al nivel {0}!",
  abrir_bau: "Abrir cofre",
  abrir_bau_nivel: "¡Abrir cofre de nivel!",
  outro_bau: "Abrir otro cofre",
  revanche: "REVANCHA",
  premio_skin: "¡Skin nueva: {0}!",
  diaria: "Recompensa diaria",
  diaria_explica: "¡Vuelve cada día: la recompensa crece! Si faltas un día, vuelve a empezar.",
  dia_n: "Día {0}",
  bau: "cofre",
  bau_lendario: "cofre legendario",
  pegar: "Reclamar",
  fechar: "Cerrar",
  sobrevivencia: "Supervivencia",
  sobrevivencia_dica: "Oleadas de bots cada vez más fuertes.\n¿Hasta dónde llegas?",
  onda_n: "OLEADA {0}",
  onda_concluida: "¡OLEADA {0} SUPERADA!",
  fim_sobrevivencia: "¡Llegaste a la oleada {0}!",
  recorde_onda: "Récord: oleada {0}",
  novo_recorde: "¡NUEVO RÉCORD!",
  continuar_vida: "Mira un anuncio y sigue en la misma oleada con la vida llena.",
  dica_bot_v3: "{0} moverse · {1} saltar\nRatón: apuntar · Clic o {2}: disparar",
  dica_2p_v3: "Jugador 1: {0} + ratón\nJugador 2: {1}\n¡En el mismo teclado!",
  queda_clique: "¡CLIC O {0}!",
  queda_aperte: "¡PULSA {0}!",
  toque_pulo: "SALTAR",
  estilo_agressivo: "Agresivo",
  estilo_atirador: "Tirador",
  estilo_saltitante: "Saltarín",
  estilo_cauteloso: "Cauteloso",
  estilo_colecionador: "Coleccionista",
  c_campo: "Prado",
  r_campo: "Clásico: ¡a luchar!",
  c_gelo: "Glaciar",
  r_gelo: "Hielo: ¡todo resbala!",
  c_lua: "Luna",
  r_lua: "Poca gravedad: saltos gigantes",
  c_vulcao: "Volcán",
  r_vulcao: "La lava sube y baja: ¡quédate arriba!",
  c_espaco: "Espacio",
  r_espaco: "Casi sin gravedad: salta para volar",
  c_laboratorio: "Laboratorio",
  r_laboratorio: "¡La gravedad se invierte!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: ¡empuja al rival fuera!",
  c_cidade: "Ciudad Neón",
  r_cidade: "¡Cuidado con el hueco entre edificios!",
  c_fliperama: "Pinball",
  r_fliperama: "¡Los rebotadores te lanzan lejos!",
  c_floresta: "Bosque Nocturno",
  r_floresta: "A oscuras: solo ves cerca de la luz",
  c_deserto: "Desierto",
  r_deserto: "¡El viento fuerte cambia de lado!",
  c_fabrica: "Fábrica",
  r_fabrica: "¡Las cintas te arrastran!",
  c_oceano: "Fondo del Mar",
  r_oceano: "Bajo el agua: salta para nadar",
  c_templo: "Templo",
  r_templo: "Sal por un lado, entra por el otro. ¡Portales!",
  c_castelo: "Castillo",
  r_castelo: "Lluvia de meteoros: ¡esquiva las marcas!",
  k_escudo: "Escudo",
  kd_escudo: "Bloquea 40 de daño",
  k_rapidez: "Velocidad",
  kd_rapidez: "Más rápido 7 s",
  k_cura: "Curación",
  kd_cura: "+35 de vida",
  k_furia: "Furia",
  kd_furia: "Daño doble 6 s",
  k_tiro_duplo: "Disparo Doble",
  kd_tiro_duplo: "Cada disparo sale doble",
  k_mini: "Mini",
  kd_mini: "Pequeño y difícil de acertar",
  k_congelar: "Congelar",
  kd_congelar: "Congela al rival",
  k_fantasma: "Fantasma",
  kd_fantasma: "Casi invisible 5 s",
  k_reflexo: "Reflejo",
  kd_reflexo: "Devuelve los disparos 5 s",
  k_super_pulo: "Súper Salto",
  kd_super_pulo: "Triple salto y más alto",
  k_chuva: "Lluvia de Meteoros",
  kd_chuva: "5 meteoros sobre el rival",
  k_municao: "Munición Infinita",
  kd_municao: "Sin gastar munición 8 s",
  a_estilingue: "Tirachinas",
  a_pistola: "Pistola",
  a_revolver: "Revólver",
  a_submetralhadora: "Subfusil",
  a_minigun: "Minigun",
  a_escopeta: "Escopeta",
  a_escopeta_dupla: "Escopeta Doble",
  a_rifle: "Rifle",
  a_sniper: "Francotirador",
  a_plasma: "Plasma",
  a_pula_pula: "Pelota Saltarina",
  a_confete: "Cañón de Confeti",
  a_arma_agua: "Pistola de Agua",
  a_zarabatana: "Cerbatana",
  a_onda_sonora: "Onda Sónica",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerán",
  a_arco: "Arco",
  a_arco_triplo: "Arco Triple",
  a_besta: "Ballesta",
  a_serra: "Sierra Giratoria",
  a_bola_neve: "Bola de Nieve",
  a_gancho: "Gancho",
  a_bazuca: "Bazuca",
  a_lanca_granadas: "Lanzagranadas",
  a_granada: "Granada",
  a_dinamite: "Dinamita",
  a_fragmentacao: "Granada de Racimo",
  a_canhao: "Cañón",
  a_mini_misseis: "Mini Misiles",
  a_missil: "Misil Teledirigido",
  a_abelhas: "Enjambre de Abejas",
  a_bola_fogo: "Bola de Fuego",
  a_granada_gelo: "Granada de Hielo",
  a_mina: "Mina",
  a_laser: "Láser",
  a_railgun: "Cañón de Riel",
  a_arco_iris: "Láser Arcoíris",
  a_feixe: "Rayo Continuo",
  a_tesla: "Tesla",
  a_raio_gelo: "Rayo de Hielo",
  a_bolhas: "Pistola de Burbujas",
  a_buraco_negro: "Agujero Negro",
  a_lanca_chamas: "Lanzallamas",
  a_soprador: "Soplador",
  a_martelo: "Martillo",
  a_espada: "Espada",
  a_luva_boxe: "Guante de Boxeo",
  a_meteoro: "Meteoros",
  a_relampago: "Relámpago",
  mi_vitorias: "Gana {0} partida(s) contra el bot",
  mi_rodadas: "Gana {0} rondas",
  mi_dano: "Causa {0} de daño",
  mi_quedas: "Gana {0} pulso(s)",
  mi_cartas: "Recoge {0} cartas",
  mi_caixas: "Recoge {0} cajas de armas",
  mi_abatesExpl: "Gana {0} ronda(s) con explosivos",
  mi_abatesMelee: "Gana {0} ronda(s) cuerpo a cuerpo",
  mi_perfeitas: "Gana {0} ronda(s) sin recibir daño",
  mi_partidas: "Juega {0} partidas",
  mi_partidas2p: "Juega {0} partida(s) de 2 jugadores",
  mi_rodadaCenario: "Gana {0} ronda(s) en: {1}",
  de_s_vitorias: "Gana {0} partida(s) contra el bot",
  de_s_rodadas: "Gana {0} rondas",
  de_s_dano: "Causa {0} de daño",
  de_s_quedas: "Gana {0} pulso(s)",
  de_s_cenarios: "Gana rondas en {0} escenarios distintos",
  de_s_5x0: "Gana una partida 3 – 0",
  de_s_expl: "Gana {0} ronda(s) con explosivos",
  de_s_cartas: "Recoge {0} cartas",
  de_s_perfeitas: "Gana {0} ronda(s) sin recibir daño",
  de_s_virada: "Remonta una partida perdiendo por 2",
  co_primeira_vitoria: "Primera Victoria",
  cod_primeira_vitoria: "Gana {0} partida(s) contra el bot",
  co_vitorias_10: "Duelista",
  cod_vitorias_10: "Gana {0} partida(s) contra el bot",
  co_vitorias_25: "Veterano",
  cod_vitorias_25: "Gana {0} partida(s) contra el bot",
  co_vitorias_100: "Leyenda",
  cod_vitorias_100: "Gana {0} partida(s) contra el bot",
  co_partidas_50: "Enganchado",
  cod_partidas_50: "Juega {0} partidas",
  co_rodadas_50: "Ganador de Rondas",
  cod_rodadas_50: "Gana {0} rondas",
  co_rodadas_250: "Máquina",
  cod_rodadas_250: "Gana {0} rondas",
  co_dano_20000: "Destructor",
  cod_dano_20000: "Causa {0} de daño",
  co_dano_100000: "Apocalipsis",
  cod_dano_100000: "Causa {0} de daño",
  co_quedas_5: "Brazo Fuerte",
  cod_quedas_5: "Gana {0} pulso(s)",
  co_quedas_20: "Campeón de Pulso",
  cod_quedas_20: "Gana {0} pulso(s)",
  co_explosivos_50: "Demoledor",
  cod_explosivos_50: "Gana {0} ronda(s) con explosivos",
  co_melee_20: "Peleador",
  cod_melee_20: "Gana {0} ronda(s) cuerpo a cuerpo",
  co_perfeitas_10: "Intocable",
  cod_perfeitas_10: "Gana {0} ronda(s) sin recibir daño",
  co_cenarios_todos: "Explorador",
  cod_cenarios_todos: "Gana rondas en {0} escenarios distintos",
  co_armas_25: "Coleccionista",
  cod_armas_25: "Recoge {0} armas distintas",
  co_armas_todas: "Arsenal Completo",
  cod_armas_todas: "Recoge {0} armas distintas",
  co_cartas_todas: "Baraja Completa",
  cod_cartas_todas: "Recoge las {0} cartas distintas",
  co_placar_5x0: "Paliza",
  cod_placar_5x0: "Gana una partida 3 – 0",
  co_virada: "Remontada Épica",
  cod_virada: "Remonta una partida perdiendo por 2",
  co_bot_mestre: "Maestro del Bot",
  cod_bot_mestre: "Vence al bot en su nivel máximo",
  co_dois_jogadores_10: "Mejores Amigos",
  cod_dois_jogadores_10: "Juega {0} partida(s) de 2 jugadores",
  co_missoes_10: "Dedicado",
  cod_missoes_10: "Reclama {0} misiones",
  co_missoes_50: "Incansable",
  cod_missoes_50: "Reclama {0} misiones",
  co_semana_completa: "Semana Perfecta",
  cod_semana_completa: "Completa todos los desafíos de una semana",
  co_onda_5: "Superviviente",
  cod_onda_5: "Llega a la oleada {0} en Supervivencia",
  co_onda_10: "Imparable",
  cod_onda_10: "Llega a la oleada {0} en Supervivencia",
  sk_classico: "Clásica",
  sk_listras: "Rayas",
  sk_pintas: "Lunares",
  sk_xadrez: "Cuadros",
  sk_camuflado: "Camuflaje",
  sk_futebol: "Balón",
  sk_melancia: "Sandía",
  sk_robo: "Robot",
  sk_doce: "Caramelo",
  sk_cromado: "Cromada",
  sk_gelo: "Cristal de Hielo",
  sk_neon: "Neón",
  sk_lava: "Lava",
  sk_diamante: "Diamante",
  sk_galaxia: "Galaxia",
  sk_ouro: "Oro",
  sk_nenhum: "Ninguno",
  sk_bone: "Gorra",
  sk_oculos: "Gafas de Sol",
  sk_orelhas_gato: "Orejas de Gato",
  sk_fone: "Auriculares",
  sk_cartola: "Chistera",
  sk_chifres: "Cuernos",
  sk_tiara_flores: "Corona de Flores",
  sk_mascara_ninja: "Máscara Ninja",
  sk_viking: "Casco Vikingo",
  sk_cowboy: "Sombrero Vaquero",
  sk_antena: "Antena Alien",
  sk_aureola: "Aureola",
  sk_coroa: "Corona",
  novo: "¡NUEVO!",
  proximo_rival: "SIGUIENTE RIVAL",
  premio_equipado: "¡{0} equipado!",
  modo_rivais: "Rivales",
  rivais_dica: "Vence a 10 rivales y sube de liga",
  rival_n: "RIVAL {0}/{1}",
  liga_0: "Bronce",
  liga_1: "Plata",
  liga_2: "Oro",
  liga_3: "Diamante",
  liga_4: "Maestro",
  liga_n: "Liga {0}",
  rival_derrotado: "¡{0} derrotado!",
  proximo: "Siguiente: {0}",
  revanche_contra: "Revancha contra {0}",
  campeao_liga: "¡CAMPEÓN DE LA LIGA {0}!",
  rival_venceu: "¡{0} gana!",
  venca_ganhe: "Gana y llévate: {0}",
  salvo: "¡SALVADO!",
  melhorar: "Mejorar",
  poder_explica: "Hazte más fuerte contra el bot y los rivales. En el modo 2 jugadores, los dos son iguales.",
  poder_n: "⚡ PODER {0}",
  poder_dica: "¡Mejora y vuelve más fuerte!",
  poder_gaste: "Usa tus monedas: ¡hazte más fuerte!",
  mel_forca: "Fuerza",
  mel_vida: "Vida",
  mel_veloc: "Velocidad",
  mel_nivel: "Nv {0}",
  mel_max: "MÁX",
  mel_d_forca: "Pega más fuerte",
  mel_d_vida: "Aguanta más",
  mel_d_veloc: "Corre más"
};
