"use strict";
TEXTOS.es = {
  titulo: "Duelo de Bolitas",
  jogar: "JUGAR",
  idioma: "Idioma",
  som_on: "Sonido: sí",
  som_off: "Sonido: no",
  voltar: "Volver",
  pausado: "Pausa",
  continuar: "Continuar",
  menu: "Menú",
  anuncio_falhou: "El anuncio no cargó. Inténtalo más tarde.",
  escolha_modo: "¿Cómo quieres jugar?",
  contra_bot: "Contra el bot",
  dois_jogadores: "2 jugadores",
  dica_bot_teclado: "A D / ← → moverse\nW / ↑ saltar\nF / Espacio / L disparar",
  dica_bot_toque: "Izquierda: arrastra para moverte y saltar\nDerecha: mantén para disparar",
  dica_2p_teclado: "Jugador 1: A D W + F\nJugador 2: ← → ↑ + L\n¡En el mismo teclado!",
  dica_2p_toque: "Cada uno usa su mitad de la pantalla",
  lendaria: "Partida Legendaria",
  lendaria_anuncio: "Partida Legendaria: solo armas raras (anuncio)",
  lendaria_ativada: "¡Partida Legendaria activada! Elige el modo",
  continuar_anuncio: "▶ Continuar",
  continuar_explica: "Mira un anuncio y la partida sigue: el bot pierde su último punto.",
  nao_obrigado: "No, gracias",
  voce: "TÚ",
  voce_curto: "TÚ",
  bot: "BOT",
  jogador_n: "JUGADOR {0}",
  rodada_n: "Ronda {0}",
  dano_dobro: "¡DAÑO DOBLE!",
  lute: "¡LUCHA!",
  empate: "¡EMPATE!",
  voce_venceu_rodada: "¡GANASTE LA RONDA!",
  bot_venceu_rodada: "EL BOT GANA LA RONDA",
  jogador_venceu_rodada: "¡RONDA PARA EL JUGADOR {0}!",
  voce_venceu: "¡GANASTE!",
  bot_venceu: "EL BOT GANA",
  jogador_venceu: "¡GANA EL JUGADOR {0}!",
  queda: "¡PULSO!",
  queda_sub: "¡Se acabó el tiempo! Gana quien haga clic más rápido",
  queda_dica_bot: "¡CLIC / ESPACIO!",
  queda_dica_toque: "¡TOCA LA PANTALLA!",
  queda_dica_p1: "¡PULSA F!",
  queda_dica_p2: "¡PULSA L!",
  queda_dica_toque_esq: "¡TOCA A LA IZQUIERDA!",
  queda_dica_toque_dir: "¡TOCA A LA DERECHA!",
  toque_mover: "mover",
  toque_tiro: "DISPARAR",
  pegou_arma: "¡{0}!",
  c_campo: "Prado",
  r_campo: "Clásico: ¡a luchar!",
  c_gelo: "Glaciar",
  r_gelo: "Hielo: ¡todo resbala!",
  c_lua: "Luna",
  r_lua: "Poca gravedad: saltos gigantes",
  c_vulcao: "Volcán",
  r_vulcao: "La lava sube y baja: ¡quédate arriba!",
  c_espaco: "Espacio",
  r_espaco: "Casi sin gravedad: salta para volar",
  c_laboratorio: "Laboratorio",
  r_laboratorio: "¡La gravedad se invierte!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: ¡empuja al rival fuera!",
  c_cidade: "Ciudad Neón",
  r_cidade: "¡Cuidado con el hueco entre edificios!",
  c_fliperama: "Pinball",
  r_fliperama: "¡Los rebotadores te lanzan lejos!",
  c_floresta: "Bosque Nocturno",
  r_floresta: "A oscuras: solo ves cerca de la luz",
  c_deserto: "Desierto",
  r_deserto: "¡El viento fuerte cambia de lado!",
  c_fabrica: "Fábrica",
  r_fabrica: "¡Las cintas te arrastran!",
  c_oceano: "Fondo del Mar",
  r_oceano: "Bajo el agua: salta para nadar",
  c_templo: "Templo",
  r_templo: "Sal por un lado, entra por el otro. ¡Portales!",
  c_castelo: "Castillo",
  r_castelo: "Lluvia de meteoros: ¡esquiva las marcas!",
  k_escudo: "Escudo",
  kd_escudo: "Bloquea 40 de daño",
  k_rapidez: "Velocidad",
  kd_rapidez: "Más rápido 7 s",
  k_cura: "Curación",
  kd_cura: "+35 de vida",
  k_furia: "Furia",
  kd_furia: "Daño doble 6 s",
  k_tiro_duplo: "Disparo Doble",
  kd_tiro_duplo: "Cada disparo sale doble",
  k_mini: "Mini",
  kd_mini: "Pequeño y difícil de acertar",
  k_congelar: "Congelar",
  kd_congelar: "Congela al rival",
  k_fantasma: "Fantasma",
  kd_fantasma: "Casi invisible 5 s",
  k_reflexo: "Reflejo",
  kd_reflexo: "Devuelve los disparos 5 s",
  k_super_pulo: "Súper Salto",
  kd_super_pulo: "Triple salto y más alto",
  k_chuva: "Lluvia de Meteoros",
  kd_chuva: "5 meteoros sobre el rival",
  k_municao: "Munición Infinita",
  kd_municao: "Sin gastar munición 8 s",
  a_estilingue: "Tirachinas",
  a_pistola: "Pistola",
  a_revolver: "Revólver",
  a_submetralhadora: "Subfusil",
  a_minigun: "Minigun",
  a_escopeta: "Escopeta",
  a_escopeta_dupla: "Escopeta Doble",
  a_rifle: "Rifle",
  a_sniper: "Francotirador",
  a_plasma: "Plasma",
  a_pula_pula: "Pelota Saltarina",
  a_confete: "Cañón de Confeti",
  a_arma_agua: "Pistola de Agua",
  a_zarabatana: "Cerbatana",
  a_onda_sonora: "Onda Sónica",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerán",
  a_arco: "Arco",
  a_arco_triplo: "Arco Triple",
  a_besta: "Ballesta",
  a_serra: "Sierra Giratoria",
  a_bola_neve: "Bola de Nieve",
  a_gancho: "Gancho",
  a_bazuca: "Bazuca",
  a_lanca_granadas: "Lanzagranadas",
  a_granada: "Granada",
  a_dinamite: "Dinamita",
  a_fragmentacao: "Granada de Racimo",
  a_canhao: "Cañón",
  a_mini_misseis: "Mini Misiles",
  a_missil: "Misil Teledirigido",
  a_abelhas: "Enjambre de Abejas",
  a_bola_fogo: "Bola de Fuego",
  a_granada_gelo: "Granada de Hielo",
  a_mina: "Mina",
  a_laser: "Láser",
  a_railgun: "Cañón de Riel",
  a_arco_iris: "Láser Arcoíris",
  a_feixe: "Rayo Continuo",
  a_tesla: "Tesla",
  a_raio_gelo: "Rayo de Hielo",
  a_bolhas: "Pistola de Burbujas",
  a_buraco_negro: "Agujero Negro",
  a_lanca_chamas: "Lanzallamas",
  a_soprador: "Soplador",
  a_martelo: "Martillo",
  a_espada: "Espada",
  a_luva_boxe: "Guante de Boxeo",
  a_meteoro: "Meteoros",
  a_relampago: "Relámpago"
};
