"use strict";
TEXTOS.fr = {
  titulo: "Duel de Boules",
  jogar: "JOUER",
  idioma: "Langue",
  som_on: "Son : activé",
  som_off: "Son : coupé",
  voltar: "Retour",
  pausado: "Pause",
  continuar: "Reprendre",
  menu: "Menu",
  anuncio_falhou: "La pub n'a pas chargé. Réessaie plus tard.",
  escolha_modo: "Comment veux-tu jouer ?",
  contra_bot: "Contre le bot",
  dois_jogadores: "2 joueurs",
  dica_bot_teclado: "Q D / ← → bouger\nZ / ↑ sauter\nF / Espace / L tirer",
  dica_bot_toque: "Gauche : glisse pour bouger et sauter\nDroite : maintiens pour tirer",
  dica_2p_teclado: "Joueur 1 : Q D Z + F\nJoueur 2 : ← → ↑ + L\nSur le même clavier !",
  dica_2p_toque: "Chacun utilise sa moitié de l'écran",
  lendaria: "Match Légendaire",
  lendaria_anuncio: "Match Légendaire : armes rares seulement (pub)",
  lendaria_ativada: "Match Légendaire activé ! Choisis le mode",
  continuar_anuncio: "▶ Continuer",
  continuar_explica: "Regarde une pub et le match continue : le bot perd son dernier point.",
  nao_obrigado: "Non merci",
  voce: "TOI",
  voce_curto: "TOI",
  bot: "BOT",
  jogador_n: "JOUEUR {0}",
  rodada_n: "Manche {0}",
  dano_dobro: "DÉGÂTS DOUBLÉS !",
  lute: "COMBATS !",
  empate: "ÉGALITÉ !",
  voce_venceu_rodada: "MANCHE GAGNÉE !",
  bot_venceu_rodada: "LE BOT GAGNE LA MANCHE",
  jogador_venceu_rodada: "MANCHE POUR LE JOUEUR {0} !",
  voce_venceu: "TU AS GAGNÉ !",
  bot_venceu: "LE BOT GAGNE",
  jogador_venceu: "LE JOUEUR {0} GAGNE !",
  queda: "BRAS DE FER !",
  queda_sub: "Temps écoulé ! Le plus rapide à cliquer gagne",
  queda_dica_bot: "CLIC / ESPACE !",
  queda_dica_toque: "TAPE L'ÉCRAN !",
  queda_dica_p1: "APPUIE SUR F !",
  queda_dica_p2: "APPUIE SUR L !",
  queda_dica_toque_esq: "TAPE À GAUCHE !",
  queda_dica_toque_dir: "TAPE À DROITE !",
  toque_mover: "bouger",
  toque_tiro: "TIRER",
  pegou_arma: "{0} !",
  c_campo: "Prairie",
  r_campo: "Classique : bats-toi !",
  c_gelo: "Glacier",
  r_gelo: "Glace : tout glisse !",
  c_lua: "Lune",
  r_lua: "Faible gravité : sauts géants",
  c_vulcao: "Volcan",
  r_vulcao: "La lave monte et descend : reste en haut !",
  c_espaco: "Espace",
  r_espaco: "Presque sans gravité : saute pour voler",
  c_laboratorio: "Labo",
  r_laboratorio: "La gravité s'inverse !",
  c_dojo: "Dojo",
  r_dojo: "Sumo : pousse l'adversaire dehors !",
  c_cidade: "Ville Néon",
  r_cidade: "Attention au vide entre les immeubles !",
  c_fliperama: "Flipper",
  r_fliperama: "Les bumpers t'envoient valser !",
  c_floresta: "Forêt Nocturne",
  r_floresta: "Dans le noir : on voit près de la lumière",
  c_deserto: "Désert",
  r_deserto: "Le vent change de sens !",
  c_fabrica: "Usine",
  r_fabrica: "Les tapis roulants t'emportent !",
  c_oceano: "Fond Marin",
  r_oceano: "Sous l'eau : saute pour nager",
  c_templo: "Temple",
  r_templo: "Sors d'un côté, reviens de l'autre. Portails !",
  c_castelo: "Château",
  r_castelo: "Pluie de météores : évite les cibles !",
  k_escudo: "Bouclier",
  kd_escudo: "Bloque 40 dégâts",
  k_rapidez: "Vitesse",
  kd_rapidez: "Plus rapide 7 s",
  k_cura: "Soin",
  kd_cura: "+35 de vie",
  k_furia: "Fureur",
  kd_furia: "Dégâts doublés 6 s",
  k_tiro_duplo: "Tir Double",
  kd_tiro_duplo: "Chaque tir est doublé",
  k_mini: "Mini",
  kd_mini: "Petit et dur à toucher",
  k_congelar: "Gel",
  kd_congelar: "Gèle l'adversaire",
  k_fantasma: "Fantôme",
  kd_fantasma: "Presque invisible 5 s",
  k_reflexo: "Reflet",
  kd_reflexo: "Renvoie les tirs 5 s",
  k_super_pulo: "Super Saut",
  kd_super_pulo: "Triple saut plus haut",
  k_chuva: "Pluie de Météores",
  kd_chuva: "5 météores sur l'adversaire",
  k_municao: "Munitions Infinies",
  kd_municao: "Aucune munition utilisée 8 s",
  a_estilingue: "Lance-pierre",
  a_pistola: "Pistolet",
  a_revolver: "Revolver",
  a_submetralhadora: "Mitraillette",
  a_minigun: "Minigun",
  a_escopeta: "Fusil à pompe",
  a_escopeta_dupla: "Double Canon",
  a_rifle: "Fusil",
  a_sniper: "Sniper",
  a_plasma: "Plasma",
  a_pula_pula: "Balle Rebondissante",
  a_confete: "Canon à Confettis",
  a_arma_agua: "Pistolet à Eau",
  a_zarabatana: "Sarbacane",
  a_onda_sonora: "Onde Sonore",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boomerang",
  a_arco: "Arc",
  a_arco_triplo: "Arc Triple",
  a_besta: "Arbalète",
  a_serra: "Scie Circulaire",
  a_bola_neve: "Boule de Neige",
  a_gancho: "Grappin",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Lance-Grenades",
  a_granada: "Grenade",
  a_dinamite: "Dynamite",
  a_fragmentacao: "Grenade à Fragmentation",
  a_canhao: "Canon",
  a_mini_misseis: "Mini Missiles",
  a_missil: "Missile à Tête Chercheuse",
  a_abelhas: "Essaim d'Abeilles",
  a_bola_fogo: "Boule de Feu",
  a_granada_gelo: "Grenade de Glace",
  a_mina: "Mine",
  a_laser: "Laser",
  a_railgun: "Canon Électrique",
  a_arco_iris: "Laser Arc-en-ciel",
  a_feixe: "Rayon Continu",
  a_tesla: "Tesla",
  a_raio_gelo: "Rayon de Glace",
  a_bolhas: "Pistolet à Bulles",
  a_buraco_negro: "Trou Noir",
  a_lanca_chamas: "Lance-Flammes",
  a_soprador: "Souffleur",
  a_martelo: "Marteau",
  a_espada: "Épée",
  a_luva_boxe: "Gant de Boxe",
  a_meteoro: "Météores",
  a_relampago: "Éclair"
};
