"use strict";
TEXTOS.fr = {
  titulo: "Crazy Balls Duel",
  jogar: "JOUER",
  idioma: "Langue",
  som_on: "Son : activé",
  som_off: "Son : coupé",
  voltar: "Retour",
  pausado: "Pause",
  continuar: "Reprendre",
  menu: "Menu",
  anuncio_falhou: "La pub n'a pas chargé. Réessaie plus tard.",
  escolha_modo: "Comment veux-tu jouer ?",
  contra_bot: "Contre le bot",
  dois_jogadores: "2 joueurs",
  dica_bot_teclado: "Q D / ← → bouger\nZ / ↑ sauter\nF / Espace / L tirer",
  dica_bot_toque: "Gauche : glisse pour bouger\nDroite : en haut saute · en bas vise et tire",
  dica_2p_teclado: "Joueur 1 : Q D Z + F\nJoueur 2 : ← → ↑ + L\nSur le même clavier !",
  dica_2p_toque: "À deux sur le même téléphone, à l'horizontale : chacun sa moitié d'écran",
  lendaria: "Match Légendaire",
  lendaria_anuncio: "Match Légendaire : armes rares seulement (pub)",
  lendaria_ativada: "Match Légendaire activé ! Choisis le mode",
  continuar_anuncio: "▶ Continuer",
  continuar_explica: "Regarde une pub et le match continue : le bot perd son dernier point.",
  nao_obrigado: "Non merci",
  voce: "TOI",
  voce_curto: "TOI",
  bot: "BOT",
  jogador_n: "JOUEUR {0}",
  rodada_n: "Manche {0}",
  dano_dobro: "DÉGÂTS DOUBLÉS !",
  lute: "COMBATS !",
  empate: "ÉGALITÉ !",
  voce_venceu_rodada: "MANCHE GAGNÉE !",
  bot_venceu_rodada: "LE BOT GAGNE LA MANCHE",
  jogador_venceu_rodada: "MANCHE POUR LE JOUEUR {0} !",
  voce_venceu: "TU AS GAGNÉ !",
  bot_venceu: "LE BOT GAGNE",
  jogador_venceu: "LE JOUEUR {0} GAGNE !",
  queda: "BRAS DE FER !",
  queda_sub: "Temps écoulé ! Le plus rapide à cliquer gagne",
  queda_dica_bot: "CLIC / ESPACE !",
  queda_dica_toque: "TAPE L'ÉCRAN !",
  queda_dica_p1: "APPUIE SUR F !",
  queda_dica_p2: "APPUIE SUR L !",
  queda_dica_toque_esq: "TAPE À GAUCHE !",
  queda_dica_toque_dir: "TAPE À DROITE !",
  toque_mover: "bouger",
  toque_tiro: "TIRER",
  pegou_arma: "{0} !",
  mesmo_aparelho: "Sur le même appareil · pas en ligne",
  qualidade_auto: "Graphismes : auto",
  qualidade_alta: "Graphismes : élevés",
  qualidade_leve: "Graphismes : légers",
  perfeito: "PARFAIT !",
  missoes: "Missions",
  skins: "Skins",
  opcoes: "Options",
  controles: "Commandes",
  controles_mouse: "Le joueur 1 vise aussi à la SOURIS (clic = tir). Clique une touche puis appuie sur la nouvelle.",
  teclas_padrao: "Touches par défaut",
  semana: "Semaine",
  conquistas: "Succès",
  skins_corpo: "Boule",
  skins_acessorio: "Accessoire",
  dobrar_moedas: "Doubler les pièces",
  resgatar: "Récupérer",
  trocar: "Changer",
  missoes_explica: "Termine des missions pour gagner des pièces. 1 changement de mission par jour.",
  semana_termina: "Se termine dans {0}j {1}h",
  premio_semana: "Prix de la semaine : réussis les 4 défis",
  equipado: "Équipé",
  equipar: "Équiper",
  so_semanal: "Prix hebdo",
  acao_esquerda: "Gauche",
  acao_direita: "Droite",
  acao_pulo: "Sauter",
  acao_baixo: "Descendre",
  acao_tiro: "Tirer",
  tecla_espaco: "Espace",
  toque_mira: "VISER",
  dica_bot_v2: "{0} bouger · {1} sauter\nSouris : vise et tire (ou {2})",
  dica_2p_v2: "Joueur 1 : {0}\nJoueur 2 : {1}\nSur le même clavier !",
  aviso_missao: "Mission réussie !",
  aviso_desafio: "Défi de la semaine réussi !",
  aviso_conquista: "Succès : {0} !",
  nivel_bot: "🤖 Bot niveau {0}",
  nivel_curto: "Niv. {0}",
  bot_subiu: "Le bot passe au niveau {0} !",
  bot_desceu: "Le bot descend au niveau {0}",
  nivel_jogador: "Niveau {0}",
  subiu_nivel: "Niveau {0} atteint !",
  abrir_bau: "Ouvrir le coffre",
  abrir_bau_nivel: "Ouvrir le coffre de niveau !",
  outro_bau: "Ouvrir un autre coffre",
  revanche: "REVANCHE",
  premio_skin: "Nouveau skin : {0} !",
  diaria: "Récompense du jour",
  diaria_explica: "Reviens chaque jour : la récompense grandit ! Un jour raté et tout recommence.",
  dia_n: "Jour {0}",
  bau: "coffre",
  bau_lendario: "coffre légendaire",
  pegar: "Récupérer",
  fechar: "Fermer",
  sobrevivencia: "Survie",
  sobrevivencia_dica: "Des vagues de bots toujours plus forts.\nJusqu'où iras-tu ?",
  onda_n: "VAGUE {0}",
  onda_concluida: "VAGUE {0} TERMINÉE !",
  fim_sobrevivencia: "Tu as atteint la vague {0} !",
  recorde_onda: "Record : vague {0}",
  novo_recorde: "NOUVEAU RECORD !",
  continuar_vida: "Regarde une pub et continue la même vague avec toute ta vie.",
  dica_bot_v3: "{0} bouger · {1} sauter\nSouris : viser · Clic ou {2} : tirer",
  dica_2p_v3: "Joueur 1 : {0} + souris\nJoueur 2 : {1}\nSur le même clavier !",
  queda_clique: "CLIC OU {0} !",
  queda_aperte: "APPUIE SUR {0} !",
  toque_pulo: "SAUTER",
  estilo_agressivo: "Agressif",
  estilo_atirador: "Tireur",
  estilo_saltitante: "Sauteur",
  estilo_cauteloso: "Prudent",
  estilo_colecionador: "Collectionneur",
  c_campo: "Prairie",
  r_campo: "Classique : bats-toi !",
  c_gelo: "Glacier",
  r_gelo: "Glace : tout glisse !",
  c_lua: "Lune",
  r_lua: "Faible gravité : sauts géants",
  c_vulcao: "Volcan",
  r_vulcao: "La lave monte et descend : reste en haut !",
  c_espaco: "Espace",
  r_espaco: "Presque sans gravité : saute pour voler",
  c_laboratorio: "Labo",
  r_laboratorio: "La gravité s'inverse !",
  c_dojo: "Dojo",
  r_dojo: "Sumo : pousse l'adversaire dehors !",
  c_cidade: "Ville Néon",
  r_cidade: "Attention au vide entre les immeubles !",
  c_fliperama: "Flipper",
  r_fliperama: "Les bumpers t'envoient valser !",
  c_floresta: "Forêt Nocturne",
  r_floresta: "Dans le noir : on voit près de la lumière",
  c_deserto: "Désert",
  r_deserto: "Le vent change de sens !",
  c_fabrica: "Usine",
  r_fabrica: "Les tapis roulants t'emportent !",
  c_oceano: "Fond Marin",
  r_oceano: "Sous l'eau : saute pour nager",
  c_templo: "Temple",
  r_templo: "Sors d'un côté, reviens de l'autre. Portails !",
  c_castelo: "Château",
  r_castelo: "Pluie de météores : évite les cibles !",
  k_escudo: "Bouclier",
  kd_escudo: "Bloque 40 dégâts",
  k_rapidez: "Vitesse",
  kd_rapidez: "Plus rapide 7 s",
  k_cura: "Soin",
  kd_cura: "+35 de vie",
  k_furia: "Fureur",
  kd_furia: "Dégâts doublés 6 s",
  k_tiro_duplo: "Tir Double",
  kd_tiro_duplo: "Chaque tir est doublé",
  k_mini: "Mini",
  kd_mini: "Petit et dur à toucher",
  k_congelar: "Gel",
  kd_congelar: "Gèle l'adversaire",
  k_fantasma: "Fantôme",
  kd_fantasma: "Presque invisible 5 s",
  k_reflexo: "Reflet",
  kd_reflexo: "Renvoie les tirs 5 s",
  k_super_pulo: "Super Saut",
  kd_super_pulo: "Triple saut plus haut",
  k_chuva: "Pluie de Météores",
  kd_chuva: "5 météores sur l'adversaire",
  k_municao: "Munitions Infinies",
  kd_municao: "Aucune munition utilisée 8 s",
  a_estilingue: "Lance-pierre",
  a_pistola: "Pistolet",
  a_revolver: "Revolver",
  a_submetralhadora: "Mitraillette",
  a_minigun: "Minigun",
  a_escopeta: "Fusil à pompe",
  a_escopeta_dupla: "Double Canon",
  a_rifle: "Fusil",
  a_sniper: "Sniper",
  a_plasma: "Plasma",
  a_pula_pula: "Balle Rebondissante",
  a_confete: "Canon à Confettis",
  a_arma_agua: "Pistolet à Eau",
  a_zarabatana: "Sarbacane",
  a_onda_sonora: "Onde Sonore",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boomerang",
  a_arco: "Arc",
  a_arco_triplo: "Arc Triple",
  a_besta: "Arbalète",
  a_serra: "Scie Circulaire",
  a_bola_neve: "Boule de Neige",
  a_gancho: "Grappin",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Lance-Grenades",
  a_granada: "Grenade",
  a_dinamite: "Dynamite",
  a_fragmentacao: "Grenade à Fragmentation",
  a_canhao: "Canon",
  a_mini_misseis: "Mini Missiles",
  a_missil: "Missile à Tête Chercheuse",
  a_abelhas: "Essaim d'Abeilles",
  a_bola_fogo: "Boule de Feu",
  a_granada_gelo: "Grenade de Glace",
  a_mina: "Mine",
  a_laser: "Laser",
  a_railgun: "Canon Électrique",
  a_arco_iris: "Laser Arc-en-ciel",
  a_feixe: "Rayon Continu",
  a_tesla: "Tesla",
  a_raio_gelo: "Rayon de Glace",
  a_bolhas: "Pistolet à Bulles",
  a_buraco_negro: "Trou Noir",
  a_lanca_chamas: "Lance-Flammes",
  a_soprador: "Souffleur",
  a_martelo: "Marteau",
  a_espada: "Épée",
  a_luva_boxe: "Gant de Boxe",
  a_meteoro: "Météores",
  a_relampago: "Éclair",
  mi_vitorias: "Gagne {0} match(s) contre le bot",
  mi_rodadas: "Gagne {0} manches",
  mi_dano: "Inflige {0} dégâts",
  mi_quedas: "Gagne {0} bras de fer",
  mi_cartas: "Prends {0} cartes",
  mi_caixas: "Prends {0} caisses d'armes",
  mi_abatesExpl: "Gagne {0} manche(s) aux explosifs",
  mi_abatesMelee: "Gagne {0} manche(s) au corps à corps",
  mi_perfeitas: "Gagne {0} manche(s) sans dégâts",
  mi_partidas: "Joue {0} matchs",
  mi_partidas2p: "Joue {0} match(s) à 2 joueurs",
  mi_rodadaCenario: "Gagne {0} manche(s) dans : {1}",
  de_s_vitorias: "Gagne {0} match(s) contre le bot",
  de_s_rodadas: "Gagne {0} manches",
  de_s_dano: "Inflige {0} dégâts",
  de_s_quedas: "Gagne {0} bras de fer",
  de_s_cenarios: "Gagne des manches dans {0} arènes différentes",
  de_s_5x0: "Gagne un match 5 – 0",
  de_s_expl: "Gagne {0} manche(s) aux explosifs",
  de_s_cartas: "Prends {0} cartes",
  de_s_perfeitas: "Gagne {0} manche(s) sans dégâts",
  de_s_virada: "Gagne en remontant 3 points de retard",
  co_primeira_vitoria: "Première Victoire",
  cod_primeira_vitoria: "Gagne {0} match(s) contre le bot",
  co_vitorias_10: "Duelliste",
  cod_vitorias_10: "Gagne {0} match(s) contre le bot",
  co_vitorias_25: "Vétéran",
  cod_vitorias_25: "Gagne {0} match(s) contre le bot",
  co_vitorias_100: "Légende",
  cod_vitorias_100: "Gagne {0} match(s) contre le bot",
  co_partidas_50: "Accro",
  cod_partidas_50: "Joue {0} matchs",
  co_rodadas_50: "Gagneur de Manches",
  cod_rodadas_50: "Gagne {0} manches",
  co_rodadas_250: "Machine",
  cod_rodadas_250: "Gagne {0} manches",
  co_dano_20000: "Destructeur",
  cod_dano_20000: "Inflige {0} dégâts",
  co_dano_100000: "Apocalypse",
  cod_dano_100000: "Inflige {0} dégâts",
  co_quedas_5: "Bras Fort",
  cod_quedas_5: "Gagne {0} bras de fer",
  co_quedas_20: "Champion de Bras de Fer",
  cod_quedas_20: "Gagne {0} bras de fer",
  co_explosivos_50: "Démolisseur",
  cod_explosivos_50: "Gagne {0} manche(s) aux explosifs",
  co_melee_20: "Bagarreur",
  cod_melee_20: "Gagne {0} manche(s) au corps à corps",
  co_perfeitas_10: "Intouchable",
  cod_perfeitas_10: "Gagne {0} manche(s) sans dégâts",
  co_cenarios_todos: "Explorateur",
  cod_cenarios_todos: "Gagne des manches dans {0} arènes différentes",
  co_armas_25: "Collectionneur",
  cod_armas_25: "Prends {0} armes différentes",
  co_armas_todas: "Arsenal Complet",
  cod_armas_todas: "Prends {0} armes différentes",
  co_cartas_todas: "Jeu Complet",
  cod_cartas_todas: "Prends les {0} cartes différentes",
  co_placar_5x0: "Raclée",
  cod_placar_5x0: "Gagne un match 5 – 0",
  co_virada: "Remontada Épique",
  cod_virada: "Gagne en remontant 3 points de retard",
  co_bot_mestre: "Maître du Bot",
  cod_bot_mestre: "Bats le bot à son niveau max",
  co_dois_jogadores_10: "Meilleurs Amis",
  cod_dois_jogadores_10: "Joue {0} match(s) à 2 joueurs",
  co_missoes_10: "Dévoué",
  cod_missoes_10: "Récupère {0} missions",
  co_missoes_50: "Infatigable",
  cod_missoes_50: "Récupère {0} missions",
  co_semana_completa: "Semaine Parfaite",
  cod_semana_completa: "Réussis tous les défis d'une semaine",
  co_onda_5: "Survivant",
  cod_onda_5: "Atteins la vague {0} en Survie",
  co_onda_10: "Inarrêtable",
  cod_onda_10: "Atteins la vague {0} en Survie",
  sk_classico: "Classique",
  sk_listras: "Rayures",
  sk_pintas: "Pois",
  sk_xadrez: "Damier",
  sk_camuflado: "Camouflage",
  sk_futebol: "Ballon de Foot",
  sk_melancia: "Pastèque",
  sk_robo: "Robot",
  sk_doce: "Bonbon",
  sk_cromado: "Chrome",
  sk_gelo: "Cristal de Glace",
  sk_neon: "Néon",
  sk_lava: "Lave",
  sk_diamante: "Diamant",
  sk_galaxia: "Galaxie",
  sk_ouro: "Or",
  sk_nenhum: "Aucun",
  sk_bone: "Casquette",
  sk_oculos: "Lunettes de Soleil",
  sk_orelhas_gato: "Oreilles de Chat",
  sk_fone: "Casque",
  sk_cartola: "Haut-de-forme",
  sk_chifres: "Cornes",
  sk_tiara_flores: "Couronne de Fleurs",
  sk_mascara_ninja: "Masque Ninja",
  sk_viking: "Casque Viking",
  sk_cowboy: "Chapeau de Cowboy",
  sk_antena: "Antenne Alien",
  sk_aureola: "Auréole",
  sk_coroa: "Couronne",
  novo: "NOUVEAU !",
  proximo_rival: "RIVAL SUIVANT",
  premio_equipado: "{0} équipé !",
  modo_rivais: "Rivaux",
  rivais_dica: "Bats 10 rivaux et monte de ligue",
  rival_n: "RIVAL {0}/{1}",
  liga_0: "Bronze",
  liga_1: "Argent",
  liga_2: "Or",
  liga_3: "Diamant",
  liga_4: "Maître",
  liga_n: "Ligue {0}",
  rival_derrotado: "{0} vaincu !",
  proximo: "Suivant : {0}",
  revanche_contra: "Revanche contre {0}",
  campeao_liga: "CHAMPION DE LA LIGUE {0} !",
  rival_venceu: "{0} gagne !",
  venca_ganhe: "Gagne et obtiens : {0}",
  salvo: "SAUVÉ !"
};
