"use strict";
TEXTOS.id = {
  titulo: "Duel Bola",
  jogar: "MAIN",
  idioma: "Bahasa",
  som_on: "Suara: nyala",
  som_off: "Suara: mati",
  voltar: "Kembali",
  pausado: "Jeda",
  continuar: "Lanjut",
  menu: "Menu",
  anuncio_falhou: "Iklan gagal dimuat. Coba lagi nanti.",
  escolha_modo: "Mau main bagaimana?",
  contra_bot: "Lawan bot",
  dois_jogadores: "2 pemain",
  dica_bot_teclado: "A D / ← → jalan\nW / ↑ lompat\nF / Spasi / L tembak",
  dica_bot_toque: "Kiri: geser untuk jalan dan lompat\nKanan: tahan untuk menembak",
  dica_2p_teclado: "Pemain 1: A D W + F\nPemain 2: ← → ↑ + L\nDi keyboard yang sama!",
  dica_2p_toque: "Masing-masing pakai separuh layar",
  lendaria: "Pertandingan Legendaris",
  lendaria_anuncio: "Pertandingan Legendaris: senjata langka saja (iklan)",
  lendaria_ativada: "Pertandingan Legendaris aktif! Pilih mode",
  continuar_anuncio: "▶ Lanjutkan",
  continuar_explica: "Tonton iklan dan pertandingan lanjut: bot kehilangan poin terakhirnya.",
  nao_obrigado: "Tidak, terima kasih",
  voce: "KAMU",
  voce_curto: "KAMU",
  bot: "BOT",
  jogador_n: "PEMAIN {0}",
  rodada_n: "Ronde {0}",
  dano_dobro: "DAMAGE GANDA!",
  lute: "BERTARUNG!",
  empate: "SERI!",
  voce_venceu_rodada: "KAMU MENANG RONDE!",
  bot_venceu_rodada: "BOT MENANG RONDE",
  jogador_venceu_rodada: "RONDE UNTUK PEMAIN {0}!",
  voce_venceu: "KAMU MENANG!",
  bot_venceu: "BOT MENANG",
  jogador_venceu: "PEMAIN {0} MENANG!",
  queda: "PANCO!",
  queda_sub: "Waktu habis! Yang klik paling cepat menang",
  queda_dica_bot: "KLIK / SPASI!",
  queda_dica_toque: "KETUK LAYAR!",
  queda_dica_p1: "TEKAN F!",
  queda_dica_p2: "TEKAN L!",
  queda_dica_toque_esq: "KETUK SISI KIRI!",
  queda_dica_toque_dir: "KETUK SISI KANAN!",
  toque_mover: "jalan",
  toque_tiro: "TEMBAK",
  pegou_arma: "{0}!",
  c_campo: "Padang",
  r_campo: "Klasik: bertarung saja!",
  c_gelo: "Gletser",
  r_gelo: "Es: semua licin!",
  c_lua: "Bulan",
  r_lua: "Gravitasi rendah: lompatan raksasa",
  c_vulcao: "Gunung Api",
  r_vulcao: "Lava naik turun: tetap di atas!",
  c_espaco: "Luar Angkasa",
  r_espaco: "Hampir tanpa gravitasi: lompat untuk terbang",
  c_laboratorio: "Laboratorium",
  r_laboratorio: "Gravitasi terbalik!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: dorong lawan keluar!",
  c_cidade: "Kota Neon",
  r_cidade: "Awas celah antar gedung!",
  c_fliperama: "Pinball",
  r_fliperama: "Bumper melemparmu jauh!",
  c_floresta: "Hutan Malam",
  r_floresta: "Gelap: hanya terlihat dekat cahaya",
  c_deserto: "Gurun",
  r_deserto: "Angin kencang berganti arah!",
  c_fabrica: "Pabrik",
  r_fabrica: "Ban berjalan membawamu!",
  c_oceano: "Dasar Laut",
  r_oceano: "Bawah air: lompat untuk berenang",
  c_templo: "Kuil",
  r_templo: "Keluar di satu sisi, masuk di sisi lain. Portal!",
  c_castelo: "Kastil",
  r_castelo: "Hujan meteor: hindari target!",
  k_escudo: "Perisai",
  kd_escudo: "Menahan 40 damage",
  k_rapidez: "Kecepatan",
  kd_rapidez: "Lebih cepat 7 dtk",
  k_cura: "Penyembuhan",
  kd_cura: "+35 nyawa",
  k_furia: "Amarah",
  kd_furia: "Damage ganda 6 dtk",
  k_tiro_duplo: "Tembakan Ganda",
  kd_tiro_duplo: "Setiap tembakan jadi dua",
  k_mini: "Mini",
  kd_mini: "Kecil dan sulit dikenai",
  k_congelar: "Bekukan",
  kd_congelar: "Membekukan lawan",
  k_fantasma: "Hantu",
  kd_fantasma: "Hampir tak terlihat 5 dtk",
  k_reflexo: "Pantul",
  kd_reflexo: "Memantulkan tembakan 5 dtk",
  k_super_pulo: "Lompatan Super",
  kd_super_pulo: "Lompat tiga kali, lebih tinggi",
  k_chuva: "Hujan Meteor",
  kd_chuva: "5 meteor ke lawan",
  k_municao: "Amunisi Tak Terbatas",
  kd_municao: "Tanpa habis amunisi 8 dtk",
  a_estilingue: "Ketapel",
  a_pistola: "Pistol",
  a_revolver: "Revolver",
  a_submetralhadora: "SMG",
  a_minigun: "Minigun",
  a_escopeta: "Shotgun",
  a_escopeta_dupla: "Shotgun Ganda",
  a_rifle: "Senapan",
  a_sniper: "Sniper",
  a_plasma: "Plasma",
  a_pula_pula: "Bola Pantul",
  a_confete: "Meriam Konfeti",
  a_arma_agua: "Pistol Air",
  a_zarabatana: "Sumpit",
  a_onda_sonora: "Gelombang Suara",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Busur",
  a_arco_triplo: "Busur Tiga",
  a_besta: "Panah Silang",
  a_serra: "Gergaji Putar",
  a_bola_neve: "Bola Salju",
  a_gancho: "Pengait",
  a_bazuca: "Bazoka",
  a_lanca_granadas: "Pelontar Granat",
  a_granada: "Granat",
  a_dinamite: "Dinamit",
  a_fragmentacao: "Granat Pecahan",
  a_canhao: "Meriam",
  a_mini_misseis: "Roket Mini",
  a_missil: "Rudal Pelacak",
  a_abelhas: "Kawanan Lebah",
  a_bola_fogo: "Bola Api",
  a_granada_gelo: "Granat Es",
  a_mina: "Ranjau",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Pelangi",
  a_feixe: "Sinar Kontinu",
  a_tesla: "Tesla",
  a_raio_gelo: "Sinar Es",
  a_bolhas: "Pistol Gelembung",
  a_buraco_negro: "Lubang Hitam",
  a_lanca_chamas: "Pelontar Api",
  a_soprador: "Peniup Daun",
  a_martelo: "Palu",
  a_espada: "Pedang",
  a_luva_boxe: "Sarung Tinju",
  a_meteoro: "Meteor",
  a_relampago: "Petir"
};
