"use strict";
TEXTOS.id = {
  titulo: "Crazy Balls Duel",
  jogar: "MAIN",
  idioma: "Bahasa",
  som_on: "Suara: nyala",
  som_off: "Suara: mati",
  voltar: "Kembali",
  pausado: "Jeda",
  continuar: "Lanjut",
  menu: "Menu",
  anuncio_falhou: "Iklan gagal dimuat. Coba lagi nanti.",
  escolha_modo: "Mau main bagaimana?",
  contra_bot: "Lawan bot",
  dois_jogadores: "2 pemain",
  dica_bot_teclado: "A D / ← → jalan\nW / ↑ lompat\nF / Spasi / L tembak",
  dica_bot_toque: "Kiri: geser untuk jalan\nKanan: atas lompat · bawah bidik dan tembak",
  dica_2p_teclado: "Pemain 1: A D W + F\nPemain 2: ← → ↑ + L\nDi keyboard yang sama!",
  dica_2p_toque: "Berdua di satu HP, posisi miring: masing-masing pakai separuh layar",
  lendaria: "Pertandingan Legendaris",
  lendaria_anuncio: "Pertandingan Legendaris: senjata langka saja (iklan)",
  lendaria_ativada: "Pertandingan Legendaris aktif! Pilih mode",
  continuar_anuncio: "▶ Lanjutkan",
  continuar_explica: "Tonton iklan dan pertandingan lanjut: bot kehilangan poin terakhirnya.",
  nao_obrigado: "Tidak, terima kasih",
  voce: "KAMU",
  voce_curto: "KAMU",
  bot: "BOT",
  jogador_n: "PEMAIN {0}",
  rodada_n: "Ronde {0}",
  dano_dobro: "DAMAGE GANDA!",
  lute: "BERTARUNG!",
  empate: "SERI!",
  voce_venceu_rodada: "KAMU MENANG RONDE!",
  bot_venceu_rodada: "BOT MENANG RONDE",
  jogador_venceu_rodada: "RONDE UNTUK PEMAIN {0}!",
  voce_venceu: "KAMU MENANG!",
  bot_venceu: "BOT MENANG",
  jogador_venceu: "PEMAIN {0} MENANG!",
  queda: "PANCO!",
  queda_sub: "Waktu habis! Yang klik paling cepat menang",
  queda_dica_bot: "KLIK / SPASI!",
  queda_dica_toque: "KETUK LAYAR!",
  queda_dica_p1: "TEKAN F!",
  queda_dica_p2: "TEKAN L!",
  queda_dica_toque_esq: "KETUK SISI KIRI!",
  queda_dica_toque_dir: "KETUK SISI KANAN!",
  toque_mover: "jalan",
  toque_tiro: "TEMBAK",
  pegou_arma: "{0}!",
  mesmo_aparelho: "Di perangkat yang sama · bukan online",
  qualidade_auto: "Grafis: otomatis",
  qualidade_alta: "Grafis: tinggi",
  qualidade_leve: "Grafis: ringan",
  perfeito: "SEMPURNA!",
  missoes: "Misi",
  skins: "Skin",
  opcoes: "Opsi",
  controles: "Kontrol",
  controles_mouse: "Pemain 1 juga membidik dengan MOUSE (klik menembak). Klik tombol lalu tekan yang baru.",
  teclas_padrao: "Tombol bawaan",
  semana: "Mingguan",
  conquistas: "Pencapaian",
  skins_corpo: "Bola",
  skins_acessorio: "Aksesori",
  dobrar_moedas: "Gandakan koin",
  resgatar: "Klaim",
  trocar: "Ganti",
  missoes_explica: "Selesaikan misi untuk koin. Bisa ganti 1 misi per hari.",
  semana_termina: "Berakhir dalam {0}h {1}j",
  premio_semana: "Hadiah mingguan: selesaikan 4 tantangan",
  equipado: "Dipakai",
  equipar: "Pakai",
  so_semanal: "Hadiah mingguan",
  acao_esquerda: "Kiri",
  acao_direita: "Kanan",
  acao_pulo: "Lompat",
  acao_baixo: "Turun",
  acao_tiro: "Tembak",
  tecla_espaco: "Spasi",
  toque_mira: "BIDIK",
  dica_bot_v2: "{0} jalan · {1} lompat\nMouse: bidik dan tembak (atau {2})",
  dica_2p_v2: "Pemain 1: {0}\nPemain 2: {1}\nDi keyboard yang sama!",
  aviso_missao: "Misi selesai!",
  aviso_desafio: "Tantangan mingguan selesai!",
  aviso_conquista: "Pencapaian: {0}!",
  nivel_bot: "🤖 Bot level {0}",
  nivel_curto: "Lv. {0}",
  bot_subiu: "Bot naik ke level {0}!",
  bot_desceu: "Bot turun ke level {0}",
  nivel_jogador: "Level {0}",
  subiu_nivel: "Naik ke level {0}!",
  abrir_bau: "Buka peti",
  abrir_bau_nivel: "Buka peti level!",
  outro_bau: "Buka peti lagi",
  revanche: "TANDING ULANG",
  premio_skin: "Skin baru: {0}!",
  diaria: "Hadiah harian",
  diaria_explica: "Kembali tiap hari: hadiahnya bertambah! Bolos sehari, mulai dari awal.",
  dia_n: "Hari {0}",
  bau: "peti",
  bau_lendario: "peti legendaris",
  pegar: "Ambil",
  fechar: "Tutup",
  sobrevivencia: "Bertahan Hidup",
  sobrevivencia_dica: "Gelombang bot yang makin kuat.\nSeberapa jauh kamu bisa?",
  onda_n: "GELOMBANG {0}",
  onda_concluida: "GELOMBANG {0} LEWAT!",
  fim_sobrevivencia: "Kamu mencapai gelombang {0}!",
  recorde_onda: "Rekor: gelombang {0}",
  novo_recorde: "REKOR BARU!",
  continuar_vida: "Tonton iklan dan lanjutkan gelombang yang sama dengan nyawa penuh.",
  dica_bot_v3: "{0} jalan · {1} lompat\nMouse: bidik · Klik atau {2}: tembak",
  dica_2p_v3: "Pemain 1: {0} + mouse\nPemain 2: {1}\nDi keyboard yang sama!",
  queda_clique: "KLIK ATAU {0}!",
  queda_aperte: "TEKAN {0}!",
  toque_pulo: "LOMPAT",
  estilo_agressivo: "Agresif",
  estilo_atirador: "Penembak",
  estilo_saltitante: "Pelompat",
  estilo_cauteloso: "Hati-hati",
  estilo_colecionador: "Kolektor",
  c_campo: "Padang",
  r_campo: "Klasik: bertarung saja!",
  c_gelo: "Gletser",
  r_gelo: "Es: semua licin!",
  c_lua: "Bulan",
  r_lua: "Gravitasi rendah: lompatan raksasa",
  c_vulcao: "Gunung Api",
  r_vulcao: "Lava naik turun: tetap di atas!",
  c_espaco: "Luar Angkasa",
  r_espaco: "Hampir tanpa gravitasi: lompat untuk terbang",
  c_laboratorio: "Laboratorium",
  r_laboratorio: "Gravitasi terbalik!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: dorong lawan keluar!",
  c_cidade: "Kota Neon",
  r_cidade: "Awas celah antar gedung!",
  c_fliperama: "Pinball",
  r_fliperama: "Bumper melemparmu jauh!",
  c_floresta: "Hutan Malam",
  r_floresta: "Gelap: hanya terlihat dekat cahaya",
  c_deserto: "Gurun",
  r_deserto: "Angin kencang berganti arah!",
  c_fabrica: "Pabrik",
  r_fabrica: "Ban berjalan membawamu!",
  c_oceano: "Dasar Laut",
  r_oceano: "Bawah air: lompat untuk berenang",
  c_templo: "Kuil",
  r_templo: "Keluar di satu sisi, masuk di sisi lain. Portal!",
  c_castelo: "Kastil",
  r_castelo: "Hujan meteor: hindari target!",
  k_escudo: "Perisai",
  kd_escudo: "Menahan 40 damage",
  k_rapidez: "Kecepatan",
  kd_rapidez: "Lebih cepat 7 dtk",
  k_cura: "Penyembuhan",
  kd_cura: "+35 nyawa",
  k_furia: "Amarah",
  kd_furia: "Damage ganda 6 dtk",
  k_tiro_duplo: "Tembakan Ganda",
  kd_tiro_duplo: "Setiap tembakan jadi dua",
  k_mini: "Mini",
  kd_mini: "Kecil dan sulit dikenai",
  k_congelar: "Bekukan",
  kd_congelar: "Membekukan lawan",
  k_fantasma: "Hantu",
  kd_fantasma: "Hampir tak terlihat 5 dtk",
  k_reflexo: "Pantul",
  kd_reflexo: "Memantulkan tembakan 5 dtk",
  k_super_pulo: "Lompatan Super",
  kd_super_pulo: "Lompat tiga kali, lebih tinggi",
  k_chuva: "Hujan Meteor",
  kd_chuva: "5 meteor ke lawan",
  k_municao: "Amunisi Tak Terbatas",
  kd_municao: "Tanpa habis amunisi 8 dtk",
  a_estilingue: "Ketapel",
  a_pistola: "Pistol",
  a_revolver: "Revolver",
  a_submetralhadora: "SMG",
  a_minigun: "Minigun",
  a_escopeta: "Shotgun",
  a_escopeta_dupla: "Shotgun Ganda",
  a_rifle: "Senapan",
  a_sniper: "Sniper",
  a_plasma: "Plasma",
  a_pula_pula: "Bola Pantul",
  a_confete: "Meriam Konfeti",
  a_arma_agua: "Pistol Air",
  a_zarabatana: "Sumpit",
  a_onda_sonora: "Gelombang Suara",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Busur",
  a_arco_triplo: "Busur Tiga",
  a_besta: "Panah Silang",
  a_serra: "Gergaji Putar",
  a_bola_neve: "Bola Salju",
  a_gancho: "Pengait",
  a_bazuca: "Bazoka",
  a_lanca_granadas: "Pelontar Granat",
  a_granada: "Granat",
  a_dinamite: "Dinamit",
  a_fragmentacao: "Granat Pecahan",
  a_canhao: "Meriam",
  a_mini_misseis: "Roket Mini",
  a_missil: "Rudal Pelacak",
  a_abelhas: "Kawanan Lebah",
  a_bola_fogo: "Bola Api",
  a_granada_gelo: "Granat Es",
  a_mina: "Ranjau",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Pelangi",
  a_feixe: "Sinar Kontinu",
  a_tesla: "Tesla",
  a_raio_gelo: "Sinar Es",
  a_bolhas: "Pistol Gelembung",
  a_buraco_negro: "Lubang Hitam",
  a_lanca_chamas: "Pelontar Api",
  a_soprador: "Peniup Daun",
  a_martelo: "Palu",
  a_espada: "Pedang",
  a_luva_boxe: "Sarung Tinju",
  a_meteoro: "Meteor",
  a_relampago: "Petir",
  mi_vitorias: "Menangkan {0} pertandingan lawan bot",
  mi_rodadas: "Menangkan {0} ronde",
  mi_dano: "Berikan {0} damage",
  mi_quedas: "Menangkan {0} panco",
  mi_cartas: "Ambil {0} kartu",
  mi_caixas: "Ambil {0} peti senjata",
  mi_abatesExpl: "Menangkan {0} ronde dengan bahan peledak",
  mi_abatesMelee: "Menangkan {0} ronde jarak dekat",
  mi_perfeitas: "Menangkan {0} ronde tanpa terkena damage",
  mi_partidas: "Mainkan {0} pertandingan",
  mi_partidas2p: "Mainkan {0} pertandingan 2 pemain",
  mi_rodadaCenario: "Menangkan {0} ronde di: {1}",
  de_s_vitorias: "Menangkan {0} pertandingan lawan bot",
  de_s_rodadas: "Menangkan {0} ronde",
  de_s_dano: "Berikan {0} damage",
  de_s_quedas: "Menangkan {0} panco",
  de_s_cenarios: "Menangkan ronde di {0} arena berbeda",
  de_s_5x0: "Menangkan pertandingan 5 – 0",
  de_s_expl: "Menangkan {0} ronde dengan bahan peledak",
  de_s_cartas: "Ambil {0} kartu",
  de_s_perfeitas: "Menangkan {0} ronde tanpa terkena damage",
  de_s_virada: "Menang setelah tertinggal 3 poin",
  co_primeira_vitoria: "Kemenangan Pertama",
  cod_primeira_vitoria: "Menangkan {0} pertandingan lawan bot",
  co_vitorias_10: "Duelis",
  cod_vitorias_10: "Menangkan {0} pertandingan lawan bot",
  co_vitorias_25: "Veteran",
  cod_vitorias_25: "Menangkan {0} pertandingan lawan bot",
  co_vitorias_100: "Legenda",
  cod_vitorias_100: "Menangkan {0} pertandingan lawan bot",
  co_partidas_50: "Ketagihan",
  cod_partidas_50: "Mainkan {0} pertandingan",
  co_rodadas_50: "Pemenang Ronde",
  cod_rodadas_50: "Menangkan {0} ronde",
  co_rodadas_250: "Mesin",
  cod_rodadas_250: "Menangkan {0} ronde",
  co_dano_20000: "Penghancur",
  cod_dano_20000: "Berikan {0} damage",
  co_dano_100000: "Kiamat",
  cod_dano_100000: "Berikan {0} damage",
  co_quedas_5: "Lengan Kuat",
  cod_quedas_5: "Menangkan {0} panco",
  co_quedas_20: "Juara Panco",
  cod_quedas_20: "Menangkan {0} panco",
  co_explosivos_50: "Penghancur Bom",
  cod_explosivos_50: "Menangkan {0} ronde dengan bahan peledak",
  co_melee_20: "Petarung",
  cod_melee_20: "Menangkan {0} ronde jarak dekat",
  co_perfeitas_10: "Tak Tersentuh",
  cod_perfeitas_10: "Menangkan {0} ronde tanpa terkena damage",
  co_cenarios_todos: "Penjelajah",
  cod_cenarios_todos: "Menangkan ronde di {0} arena berbeda",
  co_armas_25: "Kolektor",
  cod_armas_25: "Ambil {0} senjata berbeda",
  co_armas_todas: "Gudang Senjata Lengkap",
  cod_armas_todas: "Ambil {0} senjata berbeda",
  co_cartas_todas: "Dek Lengkap",
  cod_cartas_todas: "Ambil semua {0} kartu",
  co_placar_5x0: "Bantai",
  cod_placar_5x0: "Menangkan pertandingan 5 – 0",
  co_virada: "Comeback Epik",
  cod_virada: "Menang setelah tertinggal 3 poin",
  co_bot_mestre: "Master Bot",
  cod_bot_mestre: "Kalahkan bot di level tertinggi",
  co_dois_jogadores_10: "Sahabat",
  cod_dois_jogadores_10: "Mainkan {0} pertandingan 2 pemain",
  co_missoes_10: "Tekun",
  cod_missoes_10: "Klaim {0} misi",
  co_missoes_50: "Pantang Lelah",
  cod_missoes_50: "Klaim {0} misi",
  co_semana_completa: "Minggu Sempurna",
  cod_semana_completa: "Selesaikan semua tantangan seminggu",
  co_onda_5: "Penyintas",
  cod_onda_5: "Capai gelombang {0} di Bertahan Hidup",
  co_onda_10: "Tak Terbendung",
  cod_onda_10: "Capai gelombang {0} di Bertahan Hidup",
  sk_classico: "Klasik",
  sk_listras: "Garis",
  sk_pintas: "Polkadot",
  sk_xadrez: "Kotak-kotak",
  sk_camuflado: "Kamuflase",
  sk_futebol: "Bola Sepak",
  sk_melancia: "Semangka",
  sk_robo: "Robot",
  sk_doce: "Permen",
  sk_cromado: "Krom",
  sk_gelo: "Kristal Es",
  sk_neon: "Neon",
  sk_lava: "Lava",
  sk_diamante: "Berlian",
  sk_galaxia: "Galaksi",
  sk_ouro: "Emas",
  sk_nenhum: "Tidak ada",
  sk_bone: "Topi",
  sk_oculos: "Kacamata Hitam",
  sk_orelhas_gato: "Telinga Kucing",
  sk_fone: "Headphone",
  sk_cartola: "Topi Tinggi",
  sk_chifres: "Tanduk",
  sk_tiara_flores: "Mahkota Bunga",
  sk_mascara_ninja: "Topeng Ninja",
  sk_viking: "Helm Viking",
  sk_cowboy: "Topi Koboi",
  sk_antena: "Antena Alien",
  sk_aureola: "Lingkaran Cahaya",
  sk_coroa: "Mahkota",
  novo: "BARU!",
  proximo_rival: "LAWAN BERIKUTNYA",
  premio_equipado: "{0} dipakai!",
  modo_rivais: "Rival",
  rivais_dica: "Kalahkan 10 lawan dan naik liga",
  rival_n: "LAWAN {0}/{1}",
  liga_0: "Perunggu",
  liga_1: "Perak",
  liga_2: "Emas",
  liga_3: "Berlian",
  liga_4: "Master",
  liga_n: "Liga {0}",
  rival_derrotado: "{0} dikalahkan!",
  proximo: "Berikutnya: {0}",
  revanche_contra: "Tanding ulang vs {0}",
  campeao_liga: "JUARA LIGA {0}!",
  rival_venceu: "{0} menang!",
  venca_ganhe: "Menang dan dapatkan: {0}",
  salvo: "SELAMAT!"
};
