"use strict";
TEXTOS.it = {
  titulo: "Crazy Balls Duel",
  jogar: "GIOCA",
  idioma: "Lingua",
  som_on: "Audio: sì",
  som_off: "Audio: no",
  voltar: "Indietro",
  pausado: "Pausa",
  continuar: "Riprendi",
  menu: "Menu",
  anuncio_falhou: "La pubblicità non è stata caricata. Riprova più tardi.",
  escolha_modo: "Come vuoi giocare?",
  contra_bot: "Contro il bot",
  dois_jogadores: "2 giocatori",
  dica_bot_teclado: "A D / ← → muoviti\nW / ↑ salta\nF / Spazio / L spara",
  dica_bot_toque: "Sinistra: trascina per muoverti\nDestra: sopra salta · sotto mira e spara",
  dica_2p_teclado: "Giocatore 1: A D W + F\nGiocatore 2: ← → ↑ + L\nSulla stessa tastiera!",
  dica_2p_toque: "In due sullo stesso telefono, in orizzontale: ognuno usa metà schermo",
  lendaria: "Partita Leggendaria",
  lendaria_anuncio: "Partita Leggendaria: solo armi rare (pubblicità)",
  lendaria_ativada: "Partita Leggendaria attiva! Scegli la modalità",
  continuar_anuncio: "▶ Continua",
  continuar_explica: "Guarda una pubblicità e la partita continua: il bot perde l'ultimo punto.",
  nao_obrigado: "No, grazie",
  voce: "TU",
  voce_curto: "TU",
  bot: "BOT",
  jogador_n: "GIOCATORE {0}",
  rodada_n: "Round {0}",
  dano_dobro: "DANNO DOPPIO!",
  lute: "COMBATTI!",
  empate: "PAREGGIO!",
  voce_venceu_rodada: "ROUND VINTO!",
  bot_venceu_rodada: "IL BOT VINCE IL ROUND",
  jogador_venceu_rodada: "ROUND AL GIOCATORE {0}!",
  voce_venceu: "HAI VINTO!",
  bot_venceu: "VINCE IL BOT",
  jogador_venceu: "VINCE IL GIOCATORE {0}!",
  queda: "BRACCIO DI FERRO!",
  queda_sub: "Tempo scaduto! Vince chi clicca più veloce",
  queda_dica_bot: "CLIC / SPAZIO!",
  queda_dica_toque: "TOCCA LO SCHERMO!",
  queda_dica_p1: "PREMI F!",
  queda_dica_p2: "PREMI L!",
  queda_dica_toque_esq: "TOCCA A SINISTRA!",
  queda_dica_toque_dir: "TOCCA A DESTRA!",
  toque_mover: "muovi",
  toque_tiro: "SPARA",
  pegou_arma: "{0}!",
  mesmo_aparelho: "Sullo stesso dispositivo · non online",
  qualidade_auto: "Grafica: automatica",
  qualidade_alta: "Grafica: alta",
  qualidade_leve: "Grafica: leggera",
  perfeito: "PERFETTO!",
  missoes: "Missioni",
  skins: "Skin",
  opcoes: "Opzioni",
  controles: "Comandi",
  controles_mouse: "Il giocatore 1 mira anche col MOUSE (clic spara). Clicca un tasto e premi quello nuovo.",
  teclas_padrao: "Tasti predefiniti",
  semana: "Settimana",
  conquistas: "Obiettivi",
  skins_corpo: "Pallina",
  skins_acessorio: "Accessorio",
  dobrar_moedas: "Raddoppia monete",
  resgatar: "Riscuoti",
  trocar: "Cambia",
  missoes_explica: "Completa missioni per guadagnare monete. Puoi cambiare 1 missione al giorno.",
  semana_termina: "Termina tra {0}g {1}h",
  premio_semana: "Premio settimanale: completa le 4 sfide",
  equipado: "Equipaggiato",
  equipar: "Equipaggia",
  so_semanal: "Premio settimanale",
  acao_esquerda: "Sinistra",
  acao_direita: "Destra",
  acao_pulo: "Salta",
  acao_baixo: "Giù",
  acao_tiro: "Spara",
  tecla_espaco: "Spazio",
  toque_mira: "MIRA",
  dica_bot_v2: "{0} muoviti · {1} salta\nMouse: mira e spara (o {2})",
  dica_2p_v2: "Giocatore 1: {0}\nGiocatore 2: {1}\nSulla stessa tastiera!",
  aviso_missao: "Missione completata!",
  aviso_desafio: "Sfida settimanale completata!",
  aviso_conquista: "Obiettivo: {0}!",
  nivel_bot: "🤖 Bot livello {0}",
  nivel_curto: "Liv. {0}",
  bot_subiu: "Il bot sale al livello {0}!",
  bot_desceu: "Il bot scende al livello {0}",
  nivel_jogador: "Livello {0}",
  subiu_nivel: "Livello {0} raggiunto!",
  abrir_bau: "Apri il forziere",
  abrir_bau_nivel: "Apri il forziere di livello!",
  outro_bau: "Apri un altro forziere",
  revanche: "RIVINCITA",
  premio_skin: "Nuova skin: {0}!",
  diaria: "Ricompensa giornaliera",
  diaria_explica: "Torna ogni giorno: la ricompensa cresce! Se salti un giorno, si ricomincia.",
  dia_n: "Giorno {0}",
  bau: "forziere",
  bau_lendario: "forziere leggendario",
  pegar: "Riscuoti",
  fechar: "Chiudi",
  sobrevivencia: "Sopravvivenza",
  sobrevivencia_dica: "Ondate di bot sempre più forti.\nFin dove arrivi?",
  onda_n: "ONDATA {0}",
  onda_concluida: "ONDATA {0} SUPERATA!",
  fim_sobrevivencia: "Sei arrivato all'ondata {0}!",
  recorde_onda: "Record: ondata {0}",
  novo_recorde: "NUOVO RECORD!",
  continuar_vida: "Guarda una pubblicità e continua nella stessa ondata con la vita piena.",
  dica_bot_v3: "{0} muoviti · {1} salta\nMouse: mira · Clic o {2}: spara",
  dica_2p_v3: "Giocatore 1: {0} + mouse\nGiocatore 2: {1}\nSulla stessa tastiera!",
  queda_clique: "CLIC O {0}!",
  queda_aperte: "PREMI {0}!",
  toque_pulo: "SALTA",
  estilo_agressivo: "Aggressivo",
  estilo_atirador: "Cecchino",
  estilo_saltitante: "Saltellante",
  estilo_cauteloso: "Cauto",
  estilo_colecionador: "Collezionista",
  c_campo: "Prato",
  r_campo: "Classico: combatti!",
  c_gelo: "Ghiacciaio",
  r_gelo: "Ghiaccio: tutto scivola!",
  c_lua: "Luna",
  r_lua: "Poca gravità: salti giganti",
  c_vulcao: "Vulcano",
  r_vulcao: "La lava sale e scende: stai in alto!",
  c_espaco: "Spazio",
  r_espaco: "Quasi senza gravità: salta per volare",
  c_laboratorio: "Laboratorio",
  r_laboratorio: "La gravità si capovolge!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: spingi fuori l'avversario!",
  c_cidade: "Città Neon",
  r_cidade: "Attento al vuoto tra i palazzi!",
  c_fliperama: "Flipper",
  r_fliperama: "I respingenti ti lanciano lontano!",
  c_floresta: "Foresta Notturna",
  r_floresta: "Al buio: si vede solo vicino alla luce",
  c_deserto: "Deserto",
  r_deserto: "Il vento forte cambia lato!",
  c_fabrica: "Fabbrica",
  r_fabrica: "I nastri ti trascinano!",
  c_oceano: "Fondale Marino",
  r_oceano: "Sott'acqua: salta per nuotare",
  c_templo: "Tempio",
  r_templo: "Esci da un lato, rientra dall'altro. Portali!",
  c_castelo: "Castello",
  r_castelo: "Pioggia di meteore: schiva i bersagli!",
  k_escudo: "Scudo",
  kd_escudo: "Blocca 40 danni",
  k_rapidez: "Velocità",
  kd_rapidez: "Più veloce per 7 s",
  k_cura: "Cura",
  kd_cura: "+35 vita",
  k_furia: "Furia",
  kd_furia: "Danno doppio per 6 s",
  k_tiro_duplo: "Doppio Colpo",
  kd_tiro_duplo: "Ogni colpo è doppio",
  k_mini: "Mini",
  kd_mini: "Piccolo e difficile da colpire",
  k_congelar: "Congela",
  kd_congelar: "Congela l'avversario",
  k_fantasma: "Fantasma",
  kd_fantasma: "Quasi invisibile per 5 s",
  k_reflexo: "Riflesso",
  kd_reflexo: "Rimanda i colpi per 5 s",
  k_super_pulo: "Super Salto",
  kd_super_pulo: "Triplo salto più alto",
  k_chuva: "Pioggia di Meteore",
  kd_chuva: "5 meteore sull'avversario",
  k_municao: "Munizioni Infinite",
  kd_municao: "Niente munizioni consumate per 8 s",
  a_estilingue: "Fionda",
  a_pistola: "Pistola",
  a_revolver: "Revolver",
  a_submetralhadora: "Mitraglietta",
  a_minigun: "Minigun",
  a_escopeta: "Fucile a pompa",
  a_escopeta_dupla: "Doppietta",
  a_rifle: "Fucile",
  a_sniper: "Cecchino",
  a_plasma: "Plasma",
  a_pula_pula: "Palla Rimbalzina",
  a_confete: "Cannone Coriandoli",
  a_arma_agua: "Pistola ad Acqua",
  a_zarabatana: "Cerbottana",
  a_onda_sonora: "Onda Sonica",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boomerang",
  a_arco: "Arco",
  a_arco_triplo: "Arco Triplo",
  a_besta: "Balestra",
  a_serra: "Sega Rotante",
  a_bola_neve: "Palla di Neve",
  a_gancho: "Rampino",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Lanciagranate",
  a_granada: "Granata",
  a_dinamite: "Dinamite",
  a_fragmentacao: "Granata a Frammentazione",
  a_canhao: "Cannone",
  a_mini_misseis: "Mini Missili",
  a_missil: "Missile a Ricerca",
  a_abelhas: "Sciame d'Api",
  a_bola_fogo: "Palla di Fuoco",
  a_granada_gelo: "Granata di Ghiaccio",
  a_mina: "Mina",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Arcobaleno",
  a_feixe: "Raggio Continuo",
  a_tesla: "Tesla",
  a_raio_gelo: "Raggio di Ghiaccio",
  a_bolhas: "Pistola a Bolle",
  a_buraco_negro: "Buco Nero",
  a_lanca_chamas: "Lanciafiamme",
  a_soprador: "Soffiatore",
  a_martelo: "Martello",
  a_espada: "Spada",
  a_luva_boxe: "Guantone",
  a_meteoro: "Meteore",
  a_relampago: "Fulmine",
  mi_vitorias: "Vinci {0} partita/e contro il bot",
  mi_rodadas: "Vinci {0} round",
  mi_dano: "Infliggi {0} danni",
  mi_quedas: "Vinci {0} braccio di ferro",
  mi_cartas: "Prendi {0} carte",
  mi_caixas: "Prendi {0} casse di armi",
  mi_abatesExpl: "Vinci {0} round con esplosivi",
  mi_abatesMelee: "Vinci {0} round corpo a corpo",
  mi_perfeitas: "Vinci {0} round senza subire danni",
  mi_partidas: "Gioca {0} partite",
  mi_partidas2p: "Gioca {0} partita/e a 2 giocatori",
  mi_rodadaCenario: "Vinci {0} round in: {1}",
  de_s_vitorias: "Vinci {0} partita/e contro il bot",
  de_s_rodadas: "Vinci {0} round",
  de_s_dano: "Infliggi {0} danni",
  de_s_quedas: "Vinci {0} braccio di ferro",
  de_s_cenarios: "Vinci round in {0} arene diverse",
  de_s_5x0: "Vinci una partita 5 – 0",
  de_s_expl: "Vinci {0} round con esplosivi",
  de_s_cartas: "Prendi {0} carte",
  de_s_perfeitas: "Vinci {0} round senza subire danni",
  de_s_virada: "Vinci in rimonta da 3 punti sotto",
  co_primeira_vitoria: "Prima Vittoria",
  cod_primeira_vitoria: "Vinci {0} partita/e contro il bot",
  co_vitorias_10: "Duellante",
  cod_vitorias_10: "Vinci {0} partita/e contro il bot",
  co_vitorias_25: "Veterano",
  cod_vitorias_25: "Vinci {0} partita/e contro il bot",
  co_vitorias_100: "Leggenda",
  cod_vitorias_100: "Vinci {0} partita/e contro il bot",
  co_partidas_50: "Dipendente",
  cod_partidas_50: "Gioca {0} partite",
  co_rodadas_50: "Vincitore di Round",
  cod_rodadas_50: "Vinci {0} round",
  co_rodadas_250: "Macchina",
  cod_rodadas_250: "Vinci {0} round",
  co_dano_20000: "Distruttore",
  cod_dano_20000: "Infliggi {0} danni",
  co_dano_100000: "Apocalisse",
  cod_dano_100000: "Infliggi {0} danni",
  co_quedas_5: "Braccio Forte",
  cod_quedas_5: "Vinci {0} braccio di ferro",
  co_quedas_20: "Campione di Braccio",
  cod_quedas_20: "Vinci {0} braccio di ferro",
  co_explosivos_50: "Demolitore",
  cod_explosivos_50: "Vinci {0} round con esplosivi",
  co_melee_20: "Picchiatore",
  cod_melee_20: "Vinci {0} round corpo a corpo",
  co_perfeitas_10: "Intoccabile",
  cod_perfeitas_10: "Vinci {0} round senza subire danni",
  co_cenarios_todos: "Esploratore",
  cod_cenarios_todos: "Vinci round in {0} arene diverse",
  co_armas_25: "Collezionista",
  cod_armas_25: "Prendi {0} armi diverse",
  co_armas_todas: "Arsenale Completo",
  cod_armas_todas: "Prendi {0} armi diverse",
  co_cartas_todas: "Mazzo Completo",
  cod_cartas_todas: "Prendi tutte le {0} carte",
  co_placar_5x0: "Cappotto",
  cod_placar_5x0: "Vinci una partita 5 – 0",
  co_virada: "Rimonta Epica",
  cod_virada: "Vinci in rimonta da 3 punti sotto",
  co_bot_mestre: "Maestro del Bot",
  cod_bot_mestre: "Batti il bot al livello massimo",
  co_dois_jogadores_10: "Migliori Amici",
  cod_dois_jogadores_10: "Gioca {0} partita/e a 2 giocatori",
  co_missoes_10: "Dedicato",
  cod_missoes_10: "Riscuoti {0} missioni",
  co_missoes_50: "Instancabile",
  cod_missoes_50: "Riscuoti {0} missioni",
  co_semana_completa: "Settimana Perfetta",
  cod_semana_completa: "Completa tutte le sfide di una settimana",
  co_onda_5: "Sopravvissuto",
  cod_onda_5: "Raggiungi l'ondata {0} in Sopravvivenza",
  co_onda_10: "Inarrestabile",
  cod_onda_10: "Raggiungi l'ondata {0} in Sopravvivenza",
  sk_classico: "Classica",
  sk_listras: "Strisce",
  sk_pintas: "Pois",
  sk_xadrez: "Scacchi",
  sk_camuflado: "Mimetica",
  sk_futebol: "Pallone",
  sk_melancia: "Anguria",
  sk_robo: "Robot",
  sk_doce: "Caramella",
  sk_cromado: "Cromata",
  sk_gelo: "Cristallo di Ghiaccio",
  sk_neon: "Neon",
  sk_lava: "Lava",
  sk_diamante: "Diamante",
  sk_galaxia: "Galassia",
  sk_ouro: "Oro",
  sk_nenhum: "Nessuno",
  sk_bone: "Cappellino",
  sk_oculos: "Occhiali da Sole",
  sk_orelhas_gato: "Orecchie da Gatto",
  sk_fone: "Cuffie",
  sk_cartola: "Cilindro",
  sk_chifres: "Corna",
  sk_tiara_flores: "Corona di Fiori",
  sk_mascara_ninja: "Maschera Ninja",
  sk_viking: "Elmo Vichingo",
  sk_cowboy: "Cappello da Cowboy",
  sk_antena: "Antenna Aliena",
  sk_aureola: "Aureola",
  sk_coroa: "Corona",
  novo: "NUOVO!",
  proximo_rival: "PROSSIMO RIVALE",
  premio_equipado: "{0} equipaggiato!",
  modo_rivais: "Rivali",
  rivais_dica: "Batti 10 rivali e sali di lega",
  rival_n: "RIVALE {0}/{1}",
  liga_0: "Bronzo",
  liga_1: "Argento",
  liga_2: "Oro",
  liga_3: "Diamante",
  liga_4: "Maestro",
  liga_n: "Lega {0}",
  rival_derrotado: "{0} sconfitto!",
  proximo: "Prossimo: {0}",
  revanche_contra: "Rivincita contro {0}",
  campeao_liga: "CAMPIONE DELLA LEGA {0}!",
  rival_venceu: "{0} vince!",
  venca_ganhe: "Vinci e ottieni: {0}",
  salvo: "SALVO!",
  melhorar: "Potenzia",
  poder_explica: "Diventa più forte contro il bot e i rivali. In modalità 2 giocatori siete uguali.",
  poder_n: "⚡ POTENZA {0}",
  poder_dica: "Potenziati e torna più forte!",
  poder_gaste: "Usa le tue monete: diventa più forte!",
  mel_forca: "Forza",
  mel_vida: "Vita",
  mel_veloc: "Velocità",
  mel_nivel: "Liv {0}",
  mel_max: "MAX"
};
