"use strict";
TEXTOS.it = {
  titulo: "Duello di Palline",
  jogar: "GIOCA",
  idioma: "Lingua",
  som_on: "Audio: sì",
  som_off: "Audio: no",
  voltar: "Indietro",
  pausado: "Pausa",
  continuar: "Riprendi",
  menu: "Menu",
  anuncio_falhou: "La pubblicità non è stata caricata. Riprova più tardi.",
  escolha_modo: "Come vuoi giocare?",
  contra_bot: "Contro il bot",
  dois_jogadores: "2 giocatori",
  dica_bot_teclado: "A D / ← → muoviti\nW / ↑ salta\nF / Spazio / L spara",
  dica_bot_toque: "Sinistra: trascina per muoverti e saltare\nDestra: tieni premuto per sparare",
  dica_2p_teclado: "Giocatore 1: A D W + F\nGiocatore 2: ← → ↑ + L\nSulla stessa tastiera!",
  dica_2p_toque: "Ognuno usa la sua metà dello schermo",
  lendaria: "Partita Leggendaria",
  lendaria_anuncio: "Partita Leggendaria: solo armi rare (pubblicità)",
  lendaria_ativada: "Partita Leggendaria attiva! Scegli la modalità",
  continuar_anuncio: "▶ Continua",
  continuar_explica: "Guarda una pubblicità e la partita continua: il bot perde l'ultimo punto.",
  nao_obrigado: "No, grazie",
  voce: "TU",
  voce_curto: "TU",
  bot: "BOT",
  jogador_n: "GIOCATORE {0}",
  rodada_n: "Round {0}",
  dano_dobro: "DANNO DOPPIO!",
  lute: "COMBATTI!",
  empate: "PAREGGIO!",
  voce_venceu_rodada: "ROUND VINTO!",
  bot_venceu_rodada: "IL BOT VINCE IL ROUND",
  jogador_venceu_rodada: "ROUND AL GIOCATORE {0}!",
  voce_venceu: "HAI VINTO!",
  bot_venceu: "VINCE IL BOT",
  jogador_venceu: "VINCE IL GIOCATORE {0}!",
  queda: "BRACCIO DI FERRO!",
  queda_sub: "Tempo scaduto! Vince chi clicca più veloce",
  queda_dica_bot: "CLIC / SPAZIO!",
  queda_dica_toque: "TOCCA LO SCHERMO!",
  queda_dica_p1: "PREMI F!",
  queda_dica_p2: "PREMI L!",
  queda_dica_toque_esq: "TOCCA A SINISTRA!",
  queda_dica_toque_dir: "TOCCA A DESTRA!",
  toque_mover: "muovi",
  toque_tiro: "SPARA",
  pegou_arma: "{0}!",
  c_campo: "Prato",
  r_campo: "Classico: combatti!",
  c_gelo: "Ghiacciaio",
  r_gelo: "Ghiaccio: tutto scivola!",
  c_lua: "Luna",
  r_lua: "Poca gravità: salti giganti",
  c_vulcao: "Vulcano",
  r_vulcao: "La lava sale e scende: stai in alto!",
  c_espaco: "Spazio",
  r_espaco: "Quasi senza gravità: salta per volare",
  c_laboratorio: "Laboratorio",
  r_laboratorio: "La gravità si capovolge!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: spingi fuori l'avversario!",
  c_cidade: "Città Neon",
  r_cidade: "Attento al vuoto tra i palazzi!",
  c_fliperama: "Flipper",
  r_fliperama: "I respingenti ti lanciano lontano!",
  c_floresta: "Foresta Notturna",
  r_floresta: "Al buio: si vede solo vicino alla luce",
  c_deserto: "Deserto",
  r_deserto: "Il vento forte cambia lato!",
  c_fabrica: "Fabbrica",
  r_fabrica: "I nastri ti trascinano!",
  c_oceano: "Fondale Marino",
  r_oceano: "Sott'acqua: salta per nuotare",
  c_templo: "Tempio",
  r_templo: "Esci da un lato, rientra dall'altro. Portali!",
  c_castelo: "Castello",
  r_castelo: "Pioggia di meteore: schiva i bersagli!",
  k_escudo: "Scudo",
  kd_escudo: "Blocca 40 danni",
  k_rapidez: "Velocità",
  kd_rapidez: "Più veloce per 7 s",
  k_cura: "Cura",
  kd_cura: "+35 vita",
  k_furia: "Furia",
  kd_furia: "Danno doppio per 6 s",
  k_tiro_duplo: "Doppio Colpo",
  kd_tiro_duplo: "Ogni colpo è doppio",
  k_mini: "Mini",
  kd_mini: "Piccolo e difficile da colpire",
  k_congelar: "Congela",
  kd_congelar: "Congela l'avversario",
  k_fantasma: "Fantasma",
  kd_fantasma: "Quasi invisibile per 5 s",
  k_reflexo: "Riflesso",
  kd_reflexo: "Rimanda i colpi per 5 s",
  k_super_pulo: "Super Salto",
  kd_super_pulo: "Triplo salto più alto",
  k_chuva: "Pioggia di Meteore",
  kd_chuva: "5 meteore sull'avversario",
  k_municao: "Munizioni Infinite",
  kd_municao: "Niente munizioni consumate per 8 s",
  a_estilingue: "Fionda",
  a_pistola: "Pistola",
  a_revolver: "Revolver",
  a_submetralhadora: "Mitraglietta",
  a_minigun: "Minigun",
  a_escopeta: "Fucile a pompa",
  a_escopeta_dupla: "Doppietta",
  a_rifle: "Fucile",
  a_sniper: "Cecchino",
  a_plasma: "Plasma",
  a_pula_pula: "Palla Rimbalzina",
  a_confete: "Cannone Coriandoli",
  a_arma_agua: "Pistola ad Acqua",
  a_zarabatana: "Cerbottana",
  a_onda_sonora: "Onda Sonica",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boomerang",
  a_arco: "Arco",
  a_arco_triplo: "Arco Triplo",
  a_besta: "Balestra",
  a_serra: "Sega Rotante",
  a_bola_neve: "Palla di Neve",
  a_gancho: "Rampino",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Lanciagranate",
  a_granada: "Granata",
  a_dinamite: "Dinamite",
  a_fragmentacao: "Granata a Frammentazione",
  a_canhao: "Cannone",
  a_mini_misseis: "Mini Missili",
  a_missil: "Missile a Ricerca",
  a_abelhas: "Sciame d'Api",
  a_bola_fogo: "Palla di Fuoco",
  a_granada_gelo: "Granata di Ghiaccio",
  a_mina: "Mina",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Arcobaleno",
  a_feixe: "Raggio Continuo",
  a_tesla: "Tesla",
  a_raio_gelo: "Raggio di Ghiaccio",
  a_bolhas: "Pistola a Bolle",
  a_buraco_negro: "Buco Nero",
  a_lanca_chamas: "Lanciafiamme",
  a_soprador: "Soffiatore",
  a_martelo: "Martello",
  a_espada: "Spada",
  a_luva_boxe: "Guantone",
  a_meteoro: "Meteore",
  a_relampago: "Fulmine"
};
