"use strict";
TEXTOS.nl = {
  titulo: "Crazy Balls Duel",
  jogar: "SPELEN",
  idioma: "Taal",
  som_on: "Geluid: aan",
  som_off: "Geluid: uit",
  voltar: "Terug",
  pausado: "Pauze",
  continuar: "Verder",
  menu: "Menu",
  anuncio_falhou: "De advertentie laadde niet. Probeer het later.",
  escolha_modo: "Hoe wil je spelen?",
  contra_bot: "Tegen bot",
  dois_jogadores: "2 spelers",
  dica_bot_teclado: "A D / ← → lopen\nW / ↑ springen\nF / Spatie / L schieten",
  dica_bot_toque: "Links: sleep om te lopen\nRechts: boven springen · onder richten en schieten",
  dica_2p_teclado: "Speler 1: A D W + F\nSpeler 2: ← → ↑ + L\nOp hetzelfde toetsenbord!",
  dica_2p_toque: "Met z'n tweeën op één telefoon, liggend: ieder gebruikt een helft van het scherm",
  lendaria: "Legendarische Match",
  lendaria_anuncio: "Legendarische Match: alleen zeldzame wapens (advertentie)",
  lendaria_ativada: "Legendarische Match aan! Kies een modus",
  continuar_anuncio: "▶ Doorgaan",
  continuar_explica: "Bekijk een advertentie en de match gaat door: de bot verliest zijn laatste punt.",
  nao_obrigado: "Nee, bedankt",
  voce: "JIJ",
  voce_curto: "JIJ",
  bot: "BOT",
  jogador_n: "SPELER {0}",
  rodada_n: "Ronde {0}",
  dano_dobro: "DUBBELE SCHADE!",
  lute: "VECHT!",
  empate: "GELIJKSPEL!",
  voce_venceu_rodada: "RONDE GEWONNEN!",
  bot_venceu_rodada: "DE BOT WINT DE RONDE",
  jogador_venceu_rodada: "RONDE VOOR SPELER {0}!",
  voce_venceu: "JIJ WINT!",
  bot_venceu: "DE BOT WINT",
  jogador_venceu: "SPELER {0} WINT!",
  queda: "ARMWORSTELEN!",
  queda_sub: "Tijd is op! Wie het snelst klikt, wint",
  queda_dica_bot: "KLIK / SPATIE!",
  queda_dica_toque: "TIK OP HET SCHERM!",
  queda_dica_p1: "DRUK OP F!",
  queda_dica_p2: "DRUK OP L!",
  queda_dica_toque_esq: "TIK LINKS!",
  queda_dica_toque_dir: "TIK RECHTS!",
  toque_mover: "lopen",
  toque_tiro: "SCHIET",
  pegou_arma: "{0}!",
  mesmo_aparelho: "Op hetzelfde apparaat · niet online",
  qualidade_auto: "Graphics: automatisch",
  qualidade_alta: "Graphics: hoog",
  qualidade_leve: "Graphics: licht",
  perfeito: "PERFECT!",
  missoes: "Missies",
  skins: "Skins",
  opcoes: "Opties",
  controles: "Besturing",
  controles_mouse: "Speler 1 richt ook met de MUIS (klik schiet). Klik een toets en druk de nieuwe in.",
  teclas_padrao: "Standaardtoetsen",
  semana: "Week",
  conquistas: "Prestaties",
  skins_corpo: "Bal",
  skins_acessorio: "Accessoire",
  dobrar_moedas: "Munten verdubbelen",
  resgatar: "Ophalen",
  trocar: "Wissel",
  missoes_explica: "Voltooi missies voor munten. Je kunt 1 missie per dag wisselen.",
  semana_termina: "Eindigt over {0}d {1}u",
  premio_semana: "Weekprijs: voltooi alle 4 uitdagingen",
  equipado: "Uitgerust",
  equipar: "Uitrusten",
  so_semanal: "Weekprijs",
  acao_esquerda: "Links",
  acao_direita: "Rechts",
  acao_pulo: "Springen",
  acao_baixo: "Omlaag",
  acao_tiro: "Schieten",
  tecla_espaco: "Spatie",
  toque_mira: "RICHTEN",
  dica_bot_v2: "{0} lopen · {1} springen\nMuis: richten en schieten (of {2})",
  dica_2p_v2: "Speler 1: {0}\nSpeler 2: {1}\nOp hetzelfde toetsenbord!",
  aviso_missao: "Missie voltooid!",
  aviso_desafio: "Weekuitdaging voltooid!",
  aviso_conquista: "Prestatie: {0}!",
  nivel_bot: "🤖 Bot niveau {0}",
  nivel_curto: "Nv. {0}",
  bot_subiu: "Bot stijgt naar niveau {0}!",
  bot_desceu: "Bot daalt naar niveau {0}",
  nivel_jogador: "Level {0}",
  subiu_nivel: "Level {0} bereikt!",
  abrir_bau: "Kist openen",
  abrir_bau_nivel: "Levelkist openen!",
  outro_bau: "Nog een kist openen",
  revanche: "REVANCHE",
  premio_skin: "Nieuwe skin: {0}!",
  diaria: "Dagelijkse beloning",
  diaria_explica: "Kom elke dag terug: de beloning groeit! Een dag gemist en het begint opnieuw.",
  dia_n: "Dag {0}",
  bau: "kist",
  bau_lendario: "legendarische kist",
  pegar: "Ophalen",
  fechar: "Sluiten",
  sobrevivencia: "Overleven",
  sobrevivencia_dica: "Golven van steeds sterkere bots.\nHoe ver kom jij?",
  onda_n: "GOLF {0}",
  onda_concluida: "GOLF {0} GEHAALD!",
  fim_sobrevivencia: "Je bereikte golf {0}!",
  recorde_onda: "Record: golf {0}",
  novo_recorde: "NIEUW RECORD!",
  continuar_vida: "Bekijk een advertentie en ga verder in dezelfde golf met volle gezondheid.",
  dica_bot_v3: "{0} lopen · {1} springen\nMuis: richten · Klik of {2}: schieten",
  dica_2p_v3: "Speler 1: {0} + muis\nSpeler 2: {1}\nOp hetzelfde toetsenbord!",
  queda_clique: "KLIK OF {0}!",
  queda_aperte: "DRUK OP {0}!",
  toque_pulo: "SPRING",
  estilo_agressivo: "Agressief",
  estilo_atirador: "Scherpschutter",
  estilo_saltitante: "Springer",
  estilo_cauteloso: "Voorzichtig",
  estilo_colecionador: "Verzamelaar",
  c_campo: "Weide",
  r_campo: "Klassiek: gewoon vechten!",
  c_gelo: "Gletsjer",
  r_gelo: "IJs: alles glijdt!",
  c_lua: "Maan",
  r_lua: "Lage zwaartekracht: reuzensprongen",
  c_vulcao: "Vulkaan",
  r_vulcao: "Lava stijgt en daalt: blijf hoog!",
  c_espaco: "Ruimte",
  r_espaco: "Bijna gewichtloos: spring om te vliegen",
  c_laboratorio: "Lab",
  r_laboratorio: "De zwaartekracht draait om!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: duw de tegenstander eraf!",
  c_cidade: "Neonstad",
  r_cidade: "Let op het gat tussen de gebouwen!",
  c_fliperama: "Flipperkast",
  r_fliperama: "Bumpers schieten je weg!",
  c_floresta: "Nachtbos",
  r_floresta: "In het donker: alleen zicht bij licht",
  c_deserto: "Woestijn",
  r_deserto: "Harde wind wisselt van kant!",
  c_fabrica: "Fabriek",
  r_fabrica: "Lopende banden nemen je mee!",
  c_oceano: "Diepzee",
  r_oceano: "Onder water: spring om te zwemmen",
  c_templo: "Tempel",
  r_templo: "Eruit aan de ene kant, erin aan de andere. Portalen!",
  c_castelo: "Kasteel",
  r_castelo: "Meteorenregen: ontwijk de doelen!",
  k_escudo: "Schild",
  kd_escudo: "Blokkeert 40 schade",
  k_rapidez: "Snelheid",
  kd_rapidez: "7 s sneller",
  k_cura: "Genezing",
  kd_cura: "+35 leven",
  k_furia: "Woede",
  kd_furia: "Dubbele schade 6 s",
  k_tiro_duplo: "Dubbel Schot",
  kd_tiro_duplo: "Elk schot dubbel",
  k_mini: "Mini",
  kd_mini: "Klein en moeilijk te raken",
  k_congelar: "Bevriezen",
  kd_congelar: "Bevriest de tegenstander",
  k_fantasma: "Geest",
  kd_fantasma: "Bijna onzichtbaar 5 s",
  k_reflexo: "Reflectie",
  kd_reflexo: "Kaatst schoten terug 5 s",
  k_super_pulo: "Supersprong",
  kd_super_pulo: "Drievoudige, hogere sprong",
  k_chuva: "Meteorenregen",
  kd_chuva: "5 meteoren op de tegenstander",
  k_municao: "Oneindige Munitie",
  kd_municao: "8 s geen munitie verbruikt",
  a_estilingue: "Katapult",
  a_pistola: "Pistool",
  a_revolver: "Revolver",
  a_submetralhadora: "Machinepistool",
  a_minigun: "Minigun",
  a_escopeta: "Jachtgeweer",
  a_escopeta_dupla: "Dubbelloops",
  a_rifle: "Geweer",
  a_sniper: "Sluipschuttersgeweer",
  a_plasma: "Plasmageweer",
  a_pula_pula: "Stuiterbal",
  a_confete: "Confettikanon",
  a_arma_agua: "Waterpistool",
  a_zarabatana: "Blaaspijp",
  a_onda_sonora: "Geluidsgolf",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boemerang",
  a_arco: "Boog",
  a_arco_triplo: "Drievoudige Boog",
  a_besta: "Kruisboog",
  a_serra: "Zaagblad",
  a_bola_neve: "Sneeuwbal",
  a_gancho: "Grijphaak",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Granaatwerper",
  a_granada: "Granaat",
  a_dinamite: "Dynamiet",
  a_fragmentacao: "Splintergranaat",
  a_canhao: "Kanon",
  a_mini_misseis: "Mini-raketten",
  a_missil: "Geleide Raket",
  a_abelhas: "Bijenzwerm",
  a_bola_fogo: "Vuurbal",
  a_granada_gelo: "IJsgranaat",
  a_mina: "Mijn",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Regenbooglaser",
  a_feixe: "Straalkanon",
  a_tesla: "Teslageweer",
  a_raio_gelo: "IJsstraal",
  a_bolhas: "Bellenblaas",
  a_buraco_negro: "Zwart Gat",
  a_lanca_chamas: "Vlammenwerper",
  a_soprador: "Bladblazer",
  a_martelo: "Hamer",
  a_espada: "Zwaard",
  a_luva_boxe: "Bokshandschoen",
  a_meteoro: "Meteoren",
  a_relampago: "Bliksem",
  mi_vitorias: "Win {0} match(es) tegen de bot",
  mi_rodadas: "Win {0} rondes",
  mi_dano: "Doe {0} schade",
  mi_quedas: "Win {0}× armworstelen",
  mi_cartas: "Pak {0} kaarten",
  mi_caixas: "Pak {0} wapenkratten",
  mi_abatesExpl: "Win {0} ronde(s) met explosieven",
  mi_abatesMelee: "Win {0} ronde(s) in man-tegen-man",
  mi_perfeitas: "Win {0} ronde(s) zonder schade",
  mi_partidas: "Speel {0} matches",
  mi_partidas2p: "Speel {0} 2-spelermatch(es)",
  mi_rodadaCenario: "Win {0} ronde(s) in: {1}",
  de_s_vitorias: "Win {0} match(es) tegen de bot",
  de_s_rodadas: "Win {0} rondes",
  de_s_dano: "Doe {0} schade",
  de_s_quedas: "Win {0}× armworstelen",
  de_s_cenarios: "Win rondes in {0} verschillende arena's",
  de_s_5x0: "Win een match met 5 – 0",
  de_s_expl: "Win {0} ronde(s) met explosieven",
  de_s_cartas: "Pak {0} kaarten",
  de_s_perfeitas: "Win {0} ronde(s) zonder schade",
  de_s_virada: "Win na 3 punten achterstand",
  co_primeira_vitoria: "Eerste Zege",
  cod_primeira_vitoria: "Win {0} match(es) tegen de bot",
  co_vitorias_10: "Duellist",
  cod_vitorias_10: "Win {0} match(es) tegen de bot",
  co_vitorias_25: "Veteraan",
  cod_vitorias_25: "Win {0} match(es) tegen de bot",
  co_vitorias_100: "Legende",
  cod_vitorias_100: "Win {0} match(es) tegen de bot",
  co_partidas_50: "Verslaafd",
  cod_partidas_50: "Speel {0} matches",
  co_rodadas_50: "Rondewinnaar",
  cod_rodadas_50: "Win {0} rondes",
  co_rodadas_250: "Machine",
  cod_rodadas_250: "Win {0} rondes",
  co_dano_20000: "Vernietiger",
  cod_dano_20000: "Doe {0} schade",
  co_dano_100000: "Apocalyps",
  cod_dano_100000: "Doe {0} schade",
  co_quedas_5: "Sterke Arm",
  cod_quedas_5: "Win {0}× armworstelen",
  co_quedas_20: "Armworstelkampioen",
  cod_quedas_20: "Win {0}× armworstelen",
  co_explosivos_50: "Sloper",
  cod_explosivos_50: "Win {0} ronde(s) met explosieven",
  co_melee_20: "Vechter",
  cod_melee_20: "Win {0} ronde(s) in man-tegen-man",
  co_perfeitas_10: "Onaantastbaar",
  cod_perfeitas_10: "Win {0} ronde(s) zonder schade",
  co_cenarios_todos: "Ontdekker",
  cod_cenarios_todos: "Win rondes in {0} verschillende arena's",
  co_armas_25: "Verzamelaar",
  cod_armas_25: "Pak {0} verschillende wapens",
  co_armas_todas: "Volledig Arsenaal",
  cod_armas_todas: "Pak {0} verschillende wapens",
  co_cartas_todas: "Volledig Spel",
  cod_cartas_todas: "Pak alle {0} kaarten",
  co_placar_5x0: "Wals",
  cod_placar_5x0: "Win een match met 5 – 0",
  co_virada: "Epische Comeback",
  cod_virada: "Win na 3 punten achterstand",
  co_bot_mestre: "Botmeester",
  cod_bot_mestre: "Versla de bot op het hoogste niveau",
  co_dois_jogadores_10: "Beste Vrienden",
  cod_dois_jogadores_10: "Speel {0} 2-spelermatch(es)",
  co_missoes_10: "Toegewijd",
  cod_missoes_10: "Haal {0} missies op",
  co_missoes_50: "Onvermoeibaar",
  cod_missoes_50: "Haal {0} missies op",
  co_semana_completa: "Perfecte Week",
  cod_semana_completa: "Voltooi alle uitdagingen van een week",
  co_onda_5: "Overlever",
  cod_onda_5: "Bereik golf {0} in Overleven",
  co_onda_10: "Onstuitbaar",
  cod_onda_10: "Bereik golf {0} in Overleven",
  sk_classico: "Klassiek",
  sk_listras: "Strepen",
  sk_pintas: "Stippen",
  sk_xadrez: "Ruit",
  sk_camuflado: "Camouflage",
  sk_futebol: "Voetbal",
  sk_melancia: "Watermeloen",
  sk_robo: "Robot",
  sk_doce: "Snoep",
  sk_cromado: "Chroom",
  sk_gelo: "IJskristal",
  sk_neon: "Neon",
  sk_lava: "Lava",
  sk_diamante: "Diamant",
  sk_galaxia: "Melkweg",
  sk_ouro: "Goud",
  sk_nenhum: "Geen",
  sk_bone: "Pet",
  sk_oculos: "Zonnebril",
  sk_orelhas_gato: "Kattenoren",
  sk_fone: "Koptelefoon",
  sk_cartola: "Hoge Hoed",
  sk_chifres: "Hoorns",
  sk_tiara_flores: "Bloemenkroon",
  sk_mascara_ninja: "Ninjamasker",
  sk_viking: "Vikinghelm",
  sk_cowboy: "Cowboyhoed",
  sk_antena: "Alien-antenne",
  sk_aureola: "Halo",
  sk_coroa: "Kroon",
  novo: "NIEUW!",
  proximo_rival: "VOLGENDE RIVAAL",
  premio_equipado: "{0} uitgerust!",
  modo_rivais: "Rivalen",
  rivais_dica: "Versla 10 rivalen en stijg op",
  rival_n: "RIVAAL {0}/{1}",
  liga_0: "Brons",
  liga_1: "Zilver",
  liga_2: "Goud",
  liga_3: "Diamant",
  liga_4: "Meester",
  liga_n: "{0}-divisie",
  rival_derrotado: "{0} verslagen!",
  proximo: "Volgende: {0}",
  revanche_contra: "Revanche tegen {0}",
  campeao_liga: "KAMPIOEN VAN DE {0}-DIVISIE!",
  rival_venceu: "{0} wint!"
};
