"use strict";
TEXTOS.nl = {
  titulo: "Ballen Duel",
  jogar: "SPELEN",
  idioma: "Taal",
  som_on: "Geluid: aan",
  som_off: "Geluid: uit",
  voltar: "Terug",
  pausado: "Pauze",
  continuar: "Verder",
  menu: "Menu",
  anuncio_falhou: "De advertentie laadde niet. Probeer het later.",
  escolha_modo: "Hoe wil je spelen?",
  contra_bot: "Tegen bot",
  dois_jogadores: "2 spelers",
  dica_bot_teclado: "A D / ← → lopen\nW / ↑ springen\nF / Spatie / L schieten",
  dica_bot_toque: "Links: sleep om te lopen en springen\nRechts: vasthouden om te schieten",
  dica_2p_teclado: "Speler 1: A D W + F\nSpeler 2: ← → ↑ + L\nOp hetzelfde toetsenbord!",
  dica_2p_toque: "Iedereen gebruikt zijn helft van het scherm",
  lendaria: "Legendarische Match",
  lendaria_anuncio: "Legendarische Match: alleen zeldzame wapens (advertentie)",
  lendaria_ativada: "Legendarische Match aan! Kies een modus",
  continuar_anuncio: "▶ Doorgaan",
  continuar_explica: "Bekijk een advertentie en de match gaat door: de bot verliest zijn laatste punt.",
  nao_obrigado: "Nee, bedankt",
  voce: "JIJ",
  voce_curto: "JIJ",
  bot: "BOT",
  jogador_n: "SPELER {0}",
  rodada_n: "Ronde {0}",
  dano_dobro: "DUBBELE SCHADE!",
  lute: "VECHT!",
  empate: "GELIJKSPEL!",
  voce_venceu_rodada: "RONDE GEWONNEN!",
  bot_venceu_rodada: "DE BOT WINT DE RONDE",
  jogador_venceu_rodada: "RONDE VOOR SPELER {0}!",
  voce_venceu: "JIJ WINT!",
  bot_venceu: "DE BOT WINT",
  jogador_venceu: "SPELER {0} WINT!",
  queda: "ARMWORSTELEN!",
  queda_sub: "Tijd is op! Wie het snelst klikt, wint",
  queda_dica_bot: "KLIK / SPATIE!",
  queda_dica_toque: "TIK OP HET SCHERM!",
  queda_dica_p1: "DRUK OP F!",
  queda_dica_p2: "DRUK OP L!",
  queda_dica_toque_esq: "TIK LINKS!",
  queda_dica_toque_dir: "TIK RECHTS!",
  toque_mover: "lopen",
  toque_tiro: "SCHIET",
  pegou_arma: "{0}!",
  c_campo: "Weide",
  r_campo: "Klassiek: gewoon vechten!",
  c_gelo: "Gletsjer",
  r_gelo: "IJs: alles glijdt!",
  c_lua: "Maan",
  r_lua: "Lage zwaartekracht: reuzensprongen",
  c_vulcao: "Vulkaan",
  r_vulcao: "Lava stijgt en daalt: blijf hoog!",
  c_espaco: "Ruimte",
  r_espaco: "Bijna gewichtloos: spring om te vliegen",
  c_laboratorio: "Lab",
  r_laboratorio: "De zwaartekracht draait om!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: duw de tegenstander eraf!",
  c_cidade: "Neonstad",
  r_cidade: "Let op het gat tussen de gebouwen!",
  c_fliperama: "Flipperkast",
  r_fliperama: "Bumpers schieten je weg!",
  c_floresta: "Nachtbos",
  r_floresta: "In het donker: alleen zicht bij licht",
  c_deserto: "Woestijn",
  r_deserto: "Harde wind wisselt van kant!",
  c_fabrica: "Fabriek",
  r_fabrica: "Lopende banden nemen je mee!",
  c_oceano: "Diepzee",
  r_oceano: "Onder water: spring om te zwemmen",
  c_templo: "Tempel",
  r_templo: "Eruit aan de ene kant, erin aan de andere. Portalen!",
  c_castelo: "Kasteel",
  r_castelo: "Meteorenregen: ontwijk de doelen!",
  k_escudo: "Schild",
  kd_escudo: "Blokkeert 40 schade",
  k_rapidez: "Snelheid",
  kd_rapidez: "7 s sneller",
  k_cura: "Genezing",
  kd_cura: "+35 leven",
  k_furia: "Woede",
  kd_furia: "Dubbele schade 6 s",
  k_tiro_duplo: "Dubbel Schot",
  kd_tiro_duplo: "Elk schot dubbel",
  k_mini: "Mini",
  kd_mini: "Klein en moeilijk te raken",
  k_congelar: "Bevriezen",
  kd_congelar: "Bevriest de tegenstander",
  k_fantasma: "Geest",
  kd_fantasma: "Bijna onzichtbaar 5 s",
  k_reflexo: "Reflectie",
  kd_reflexo: "Kaatst schoten terug 5 s",
  k_super_pulo: "Supersprong",
  kd_super_pulo: "Drievoudige, hogere sprong",
  k_chuva: "Meteorenregen",
  kd_chuva: "5 meteoren op de tegenstander",
  k_municao: "Oneindige Munitie",
  kd_municao: "8 s geen munitie verbruikt",
  a_estilingue: "Katapult",
  a_pistola: "Pistool",
  a_revolver: "Revolver",
  a_submetralhadora: "Machinepistool",
  a_minigun: "Minigun",
  a_escopeta: "Jachtgeweer",
  a_escopeta_dupla: "Dubbelloops",
  a_rifle: "Geweer",
  a_sniper: "Sluipschuttersgeweer",
  a_plasma: "Plasmageweer",
  a_pula_pula: "Stuiterbal",
  a_confete: "Confettikanon",
  a_arma_agua: "Waterpistool",
  a_zarabatana: "Blaaspijp",
  a_onda_sonora: "Geluidsgolf",
  a_shuriken: "Shuriken",
  a_bumerangue: "Boemerang",
  a_arco: "Boog",
  a_arco_triplo: "Drievoudige Boog",
  a_besta: "Kruisboog",
  a_serra: "Zaagblad",
  a_bola_neve: "Sneeuwbal",
  a_gancho: "Grijphaak",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Granaatwerper",
  a_granada: "Granaat",
  a_dinamite: "Dynamiet",
  a_fragmentacao: "Splintergranaat",
  a_canhao: "Kanon",
  a_mini_misseis: "Mini-raketten",
  a_missil: "Geleide Raket",
  a_abelhas: "Bijenzwerm",
  a_bola_fogo: "Vuurbal",
  a_granada_gelo: "IJsgranaat",
  a_mina: "Mijn",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Regenbooglaser",
  a_feixe: "Straalkanon",
  a_tesla: "Teslageweer",
  a_raio_gelo: "IJsstraal",
  a_bolhas: "Bellenblaas",
  a_buraco_negro: "Zwart Gat",
  a_lanca_chamas: "Vlammenwerper",
  a_soprador: "Bladblazer",
  a_martelo: "Hamer",
  a_espada: "Zwaard",
  a_luva_boxe: "Bokshandschoen",
  a_meteoro: "Meteoren",
  a_relampago: "Bliksem"
};
