"use strict";
TEXTOS.pl = {
  titulo: "Pojedynek Kulek",
  jogar: "GRAJ",
  idioma: "Język",
  som_on: "Dźwięk: wł.",
  som_off: "Dźwięk: wył.",
  voltar: "Wróć",
  pausado: "Pauza",
  continuar: "Wznów",
  menu: "Menu",
  anuncio_falhou: "Reklama się nie załadowała. Spróbuj później.",
  escolha_modo: "Jak chcesz grać?",
  contra_bot: "Z botem",
  dois_jogadores: "2 graczy",
  dica_bot_teclado: "A D / ← → ruch\nW / ↑ skok\nF / Spacja / L strzał",
  dica_bot_toque: "Lewo: przeciągnij, by iść i skakać\nPrawo: przytrzymaj, by strzelać",
  dica_2p_teclado: "Gracz 1: A D W + F\nGracz 2: ← → ↑ + L\nNa jednej klawiaturze!",
  dica_2p_toque: "Każdy używa swojej połowy ekranu",
  lendaria: "Legendarny Mecz",
  lendaria_anuncio: "Legendarny Mecz: tylko rzadkie bronie (reklama)",
  lendaria_ativada: "Legendarny Mecz włączony! Wybierz tryb",
  continuar_anuncio: "▶ Kontynuuj",
  continuar_explica: "Obejrzyj reklamę, a mecz trwa dalej: bot traci ostatni punkt.",
  nao_obrigado: "Nie, dziękuję",
  voce: "TY",
  voce_curto: "TY",
  bot: "BOT",
  jogador_n: "GRACZ {0}",
  rodada_n: "Runda {0}",
  dano_dobro: "PODWÓJNE OBRAŻENIA!",
  lute: "WALCZ!",
  empate: "REMIS!",
  voce_venceu_rodada: "WYGRANA RUNDA!",
  bot_venceu_rodada: "BOT WYGRYWA RUNDĘ",
  jogador_venceu_rodada: "RUNDA DLA GRACZA {0}!",
  voce_venceu: "WYGRAŁEŚ!",
  bot_venceu: "BOT WYGRYWA",
  jogador_venceu: "WYGRYWA GRACZ {0}!",
  queda: "SIŁOWANIE NA RĘKĘ!",
  queda_sub: "Koniec czasu! Wygrywa ten, kto szybciej klika",
  queda_dica_bot: "KLIKAJ / SPACJA!",
  queda_dica_toque: "STUKAJ W EKRAN!",
  queda_dica_p1: "WCISKAJ F!",
  queda_dica_p2: "WCISKAJ L!",
  queda_dica_toque_esq: "STUKAJ PO LEWEJ!",
  queda_dica_toque_dir: "STUKAJ PO PRAWEJ!",
  toque_mover: "ruch",
  toque_tiro: "STRZAŁ",
  pegou_arma: "{0}!",
  c_campo: "Łąka",
  r_campo: "Klasyka: po prostu walcz!",
  c_gelo: "Lodowiec",
  r_gelo: "Lód: wszystko się ślizga!",
  c_lua: "Księżyc",
  r_lua: "Niska grawitacja: ogromne skoki",
  c_vulcao: "Wulkan",
  r_vulcao: "Lawa się podnosi: zostań wysoko!",
  c_espaco: "Kosmos",
  r_espaco: "Prawie bez grawitacji: skacz, by latać",
  c_laboratorio: "Laboratorium",
  r_laboratorio: "Grawitacja się odwraca!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: wypchnij rywala!",
  c_cidade: "Neonowe Miasto",
  r_cidade: "Uważaj na przepaść między budynkami!",
  c_fliperama: "Pinball",
  r_fliperama: "Odbijacze wystrzeliwują cię!",
  c_floresta: "Nocny Las",
  r_floresta: "W ciemności: widać tylko przy świetle",
  c_deserto: "Pustynia",
  r_deserto: "Silny wiatr zmienia kierunek!",
  c_fabrica: "Fabryka",
  r_fabrica: "Taśmociągi cię niosą!",
  c_oceano: "Głębia Morza",
  r_oceano: "Pod wodą: skacz, by płynąć",
  c_templo: "Świątynia",
  r_templo: "Wyjdź z jednej strony, wejdź z drugiej. Portale!",
  c_castelo: "Zamek",
  r_castelo: "Deszcz meteorów: unikaj celów!",
  k_escudo: "Tarcza",
  kd_escudo: "Blokuje 40 obrażeń",
  k_rapidez: "Szybkość",
  kd_rapidez: "Szybciej przez 7 s",
  k_cura: "Leczenie",
  kd_cura: "+35 zdrowia",
  k_furia: "Furia",
  kd_furia: "Podwójne obrażenia 6 s",
  k_tiro_duplo: "Podwójny Strzał",
  kd_tiro_duplo: "Każdy strzał podwójny",
  k_mini: "Mini",
  kd_mini: "Mały i trudny do trafienia",
  k_congelar: "Zamrożenie",
  kd_congelar: "Zamraża rywala",
  k_fantasma: "Duch",
  kd_fantasma: "Prawie niewidzialny 5 s",
  k_reflexo: "Odbicie",
  kd_reflexo: "Odbija strzały przez 5 s",
  k_super_pulo: "Super Skok",
  kd_super_pulo: "Potrójny, wyższy skok",
  k_chuva: "Deszcz Meteorów",
  kd_chuva: "5 meteorów na rywala",
  k_municao: "Nieskończona Amunicja",
  kd_municao: "Bez zużycia amunicji 8 s",
  a_estilingue: "Proca",
  a_pistola: "Pistolet",
  a_revolver: "Rewolwer",
  a_submetralhadora: "Pistolet maszynowy",
  a_minigun: "Minigun",
  a_escopeta: "Strzelba",
  a_escopeta_dupla: "Dwururka",
  a_rifle: "Karabin",
  a_sniper: "Snajperka",
  a_plasma: "Plazma",
  a_pula_pula: "Skacząca Piłka",
  a_confete: "Armatka Konfetti",
  a_arma_agua: "Pistolet na Wodę",
  a_zarabatana: "Dmuchawka",
  a_onda_sonora: "Fala Dźwiękowa",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Łuk",
  a_arco_triplo: "Potrójny Łuk",
  a_besta: "Kusza",
  a_serra: "Piła Tarczowa",
  a_bola_neve: "Śnieżka",
  a_gancho: "Hak",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Granatnik",
  a_granada: "Granat",
  a_dinamite: "Dynamit",
  a_fragmentacao: "Granat Odłamkowy",
  a_canhao: "Armata",
  a_mini_misseis: "Mini Rakiety",
  a_missil: "Rakieta Samonaprowadzająca",
  a_abelhas: "Rój Pszczół",
  a_bola_fogo: "Kula Ognia",
  a_granada_gelo: "Granat Lodowy",
  a_mina: "Mina",
  a_laser: "Laser",
  a_railgun: "Działo Szynowe",
  a_arco_iris: "Tęczowy Laser",
  a_feixe: "Ciągły Promień",
  a_tesla: "Tesla",
  a_raio_gelo: "Promień Lodu",
  a_bolhas: "Pistolet na Bańki",
  a_buraco_negro: "Czarna Dziura",
  a_lanca_chamas: "Miotacz Ognia",
  a_soprador: "Dmuchawa",
  a_martelo: "Młot",
  a_espada: "Miecz",
  a_luva_boxe: "Rękawica",
  a_meteoro: "Meteory",
  a_relampago: "Piorun"
};
