"use strict";
TEXTOS.pl = {
  titulo: "Crazy Balls Duel",
  jogar: "GRAJ",
  idioma: "Język",
  som_on: "Dźwięk: wł.",
  som_off: "Dźwięk: wył.",
  voltar: "Wróć",
  pausado: "Pauza",
  continuar: "Wznów",
  menu: "Menu",
  anuncio_falhou: "Reklama się nie załadowała. Spróbuj później.",
  escolha_modo: "Jak chcesz grać?",
  contra_bot: "Z botem",
  dois_jogadores: "2 graczy",
  dica_bot_teclado: "A D / ← → ruch\nW / ↑ skok\nF / Spacja / L strzał",
  dica_bot_toque: "Lewo: przeciągnij, by iść\nPrawo: góra skok · dół celowanie i strzał",
  dica_2p_teclado: "Gracz 1: A D W + F\nGracz 2: ← → ↑ + L\nNa jednej klawiaturze!",
  dica_2p_toque: "We dwoje na jednym telefonie, poziomo: każdy używa połowy ekranu",
  lendaria: "Legendarny Mecz",
  lendaria_anuncio: "Legendarny Mecz: tylko rzadkie bronie (reklama)",
  lendaria_ativada: "Legendarny Mecz włączony! Wybierz tryb",
  continuar_anuncio: "▶ Kontynuuj",
  continuar_explica: "Obejrzyj reklamę, a mecz trwa dalej: bot traci ostatni punkt.",
  nao_obrigado: "Nie, dziękuję",
  voce: "TY",
  voce_curto: "TY",
  bot: "BOT",
  jogador_n: "GRACZ {0}",
  rodada_n: "Runda {0}",
  dano_dobro: "PODWÓJNE OBRAŻENIA!",
  lute: "WALCZ!",
  empate: "REMIS!",
  voce_venceu_rodada: "WYGRANA RUNDA!",
  bot_venceu_rodada: "BOT WYGRYWA RUNDĘ",
  jogador_venceu_rodada: "RUNDA DLA GRACZA {0}!",
  voce_venceu: "WYGRAŁEŚ!",
  bot_venceu: "BOT WYGRYWA",
  jogador_venceu: "WYGRYWA GRACZ {0}!",
  queda: "SIŁOWANIE NA RĘKĘ!",
  queda_sub: "Koniec czasu! Wygrywa ten, kto szybciej klika",
  queda_dica_bot: "KLIKAJ / SPACJA!",
  queda_dica_toque: "STUKAJ W EKRAN!",
  queda_dica_p1: "WCISKAJ F!",
  queda_dica_p2: "WCISKAJ L!",
  queda_dica_toque_esq: "STUKAJ PO LEWEJ!",
  queda_dica_toque_dir: "STUKAJ PO PRAWEJ!",
  toque_mover: "ruch",
  toque_tiro: "STRZAŁ",
  pegou_arma: "{0}!",
  mesmo_aparelho: "Na jednym urządzeniu · nie online",
  qualidade_auto: "Grafika: automatyczna",
  qualidade_alta: "Grafika: wysoka",
  qualidade_leve: "Grafika: lekka",
  perfeito: "PERFEKCYJNIE!",
  missoes: "Misje",
  skins: "Skórki",
  opcoes: "Opcje",
  controles: "Sterowanie",
  controles_mouse: "Gracz 1 celuje też MYSZKĄ (klik strzela). Kliknij klawisz i wciśnij nowy.",
  teclas_padrao: "Domyślne klawisze",
  semana: "Tydzień",
  conquistas: "Osiągnięcia",
  skins_corpo: "Kulka",
  skins_acessorio: "Dodatek",
  dobrar_moedas: "Podwój monety",
  resgatar: "Odbierz",
  trocar: "Zmień",
  missoes_explica: "Wykonuj misje, by zdobyć monety. Możesz zmienić 1 misję dziennie.",
  semana_termina: "Kończy się za {0}d {1}h",
  premio_semana: "Nagroda tygodnia: ukończ 4 wyzwania",
  equipado: "Założone",
  equipar: "Załóż",
  so_semanal: "Nagroda tygodnia",
  acao_esquerda: "Lewo",
  acao_direita: "Prawo",
  acao_pulo: "Skok",
  acao_baixo: "W dół",
  acao_tiro: "Strzał",
  tecla_espaco: "Spacja",
  toque_mira: "CEL",
  dica_bot_v2: "{0} ruch · {1} skok\nMysz: celuj i strzelaj (lub {2})",
  dica_2p_v2: "Gracz 1: {0}\nGracz 2: {1}\nNa jednej klawiaturze!",
  aviso_missao: "Misja wykonana!",
  aviso_desafio: "Wyzwanie tygodnia ukończone!",
  aviso_conquista: "Osiągnięcie: {0}!",
  nivel_bot: "🤖 Bot poziom {0}",
  nivel_curto: "Poz. {0}",
  bot_subiu: "Bot awansował na poziom {0}!",
  bot_desceu: "Bot spadł na poziom {0}",
  nivel_jogador: "Poziom {0}",
  subiu_nivel: "Awans na poziom {0}!",
  abrir_bau: "Otwórz skrzynię",
  abrir_bau_nivel: "Otwórz skrzynię poziomu!",
  outro_bau: "Otwórz kolejną skrzynię",
  revanche: "REWANŻ",
  premio_skin: "Nowa skórka: {0}!",
  diaria: "Nagroda dzienna",
  diaria_explica: "Wracaj codziennie: nagroda rośnie! Opuść dzień, a zacznie się od nowa.",
  dia_n: "Dzień {0}",
  bau: "skrzynia",
  bau_lendario: "legendarna skrzynia",
  pegar: "Odbierz",
  fechar: "Zamknij",
  sobrevivencia: "Przetrwanie",
  sobrevivencia_dica: "Fale coraz silniejszych botów.\nJak daleko dojdziesz?",
  onda_n: "FALA {0}",
  onda_concluida: "FALA {0} POKONANA!",
  fim_sobrevivencia: "Dotarłeś do fali {0}!",
  recorde_onda: "Rekord: fala {0}",
  novo_recorde: "NOWY REKORD!",
  continuar_vida: "Obejrzyj reklamę i kontynuuj tę samą falę z pełnym zdrowiem.",
  dica_bot_v3: "{0} ruch · {1} skok\nMysz: celowanie · Klik lub {2}: strzał",
  dica_2p_v3: "Gracz 1: {0} + mysz\nGracz 2: {1}\nNa jednej klawiaturze!",
  queda_clique: "KLIKAJ LUB {0}!",
  queda_aperte: "WCISKAJ {0}!",
  toque_pulo: "SKOK",
  estilo_agressivo: "Agresywny",
  estilo_atirador: "Snajper",
  estilo_saltitante: "Skoczek",
  estilo_cauteloso: "Ostrożny",
  estilo_colecionador: "Kolekcjoner",
  c_campo: "Łąka",
  r_campo: "Klasyka: po prostu walcz!",
  c_gelo: "Lodowiec",
  r_gelo: "Lód: wszystko się ślizga!",
  c_lua: "Księżyc",
  r_lua: "Niska grawitacja: ogromne skoki",
  c_vulcao: "Wulkan",
  r_vulcao: "Lawa się podnosi: zostań wysoko!",
  c_espaco: "Kosmos",
  r_espaco: "Prawie bez grawitacji: skacz, by latać",
  c_laboratorio: "Laboratorium",
  r_laboratorio: "Grawitacja się odwraca!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: wypchnij rywala!",
  c_cidade: "Neonowe Miasto",
  r_cidade: "Uważaj na przepaść między budynkami!",
  c_fliperama: "Pinball",
  r_fliperama: "Odbijacze wystrzeliwują cię!",
  c_floresta: "Nocny Las",
  r_floresta: "W ciemności: widać tylko przy świetle",
  c_deserto: "Pustynia",
  r_deserto: "Silny wiatr zmienia kierunek!",
  c_fabrica: "Fabryka",
  r_fabrica: "Taśmociągi cię niosą!",
  c_oceano: "Głębia Morza",
  r_oceano: "Pod wodą: skacz, by płynąć",
  c_templo: "Świątynia",
  r_templo: "Wyjdź z jednej strony, wejdź z drugiej. Portale!",
  c_castelo: "Zamek",
  r_castelo: "Deszcz meteorów: unikaj celów!",
  k_escudo: "Tarcza",
  kd_escudo: "Blokuje 40 obrażeń",
  k_rapidez: "Szybkość",
  kd_rapidez: "Szybciej przez 7 s",
  k_cura: "Leczenie",
  kd_cura: "+35 zdrowia",
  k_furia: "Furia",
  kd_furia: "Podwójne obrażenia 6 s",
  k_tiro_duplo: "Podwójny Strzał",
  kd_tiro_duplo: "Każdy strzał podwójny",
  k_mini: "Mini",
  kd_mini: "Mały i trudny do trafienia",
  k_congelar: "Zamrożenie",
  kd_congelar: "Zamraża rywala",
  k_fantasma: "Duch",
  kd_fantasma: "Prawie niewidzialny 5 s",
  k_reflexo: "Odbicie",
  kd_reflexo: "Odbija strzały przez 5 s",
  k_super_pulo: "Super Skok",
  kd_super_pulo: "Potrójny, wyższy skok",
  k_chuva: "Deszcz Meteorów",
  kd_chuva: "5 meteorów na rywala",
  k_municao: "Nieskończona Amunicja",
  kd_municao: "Bez zużycia amunicji 8 s",
  a_estilingue: "Proca",
  a_pistola: "Pistolet",
  a_revolver: "Rewolwer",
  a_submetralhadora: "Pistolet maszynowy",
  a_minigun: "Minigun",
  a_escopeta: "Strzelba",
  a_escopeta_dupla: "Dwururka",
  a_rifle: "Karabin",
  a_sniper: "Snajperka",
  a_plasma: "Plazma",
  a_pula_pula: "Skacząca Piłka",
  a_confete: "Armatka Konfetti",
  a_arma_agua: "Pistolet na Wodę",
  a_zarabatana: "Dmuchawka",
  a_onda_sonora: "Fala Dźwiękowa",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Łuk",
  a_arco_triplo: "Potrójny Łuk",
  a_besta: "Kusza",
  a_serra: "Piła Tarczowa",
  a_bola_neve: "Śnieżka",
  a_gancho: "Hak",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Granatnik",
  a_granada: "Granat",
  a_dinamite: "Dynamit",
  a_fragmentacao: "Granat Odłamkowy",
  a_canhao: "Armata",
  a_mini_misseis: "Mini Rakiety",
  a_missil: "Rakieta Samonaprowadzająca",
  a_abelhas: "Rój Pszczół",
  a_bola_fogo: "Kula Ognia",
  a_granada_gelo: "Granat Lodowy",
  a_mina: "Mina",
  a_laser: "Laser",
  a_railgun: "Działo Szynowe",
  a_arco_iris: "Tęczowy Laser",
  a_feixe: "Ciągły Promień",
  a_tesla: "Tesla",
  a_raio_gelo: "Promień Lodu",
  a_bolhas: "Pistolet na Bańki",
  a_buraco_negro: "Czarna Dziura",
  a_lanca_chamas: "Miotacz Ognia",
  a_soprador: "Dmuchawa",
  a_martelo: "Młot",
  a_espada: "Miecz",
  a_luva_boxe: "Rękawica",
  a_meteoro: "Meteory",
  a_relampago: "Piorun",
  mi_vitorias: "Wygraj {0} mecz(e) z botem",
  mi_rodadas: "Wygraj {0} rund",
  mi_dano: "Zadaj {0} obrażeń",
  mi_quedas: "Wygraj {0} siłowanie(a)",
  mi_cartas: "Zbierz {0} kart",
  mi_caixas: "Zbierz {0} skrzynek z bronią",
  mi_abatesExpl: "Wygraj {0} rund(y) materiałami wybuchowymi",
  mi_abatesMelee: "Wygraj {0} rund(y) w zwarciu",
  mi_perfeitas: "Wygraj {0} rund(y) bez obrażeń",
  mi_partidas: "Zagraj {0} mecze",
  mi_partidas2p: "Zagraj {0} mecz(e) we dwóch",
  mi_rodadaCenario: "Wygraj {0} rund(y) w: {1}",
  de_s_vitorias: "Wygraj {0} mecz(e) z botem",
  de_s_rodadas: "Wygraj {0} rund",
  de_s_dano: "Zadaj {0} obrażeń",
  de_s_quedas: "Wygraj {0} siłowanie(a)",
  de_s_cenarios: "Wygraj rundy na {0} różnych arenach",
  de_s_5x0: "Wygraj mecz 3 – 0",
  de_s_expl: "Wygraj {0} rund(y) materiałami wybuchowymi",
  de_s_cartas: "Zbierz {0} kart",
  de_s_perfeitas: "Wygraj {0} rund(y) bez obrażeń",
  de_s_virada: "Wygraj, przegrywając 2 punktami",
  co_primeira_vitoria: "Pierwsze Zwycięstwo",
  cod_primeira_vitoria: "Wygraj {0} mecz(e) z botem",
  co_vitorias_10: "Pojedynkowicz",
  cod_vitorias_10: "Wygraj {0} mecz(e) z botem",
  co_vitorias_25: "Weteran",
  cod_vitorias_25: "Wygraj {0} mecz(e) z botem",
  co_vitorias_100: "Legenda",
  cod_vitorias_100: "Wygraj {0} mecz(e) z botem",
  co_partidas_50: "Uzależniony",
  cod_partidas_50: "Zagraj {0} mecze",
  co_rodadas_50: "Zwycięzca Rund",
  cod_rodadas_50: "Wygraj {0} rund",
  co_rodadas_250: "Maszyna",
  cod_rodadas_250: "Wygraj {0} rund",
  co_dano_20000: "Niszczyciel",
  cod_dano_20000: "Zadaj {0} obrażeń",
  co_dano_100000: "Apokalipsa",
  cod_dano_100000: "Zadaj {0} obrażeń",
  co_quedas_5: "Silne Ramię",
  cod_quedas_5: "Wygraj {0} siłowanie(a)",
  co_quedas_20: "Mistrz Siłowania",
  cod_quedas_20: "Wygraj {0} siłowanie(a)",
  co_explosivos_50: "Burzyciel",
  cod_explosivos_50: "Wygraj {0} rund(y) materiałami wybuchowymi",
  co_melee_20: "Zabijaka",
  cod_melee_20: "Wygraj {0} rund(y) w zwarciu",
  co_perfeitas_10: "Nietykalny",
  cod_perfeitas_10: "Wygraj {0} rund(y) bez obrażeń",
  co_cenarios_todos: "Odkrywca",
  cod_cenarios_todos: "Wygraj rundy na {0} różnych arenach",
  co_armas_25: "Kolekcjoner",
  cod_armas_25: "Zbierz {0} różnych broni",
  co_armas_todas: "Pełny Arsenał",
  cod_armas_todas: "Zbierz {0} różnych broni",
  co_cartas_todas: "Pełna Talia",
  cod_cartas_todas: "Zbierz wszystkie {0} karty",
  co_placar_5x0: "Pogrom",
  cod_placar_5x0: "Wygraj mecz 3 – 0",
  co_virada: "Epicki Powrót",
  cod_virada: "Wygraj, przegrywając 2 punktami",
  co_bot_mestre: "Mistrz Bota",
  cod_bot_mestre: "Pokonaj bota na najwyższym poziomie",
  co_dois_jogadores_10: "Najlepsi Przyjaciele",
  cod_dois_jogadores_10: "Zagraj {0} mecz(e) we dwóch",
  co_missoes_10: "Oddany",
  cod_missoes_10: "Odbierz {0} misji",
  co_missoes_50: "Niestrudzony",
  cod_missoes_50: "Odbierz {0} misji",
  co_semana_completa: "Idealny Tydzień",
  cod_semana_completa: "Ukończ wszystkie wyzwania tygodnia",
  co_onda_5: "Ocalały",
  cod_onda_5: "Dojdź do fali {0} w Przetrwaniu",
  co_onda_10: "Niepowstrzymany",
  cod_onda_10: "Dojdź do fali {0} w Przetrwaniu",
  sk_classico: "Klasyczna",
  sk_listras: "Paski",
  sk_pintas: "Kropki",
  sk_xadrez: "Krata",
  sk_camuflado: "Moro",
  sk_futebol: "Piłka",
  sk_melancia: "Arbuz",
  sk_robo: "Robot",
  sk_doce: "Cukierek",
  sk_cromado: "Chrom",
  sk_gelo: "Kryształ Lodu",
  sk_neon: "Neon",
  sk_lava: "Lawa",
  sk_diamante: "Diament",
  sk_galaxia: "Galaktyka",
  sk_ouro: "Złoto",
  sk_nenhum: "Brak",
  sk_bone: "Czapka",
  sk_oculos: "Okulary",
  sk_orelhas_gato: "Kocie Uszy",
  sk_fone: "Słuchawki",
  sk_cartola: "Cylinder",
  sk_chifres: "Rogi",
  sk_tiara_flores: "Wianek",
  sk_mascara_ninja: "Maska Ninja",
  sk_viking: "Hełm Wikinga",
  sk_cowboy: "Kapelusz Kowboja",
  sk_antena: "Antena Kosmity",
  sk_aureola: "Aureola",
  sk_coroa: "Korona",
  novo: "NOWE!",
  proximo_rival: "NASTĘPNY RYWAL",
  premio_equipado: "{0} założone!",
  modo_rivais: "Rywale",
  rivais_dica: "Pokonaj 10 rywali i awansuj",
  rival_n: "RYWAL {0}/{1}",
  liga_0: "Brąz",
  liga_1: "Srebro",
  liga_2: "Złoto",
  liga_3: "Diament",
  liga_4: "Mistrz",
  liga_n: "Liga {0}",
  rival_derrotado: "{0} pokonany!",
  proximo: "Następny: {0}",
  revanche_contra: "Rewanż: {0}",
  campeao_liga: "MISTRZ LIGI {0}!",
  rival_venceu: "{0} wygrywa!",
  venca_ganhe: "Wygraj i zdobądź: {0}",
  salvo: "URATOWANY!",
  melhorar: "Ulepsz",
  poder_explica: "Stań się silniejszy w walce z botem i rywalami. W trybie 2 graczy obaj są równi.",
  poder_n: "⚡ MOC {0}",
  poder_dica: "Ulepsz się i wróć silniejszy!",
  poder_gaste: "Wydaj monety: stań się silniejszy!",
  mel_forca: "Siła",
  mel_vida: "Życie",
  mel_veloc: "Szybkość",
  mel_nivel: "Poz. {0}",
  mel_max: "MAX",
  mel_d_forca: "Mocniejsze ciosy",
  mel_d_vida: "Więcej wytrzymasz",
  mel_d_veloc: "Szybszy ruch",
  gratis: "ZA DARMO!",
  escolha_gratis: "Wybierz 1 za darmo!"
};
