"use strict";
TEXTOS.pt = {
  titulo: "Duelo de Bolinhas",
  jogar: "JOGAR",
  idioma: "Idioma",
  som_on: "Som: ligado",
  som_off: "Som: desligado",
  voltar: "Voltar",
  pausado: "Pausado",
  continuar: "Continuar",
  menu: "Menu",
  anuncio_falhou: "O anúncio não carregou. Tente de novo mais tarde.",
  escolha_modo: "Como você quer jogar?",
  contra_bot: "Contra o bot",
  dois_jogadores: "2 jogadores",
  dica_bot_teclado: "A D / ← → andar\nW / ↑ pular\nF / Espaço / L atirar",
  dica_bot_toque: "Esquerda: arraste para andar e pular\nDireita: segure para atirar",
  dica_2p_teclado: "Jogador 1: A D W + F\nJogador 2: ← → ↑ + L\nNo mesmo teclado!",
  dica_2p_toque: "Cada um usa a sua metade da tela",
  lendaria: "Partida Lendária",
  lendaria_anuncio: "Partida Lendária: só armas raras (anúncio)",
  lendaria_ativada: "Partida Lendária ativada! Escolha o modo",
  continuar_anuncio: "▶ Continuar",
  continuar_explica: "Assista um anúncio e a partida continua: o bot perde o último ponto.",
  nao_obrigado: "Não, obrigado",
  voce: "VOCÊ",
  voce_curto: "VOCÊ",
  bot: "BOT",
  jogador_n: "JOGADOR {0}",
  rodada_n: "Rodada {0}",
  dano_dobro: "DANO EM DOBRO!",
  lute: "LUTE!",
  empate: "EMPATE!",
  voce_venceu_rodada: "VOCÊ VENCEU A RODADA!",
  bot_venceu_rodada: "O BOT VENCEU A RODADA",
  jogador_venceu_rodada: "RODADA DO JOGADOR {0}!",
  voce_venceu: "VOCÊ VENCEU!",
  bot_venceu: "O BOT VENCEU",
  jogador_venceu: "JOGADOR {0} VENCEU!",
  queda: "QUEDA DE BRAÇO!",
  queda_sub: "O tempo acabou! Quem clicar mais rápido vence",
  queda_dica_bot: "CLIQUE / ESPAÇO!",
  queda_dica_toque: "TOQUE NA TELA!",
  queda_dica_p1: "APERTE F!",
  queda_dica_p2: "APERTE L!",
  queda_dica_toque_esq: "TOQUE NA ESQUERDA!",
  queda_dica_toque_dir: "TOQUE NA DIREITA!",
  toque_mover: "andar",
  toque_tiro: "ATIRAR",
  pegou_arma: "{0}!",
  c_campo: "Campo",
  r_campo: "Clássico: só lutar!",
  c_gelo: "Geleira",
  r_gelo: "Gelo: tudo escorrega!",
  c_lua: "Lua",
  r_lua: "Pouca gravidade: pulos gigantes",
  c_vulcao: "Vulcão",
  r_vulcao: "A lava sobe e desce: fique no alto!",
  c_espaco: "Espaço",
  r_espaco: "Quase sem gravidade: pule para voar",
  c_laboratorio: "Laboratório",
  r_laboratorio: "A gravidade vira de cabeça para baixo!",
  c_dojo: "Dojô",
  r_dojo: "Sumô: empurre o oponente para fora!",
  c_cidade: "Cidade Neon",
  r_cidade: "Cuidado com o vão entre os prédios!",
  c_fliperama: "Fliperama",
  r_fliperama: "Bumpers jogam você longe!",
  c_floresta: "Floresta Noturna",
  r_floresta: "No escuro: só se vê perto da luz",
  c_deserto: "Deserto",
  r_deserto: "Vento forte muda de lado!",
  c_fabrica: "Fábrica",
  r_fabrica: "Esteiras levam você junto!",
  c_oceano: "Fundo do Mar",
  r_oceano: "Embaixo d'água: pule para nadar",
  c_templo: "Templo",
  r_templo: "Saia de um lado, volte pelo outro. Portais!",
  c_castelo: "Castelo",
  r_castelo: "Chuva de meteoros: fuja dos alvos!",
  k_escudo: "Escudo",
  kd_escudo: "Segura 40 de dano",
  k_rapidez: "Rapidez",
  kd_rapidez: "Mais rápido por 7 s",
  k_cura: "Cura",
  kd_cura: "+35 de vida",
  k_furia: "Fúria",
  kd_furia: "Dano em dobro por 6 s",
  k_tiro_duplo: "Tiro Duplo",
  kd_tiro_duplo: "Cada tiro sai em dobro",
  k_mini: "Mini",
  kd_mini: "Pequeno e difícil de acertar",
  k_congelar: "Congelar",
  kd_congelar: "Congela o oponente",
  k_fantasma: "Fantasma",
  kd_fantasma: "Quase invisível por 5 s",
  k_reflexo: "Reflexo",
  kd_reflexo: "Devolve os tiros por 5 s",
  k_super_pulo: "Super Pulo",
  kd_super_pulo: "Pulo triplo e mais alto",
  k_chuva: "Chuva de Meteoros",
  kd_chuva: "5 meteoros no oponente",
  k_municao: "Munição Infinita",
  kd_municao: "Sem gastar munição por 8 s",
  a_estilingue: "Estilingue",
  a_pistola: "Pistola",
  a_revolver: "Revólver",
  a_submetralhadora: "Submetralhadora",
  a_minigun: "Minigun",
  a_escopeta: "Escopeta",
  a_escopeta_dupla: "Escopeta Dupla",
  a_rifle: "Rifle",
  a_sniper: "Sniper",
  a_plasma: "Plasma",
  a_pula_pula: "Bola Pula-Pula",
  a_confete: "Canhão de Confete",
  a_arma_agua: "Arma de Água",
  a_zarabatana: "Zarabatana",
  a_onda_sonora: "Onda Sonora",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerangue",
  a_arco: "Arco",
  a_arco_triplo: "Arco Triplo",
  a_besta: "Besta",
  a_serra: "Serra Giratória",
  a_bola_neve: "Bola de Neve",
  a_gancho: "Gancho",
  a_bazuca: "Bazuca",
  a_lanca_granadas: "Lança-Granadas",
  a_granada: "Granada",
  a_dinamite: "Dinamite",
  a_fragmentacao: "Granada de Fragmentação",
  a_canhao: "Canhão",
  a_mini_misseis: "Mini Mísseis",
  a_missil: "Míssil Teleguiado",
  a_abelhas: "Enxame de Abelhas",
  a_bola_fogo: "Bola de Fogo",
  a_granada_gelo: "Granada de Gelo",
  a_mina: "Mina",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Arco-Íris",
  a_feixe: "Raio Contínuo",
  a_tesla: "Tesla",
  a_raio_gelo: "Raio de Gelo",
  a_bolhas: "Arma de Bolhas",
  a_buraco_negro: "Buraco Negro",
  a_lanca_chamas: "Lança-Chamas",
  a_soprador: "Soprador",
  a_martelo: "Martelo",
  a_espada: "Espada",
  a_luva_boxe: "Luva de Boxe",
  a_meteoro: "Meteoros",
  a_relampago: "Relâmpago"
};
