"use strict";
TEXTOS.pt = {
  titulo: "Crazy Balls Duel",
  jogar: "JOGAR",
  idioma: "Idioma",
  som_on: "Som: ligado",
  som_off: "Som: desligado",
  voltar: "Voltar",
  pausado: "Pausado",
  continuar: "Continuar",
  menu: "Menu",
  anuncio_falhou: "O anúncio não carregou. Tente de novo mais tarde.",
  escolha_modo: "Como você quer jogar?",
  contra_bot: "Contra o bot",
  dois_jogadores: "2 jogadores",
  dica_bot_teclado: "A D / ← → andar\nW / ↑ pular\nF / Espaço / L atirar",
  dica_bot_toque: "Esquerda: arraste para andar\nDireita: em cima pula · embaixo mira e atira",
  dica_2p_teclado: "Jogador 1: A D W + F\nJogador 2: ← → ↑ + L\nNo mesmo teclado!",
  dica_2p_toque: "Dois no mesmo celular, deitado: cada um usa uma metade da tela",
  lendaria: "Partida Lendária",
  lendaria_anuncio: "Partida Lendária: só armas raras (anúncio)",
  lendaria_ativada: "Partida Lendária ativada! Escolha o modo",
  continuar_anuncio: "▶ Continuar",
  continuar_explica: "Assista um anúncio e a partida continua: o bot perde o último ponto.",
  nao_obrigado: "Não, obrigado",
  voce: "VOCÊ",
  voce_curto: "VOCÊ",
  bot: "BOT",
  jogador_n: "JOGADOR {0}",
  rodada_n: "Rodada {0}",
  dano_dobro: "DANO EM DOBRO!",
  lute: "LUTE!",
  empate: "EMPATE!",
  voce_venceu_rodada: "VOCÊ VENCEU A RODADA!",
  bot_venceu_rodada: "O BOT VENCEU A RODADA",
  jogador_venceu_rodada: "RODADA DO JOGADOR {0}!",
  voce_venceu: "VOCÊ VENCEU!",
  bot_venceu: "O BOT VENCEU",
  jogador_venceu: "JOGADOR {0} VENCEU!",
  queda: "QUEDA DE BRAÇO!",
  queda_sub: "O tempo acabou! Quem clicar mais rápido vence",
  queda_dica_bot: "CLIQUE / ESPAÇO!",
  queda_dica_toque: "TOQUE NA TELA!",
  queda_dica_p1: "APERTE F!",
  queda_dica_p2: "APERTE L!",
  queda_dica_toque_esq: "TOQUE NA ESQUERDA!",
  queda_dica_toque_dir: "TOQUE NA DIREITA!",
  toque_mover: "andar",
  toque_tiro: "ATIRAR",
  pegou_arma: "{0}!",
  mesmo_aparelho: "No mesmo aparelho · não é online",
  qualidade_auto: "Gráficos: automático",
  qualidade_alta: "Gráficos: altos",
  qualidade_leve: "Gráficos: leves",
  perfeito: "PERFEITO!",
  missoes: "Missões",
  skins: "Skins",
  opcoes: "Opções",
  controles: "Controles",
  controles_mouse: "Jogador 1 também mira com o MOUSE (clique atira). Clique numa tecla e aperte a nova.",
  teclas_padrao: "Teclas padrão",
  semana: "Semana",
  conquistas: "Conquistas",
  skins_corpo: "Bolinha",
  skins_acessorio: "Acessório",
  dobrar_moedas: "Dobrar moedas",
  resgatar: "Resgatar",
  trocar: "Trocar",
  missoes_explica: "Complete missões para ganhar moedas. Dá para trocar 1 missão por dia.",
  semana_termina: "Termina em {0}d {1}h",
  premio_semana: "Prêmio da semana: complete os 4 desafios",
  equipado: "Equipado",
  equipar: "Equipar",
  so_semanal: "Prêmio semanal",
  acao_esquerda: "Esquerda",
  acao_direita: "Direita",
  acao_pulo: "Pular",
  acao_baixo: "Descer",
  acao_tiro: "Atirar",
  tecla_espaco: "Espaço",
  toque_mira: "MIRAR",
  dica_bot_v2: "{0} andar · {1} pular\nMouse: mira e atira (ou {2})",
  dica_2p_v2: "Jogador 1: {0}\nJogador 2: {1}\nNo mesmo teclado!",
  aviso_missao: "Missão concluída!",
  aviso_desafio: "Desafio da semana concluído!",
  aviso_conquista: "Conquista: {0}!",
  nivel_bot: "🤖 Bot nível {0}",
  nivel_curto: "Nv. {0}",
  bot_subiu: "Bot subiu para o nível {0}!",
  bot_desceu: "Bot desceu para o nível {0}",
  nivel_jogador: "Nível {0}",
  subiu_nivel: "Subiu para o nível {0}!",
  abrir_bau: "Abrir baú",
  abrir_bau_nivel: "Abrir baú de nível!",
  outro_bau: "Abrir outro baú",
  revanche: "REVANCHE",
  premio_skin: "Skin nova: {0}!",
  diaria: "Recompensa diária",
  diaria_explica: "Volte todo dia: a recompensa cresce! Faltar um dia volta para o começo.",
  dia_n: "Dia {0}",
  bau: "baú",
  bau_lendario: "baú lendário",
  pegar: "Pegar",
  fechar: "Fechar",
  sobrevivencia: "Sobrevivência",
  sobrevivencia_dica: "Ondas de bots cada vez mais fortes.\nAté onde você chega?",
  onda_n: "ONDA {0}",
  onda_concluida: "ONDA {0} VENCIDA!",
  fim_sobrevivencia: "Você chegou à onda {0}!",
  recorde_onda: "Recorde: onda {0}",
  novo_recorde: "NOVO RECORDE!",
  continuar_vida: "Assista um anúncio e continue na mesma onda com a vida cheia.",
  dica_bot_v3: "{0} andar · {1} pular\nMouse: mirar · Clique ou {2}: atirar",
  dica_2p_v3: "Jogador 1: {0} + mouse\nJogador 2: {1}\nNo mesmo teclado!",
  queda_clique: "CLIQUE OU {0}!",
  queda_aperte: "APERTE {0}!",
  toque_pulo: "PULAR",
  estilo_agressivo: "Agressivo",
  estilo_atirador: "Atirador",
  estilo_saltitante: "Saltitante",
  estilo_cauteloso: "Cauteloso",
  estilo_colecionador: "Colecionador",
  c_campo: "Campo",
  r_campo: "Clássico: só lutar!",
  c_gelo: "Geleira",
  r_gelo: "Gelo: tudo escorrega!",
  c_lua: "Lua",
  r_lua: "Pouca gravidade: pulos gigantes",
  c_vulcao: "Vulcão",
  r_vulcao: "A lava sobe e desce: fique no alto!",
  c_espaco: "Espaço",
  r_espaco: "Quase sem gravidade: pule para voar",
  c_laboratorio: "Laboratório",
  r_laboratorio: "A gravidade vira de cabeça para baixo!",
  c_dojo: "Dojô",
  r_dojo: "Sumô: empurre o oponente para fora!",
  c_cidade: "Cidade Neon",
  r_cidade: "Cuidado com o vão entre os prédios!",
  c_fliperama: "Fliperama",
  r_fliperama: "Bumpers jogam você longe!",
  c_floresta: "Floresta Noturna",
  r_floresta: "No escuro: só se vê perto da luz",
  c_deserto: "Deserto",
  r_deserto: "Vento forte muda de lado!",
  c_fabrica: "Fábrica",
  r_fabrica: "Esteiras levam você junto!",
  c_oceano: "Fundo do Mar",
  r_oceano: "Embaixo d'água: pule para nadar",
  c_templo: "Templo",
  r_templo: "Saia de um lado, volte pelo outro. Portais!",
  c_castelo: "Castelo",
  r_castelo: "Chuva de meteoros: fuja dos alvos!",
  k_escudo: "Escudo",
  kd_escudo: "Segura 40 de dano",
  k_rapidez: "Rapidez",
  kd_rapidez: "Mais rápido por 7 s",
  k_cura: "Cura",
  kd_cura: "+35 de vida",
  k_furia: "Fúria",
  kd_furia: "Dano em dobro por 6 s",
  k_tiro_duplo: "Tiro Duplo",
  kd_tiro_duplo: "Cada tiro sai em dobro",
  k_mini: "Mini",
  kd_mini: "Pequeno e difícil de acertar",
  k_congelar: "Congelar",
  kd_congelar: "Congela o oponente",
  k_fantasma: "Fantasma",
  kd_fantasma: "Quase invisível por 5 s",
  k_reflexo: "Reflexo",
  kd_reflexo: "Devolve os tiros por 5 s",
  k_super_pulo: "Super Pulo",
  kd_super_pulo: "Pulo triplo e mais alto",
  k_chuva: "Chuva de Meteoros",
  kd_chuva: "5 meteoros no oponente",
  k_municao: "Munição Infinita",
  kd_municao: "Sem gastar munição por 8 s",
  a_estilingue: "Estilingue",
  a_pistola: "Pistola",
  a_revolver: "Revólver",
  a_submetralhadora: "Submetralhadora",
  a_minigun: "Minigun",
  a_escopeta: "Escopeta",
  a_escopeta_dupla: "Escopeta Dupla",
  a_rifle: "Rifle",
  a_sniper: "Sniper",
  a_plasma: "Plasma",
  a_pula_pula: "Bola Pula-Pula",
  a_confete: "Canhão de Confete",
  a_arma_agua: "Arma de Água",
  a_zarabatana: "Zarabatana",
  a_onda_sonora: "Onda Sonora",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerangue",
  a_arco: "Arco",
  a_arco_triplo: "Arco Triplo",
  a_besta: "Besta",
  a_serra: "Serra Giratória",
  a_bola_neve: "Bola de Neve",
  a_gancho: "Gancho",
  a_bazuca: "Bazuca",
  a_lanca_granadas: "Lança-Granadas",
  a_granada: "Granada",
  a_dinamite: "Dinamite",
  a_fragmentacao: "Granada de Fragmentação",
  a_canhao: "Canhão",
  a_mini_misseis: "Mini Mísseis",
  a_missil: "Míssil Teleguiado",
  a_abelhas: "Enxame de Abelhas",
  a_bola_fogo: "Bola de Fogo",
  a_granada_gelo: "Granada de Gelo",
  a_mina: "Mina",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Arco-Íris",
  a_feixe: "Raio Contínuo",
  a_tesla: "Tesla",
  a_raio_gelo: "Raio de Gelo",
  a_bolhas: "Arma de Bolhas",
  a_buraco_negro: "Buraco Negro",
  a_lanca_chamas: "Lança-Chamas",
  a_soprador: "Soprador",
  a_martelo: "Martelo",
  a_espada: "Espada",
  a_luva_boxe: "Luva de Boxe",
  a_meteoro: "Meteoros",
  a_relampago: "Relâmpago",
  mi_vitorias: "Vença {0} partida(s) contra o bot",
  mi_rodadas: "Vença {0} rodadas",
  mi_dano: "Cause {0} de dano",
  mi_quedas: "Vença {0} queda(s) de braço",
  mi_cartas: "Pegue {0} cartas",
  mi_caixas: "Pegue {0} caixas de arma",
  mi_abatesExpl: "Vença {0} rodada(s) com explosivos",
  mi_abatesMelee: "Vença {0} rodada(s) no corpo a corpo",
  mi_perfeitas: "Vença {0} rodada(s) sem levar dano",
  mi_partidas: "Jogue {0} partidas",
  mi_partidas2p: "Jogue {0} partida(s) de 2 jogadores",
  mi_rodadaCenario: "Vença {0} rodada(s) em: {1}",
  de_s_vitorias: "Vença {0} partida(s) contra o bot",
  de_s_rodadas: "Vença {0} rodadas",
  de_s_dano: "Cause {0} de dano",
  de_s_quedas: "Vença {0} queda(s) de braço",
  de_s_cenarios: "Vença rodadas em {0} cenários diferentes",
  de_s_5x0: "Vença uma partida por 3 – 0",
  de_s_expl: "Vença {0} rodada(s) com explosivos",
  de_s_cartas: "Pegue {0} cartas",
  de_s_perfeitas: "Vença {0} rodada(s) sem levar dano",
  de_s_virada: "Vire uma partida perdendo por 2 pontos",
  co_primeira_vitoria: "Primeira Vitória",
  cod_primeira_vitoria: "Vença {0} partida(s) contra o bot",
  co_vitorias_10: "Duelista",
  cod_vitorias_10: "Vença {0} partida(s) contra o bot",
  co_vitorias_25: "Veterano",
  cod_vitorias_25: "Vença {0} partida(s) contra o bot",
  co_vitorias_100: "Lenda",
  cod_vitorias_100: "Vença {0} partida(s) contra o bot",
  co_partidas_50: "Viciado",
  cod_partidas_50: "Jogue {0} partidas",
  co_rodadas_50: "Vencedor de Rodadas",
  cod_rodadas_50: "Vença {0} rodadas",
  co_rodadas_250: "Máquina",
  cod_rodadas_250: "Vença {0} rodadas",
  co_dano_20000: "Destruidor",
  cod_dano_20000: "Cause {0} de dano",
  co_dano_100000: "Apocalipse",
  cod_dano_100000: "Cause {0} de dano",
  co_quedas_5: "Braço Forte",
  cod_quedas_5: "Vença {0} queda(s) de braço",
  co_quedas_20: "Campeão de Braço",
  cod_quedas_20: "Vença {0} queda(s) de braço",
  co_explosivos_50: "Demolidor",
  cod_explosivos_50: "Vença {0} rodada(s) com explosivos",
  co_melee_20: "Lutador",
  cod_melee_20: "Vença {0} rodada(s) no corpo a corpo",
  co_perfeitas_10: "Intocável",
  cod_perfeitas_10: "Vença {0} rodada(s) sem levar dano",
  co_cenarios_todos: "Explorador",
  cod_cenarios_todos: "Vença rodadas em {0} cenários diferentes",
  co_armas_25: "Colecionador",
  cod_armas_25: "Pegue {0} armas diferentes",
  co_armas_todas: "Arsenal Completo",
  cod_armas_todas: "Pegue {0} armas diferentes",
  co_cartas_todas: "Baralho Completo",
  cod_cartas_todas: "Pegue as {0} cartas diferentes",
  co_placar_5x0: "Massacre",
  cod_placar_5x0: "Vença uma partida por 3 – 0",
  co_virada: "Virada Épica",
  cod_virada: "Vire uma partida perdendo por 2 pontos",
  co_bot_mestre: "Mestre do Bot",
  cod_bot_mestre: "Vença o bot no nível máximo",
  co_dois_jogadores_10: "Melhores Amigos",
  cod_dois_jogadores_10: "Jogue {0} partida(s) de 2 jogadores",
  co_missoes_10: "Dedicado",
  cod_missoes_10: "Resgate {0} missões",
  co_missoes_50: "Incansável",
  cod_missoes_50: "Resgate {0} missões",
  co_semana_completa: "Semana Perfeita",
  cod_semana_completa: "Complete todos os desafios de uma semana",
  co_onda_5: "Sobrevivente",
  cod_onda_5: "Chegue à onda {0} na Sobrevivência",
  co_onda_10: "Imparável",
  cod_onda_10: "Chegue à onda {0} na Sobrevivência",
  sk_classico: "Clássica",
  sk_listras: "Listras",
  sk_pintas: "Pintas",
  sk_xadrez: "Xadrez",
  sk_camuflado: "Camuflada",
  sk_futebol: "Bola de Futebol",
  sk_melancia: "Melancia",
  sk_robo: "Robô",
  sk_doce: "Bala Doce",
  sk_cromado: "Cromada",
  sk_gelo: "Cristal de Gelo",
  sk_neon: "Neon",
  sk_lava: "Lava",
  sk_diamante: "Diamante",
  sk_galaxia: "Galáxia",
  sk_ouro: "Ouro",
  sk_nenhum: "Nenhum",
  sk_bone: "Boné",
  sk_oculos: "Óculos Escuros",
  sk_orelhas_gato: "Orelhas de Gato",
  sk_fone: "Fone",
  sk_cartola: "Cartola",
  sk_chifres: "Chifres",
  sk_tiara_flores: "Tiara de Flores",
  sk_mascara_ninja: "Faixa Ninja",
  sk_viking: "Capacete Viking",
  sk_cowboy: "Chapéu de Caubói",
  sk_antena: "Antena Alien",
  sk_aureola: "Auréola",
  sk_coroa: "Coroa",
  novo: "NOVO!",
  proximo_rival: "PRÓXIMO RIVAL",
  premio_equipado: "{0} equipado!",
  modo_rivais: "Rivais",
  rivais_dica: "Vença 10 rivais e suba de liga",
  rival_n: "RIVAL {0}/{1}",
  liga_0: "Bronze",
  liga_1: "Prata",
  liga_2: "Ouro",
  liga_3: "Diamante",
  liga_4: "Mestre",
  liga_n: "Liga {0}",
  rival_derrotado: "{0} derrotado!",
  proximo: "Próximo: {0}",
  revanche_contra: "Revanche contra {0}",
  campeao_liga: "CAMPEÃO DA LIGA {0}!",
  rival_venceu: "{0} venceu!",
  venca_ganhe: "Vença e ganhe: {0}",
  salvo: "SALVO!",
  melhorar: "Melhorar",
  poder_explica: "Fique mais forte contra o bot e os rivais. No modo 2 jogadores, os dois são iguais.",
  poder_n: "⚡ PODER {0}",
  poder_dica: "Melhore e volte mais forte!",
  poder_gaste: "Use suas moedas: fique mais forte!",
  mel_forca: "Força",
  mel_vida: "Vida",
  mel_veloc: "Velocidade",
  mel_nivel: "Nv {0}",
  mel_max: "MÁX",
  mel_d_forca: "Bate mais forte",
  mel_d_vida: "Aguenta mais",
  mel_d_veloc: "Corre mais"
};
