"use strict";
TEXTOS.ro = {
  titulo: "Duelul Bilelor",
  jogar: "JOACĂ",
  idioma: "Limbă",
  som_on: "Sunet: pornit",
  som_off: "Sunet: oprit",
  voltar: "Înapoi",
  pausado: "Pauză",
  continuar: "Continuă",
  menu: "Meniu",
  anuncio_falhou: "Reclama nu s-a încărcat. Încearcă mai târziu.",
  escolha_modo: "Cum vrei să joci?",
  contra_bot: "Contra botului",
  dois_jogadores: "2 jucători",
  dica_bot_teclado: "A D / ← → mergi\nW / ↑ sari\nF / Spațiu / L trage",
  dica_bot_toque: "Stânga: trage ca să mergi și să sari\nDreapta: ține apăsat ca să tragi",
  dica_2p_teclado: "Jucătorul 1: A D W + F\nJucătorul 2: ← → ↑ + L\nPe aceeași tastatură!",
  dica_2p_toque: "Fiecare folosește jumătatea lui de ecran",
  lendaria: "Meci Legendar",
  lendaria_anuncio: "Meci Legendar: doar arme rare (reclamă)",
  lendaria_ativada: "Meci Legendar activat! Alege modul",
  continuar_anuncio: "▶ Continuă",
  continuar_explica: "Urmărește o reclamă și meciul continuă: botul pierde ultimul punct.",
  nao_obrigado: "Nu, mulțumesc",
  voce: "TU",
  voce_curto: "TU",
  bot: "BOT",
  jogador_n: "JUCĂTOR {0}",
  rodada_n: "Runda {0}",
  dano_dobro: "DAUNE DUBLE!",
  lute: "LUPTĂ!",
  empate: "EGALITATE!",
  voce_venceu_rodada: "AI CÂȘTIGAT RUNDA!",
  bot_venceu_rodada: "BOTUL CÂȘTIGĂ RUNDA",
  jogador_venceu_rodada: "RUNDA PENTRU JUCĂTORUL {0}!",
  voce_venceu: "AI CÂȘTIGAT!",
  bot_venceu: "BOTUL CÂȘTIGĂ",
  jogador_venceu: "CÂȘTIGĂ JUCĂTORUL {0}!",
  queda: "SKANDENBERG!",
  queda_sub: "Timpul a expirat! Câștigă cine apasă mai repede",
  queda_dica_bot: "CLICK / SPAȚIU!",
  queda_dica_toque: "ATINGE ECRANUL!",
  queda_dica_p1: "APASĂ F!",
  queda_dica_p2: "APASĂ L!",
  queda_dica_toque_esq: "ATINGE ÎN STÂNGA!",
  queda_dica_toque_dir: "ATINGE ÎN DREAPTA!",
  toque_mover: "mergi",
  toque_tiro: "TRAGE",
  pegou_arma: "{0}!",
  c_campo: "Pajiște",
  r_campo: "Clasic: doar luptă!",
  c_gelo: "Ghețar",
  r_gelo: "Gheață: totul alunecă!",
  c_lua: "Luna",
  r_lua: "Gravitație mică: sărituri uriașe",
  c_vulcao: "Vulcan",
  r_vulcao: "Lava urcă și coboară: stai sus!",
  c_espaco: "Spațiu",
  r_espaco: "Aproape fără gravitație: sari ca să zbori",
  c_laboratorio: "Laborator",
  r_laboratorio: "Gravitația se inversează!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: împinge adversarul afară!",
  c_cidade: "Orașul Neon",
  r_cidade: "Atenție la golul dintre clădiri!",
  c_fliperama: "Pinball",
  r_fliperama: "Bumperele te aruncă departe!",
  c_floresta: "Pădurea de Noapte",
  r_floresta: "În întuneric: vezi doar lângă lumină",
  c_deserto: "Deșert",
  r_deserto: "Vântul puternic schimbă direcția!",
  c_fabrica: "Fabrică",
  r_fabrica: "Benzile rulante te duc!",
  c_oceano: "Adâncul Mării",
  r_oceano: "Sub apă: sari ca să înoți",
  c_templo: "Templu",
  r_templo: "Ieși pe o parte, intri pe cealaltă. Portaluri!",
  c_castelo: "Castel",
  r_castelo: "Ploaie de meteoriți: evită țintele!",
  k_escudo: "Scut",
  kd_escudo: "Blochează 40 daune",
  k_rapidez: "Viteză",
  kd_rapidez: "Mai rapid 7 s",
  k_cura: "Vindecare",
  kd_cura: "+35 viață",
  k_furia: "Furie",
  kd_furia: "Daune duble 6 s",
  k_tiro_duplo: "Foc Dublu",
  kd_tiro_duplo: "Fiecare foc e dublu",
  k_mini: "Mini",
  kd_mini: "Mic și greu de lovit",
  k_congelar: "Înghețare",
  kd_congelar: "Îngheață adversarul",
  k_fantasma: "Fantomă",
  kd_fantasma: "Aproape invizibil 5 s",
  k_reflexo: "Reflexie",
  kd_reflexo: "Respinge focurile 5 s",
  k_super_pulo: "Super Săritură",
  kd_super_pulo: "Săritură triplă și mai înaltă",
  k_chuva: "Ploaie de Meteoriți",
  kd_chuva: "5 meteoriți pe adversar",
  k_municao: "Muniție Infinită",
  kd_municao: "Fără consum de muniție 8 s",
  a_estilingue: "Praștie",
  a_pistola: "Pistol",
  a_revolver: "Revolver",
  a_submetralhadora: "Pistol-mitralieră",
  a_minigun: "Minigun",
  a_escopeta: "Pușcă cu alice",
  a_escopeta_dupla: "Pușcă dublă",
  a_rifle: "Pușcă",
  a_sniper: "Lunetă",
  a_plasma: "Plasmă",
  a_pula_pula: "Minge Săltăreață",
  a_confete: "Tun de Confetti",
  a_arma_agua: "Pistol cu Apă",
  a_zarabatana: "Sarbacană",
  a_onda_sonora: "Undă Sonoră",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Arc",
  a_arco_triplo: "Arc Triplu",
  a_besta: "Arbaletă",
  a_serra: "Ferăstrău",
  a_bola_neve: "Bulgăre",
  a_gancho: "Cârlig",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Aruncător de Grenade",
  a_granada: "Grenadă",
  a_dinamite: "Dinamită",
  a_fragmentacao: "Grenadă cu Fragmentare",
  a_canhao: "Tun",
  a_mini_misseis: "Mini Rachete",
  a_missil: "Rachetă Ghidată",
  a_abelhas: "Roi de Albine",
  a_bola_fogo: "Minge de Foc",
  a_granada_gelo: "Grenadă de Gheață",
  a_mina: "Mină",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Curcubeu",
  a_feixe: "Rază Continuă",
  a_tesla: "Tesla",
  a_raio_gelo: "Rază de Gheață",
  a_bolhas: "Pistol cu Bule",
  a_buraco_negro: "Gaură Neagră",
  a_lanca_chamas: "Aruncător de Flăcări",
  a_soprador: "Suflantă",
  a_martelo: "Ciocan",
  a_espada: "Sabie",
  a_luva_boxe: "Mănușă de Box",
  a_meteoro: "Meteoriți",
  a_relampago: "Fulger"
};
