"use strict";
TEXTOS.ro = {
  titulo: "Crazy Balls Duel",
  jogar: "JOACĂ",
  idioma: "Limbă",
  som_on: "Sunet: pornit",
  som_off: "Sunet: oprit",
  voltar: "Înapoi",
  pausado: "Pauză",
  continuar: "Continuă",
  menu: "Meniu",
  anuncio_falhou: "Reclama nu s-a încărcat. Încearcă mai târziu.",
  escolha_modo: "Cum vrei să joci?",
  contra_bot: "Contra botului",
  dois_jogadores: "2 jucători",
  dica_bot_teclado: "A D / ← → mergi\nW / ↑ sari\nF / Spațiu / L trage",
  dica_bot_toque: "Stânga: trage ca să mergi și să sari\nDreapta: trage ca să țintești și să tragi",
  dica_2p_teclado: "Jucătorul 1: A D W + F\nJucătorul 2: ← → ↑ + L\nPe aceeași tastatură!",
  dica_2p_toque: "Fiecare folosește jumătatea lui de ecran",
  lendaria: "Meci Legendar",
  lendaria_anuncio: "Meci Legendar: doar arme rare (reclamă)",
  lendaria_ativada: "Meci Legendar activat! Alege modul",
  continuar_anuncio: "▶ Continuă",
  continuar_explica: "Urmărește o reclamă și meciul continuă: botul pierde ultimul punct.",
  nao_obrigado: "Nu, mulțumesc",
  voce: "TU",
  voce_curto: "TU",
  bot: "BOT",
  jogador_n: "JUCĂTOR {0}",
  rodada_n: "Runda {0}",
  dano_dobro: "DAUNE DUBLE!",
  lute: "LUPTĂ!",
  empate: "EGALITATE!",
  voce_venceu_rodada: "AI CÂȘTIGAT RUNDA!",
  bot_venceu_rodada: "BOTUL CÂȘTIGĂ RUNDA",
  jogador_venceu_rodada: "RUNDA PENTRU JUCĂTORUL {0}!",
  voce_venceu: "AI CÂȘTIGAT!",
  bot_venceu: "BOTUL CÂȘTIGĂ",
  jogador_venceu: "CÂȘTIGĂ JUCĂTORUL {0}!",
  queda: "SKANDENBERG!",
  queda_sub: "Timpul a expirat! Câștigă cine apasă mai repede",
  queda_dica_bot: "CLICK / SPAȚIU!",
  queda_dica_toque: "ATINGE ECRANUL!",
  queda_dica_p1: "APASĂ F!",
  queda_dica_p2: "APASĂ L!",
  queda_dica_toque_esq: "ATINGE ÎN STÂNGA!",
  queda_dica_toque_dir: "ATINGE ÎN DREAPTA!",
  toque_mover: "mergi",
  toque_tiro: "TRAGE",
  pegou_arma: "{0}!",
  missoes: "Misiuni",
  skins: "Skinuri",
  opcoes: "Opțiuni",
  controles: "Controale",
  controles_mouse: "Jucătorul 1 țintește și cu MOUSE-ul (click trage). Apasă o tastă, apoi pe cea nouă.",
  teclas_padrao: "Taste implicite",
  semana: "Săptămâna",
  conquistas: "Realizări",
  skins_corpo: "Bilă",
  skins_acessorio: "Accesoriu",
  dobrar_moedas: "Dublează monedele",
  resgatar: "Revendică",
  trocar: "Schimbă",
  missoes_explica: "Termină misiuni ca să câștigi monede. Poți schimba 1 misiune pe zi.",
  semana_termina: "Se termină în {0}z {1}h",
  premio_semana: "Premiul săptămânii: termină cele 4 provocări",
  equipado: "Echipat",
  equipar: "Echipează",
  so_semanal: "Premiu săptămânal",
  acao_esquerda: "Stânga",
  acao_direita: "Dreapta",
  acao_pulo: "Sari",
  acao_baixo: "Coboară",
  acao_tiro: "Trage",
  tecla_espaco: "Spațiu",
  toque_mira: "ȚINTEȘTE",
  dica_bot_v2: "{0} mergi · {1} sari\nMouse: țintește și trage (sau {2})",
  dica_2p_v2: "Jucătorul 1: {0}\nJucătorul 2: {1}\nPe aceeași tastatură!",
  aviso_missao: "Misiune îndeplinită!",
  aviso_desafio: "Provocare săptămânală îndeplinită!",
  aviso_conquista: "Realizare: {0}!",
  nivel_bot: "🤖 Bot nivelul {0}",
  nivel_curto: "Nv. {0}",
  bot_subiu: "Botul a urcat la nivelul {0}!",
  bot_desceu: "Botul a coborât la nivelul {0}",
  c_campo: "Pajiște",
  r_campo: "Clasic: doar luptă!",
  c_gelo: "Ghețar",
  r_gelo: "Gheață: totul alunecă!",
  c_lua: "Luna",
  r_lua: "Gravitație mică: sărituri uriașe",
  c_vulcao: "Vulcan",
  r_vulcao: "Lava urcă și coboară: stai sus!",
  c_espaco: "Spațiu",
  r_espaco: "Aproape fără gravitație: sari ca să zbori",
  c_laboratorio: "Laborator",
  r_laboratorio: "Gravitația se inversează!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: împinge adversarul afară!",
  c_cidade: "Orașul Neon",
  r_cidade: "Atenție la golul dintre clădiri!",
  c_fliperama: "Pinball",
  r_fliperama: "Bumperele te aruncă departe!",
  c_floresta: "Pădurea de Noapte",
  r_floresta: "În întuneric: vezi doar lângă lumină",
  c_deserto: "Deșert",
  r_deserto: "Vântul puternic schimbă direcția!",
  c_fabrica: "Fabrică",
  r_fabrica: "Benzile rulante te duc!",
  c_oceano: "Adâncul Mării",
  r_oceano: "Sub apă: sari ca să înoți",
  c_templo: "Templu",
  r_templo: "Ieși pe o parte, intri pe cealaltă. Portaluri!",
  c_castelo: "Castel",
  r_castelo: "Ploaie de meteoriți: evită țintele!",
  k_escudo: "Scut",
  kd_escudo: "Blochează 40 daune",
  k_rapidez: "Viteză",
  kd_rapidez: "Mai rapid 7 s",
  k_cura: "Vindecare",
  kd_cura: "+35 viață",
  k_furia: "Furie",
  kd_furia: "Daune duble 6 s",
  k_tiro_duplo: "Foc Dublu",
  kd_tiro_duplo: "Fiecare foc e dublu",
  k_mini: "Mini",
  kd_mini: "Mic și greu de lovit",
  k_congelar: "Înghețare",
  kd_congelar: "Îngheață adversarul",
  k_fantasma: "Fantomă",
  kd_fantasma: "Aproape invizibil 5 s",
  k_reflexo: "Reflexie",
  kd_reflexo: "Respinge focurile 5 s",
  k_super_pulo: "Super Săritură",
  kd_super_pulo: "Săritură triplă și mai înaltă",
  k_chuva: "Ploaie de Meteoriți",
  kd_chuva: "5 meteoriți pe adversar",
  k_municao: "Muniție Infinită",
  kd_municao: "Fără consum de muniție 8 s",
  a_estilingue: "Praștie",
  a_pistola: "Pistol",
  a_revolver: "Revolver",
  a_submetralhadora: "Pistol-mitralieră",
  a_minigun: "Minigun",
  a_escopeta: "Pușcă cu alice",
  a_escopeta_dupla: "Pușcă dublă",
  a_rifle: "Pușcă",
  a_sniper: "Lunetă",
  a_plasma: "Plasmă",
  a_pula_pula: "Minge Săltăreață",
  a_confete: "Tun de Confetti",
  a_arma_agua: "Pistol cu Apă",
  a_zarabatana: "Sarbacană",
  a_onda_sonora: "Undă Sonoră",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Arc",
  a_arco_triplo: "Arc Triplu",
  a_besta: "Arbaletă",
  a_serra: "Ferăstrău",
  a_bola_neve: "Bulgăre",
  a_gancho: "Cârlig",
  a_bazuca: "Bazooka",
  a_lanca_granadas: "Aruncător de Grenade",
  a_granada: "Grenadă",
  a_dinamite: "Dinamită",
  a_fragmentacao: "Grenadă cu Fragmentare",
  a_canhao: "Tun",
  a_mini_misseis: "Mini Rachete",
  a_missil: "Rachetă Ghidată",
  a_abelhas: "Roi de Albine",
  a_bola_fogo: "Minge de Foc",
  a_granada_gelo: "Grenadă de Gheață",
  a_mina: "Mină",
  a_laser: "Laser",
  a_railgun: "Railgun",
  a_arco_iris: "Laser Curcubeu",
  a_feixe: "Rază Continuă",
  a_tesla: "Tesla",
  a_raio_gelo: "Rază de Gheață",
  a_bolhas: "Pistol cu Bule",
  a_buraco_negro: "Gaură Neagră",
  a_lanca_chamas: "Aruncător de Flăcări",
  a_soprador: "Suflantă",
  a_martelo: "Ciocan",
  a_espada: "Sabie",
  a_luva_boxe: "Mănușă de Box",
  a_meteoro: "Meteoriți",
  a_relampago: "Fulger",
  mi_vitorias: "Câștigă {0} meci(uri) contra botului",
  mi_rodadas: "Câștigă {0} runde",
  mi_dano: "Provoacă {0} daune",
  mi_quedas: "Câștigă {0} skandenberg",
  mi_cartas: "Ia {0} cărți",
  mi_caixas: "Ia {0} lăzi cu arme",
  mi_abatesExpl: "Câștigă {0} rundă(e) cu explozibili",
  mi_abatesMelee: "Câștigă {0} rundă(e) corp la corp",
  mi_perfeitas: "Câștigă {0} rundă(e) fără să fii lovit",
  mi_partidas: "Joacă {0} meciuri",
  mi_partidas2p: "Joacă {0} meci(uri) în 2",
  mi_rodadaCenario: "Câștigă {0} rundă(e) în: {1}",
  de_s_vitorias: "Câștigă {0} meci(uri) contra botului",
  de_s_rodadas: "Câștigă {0} runde",
  de_s_dano: "Provoacă {0} daune",
  de_s_quedas: "Câștigă {0} skandenberg",
  de_s_cenarios: "Câștigă runde în {0} arene diferite",
  de_s_5x0: "Câștigă un meci cu 5 – 0",
  de_s_expl: "Câștigă {0} rundă(e) cu explozibili",
  de_s_cartas: "Ia {0} cărți",
  de_s_perfeitas: "Câștigă {0} rundă(e) fără să fii lovit",
  de_s_virada: "Câștigă revenind de la 3 puncte în urmă",
  co_primeira_vitoria: "Prima Victorie",
  cod_primeira_vitoria: "Câștigă {0} meci(uri) contra botului",
  co_vitorias_10: "Duelist",
  cod_vitorias_10: "Câștigă {0} meci(uri) contra botului",
  co_vitorias_25: "Veteran",
  cod_vitorias_25: "Câștigă {0} meci(uri) contra botului",
  co_vitorias_100: "Legendă",
  cod_vitorias_100: "Câștigă {0} meci(uri) contra botului",
  co_partidas_50: "Dependent",
  cod_partidas_50: "Joacă {0} meciuri",
  co_rodadas_50: "Câștigător de Runde",
  cod_rodadas_50: "Câștigă {0} runde",
  co_rodadas_250: "Mașinărie",
  cod_rodadas_250: "Câștigă {0} runde",
  co_dano_20000: "Distrugător",
  cod_dano_20000: "Provoacă {0} daune",
  co_dano_100000: "Apocalipsă",
  cod_dano_100000: "Provoacă {0} daune",
  co_quedas_5: "Braț Puternic",
  cod_quedas_5: "Câștigă {0} skandenberg",
  co_quedas_20: "Campion la Skandenberg",
  cod_quedas_20: "Câștigă {0} skandenberg",
  co_explosivos_50: "Demolator",
  cod_explosivos_50: "Câștigă {0} rundă(e) cu explozibili",
  co_melee_20: "Bătăuș",
  cod_melee_20: "Câștigă {0} rundă(e) corp la corp",
  co_perfeitas_10: "Intangibil",
  cod_perfeitas_10: "Câștigă {0} rundă(e) fără să fii lovit",
  co_cenarios_todos: "Explorator",
  cod_cenarios_todos: "Câștigă runde în {0} arene diferite",
  co_armas_25: "Colecționar",
  cod_armas_25: "Ia {0} arme diferite",
  co_armas_todas: "Arsenal Complet",
  cod_armas_todas: "Ia {0} arme diferite",
  co_cartas_todas: "Pachet Complet",
  cod_cartas_todas: "Ia toate cele {0} cărți",
  co_placar_5x0: "Măcel",
  cod_placar_5x0: "Câștigă un meci cu 5 – 0",
  co_virada: "Revenire Epică",
  cod_virada: "Câștigă revenind de la 3 puncte în urmă",
  co_bot_mestre: "Maestrul Botului",
  cod_bot_mestre: "Învinge botul la nivelul maxim",
  co_dois_jogadores_10: "Cei Mai Buni Prieteni",
  cod_dois_jogadores_10: "Joacă {0} meci(uri) în 2",
  co_missoes_10: "Dedicat",
  cod_missoes_10: "Revendică {0} misiuni",
  co_missoes_50: "Neobosit",
  cod_missoes_50: "Revendică {0} misiuni",
  co_semana_completa: "Săptămână Perfectă",
  cod_semana_completa: "Termină toate provocările unei săptămâni",
  sk_classico: "Clasică",
  sk_listras: "Dungi",
  sk_pintas: "Buline",
  sk_xadrez: "Carouri",
  sk_camuflado: "Camuflaj",
  sk_futebol: "Minge de Fotbal",
  sk_melancia: "Pepene",
  sk_robo: "Robot",
  sk_doce: "Bomboană",
  sk_cromado: "Cromată",
  sk_gelo: "Cristal de Gheață",
  sk_neon: "Neon",
  sk_lava: "Lavă",
  sk_diamante: "Diamant",
  sk_galaxia: "Galaxie",
  sk_ouro: "Aur",
  sk_nenhum: "Niciunul",
  sk_bone: "Șapcă",
  sk_oculos: "Ochelari de Soare",
  sk_orelhas_gato: "Urechi de Pisică",
  sk_fone: "Căști",
  sk_cartola: "Joben",
  sk_chifres: "Coarne",
  sk_tiara_flores: "Coroniță de Flori",
  sk_mascara_ninja: "Mască Ninja",
  sk_viking: "Coif Viking",
  sk_cowboy: "Pălărie de Cowboy",
  sk_antena: "Antenă Extraterestră",
  sk_aureola: "Aureolă",
  sk_coroa: "Coroană"
};
