"use strict";
TEXTOS.ru = {
  titulo: "Crazy Balls Duel",
  jogar: "ИГРАТЬ",
  idioma: "Язык",
  som_on: "Звук: вкл.",
  som_off: "Звук: выкл.",
  voltar: "Назад",
  pausado: "Пауза",
  continuar: "Продолжить",
  menu: "Меню",
  anuncio_falhou: "Реклама не загрузилась. Попробуйте позже.",
  escolha_modo: "Как будете играть?",
  contra_bot: "Против бота",
  dois_jogadores: "2 игрока",
  dica_bot_teclado: "A D / ← → идти\nW / ↑ прыжок\nF / Пробел / L огонь",
  dica_bot_toque: "Слева: ведите, чтобы идти\nСправа: вверху прыжок · внизу прицел и огонь",
  dica_2p_teclado: "Игрок 1: A D W + F\nИгрок 2: ← → ↑ + L\nНа одной клавиатуре!",
  dica_2p_toque: "Вдвоём на одном телефоне, горизонтально: у каждого своя половина экрана",
  lendaria: "Легендарный матч",
  lendaria_anuncio: "Легендарный матч: только редкое оружие (реклама)",
  lendaria_ativada: "Легендарный матч включён! Выберите режим",
  continuar_anuncio: "▶ Продолжить",
  continuar_explica: "Посмотрите рекламу — матч продолжится, а бот потеряет последнее очко.",
  nao_obrigado: "Нет, спасибо",
  voce: "ВЫ",
  voce_curto: "ВЫ",
  bot: "БОТ",
  jogador_n: "ИГРОК {0}",
  rodada_n: "Раунд {0}",
  dano_dobro: "ДВОЙНОЙ УРОН!",
  lute: "В БОЙ!",
  empate: "НИЧЬЯ!",
  voce_venceu_rodada: "РАУНД ВАШ!",
  bot_venceu_rodada: "РАУНД ЗА БОТОМ",
  jogador_venceu_rodada: "РАУНД ЗА ИГРОКОМ {0}!",
  voce_venceu: "ВЫ ПОБЕДИЛИ!",
  bot_venceu: "БОТ ПОБЕДИЛ",
  jogador_venceu: "ПОБЕДИЛ ИГРОК {0}!",
  queda: "АРМРЕСТЛИНГ!",
  queda_sub: "Время вышло! Побеждает тот, кто быстрее жмёт",
  queda_dica_bot: "КЛИК / ПРОБЕЛ!",
  queda_dica_toque: "ЖМИТЕ НА ЭКРАН!",
  queda_dica_p1: "ЖМИТЕ F!",
  queda_dica_p2: "ЖМИТЕ L!",
  queda_dica_toque_esq: "ЖМИТЕ СЛЕВА!",
  queda_dica_toque_dir: "ЖМИТЕ СПРАВА!",
  toque_mover: "идти",
  toque_tiro: "ОГОНЬ",
  pegou_arma: "{0}!",
  mesmo_aparelho: "На одном устройстве · не онлайн",
  qualidade_auto: "Графика: авто",
  qualidade_alta: "Графика: высокая",
  qualidade_leve: "Графика: лёгкая",
  perfeito: "ИДЕАЛЬНО!",
  missoes: "Задания",
  skins: "Скины",
  opcoes: "Настройки",
  controles: "Управление",
  controles_mouse: "Игрок 1 целится и МЫШЬЮ (клик — выстрел). Нажмите на клавишу, затем новую.",
  teclas_padrao: "По умолчанию",
  semana: "Неделя",
  conquistas: "Достижения",
  skins_corpo: "Шарик",
  skins_acessorio: "Аксессуар",
  dobrar_moedas: "Удвоить монеты",
  resgatar: "Забрать",
  trocar: "Сменить",
  missoes_explica: "Выполняйте задания за монеты. Можно сменить 1 задание в день.",
  semana_termina: "Закончится через {0}д {1}ч",
  premio_semana: "Приз недели: выполните все 4 испытания",
  equipado: "Надето",
  equipar: "Надеть",
  so_semanal: "Приз недели",
  acao_esquerda: "Влево",
  acao_direita: "Вправо",
  acao_pulo: "Прыжок",
  acao_baixo: "Вниз",
  acao_tiro: "Огонь",
  tecla_espaco: "Пробел",
  toque_mira: "ЦЕЛЬ",
  dica_bot_v2: "{0} идти · {1} прыжок\nМышь: цель и огонь (или {2})",
  dica_2p_v2: "Игрок 1: {0}\nИгрок 2: {1}\nНа одной клавиатуре!",
  aviso_missao: "Задание выполнено!",
  aviso_desafio: "Испытание недели выполнено!",
  aviso_conquista: "Достижение: {0}!",
  nivel_bot: "🤖 Бот, уровень {0}",
  nivel_curto: "Ур. {0}",
  bot_subiu: "Бот вырос до уровня {0}!",
  bot_desceu: "Бот опустился до уровня {0}",
  nivel_jogador: "Уровень {0}",
  subiu_nivel: "Новый уровень: {0}!",
  abrir_bau: "Открыть сундук",
  abrir_bau_nivel: "Открыть сундук уровня!",
  outro_bau: "Открыть ещё сундук",
  revanche: "РЕВАНШ",
  premio_skin: "Новый скин: {0}!",
  diaria: "Ежедневная награда",
  diaria_explica: "Заходите каждый день — награда растёт! Пропустите день — всё сначала.",
  dia_n: "День {0}",
  bau: "сундук",
  bau_lendario: "легендарный сундук",
  pegar: "Забрать",
  fechar: "Закрыть",
  sobrevivencia: "Выживание",
  sobrevivencia_dica: "Волны всё более сильных ботов.\nКак далеко вы зайдёте?",
  onda_n: "ВОЛНА {0}",
  onda_concluida: "ВОЛНА {0} ПРОЙДЕНА!",
  fim_sobrevivencia: "Вы дошли до волны {0}!",
  recorde_onda: "Рекорд: волна {0}",
  novo_recorde: "НОВЫЙ РЕКОРД!",
  continuar_vida: "Посмотрите рекламу и продолжите ту же волну с полным здоровьем.",
  dica_bot_v3: "{0} идти · {1} прыжок\nМышь: прицел · Клик или {2}: огонь",
  dica_2p_v3: "Игрок 1: {0} + мышь\nИгрок 2: {1}\nНа одной клавиатуре!",
  queda_clique: "КЛИК ИЛИ {0}!",
  queda_aperte: "ЖМИТЕ {0}!",
  toque_pulo: "ПРЫЖОК",
  estilo_agressivo: "Агрессор",
  estilo_atirador: "Снайпер",
  estilo_saltitante: "Прыгун",
  estilo_cauteloso: "Осторожный",
  estilo_colecionador: "Собиратель",
  c_campo: "Луг",
  r_campo: "Классика: просто деритесь!",
  c_gelo: "Ледник",
  r_gelo: "Лёд: всё скользит!",
  c_lua: "Луна",
  r_lua: "Низкая гравитация: огромные прыжки",
  c_vulcao: "Вулкан",
  r_vulcao: "Лава поднимается: держитесь выше!",
  c_espaco: "Космос",
  r_espaco: "Почти невесомость: прыгайте, чтобы лететь",
  c_laboratorio: "Лаборатория",
  r_laboratorio: "Гравитация переворачивается!",
  c_dojo: "Додзё",
  r_dojo: "Сумо: столкните соперника!",
  c_cidade: "Неоновый город",
  r_cidade: "Осторожно, пропасть между домами!",
  c_fliperama: "Пинбол",
  r_fliperama: "Отбойники отбрасывают вас!",
  c_floresta: "Ночной лес",
  r_floresta: "В темноте: видно только у света",
  c_deserto: "Пустыня",
  r_deserto: "Сильный ветер меняет сторону!",
  c_fabrica: "Фабрика",
  r_fabrica: "Конвейеры тащат вас!",
  c_oceano: "Морское дно",
  r_oceano: "Под водой: прыгайте, чтобы плыть",
  c_templo: "Храм",
  r_templo: "Выйди с одной стороны — войди с другой. Порталы!",
  c_castelo: "Замок",
  r_castelo: "Метеоритный дождь: уходите от меток!",
  k_escudo: "Щит",
  kd_escudo: "Блокирует 40 урона",
  k_rapidez: "Скорость",
  kd_rapidez: "Быстрее на 7 с",
  k_cura: "Лечение",
  kd_cura: "+35 здоровья",
  k_furia: "Ярость",
  kd_furia: "Двойной урон на 6 с",
  k_tiro_duplo: "Двойной выстрел",
  kd_tiro_duplo: "Каждый выстрел удвоен",
  k_mini: "Мини",
  kd_mini: "Маленький и неуловимый",
  k_congelar: "Заморозка",
  kd_congelar: "Замораживает соперника",
  k_fantasma: "Призрак",
  kd_fantasma: "Почти невидим 5 с",
  k_reflexo: "Отражение",
  kd_reflexo: "Отражает выстрелы 5 с",
  k_super_pulo: "Суперпрыжок",
  kd_super_pulo: "Тройной и высокий прыжок",
  k_chuva: "Метеоритный дождь",
  kd_chuva: "5 метеоров на соперника",
  k_municao: "Бесконечные патроны",
  kd_municao: "8 с без расхода патронов",
  a_estilingue: "Рогатка",
  a_pistola: "Пистолет",
  a_revolver: "Револьвер",
  a_submetralhadora: "Пистолет-пулемёт",
  a_minigun: "Миниган",
  a_escopeta: "Дробовик",
  a_escopeta_dupla: "Двустволка",
  a_rifle: "Винтовка",
  a_sniper: "Снайперка",
  a_plasma: "Плазмаган",
  a_pula_pula: "Попрыгунчик",
  a_confete: "Конфетти-пушка",
  a_arma_agua: "Водяной пистолет",
  a_zarabatana: "Духовая трубка",
  a_onda_sonora: "Звуковая волна",
  a_shuriken: "Сюрикены",
  a_bumerangue: "Бумеранг",
  a_arco: "Лук",
  a_arco_triplo: "Тройной лук",
  a_besta: "Арбалет",
  a_serra: "Пила",
  a_bola_neve: "Снежок",
  a_gancho: "Крюк",
  a_bazuca: "Базука",
  a_lanca_granadas: "Гранатомёт",
  a_granada: "Граната",
  a_dinamite: "Динамит",
  a_fragmentacao: "Осколочная граната",
  a_canhao: "Пушка",
  a_mini_misseis: "Мини-ракеты",
  a_missil: "Самонаводящаяся ракета",
  a_abelhas: "Пчелиный рой",
  a_bola_fogo: "Огненный шар",
  a_granada_gelo: "Ледяная граната",
  a_mina: "Мина",
  a_laser: "Лазер",
  a_railgun: "Рельсотрон",
  a_arco_iris: "Радужный лазер",
  a_feixe: "Луч",
  a_tesla: "Тесла-пушка",
  a_raio_gelo: "Ледяной луч",
  a_bolhas: "Пузырьковый пистолет",
  a_buraco_negro: "Чёрная дыра",
  a_lanca_chamas: "Огнемёт",
  a_soprador: "Воздуходувка",
  a_martelo: "Молот",
  a_espada: "Меч",
  a_luva_boxe: "Боксёрская перчатка",
  a_meteoro: "Метеоры",
  a_relampago: "Молния",
  mi_vitorias: "Победите бота в {0} матч(ах)",
  mi_rodadas: "Выиграйте {0} раундов",
  mi_dano: "Нанесите {0} урона",
  mi_quedas: "Выиграйте {0} армрестлинг(а)",
  mi_cartas: "Соберите {0} карт",
  mi_caixas: "Соберите {0} ящиков с оружием",
  mi_abatesExpl: "Выиграйте {0} раунд(а) взрывчаткой",
  mi_abatesMelee: "Выиграйте {0} раунд(а) в ближнем бою",
  mi_perfeitas: "Выиграйте {0} раунд(а) без урона",
  mi_partidas: "Сыграйте {0} матча",
  mi_partidas2p: "Сыграйте {0} матч(а) вдвоём",
  mi_rodadaCenario: "Выиграйте {0} раунд(а) в: {1}",
  de_s_vitorias: "Победите бота в {0} матч(ах)",
  de_s_rodadas: "Выиграйте {0} раундов",
  de_s_dano: "Нанесите {0} урона",
  de_s_quedas: "Выиграйте {0} армрестлинг(а)",
  de_s_cenarios: "Выиграйте раунды на {0} разных аренах",
  de_s_5x0: "Выиграйте матч 5 – 0",
  de_s_expl: "Выиграйте {0} раунд(а) взрывчаткой",
  de_s_cartas: "Соберите {0} карт",
  de_s_perfeitas: "Выиграйте {0} раунд(а) без урона",
  de_s_virada: "Победите, проигрывая 3 очка",
  co_primeira_vitoria: "Первая победа",
  cod_primeira_vitoria: "Победите бота в {0} матч(ах)",
  co_vitorias_10: "Дуэлянт",
  cod_vitorias_10: "Победите бота в {0} матч(ах)",
  co_vitorias_25: "Ветеран",
  cod_vitorias_25: "Победите бота в {0} матч(ах)",
  co_vitorias_100: "Легенда",
  cod_vitorias_100: "Победите бота в {0} матч(ах)",
  co_partidas_50: "Фанат",
  cod_partidas_50: "Сыграйте {0} матча",
  co_rodadas_50: "Победитель раундов",
  cod_rodadas_50: "Выиграйте {0} раундов",
  co_rodadas_250: "Машина",
  cod_rodadas_250: "Выиграйте {0} раундов",
  co_dano_20000: "Разрушитель",
  cod_dano_20000: "Нанесите {0} урона",
  co_dano_100000: "Апокалипсис",
  cod_dano_100000: "Нанесите {0} урона",
  co_quedas_5: "Сильная рука",
  cod_quedas_5: "Выиграйте {0} армрестлинг(а)",
  co_quedas_20: "Чемпион армрестлинга",
  cod_quedas_20: "Выиграйте {0} армрестлинг(а)",
  co_explosivos_50: "Подрывник",
  cod_explosivos_50: "Выиграйте {0} раунд(а) взрывчаткой",
  co_melee_20: "Драчун",
  cod_melee_20: "Выиграйте {0} раунд(а) в ближнем бою",
  co_perfeitas_10: "Неуязвимый",
  cod_perfeitas_10: "Выиграйте {0} раунд(а) без урона",
  co_cenarios_todos: "Исследователь",
  cod_cenarios_todos: "Выиграйте раунды на {0} разных аренах",
  co_armas_25: "Коллекционер",
  cod_armas_25: "Соберите {0} разных видов оружия",
  co_armas_todas: "Полный арсенал",
  cod_armas_todas: "Соберите {0} разных видов оружия",
  co_cartas_todas: "Полная колода",
  cod_cartas_todas: "Соберите все {0} карт",
  co_placar_5x0: "Разгром",
  cod_placar_5x0: "Выиграйте матч 5 – 0",
  co_virada: "Эпичный камбэк",
  cod_virada: "Победите, проигрывая 3 очка",
  co_bot_mestre: "Мастер бота",
  cod_bot_mestre: "Победите бота на максимальном уровне",
  co_dois_jogadores_10: "Лучшие друзья",
  cod_dois_jogadores_10: "Сыграйте {0} матч(а) вдвоём",
  co_missoes_10: "Преданный",
  cod_missoes_10: "Заберите награды {0} заданий",
  co_missoes_50: "Неутомимый",
  cod_missoes_50: "Заберите награды {0} заданий",
  co_semana_completa: "Идеальная неделя",
  cod_semana_completa: "Выполните все испытания недели",
  co_onda_5: "Выживший",
  cod_onda_5: "Дойдите до волны {0} в Выживании",
  co_onda_10: "Неудержимый",
  cod_onda_10: "Дойдите до волны {0} в Выживании",
  sk_classico: "Классика",
  sk_listras: "Полоски",
  sk_pintas: "Горошек",
  sk_xadrez: "Клетка",
  sk_camuflado: "Камуфляж",
  sk_futebol: "Мяч",
  sk_melancia: "Арбуз",
  sk_robo: "Робот",
  sk_doce: "Конфета",
  sk_cromado: "Хром",
  sk_gelo: "Ледяной кристалл",
  sk_neon: "Неон",
  sk_lava: "Лава",
  sk_diamante: "Алмаз",
  sk_galaxia: "Галактика",
  sk_ouro: "Золото",
  sk_nenhum: "Нет",
  sk_bone: "Кепка",
  sk_oculos: "Очки",
  sk_orelhas_gato: "Кошачьи ушки",
  sk_fone: "Наушники",
  sk_cartola: "Цилиндр",
  sk_chifres: "Рожки",
  sk_tiara_flores: "Венок",
  sk_mascara_ninja: "Маска ниндзя",
  sk_viking: "Шлем викинга",
  sk_cowboy: "Ковбойская шляпа",
  sk_antena: "Антенна пришельца",
  sk_aureola: "Нимб",
  sk_coroa: "Корона",
  novo: "НОВОЕ!",
  proximo_rival: "СЛЕДУЮЩИЙ СОПЕРНИК",
  premio_equipado: "{0} надето!",
  modo_rivais: "Соперники",
  rivais_dica: "Победи 10 соперников и поднимись",
  rival_n: "СОПЕРНИК {0}/{1}",
  liga_0: "Бронза",
  liga_1: "Серебро",
  liga_2: "Золото",
  liga_3: "Алмаз",
  liga_4: "Мастер",
  liga_n: "Лига «{0}»",
  rival_derrotado: "{0} побеждён!",
  proximo: "Следующий: {0}",
  revanche_contra: "Реванш: {0}",
  campeao_liga: "ЧЕМПИОН ЛИГИ «{0}»!",
  rival_venceu: "{0} победил!",
  venca_ganhe: "Победи и получи: {0}",
  salvo: "СПАСЁН!"
};
