"use strict";
TEXTOS.ru = {
  titulo: "Дуэль шариков",
  jogar: "ИГРАТЬ",
  idioma: "Язык",
  som_on: "Звук: вкл.",
  som_off: "Звук: выкл.",
  voltar: "Назад",
  pausado: "Пауза",
  continuar: "Продолжить",
  menu: "Меню",
  anuncio_falhou: "Реклама не загрузилась. Попробуйте позже.",
  escolha_modo: "Как будете играть?",
  contra_bot: "Против бота",
  dois_jogadores: "2 игрока",
  dica_bot_teclado: "A D / ← → идти\nW / ↑ прыжок\nF / Пробел / L огонь",
  dica_bot_toque: "Слева: ведите, чтобы идти и прыгать\nСправа: держите, чтобы стрелять",
  dica_2p_teclado: "Игрок 1: A D W + F\nИгрок 2: ← → ↑ + L\nНа одной клавиатуре!",
  dica_2p_toque: "Каждый играет на своей половине экрана",
  lendaria: "Легендарный матч",
  lendaria_anuncio: "Легендарный матч: только редкое оружие (реклама)",
  lendaria_ativada: "Легендарный матч включён! Выберите режим",
  continuar_anuncio: "▶ Продолжить",
  continuar_explica: "Посмотрите рекламу — матч продолжится, а бот потеряет последнее очко.",
  nao_obrigado: "Нет, спасибо",
  voce: "ВЫ",
  voce_curto: "ВЫ",
  bot: "БОТ",
  jogador_n: "ИГРОК {0}",
  rodada_n: "Раунд {0}",
  dano_dobro: "ДВОЙНОЙ УРОН!",
  lute: "В БОЙ!",
  empate: "НИЧЬЯ!",
  voce_venceu_rodada: "РАУНД ВАШ!",
  bot_venceu_rodada: "РАУНД ЗА БОТОМ",
  jogador_venceu_rodada: "РАУНД ЗА ИГРОКОМ {0}!",
  voce_venceu: "ВЫ ПОБЕДИЛИ!",
  bot_venceu: "БОТ ПОБЕДИЛ",
  jogador_venceu: "ПОБЕДИЛ ИГРОК {0}!",
  queda: "АРМРЕСТЛИНГ!",
  queda_sub: "Время вышло! Побеждает тот, кто быстрее жмёт",
  queda_dica_bot: "КЛИК / ПРОБЕЛ!",
  queda_dica_toque: "ЖМИТЕ НА ЭКРАН!",
  queda_dica_p1: "ЖМИТЕ F!",
  queda_dica_p2: "ЖМИТЕ L!",
  queda_dica_toque_esq: "ЖМИТЕ СЛЕВА!",
  queda_dica_toque_dir: "ЖМИТЕ СПРАВА!",
  toque_mover: "идти",
  toque_tiro: "ОГОНЬ",
  pegou_arma: "{0}!",
  c_campo: "Луг",
  r_campo: "Классика: просто деритесь!",
  c_gelo: "Ледник",
  r_gelo: "Лёд: всё скользит!",
  c_lua: "Луна",
  r_lua: "Низкая гравитация: огромные прыжки",
  c_vulcao: "Вулкан",
  r_vulcao: "Лава поднимается: держитесь выше!",
  c_espaco: "Космос",
  r_espaco: "Почти невесомость: прыгайте, чтобы лететь",
  c_laboratorio: "Лаборатория",
  r_laboratorio: "Гравитация переворачивается!",
  c_dojo: "Додзё",
  r_dojo: "Сумо: столкните соперника!",
  c_cidade: "Неоновый город",
  r_cidade: "Осторожно, пропасть между домами!",
  c_fliperama: "Пинбол",
  r_fliperama: "Отбойники отбрасывают вас!",
  c_floresta: "Ночной лес",
  r_floresta: "В темноте: видно только у света",
  c_deserto: "Пустыня",
  r_deserto: "Сильный ветер меняет сторону!",
  c_fabrica: "Фабрика",
  r_fabrica: "Конвейеры тащат вас!",
  c_oceano: "Морское дно",
  r_oceano: "Под водой: прыгайте, чтобы плыть",
  c_templo: "Храм",
  r_templo: "Выйди с одной стороны — войди с другой. Порталы!",
  c_castelo: "Замок",
  r_castelo: "Метеоритный дождь: уходите от меток!",
  k_escudo: "Щит",
  kd_escudo: "Блокирует 40 урона",
  k_rapidez: "Скорость",
  kd_rapidez: "Быстрее на 7 с",
  k_cura: "Лечение",
  kd_cura: "+35 здоровья",
  k_furia: "Ярость",
  kd_furia: "Двойной урон на 6 с",
  k_tiro_duplo: "Двойной выстрел",
  kd_tiro_duplo: "Каждый выстрел удвоен",
  k_mini: "Мини",
  kd_mini: "Маленький и неуловимый",
  k_congelar: "Заморозка",
  kd_congelar: "Замораживает соперника",
  k_fantasma: "Призрак",
  kd_fantasma: "Почти невидим 5 с",
  k_reflexo: "Отражение",
  kd_reflexo: "Отражает выстрелы 5 с",
  k_super_pulo: "Суперпрыжок",
  kd_super_pulo: "Тройной и высокий прыжок",
  k_chuva: "Метеоритный дождь",
  kd_chuva: "5 метеоров на соперника",
  k_municao: "Бесконечные патроны",
  kd_municao: "8 с без расхода патронов",
  a_estilingue: "Рогатка",
  a_pistola: "Пистолет",
  a_revolver: "Револьвер",
  a_submetralhadora: "Пистолет-пулемёт",
  a_minigun: "Миниган",
  a_escopeta: "Дробовик",
  a_escopeta_dupla: "Двустволка",
  a_rifle: "Винтовка",
  a_sniper: "Снайперка",
  a_plasma: "Плазмаган",
  a_pula_pula: "Попрыгунчик",
  a_confete: "Конфетти-пушка",
  a_arma_agua: "Водяной пистолет",
  a_zarabatana: "Духовая трубка",
  a_onda_sonora: "Звуковая волна",
  a_shuriken: "Сюрикены",
  a_bumerangue: "Бумеранг",
  a_arco: "Лук",
  a_arco_triplo: "Тройной лук",
  a_besta: "Арбалет",
  a_serra: "Пила",
  a_bola_neve: "Снежок",
  a_gancho: "Крюк",
  a_bazuca: "Базука",
  a_lanca_granadas: "Гранатомёт",
  a_granada: "Граната",
  a_dinamite: "Динамит",
  a_fragmentacao: "Осколочная граната",
  a_canhao: "Пушка",
  a_mini_misseis: "Мини-ракеты",
  a_missil: "Самонаводящаяся ракета",
  a_abelhas: "Пчелиный рой",
  a_bola_fogo: "Огненный шар",
  a_granada_gelo: "Ледяная граната",
  a_mina: "Мина",
  a_laser: "Лазер",
  a_railgun: "Рельсотрон",
  a_arco_iris: "Радужный лазер",
  a_feixe: "Луч",
  a_tesla: "Тесла-пушка",
  a_raio_gelo: "Ледяной луч",
  a_bolhas: "Пузырьковый пистолет",
  a_buraco_negro: "Чёрная дыра",
  a_lanca_chamas: "Огнемёт",
  a_soprador: "Воздуходувка",
  a_martelo: "Молот",
  a_espada: "Меч",
  a_luva_boxe: "Боксёрская перчатка",
  a_meteoro: "Метеоры",
  a_relampago: "Молния"
};
