"use strict";
TEXTOS.tr = {
  titulo: "Crazy Balls Duel",
  jogar: "OYNA",
  idioma: "Dil",
  som_on: "Ses: açık",
  som_off: "Ses: kapalı",
  voltar: "Geri",
  pausado: "Duraklatıldı",
  continuar: "Devam",
  menu: "Menü",
  anuncio_falhou: "Reklam yüklenemedi. Sonra tekrar dene.",
  escolha_modo: "Nasıl oynamak istersin?",
  contra_bot: "Bota karşı",
  dois_jogadores: "2 oyuncu",
  dica_bot_teclado: "A D / ← → yürü\nW / ↑ zıpla\nF / Boşluk / L ateş",
  dica_bot_toque: "Sol: yürümek için sürükle\nSağ: üst zıplar · alt nişan alır ve ateş eder",
  dica_2p_teclado: "Oyuncu 1: A D W + F\nOyuncu 2: ← → ↑ + L\nAynı klavyede!",
  dica_2p_toque: "Aynı telefonda iki kişi, yatay: herkes ekranın bir yarısını kullanır",
  lendaria: "Efsanevi Maç",
  lendaria_anuncio: "Efsanevi Maç: sadece nadir silahlar (reklam)",
  lendaria_ativada: "Efsanevi Maç açık! Modu seç",
  continuar_anuncio: "▶ Devam et",
  continuar_explica: "Reklam izle, maç devam etsin: bot son puanını kaybeder.",
  nao_obrigado: "Hayır, teşekkürler",
  voce: "SEN",
  voce_curto: "SEN",
  bot: "BOT",
  jogador_n: "OYUNCU {0}",
  rodada_n: "Raunt {0}",
  dano_dobro: "ÇİFT HASAR!",
  lute: "SAVAŞ!",
  empate: "BERABERE!",
  voce_venceu_rodada: "RAUNDU KAZANDIN!",
  bot_venceu_rodada: "BOT RAUNDU KAZANDI",
  jogador_venceu_rodada: "RAUNT OYUNCU {0}'İN!",
  voce_venceu: "KAZANDIN!",
  bot_venceu: "BOT KAZANDI",
  jogador_venceu: "OYUNCU {0} KAZANDI!",
  queda: "BİLEK GÜREŞİ!",
  queda_sub: "Süre bitti! Daha hızlı tıklayan kazanır",
  queda_dica_bot: "TIKLA / BOŞLUK!",
  queda_dica_toque: "EKRANA DOKUN!",
  queda_dica_p1: "F'YE BAS!",
  queda_dica_p2: "L'YE BAS!",
  queda_dica_toque_esq: "SOLA DOKUN!",
  queda_dica_toque_dir: "SAĞA DOKUN!",
  toque_mover: "yürü",
  toque_tiro: "ATEŞ",
  pegou_arma: "{0}!",
  mesmo_aparelho: "Aynı cihazda · çevrimiçi değil",
  qualidade_auto: "Grafik: otomatik",
  qualidade_alta: "Grafik: yüksek",
  qualidade_leve: "Grafik: hafif",
  perfeito: "MÜKEMMEL!",
  missoes: "Görevler",
  skins: "Kostümler",
  opcoes: "Ayarlar",
  controles: "Kontroller",
  controles_mouse: "Oyuncu 1 FARE ile de nişan alır (tık ateş eder). Bir tuşa tıkla, yenisine bas.",
  teclas_padrao: "Varsayılan tuşlar",
  semana: "Haftalık",
  conquistas: "Başarımlar",
  skins_corpo: "Top",
  skins_acessorio: "Aksesuar",
  dobrar_moedas: "Paraları ikiye katla",
  resgatar: "Al",
  trocar: "Değiştir",
  missoes_explica: "Para kazanmak için görevleri tamamla. Günde 1 görev değiştirebilirsin.",
  semana_termina: "{0}g {1}s sonra biter",
  premio_semana: "Haftanın ödülü: 4 görevi de tamamla",
  equipado: "Kuşanıldı",
  equipar: "Kuşan",
  so_semanal: "Haftalık ödül",
  acao_esquerda: "Sol",
  acao_direita: "Sağ",
  acao_pulo: "Zıpla",
  acao_baixo: "Aşağı",
  acao_tiro: "Ateş",
  tecla_espaco: "Boşluk",
  toque_mira: "NİŞAN",
  dica_bot_v2: "{0} yürü · {1} zıpla\nFare: nişan al ve ateş et (veya {2})",
  dica_2p_v2: "Oyuncu 1: {0}\nOyuncu 2: {1}\nAynı klavyede!",
  aviso_missao: "Görev tamamlandı!",
  aviso_desafio: "Haftalık görev tamamlandı!",
  aviso_conquista: "Başarım: {0}!",
  nivel_bot: "🤖 Bot seviye {0}",
  nivel_curto: "Sv. {0}",
  bot_subiu: "Bot seviye {0} oldu!",
  bot_desceu: "Bot seviye {0}'e düştü",
  nivel_jogador: "Seviye {0}",
  subiu_nivel: "Seviye {0} oldun!",
  abrir_bau: "Sandığı aç",
  abrir_bau_nivel: "Seviye sandığını aç!",
  outro_bau: "Bir sandık daha aç",
  revanche: "RÖVANŞ",
  premio_skin: "Yeni kostüm: {0}!",
  diaria: "Günlük ödül",
  diaria_explica: "Her gün gel: ödül büyür! Bir gün kaçırırsan baştan başlar.",
  dia_n: "Gün {0}",
  bau: "sandık",
  bau_lendario: "efsanevi sandık",
  pegar: "Al",
  fechar: "Kapat",
  sobrevivencia: "Hayatta Kalma",
  sobrevivencia_dica: "Giderek güçlenen bot dalgaları.\nNereye kadar gidebilirsin?",
  onda_n: "DALGA {0}",
  onda_concluida: "DALGA {0} GEÇİLDİ!",
  fim_sobrevivencia: "{0}. dalgaya ulaştın!",
  recorde_onda: "Rekor: dalga {0}",
  novo_recorde: "YENİ REKOR!",
  continuar_vida: "Reklam izle, aynı dalgada tam canla devam et.",
  dica_bot_v3: "{0} yürü · {1} zıpla\nFare: nişan · Tık veya {2}: ateş",
  dica_2p_v3: "Oyuncu 1: {0} + fare\nOyuncu 2: {1}\nAynı klavyede!",
  queda_clique: "TIKLA VEYA {0}!",
  queda_aperte: "{0} BAS!",
  toque_pulo: "ZIPLA",
  estilo_agressivo: "Saldırgan",
  estilo_atirador: "Keskin Nişancı",
  estilo_saltitante: "Zıplayan",
  estilo_cauteloso: "Temkinli",
  estilo_colecionador: "Koleksiyoncu",
  c_campo: "Çayır",
  r_campo: "Klasik: sadece savaş!",
  c_gelo: "Buzul",
  r_gelo: "Buz: her şey kayıyor!",
  c_lua: "Ay",
  r_lua: "Düşük yerçekimi: dev zıplamalar",
  c_vulcao: "Yanardağ",
  r_vulcao: "Lav yükselip alçalıyor: yüksekte kal!",
  c_espaco: "Uzay",
  r_espaco: "Neredeyse yerçekimsiz: uçmak için zıpla",
  c_laboratorio: "Laboratuvar",
  r_laboratorio: "Yerçekimi ters dönüyor!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: rakibi dışarı it!",
  c_cidade: "Neon Şehir",
  r_cidade: "Binalar arasındaki boşluğa dikkat!",
  c_fliperama: "Langırt",
  r_fliperama: "Tamponlar seni fırlatır!",
  c_floresta: "Gece Ormanı",
  r_floresta: "Karanlıkta: sadece ışık yakınında görünür",
  c_deserto: "Çöl",
  r_deserto: "Güçlü rüzgar yön değiştirir!",
  c_fabrica: "Fabrika",
  r_fabrica: "Yürüyen bantlar seni taşır!",
  c_oceano: "Derin Deniz",
  r_oceano: "Su altında: yüzmek için zıpla",
  c_templo: "Tapınak",
  r_templo: "Bir yandan çık, diğerinden gir. Portallar!",
  c_castelo: "Kale",
  r_castelo: "Meteor yağmuru: hedeflerden kaç!",
  k_escudo: "Kalkan",
  kd_escudo: "40 hasarı engeller",
  k_rapidez: "Hız",
  kd_rapidez: "7 sn daha hızlı",
  k_cura: "İyileşme",
  kd_cura: "+35 can",
  k_furia: "Öfke",
  kd_furia: "6 sn çift hasar",
  k_tiro_duplo: "Çift Atış",
  kd_tiro_duplo: "Her atış ikiye katlanır",
  k_mini: "Mini",
  kd_mini: "Küçük ve vurulması zor",
  k_congelar: "Dondur",
  kd_congelar: "Rakibi dondurur",
  k_fantasma: "Hayalet",
  kd_fantasma: "5 sn neredeyse görünmez",
  k_reflexo: "Yansıma",
  kd_reflexo: "5 sn atışları geri yollar",
  k_super_pulo: "Süper Zıplama",
  kd_super_pulo: "Üçlü ve yüksek zıplama",
  k_chuva: "Meteor Yağmuru",
  kd_chuva: "Rakibe 5 meteor",
  k_municao: "Sonsuz Mermi",
  kd_municao: "8 sn mermi harcamaz",
  a_estilingue: "Sapan",
  a_pistola: "Tabanca",
  a_revolver: "Altıpatlar",
  a_submetralhadora: "Hafif Makineli",
  a_minigun: "Minigun",
  a_escopeta: "Pompalı",
  a_escopeta_dupla: "Çift Namlu",
  a_rifle: "Tüfek",
  a_sniper: "Keskin Nişancı",
  a_plasma: "Plazma",
  a_pula_pula: "Zıp Zıp Top",
  a_confete: "Konfeti Topu",
  a_arma_agua: "Su Tabancası",
  a_zarabatana: "Üfleme Borusu",
  a_onda_sonora: "Ses Dalgası",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Yay",
  a_arco_triplo: "Üçlü Yay",
  a_besta: "Arbalet",
  a_serra: "Testere",
  a_bola_neve: "Kartopu",
  a_gancho: "Kanca",
  a_bazuca: "Bazuka",
  a_lanca_granadas: "Bombaatar",
  a_granada: "El Bombası",
  a_dinamite: "Dinamit",
  a_fragmentacao: "Parça Bombası",
  a_canhao: "Top",
  a_mini_misseis: "Mini Füzeler",
  a_missil: "Güdümlü Füze",
  a_abelhas: "Arı Sürüsü",
  a_bola_fogo: "Ateş Topu",
  a_granada_gelo: "Buz Bombası",
  a_mina: "Mayın",
  a_laser: "Lazer",
  a_railgun: "Raylı Top",
  a_arco_iris: "Gökkuşağı Lazeri",
  a_feixe: "Işın Silahı",
  a_tesla: "Tesla",
  a_raio_gelo: "Buz Işını",
  a_bolhas: "Baloncuk Tabancası",
  a_buraco_negro: "Kara Delik",
  a_lanca_chamas: "Alev Silahı",
  a_soprador: "Üfleyici",
  a_martelo: "Çekiç",
  a_espada: "Kılıç",
  a_luva_boxe: "Boks Eldiveni",
  a_meteoro: "Meteorlar",
  a_relampago: "Yıldırım",
  mi_vitorias: "Bota karşı {0} maç kazan",
  mi_rodadas: "{0} raunt kazan",
  mi_dano: "{0} hasar ver",
  mi_quedas: "{0} bilek güreşi kazan",
  mi_cartas: "{0} kart topla",
  mi_caixas: "{0} silah kutusu topla",
  mi_abatesExpl: "Patlayıcıyla {0} raunt kazan",
  mi_abatesMelee: "Yakın dövüşle {0} raunt kazan",
  mi_perfeitas: "Hasar almadan {0} raunt kazan",
  mi_partidas: "{0} maç oyna",
  mi_partidas2p: "{0} iki kişilik maç oyna",
  mi_rodadaCenario: "Şurada {0} raunt kazan: {1}",
  de_s_vitorias: "Bota karşı {0} maç kazan",
  de_s_rodadas: "{0} raunt kazan",
  de_s_dano: "{0} hasar ver",
  de_s_quedas: "{0} bilek güreşi kazan",
  de_s_cenarios: "{0} farklı arenada raunt kazan",
  de_s_5x0: "Bir maçı 5 – 0 kazan",
  de_s_expl: "Patlayıcıyla {0} raunt kazan",
  de_s_cartas: "{0} kart topla",
  de_s_perfeitas: "Hasar almadan {0} raunt kazan",
  de_s_virada: "3 sayı gerideyken geri dön ve kazan",
  co_primeira_vitoria: "İlk Zafer",
  cod_primeira_vitoria: "Bota karşı {0} maç kazan",
  co_vitorias_10: "Düellocu",
  cod_vitorias_10: "Bota karşı {0} maç kazan",
  co_vitorias_25: "Kıdemli",
  cod_vitorias_25: "Bota karşı {0} maç kazan",
  co_vitorias_100: "Efsane",
  cod_vitorias_100: "Bota karşı {0} maç kazan",
  co_partidas_50: "Bağımlı",
  cod_partidas_50: "{0} maç oyna",
  co_rodadas_50: "Raunt Ustası",
  cod_rodadas_50: "{0} raunt kazan",
  co_rodadas_250: "Makine",
  cod_rodadas_250: "{0} raunt kazan",
  co_dano_20000: "Yok Edici",
  cod_dano_20000: "{0} hasar ver",
  co_dano_100000: "Kıyamet",
  cod_dano_100000: "{0} hasar ver",
  co_quedas_5: "Güçlü Kol",
  cod_quedas_5: "{0} bilek güreşi kazan",
  co_quedas_20: "Bilek Şampiyonu",
  cod_quedas_20: "{0} bilek güreşi kazan",
  co_explosivos_50: "Yıkıcı",
  cod_explosivos_50: "Patlayıcıyla {0} raunt kazan",
  co_melee_20: "Kavgacı",
  cod_melee_20: "Yakın dövüşle {0} raunt kazan",
  co_perfeitas_10: "Dokunulmaz",
  cod_perfeitas_10: "Hasar almadan {0} raunt kazan",
  co_cenarios_todos: "Kaşif",
  cod_cenarios_todos: "{0} farklı arenada raunt kazan",
  co_armas_25: "Koleksiyoncu",
  cod_armas_25: "{0} farklı silah topla",
  co_armas_todas: "Tam Cephanelik",
  cod_armas_todas: "{0} farklı silah topla",
  co_cartas_todas: "Tam Deste",
  cod_cartas_todas: "{0} farklı kartın hepsini topla",
  co_placar_5x0: "Ezici Galibiyet",
  cod_placar_5x0: "Bir maçı 5 – 0 kazan",
  co_virada: "Destansı Dönüş",
  cod_virada: "3 sayı gerideyken geri dön ve kazan",
  co_bot_mestre: "Bot Ustası",
  cod_bot_mestre: "Botu en üst seviyede yen",
  co_dois_jogadores_10: "En İyi Arkadaşlar",
  cod_dois_jogadores_10: "{0} iki kişilik maç oyna",
  co_missoes_10: "Azimli",
  cod_missoes_10: "{0} görev ödülü al",
  co_missoes_50: "Yorulmaz",
  cod_missoes_50: "{0} görev ödülü al",
  co_semana_completa: "Mükemmel Hafta",
  cod_semana_completa: "Bir haftanın tüm görevlerini tamamla",
  co_onda_5: "Hayatta Kalan",
  cod_onda_5: "Hayatta Kalma'da {0}. dalgaya ulaş",
  co_onda_10: "Durdurulamaz",
  cod_onda_10: "Hayatta Kalma'da {0}. dalgaya ulaş",
  sk_classico: "Klasik",
  sk_listras: "Çizgili",
  sk_pintas: "Puantiye",
  sk_xadrez: "Damalı",
  sk_camuflado: "Kamuflaj",
  sk_futebol: "Futbol Topu",
  sk_melancia: "Karpuz",
  sk_robo: "Robot",
  sk_doce: "Şeker",
  sk_cromado: "Krom",
  sk_gelo: "Buz Kristali",
  sk_neon: "Neon",
  sk_lava: "Lav",
  sk_diamante: "Elmas",
  sk_galaxia: "Galaksi",
  sk_ouro: "Altın",
  sk_nenhum: "Yok",
  sk_bone: "Şapka",
  sk_oculos: "Güneş Gözlüğü",
  sk_orelhas_gato: "Kedi Kulakları",
  sk_fone: "Kulaklık",
  sk_cartola: "Silindir Şapka",
  sk_chifres: "Boynuzlar",
  sk_tiara_flores: "Çiçek Taç",
  sk_mascara_ninja: "Ninja Maskesi",
  sk_viking: "Viking Miğferi",
  sk_cowboy: "Kovboy Şapkası",
  sk_antena: "Uzaylı Anteni",
  sk_aureola: "Hale",
  sk_coroa: "Taç",
  novo: "YENİ!",
  proximo_rival: "SIRADAKİ RAKİP",
  premio_equipado: "{0} kuşanıldı!",
  modo_rivais: "Rakipler",
  rivais_dica: "10 rakibi yen, lig atla",
  rival_n: "RAKİP {0}/{1}",
  liga_0: "Bronz",
  liga_1: "Gümüş",
  liga_2: "Altın",
  liga_3: "Elmas",
  liga_4: "Usta",
  liga_n: "{0} Ligi",
  rival_derrotado: "{0} yenildi!",
  proximo: "Sıradaki: {0}",
  revanche_contra: "{0} ile rövanş",
  campeao_liga: "{0} LİGİ ŞAMPİYONU!",
  rival_venceu: "{0} kazandı!",
  venca_ganhe: "Kazan ve al: {0}",
  salvo: "KURTULDUN!"
};
