"use strict";
TEXTOS.tr = {
  titulo: "Top Düellosu",
  jogar: "OYNA",
  idioma: "Dil",
  som_on: "Ses: açık",
  som_off: "Ses: kapalı",
  voltar: "Geri",
  pausado: "Duraklatıldı",
  continuar: "Devam",
  menu: "Menü",
  anuncio_falhou: "Reklam yüklenemedi. Sonra tekrar dene.",
  escolha_modo: "Nasıl oynamak istersin?",
  contra_bot: "Bota karşı",
  dois_jogadores: "2 oyuncu",
  dica_bot_teclado: "A D / ← → yürü\nW / ↑ zıpla\nF / Boşluk / L ateş",
  dica_bot_toque: "Sol: yürümek ve zıplamak için sürükle\nSağ: ateş için basılı tut",
  dica_2p_teclado: "Oyuncu 1: A D W + F\nOyuncu 2: ← → ↑ + L\nAynı klavyede!",
  dica_2p_toque: "Herkes ekranın kendi yarısını kullanır",
  lendaria: "Efsanevi Maç",
  lendaria_anuncio: "Efsanevi Maç: sadece nadir silahlar (reklam)",
  lendaria_ativada: "Efsanevi Maç açık! Modu seç",
  continuar_anuncio: "▶ Devam et",
  continuar_explica: "Reklam izle, maç devam etsin: bot son puanını kaybeder.",
  nao_obrigado: "Hayır, teşekkürler",
  voce: "SEN",
  voce_curto: "SEN",
  bot: "BOT",
  jogador_n: "OYUNCU {0}",
  rodada_n: "Raunt {0}",
  dano_dobro: "ÇİFT HASAR!",
  lute: "SAVAŞ!",
  empate: "BERABERE!",
  voce_venceu_rodada: "RAUNDU KAZANDIN!",
  bot_venceu_rodada: "BOT RAUNDU KAZANDI",
  jogador_venceu_rodada: "RAUNT OYUNCU {0}'İN!",
  voce_venceu: "KAZANDIN!",
  bot_venceu: "BOT KAZANDI",
  jogador_venceu: "OYUNCU {0} KAZANDI!",
  queda: "BİLEK GÜREŞİ!",
  queda_sub: "Süre bitti! Daha hızlı tıklayan kazanır",
  queda_dica_bot: "TIKLA / BOŞLUK!",
  queda_dica_toque: "EKRANA DOKUN!",
  queda_dica_p1: "F'YE BAS!",
  queda_dica_p2: "L'YE BAS!",
  queda_dica_toque_esq: "SOLA DOKUN!",
  queda_dica_toque_dir: "SAĞA DOKUN!",
  toque_mover: "yürü",
  toque_tiro: "ATEŞ",
  pegou_arma: "{0}!",
  c_campo: "Çayır",
  r_campo: "Klasik: sadece savaş!",
  c_gelo: "Buzul",
  r_gelo: "Buz: her şey kayıyor!",
  c_lua: "Ay",
  r_lua: "Düşük yerçekimi: dev zıplamalar",
  c_vulcao: "Yanardağ",
  r_vulcao: "Lav yükselip alçalıyor: yüksekte kal!",
  c_espaco: "Uzay",
  r_espaco: "Neredeyse yerçekimsiz: uçmak için zıpla",
  c_laboratorio: "Laboratuvar",
  r_laboratorio: "Yerçekimi ters dönüyor!",
  c_dojo: "Dojo",
  r_dojo: "Sumo: rakibi dışarı it!",
  c_cidade: "Neon Şehir",
  r_cidade: "Binalar arasındaki boşluğa dikkat!",
  c_fliperama: "Langırt",
  r_fliperama: "Tamponlar seni fırlatır!",
  c_floresta: "Gece Ormanı",
  r_floresta: "Karanlıkta: sadece ışık yakınında görünür",
  c_deserto: "Çöl",
  r_deserto: "Güçlü rüzgar yön değiştirir!",
  c_fabrica: "Fabrika",
  r_fabrica: "Yürüyen bantlar seni taşır!",
  c_oceano: "Derin Deniz",
  r_oceano: "Su altında: yüzmek için zıpla",
  c_templo: "Tapınak",
  r_templo: "Bir yandan çık, diğerinden gir. Portallar!",
  c_castelo: "Kale",
  r_castelo: "Meteor yağmuru: hedeflerden kaç!",
  k_escudo: "Kalkan",
  kd_escudo: "40 hasarı engeller",
  k_rapidez: "Hız",
  kd_rapidez: "7 sn daha hızlı",
  k_cura: "İyileşme",
  kd_cura: "+35 can",
  k_furia: "Öfke",
  kd_furia: "6 sn çift hasar",
  k_tiro_duplo: "Çift Atış",
  kd_tiro_duplo: "Her atış ikiye katlanır",
  k_mini: "Mini",
  kd_mini: "Küçük ve vurulması zor",
  k_congelar: "Dondur",
  kd_congelar: "Rakibi dondurur",
  k_fantasma: "Hayalet",
  kd_fantasma: "5 sn neredeyse görünmez",
  k_reflexo: "Yansıma",
  kd_reflexo: "5 sn atışları geri yollar",
  k_super_pulo: "Süper Zıplama",
  kd_super_pulo: "Üçlü ve yüksek zıplama",
  k_chuva: "Meteor Yağmuru",
  kd_chuva: "Rakibe 5 meteor",
  k_municao: "Sonsuz Mermi",
  kd_municao: "8 sn mermi harcamaz",
  a_estilingue: "Sapan",
  a_pistola: "Tabanca",
  a_revolver: "Altıpatlar",
  a_submetralhadora: "Hafif Makineli",
  a_minigun: "Minigun",
  a_escopeta: "Pompalı",
  a_escopeta_dupla: "Çift Namlu",
  a_rifle: "Tüfek",
  a_sniper: "Keskin Nişancı",
  a_plasma: "Plazma",
  a_pula_pula: "Zıp Zıp Top",
  a_confete: "Konfeti Topu",
  a_arma_agua: "Su Tabancası",
  a_zarabatana: "Üfleme Borusu",
  a_onda_sonora: "Ses Dalgası",
  a_shuriken: "Shuriken",
  a_bumerangue: "Bumerang",
  a_arco: "Yay",
  a_arco_triplo: "Üçlü Yay",
  a_besta: "Arbalet",
  a_serra: "Testere",
  a_bola_neve: "Kartopu",
  a_gancho: "Kanca",
  a_bazuca: "Bazuka",
  a_lanca_granadas: "Bombaatar",
  a_granada: "El Bombası",
  a_dinamite: "Dinamit",
  a_fragmentacao: "Parça Bombası",
  a_canhao: "Top",
  a_mini_misseis: "Mini Füzeler",
  a_missil: "Güdümlü Füze",
  a_abelhas: "Arı Sürüsü",
  a_bola_fogo: "Ateş Topu",
  a_granada_gelo: "Buz Bombası",
  a_mina: "Mayın",
  a_laser: "Lazer",
  a_railgun: "Raylı Top",
  a_arco_iris: "Gökkuşağı Lazeri",
  a_feixe: "Işın Silahı",
  a_tesla: "Tesla",
  a_raio_gelo: "Buz Işını",
  a_bolhas: "Baloncuk Tabancası",
  a_buraco_negro: "Kara Delik",
  a_lanca_chamas: "Alev Silahı",
  a_soprador: "Üfleyici",
  a_martelo: "Çekiç",
  a_espada: "Kılıç",
  a_luva_boxe: "Boks Eldiveni",
  a_meteoro: "Meteorlar",
  a_relampago: "Yıldırım"
};
